### ISSUE TITLE
After Column Deletion, Some Validations are not Moved/Deleted

### ISSUE THREAD

**Issue by as321d** [EPPlusSoftware/EPPlus#100]
Version 5.1.0:

When I use `ExcelWorksheet.RemoveColumn()`, I encounter two issues:
1. Validations tied to the column I delete remain in place, (i.e. deleting column A changes the old Column B to be the new Column A, but any validations previously in Column A remain, now affecting the old Column B/new Column A)
2. Validations tied to the column immediately to the right of the deleted column do not shift to the left, causing another instance of mismatch (deleting column A changes the old Column C to be the new Column B, but any validations previously in Column B remain, now affecting the old Column C/new Column B, and leaving the new Column A/old Column B without its validations).

Validations on columns further to the right (if A is deleted, this would mean columns C and beyond),  shift to the left as expected.

**Comment by JanKallman** [comment]
I'll supply a fix shortly

**Comment by as321d** [comment]
Hi, when will this fix be released and usable? My team needs to know in order to decide how to proceed with a project.

**Comment by as321d** [comment]
Also, when will this be available in the development version?

**Comment by JanKallman** [comment]
Develop version is available now.
We will create a new version within the coming two weeks.

**Comment by JanKallman** [comment]
Fixed in version 5.1.2
