### ISSUE TITLE
InsertRow and DeleteRow fails with an Exception, if a defined name references another defined name

### ISSUE THREAD

**Issue by JanKallman** [EPPlusSoftware/EPPlus#1008]

**Comment by arnileibovits** [comment]
It looks like test `CsvRead `is failing due to a missing file.

Otherwise, how soon would it be possible to get a nightly build with this fix? Thank you!

**Comment by sanderpriivits** [comment]
@JanKallman any update, please?

**Comment by JanKallman** [comment]
@arnileibovits , Sorry about the failing develop build. The failing test has been removed and the build is running now.

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.2.8
