### ISSUE TITLE
Lack of compatibility with System.IO.Compression

### ISSUE THREAD

**Issue by lolsoftware** [EPPlusSoftware/EPPlus#101]
If EPPlus saves an Excel file which was previously compressed using System.IO.Compression, then the resulting file is considered corrupted by MS Excel ("file format is not valid").

I attach a sample project:
[project.zip](https://github.com/EPPlusSoftware/EPPlus/files/4573968/project.zip)

Also, I attach an example of a corrupted file:
[test-corrupted.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4573973/test-corrupted.xlsx)

![image](https://user-images.githubusercontent.com/4579687/80955656-ebc5b100-8dff-11ea-9382-367401f53166.png)

What fixed the issue for me was to change the EPPlus source code (src\EPPlus\Packaging\ZipPackage.cs) from this:

![image](https://user-images.githubusercontent.com/4579687/80956461-938fae80-8e01-11ea-85df-e80344647f31.png)

to this:

![image](https://user-images.githubusercontent.com/4579687/80956518-b15d1380-8e01-11ea-986e-1581b1795562.png)

**Comment by JanKallman** [comment]
System.IO.Compression uses backslashes in the filenames causing EPPlus to loose the root relationship in this case. Fix applied.

**Comment by JanKallman** [comment]
Fixed in version 5.1.2
