### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by aron-666** [EPPlusSoftware/EPPlus#1015]
### Throw the exception at my code: 
`selectedCell.RichText.Add(strings1[0]).VerticalAlign` = `ExcelVerticalAlignmentFont.Superscript;`

Detail: 
`System.ArgumentException: An item with the same key has already been added. Key: /xl/theme/theme1.xml at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at OfficeOpenXml.Packaging.ZipPackage.CreatePart(Uri partUri, String contentType, CompressionLevel compressionLevel, String extension) at OfficeOpenXml.Packaging.ZipPackage.CreatePart(Uri partUri, String contentType) at OfficeOpenXml.Drawing.Theme.ExcelThemeManager.Load(XmlDocument themeXml) at OfficeOpenXml.Drawing.Theme.ExcelThemeManager.CreateDefaultTheme() at OfficeOpenXml.Style.ExcelRichText.get_Color() at OfficeOpenXml.Style.ExcelRichTextCollection.Insert(Int32 index, String text) 

### Becouse the key '/xl/theme/theme1.xml' is already exist.
![螢幕擷取畫面 2023-08-16 192528](https://github.com/EPPlusSoftware/EPPlus/assets/52336358/48463522-c762-4e2b-9035-3063ea35697a)

**Comment by JanKallman** [comment]
The theme should be loaded in this case. Can you provide your workbook so I can se why this fails?
I'm unsure if fixing this in the ZipPackage class is the right way to solving this issue.

**Comment by OssianEPPlus** [comment]
Closed due to inactivity.
