### ISSUE TITLE
UnGroup Drawings

### ISSUE THREAD

**Issue by FedePorti** [EPPlusSoftware/EPPlus#1017]
I have tried to use ungroup in the drawings but I have some problems, for example:

1) I group all the drawings and then I ungroup all the drawings (I know it not have sense)

`sheet3.Drawings.Item(0).Group(sheet3.Drawings.ToArray)`
`sheet3.Drawings.Item(0).UnGroup()`

And I have this exception:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/5a2b88cb-4c49-48cd-8686-8f99e66f00f7)

2) Doing the same but like this:

`sheet3.Drawings.Item(0).Group(sheet3.Drawings.ToArray).Name = "Test"`
`sheet3.Drawings.Item("Test").UnGroup()`

And I have this exception:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/2e4fb90c-477f-4f16-85d4-b174d037ec41)
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/dac2f95c-cd5e-4ba1-bb71-ea5ed4680c82)

3) Ungroup only one drawing, this way works but the drawing that I ungroup have a different size and position that it had before

`Dim shape As ExcelDrawing = sheet3.Drawings.Item("TDS")`
`sheet3.Drawings.Item(0).Group(sheet3.Drawings.ToArray).Name = "Test"`
`shape.UnGroup()`

Original size and position:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/cadf2b8e-67f3-4ca2-b431-621da18d5a41)

Size and position after ungroup:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/86584a4a-415f-4d43-bd91-b9e4d509caea)

**Comment by JanKallman** [comment]
Can you provide your workbook and some code to test this?

**Comment by JanKallman** [comment]
This looks like a bug. I'll investigate and try to supply a fix.

**Comment by JanKallman** [comment]
Fix added. Feel free to test it [using our develop nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed)...

**Comment by JanKallman** [comment]
Fixed in 6.2.9
