### ISSUE TITLE
Handle missing part due to relationship

### ISSUE THREAD

**Issue by leecannon** [EPPlusSoftware/EPPlus#102]
With the latest version im still getting the error referenced by PR #84

Any chance of either merging or fixing in some other way?

**Comment by leecannon** [comment]
Looking at the latest code `ZipPackagePart GetPart(Uri partUri)` in Packaging\ZipPackage.cs throws an InvalidOperationException now.

Which is valid in the case where the the part is required to do some operation however in the context of `DeleteRelationsAndParts(Packaging.ZipPackagePart part)` in ExcelWorksheets.cs the part already not being present is not a fail state (just like File.Delete does not throw if the file already doesnt exist)

**Comment by JanKallman** [comment]
Ok, that's bad. When does this happend? External links? Can you supply a repro, so I can find out the real cause for this exception.

**Comment by JanKallman** [comment]
Made an additional change in v5.1.2. Re-open this issue if it does not work.
