### ISSUE TITLE
Rotate Image

### ISSUE THREAD

**Issue by FedePorti** [EPPlusSoftware/EPPlus#1037]
Is it possible to rotate an image? 
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/b5145a0f-c280-42ff-bfea-e3380e98e667)

**Comment by JanKallman** [comment]
No, not directly via the EPPlus API. 
I will add this as an enhancement for an coming version.

**Comment by AdrianEPPlus** [comment]
This was implemented in EPPlus 7.2.
