### ISSUE TITLE
CalcMode is not saved

### ISSUE THREAD

**Issue by Aurelianus** [EPPlusSoftware/EPPlus#1045]
It seems, that the CalcMode is Read correctly but not saved if changed.

**WORKS**
Create MS Excel File and set CalcMode to manual - open this File in Epplus the Field CalcMode represents ExcelCalcMode.Manual.

**FAIL**
Create Epplus File with CalcMode = manual, Save, Reopen CalcMode = Auto

This TestMethod fails
```
[TestMethod]
public void CalcMode()
{
    var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Test.xlsx");
    using (var package = new ExcelPackage(path))
    {
        package.Workbook.Worksheets.Add("Sheet1");
        package.Workbook.CalcMode = ExcelCalcMode.Manual;
    }

    using (var package = new ExcelPackage(path))
    {
        Assert.IsTrue(package.Workbook.CalcMode == ExcelCalcMode.Manual);
    }
}
```

**Comment by JanKallman** [comment]
You never save the package in your test, so it is never written to the output path. 
Adding `package.Save()`  after  `package.Workbook.CalcMode = ExcelCalcMode.Manual;`  and all seems to work as expected.

**Comment by Aurelianus** [comment]
Oh, thats right. Sorry for that one.
