### ISSUE TITLE
Printing spreadsheets to PDF or exporting to PDF

### ISSUE THREAD

**Issue by lafar6502** [EPPlusSoftware/EPPlus#1048]
Hi, i can't find much about the ability of EPPlus to print from Excel spreadsheets. 
Is printing supported and to what extent? I would like to print to PDF document, with results exactly the same as when printing from Excel. Is it possible? If so, which APIs to use for that?
Thank you
RG

**Comment by JanKallman** [comment]
No, EPPlus has no export to PDF. The only visual export we have is the HTML export. See https://samples.epplussoftware.com/HtmlExport.
I thing the Office 365 Graph API has a convert to pdf function, if that is an option for you, but I have not tried it.
