### ISSUE TITLE
On Column Deletion, Data Validations on multiple ranges are only retained for the first range.

### ISSUE THREAD

**Issue by as321d** [EPPlusSoftware/EPPlus#105]
EPPlus Latest Dev Version

I have validations on `{T4:T1048576,V4:V1048576,R4:R1048576}`.
When I delete a column to the left of all of these ranges, the validation's address becomes `{S4:S1048576}`, while I expect `{S4:S1048576,U4:U1048576,Q4:Q1048576}`.

I believe expected behavior would be as follows. All ranges to the right of the deleted column should be retained and shifted. If any of the ranges are to the left of the deleted column, they should remain where they are.

**Comment by JanKallman** [comment]
Deleting in comma separated addresses for Datavalidation and Conditional formatting didn't only effected the first address in the list. Fix applied. Need some more test before merge to develop.

**Comment by JanKallman** [comment]
Fixed in version 5.1.2
