### ISSUE TITLE
Question: cloning the spreadsheet in memory / faster initialization

### ISSUE THREAD

**Issue by lafar6502** [EPPlusSoftware/EPPlus#1064]
Hi, i need some advice

I'm using EPPlus (ver 4) for calculations in an application. The calculation logic is done in Excel, and the application is using EPPlus for running the calculation and getting results out.
The calculation is done many times and i need it to work quickly. But the calculation changes the spreadsheet contents (different input parameters are modified), so after calculating i can't reuse the same spreadsheet - need to load it again every time in order to be sure i'm starting from known state every time.
The problem: loading the excel file is a bit slow, takes about a second or more, and it becomes a problem if calculation needs to be done 20 times.
Question: how to make it faster? Is it possible, for example, to load spreadsheet just once into EPPlus object model, and only clone the object model in memory every time when i need to calculate?
Or any other ideas?

At the moment i'm using free EPPlus version 4.x.x, but if 5.x.x versions have some better capabilities in this regard then it's also good.
Thanks
RG

**Comment by swmal** [comment]
Hi,

not sure if I understand the scenario. 

Are you using the Calculate() method of EPPlus or are you triggering the calculation via Excel Interop or similar?

**Comment by lafar6502** [comment]
Hi, i'm using EPPlus, loading ExcelPackage from a file 
then set input parameters (put them into a numer of cells)
and then use Calculate method to calculate the results.
Not doing any Excel interop, relying just on EPPlus

The problem is that i need to repeat the calculation many times, but with different sets of input parameters. And making the calculation changes the contents of the spreadsheet (because inputs are modified), so i cant reuse the same loaded spreadsheet for next calculations. So i have to load it again, which is a bit costly and slow. 
Would be better if i could 'reset' the spreadsheet to an initial state, or to load it only once and then 'clone' in memory every time when i'm doing a calculation (so original stays the same, and i only calculate on cloned spreadsheet objects).

**Comment by lafar6502** [comment]
btw experimenting now with v5.8.14 and the speed seems to be better, so maybe upgrading it's the way to go

**Comment by swmal** [comment]
If you are going to use any later version than 4.* I would recommend you to use the latest stable version 6.2.9. We have improved the reliability of the formula calculation since v 5.8. You can also try the new version 7 beta which has a totally rewritten, faster calculation engine.

See https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-6 and https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-7

You can perhaps improve performance by using a MemoryStream to save the state instead of a file. If you do this:

``` cs
using(var package = new ExcelPackage())
{
   // do stuff...
   package.SaveAs(myMemoryStream);
}
```

The package will be saved to a memory stream instead of a file. You can then use that file as a parameter to the constructor of a new ExcelPackage instance.

Another potential improvement could be to just replace a single worksheet instead of reloading the entire workbook, but don't know if that is feasible in your case. From v5.8 you can copy worksheets and exclude formulas, values, etc so maybe you can do something with this too. See https://github.com/EPPlusSoftware/EPPlus/wiki/Copy-Ranges-or-Entire-Worksheets

**Comment by lafar6502** [comment]
thanks, i'm looking forward to your newest developments and will switch to 6/7 versions, but didnt want to jump too many releases at once. Thanks. And regarding the speed of loading excels, for now we can work on reducing their size because only few big ones were problematic.

**Comment by lafar6502** [comment]
Hi, now we've switched to v7.0.0
And would like to return to this issue.
We're duing more and more calculations via EPPlus, multiple times per request. And the loading time seems to be a bit of a problem still.
I have tried to implement some clever strategies for reusing already loaded spreadsheets, but it gets problematic - can't guarantee every calculation runs in the same initial state, there are some cases when the data in a spreadsheet is 'dirty' from previous calculation and it affects next calculations on the same spreadsheet instance. Since we don't have full control over the contents of Excel, it's always possible that an user will upload a version that's not immune to these problems and then they will get errors without any warning.
So for now i have removed my 'clever' logic and switched back to re-loading the Excel file every time calculation is done. 
Works nicely, but getting slower with increasing number of calculations and raising complexity of excel files.
So it's not something urgent, the application works, but would be nice to improve this case.

Example numbers: loading an Excel file 1000 times and doing some simple calculation takes about 11 seconds.
Doing the same calculation 1000 times without re-loading spreadsheet every time - 0.8 sec
So there's significant time difference between the two.
(it's not file I/O time because the contents are loaded from a memory stream- so it's time EPPlus needs to parse the input bytes and create in memory representation of the spreadsheet).

My idea would be to add some 'in memory clone' to ExcelPackage. So you load the initial version once, and then only clone it in memory for every calculation. I don't know the internals of EPPlus and have no idea if this would save significant time compared to normal Load(). Please let me know if this makes sense, and if so, i'd like to kindly ask you to add such function in future releases.

(edit: been thinking about this a little, i think some low hanging fruit would be to clone/reuse the underlying XML DOM  - this would save the time on loading and decompressing zip + parsing the XML again. Or maybe even the XML DOM is read only and never modified in memory, then it wouldn't even need to be cloned).

**Comment by swmal** [comment]
Hi,

If you want to reset the cell values added by a previous calculation you can call `package.Workbook.ClearFormulaValues()`, then you should be able to use the same ExcelPackage instance without having to recreate it. This method is also available on worksheets and ranges:

```csharp
using var package = new ExcelPackage(@"c:\myWorkbook.xlsx");
package.Workbook.ClearFormulaValues();
package.Workbook.Worksheets["sheet1"].ClearFormulaValues();
package.Workbook.Worksheets["sheet1"].Cells["A1:C13"].ClearFormulaValues();
```
So to recalc multiple times could look something like this:

```csharp
using var package = new ExcelPackage(@"c:\myWorkbook.xlsx");
package.Workbook.Calculate();
package.Workbook.ClearFormulaValues();
// change some values...
package.Workbook.Calculate();
package.Workbook.ClearFormulaValues();
// change some values...
package.Workbook.Calculate();
```

**Comment by swmal** [comment]
Closing this issue as it hasn't been active for a while.  Regarding cloning the internal state of EPPlus - the state is spread out over multiple Xml-documents and parts of it is stored in other structures until it is flushed out to a Stream on Save. So it would be risky and complex to try and create this kind of snapshots.
