### ISSUE TITLE
Worksheet Xml is invalid Exception

### ISSUE THREAD

**Issue by johnmiller86** [EPPlusSoftware/EPPlus#1065]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

6.2.3

### Description

We have a process that uses EPPlus to generate a set of files and a summary file based on the file calculations.  Our Underwriting team will then make some updates to the initial files and request a regenerated summary based on the updated files.  We have noticed on a handful of files that we receive the following error when trying to read in the modified files:

System.InvalidOperationException: Worksheet Xml is invalid at OfficeOpenXml.WorksheetZipStream.ReadToExt(String startXml, String uriValue, String& lastElement, String lastUri) at OfficeOpenXml.ExcelWorksheet.LoadExtLst(XmlReader xr, WorksheetZipStream stream, String& xml, String& lastXmlElement) at OfficeOpenXml.ExcelWorksheet.CreateXml() at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide) at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode) at OfficeOpenXml.ExcelWorkbook.get_Worksheets() at OfficeOpenXml.ExcelWorkbook.GetDefinedNames() at OfficeOpenXml.ExcelPackage.get_Workbook()

Updating to 6.2.9 does not resolve the issue.

The problem is that these files contain Production data and PII/PHI.  Is there a way to securely transmit a before and after file for review, and would EPPlus be able to provide some form of NDA that the files will not be shared?

**Comment by OssianEPPlus** [comment]
Hi there! As a commercial customer you should have access to our [high-priorty support](https://epplussoftware.com/en/Support)
There all ticket threads are private and any files shared unless otherwise requested by our customers are only used to resolve your issue and/or internal testing if we cannot re-create the issue in a simpler way.  We have no problem signing an NDA if proposed there.

**Comment by swmal** [comment]
If you don't have access to our online support, please send an email to info (at) epplussoftware.com (include the license number or your company name/address) and we will send out an invite.

**Comment by johnmiller86** [comment]
Thank you both, I have reached out to management to see if they were provided any credentials for the case system.  Please feel free to close this one out.
