### ISSUE TITLE
ToDataTable Performance and null handling

### ISSUE THREAD

**Issue by GhBogdan97** [EPPlusSoftware/EPPlus#1068]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

6.2.8

### Description

Hello, this issue has 2 parts:

Part 1

Performance Improvements suggestions for large data sets (300+ columns, 40.000+ rows).

In the DataTableExporter.cs class, Export method, populating a dataRow cells with values should be "wrapped" in dataRow.BeginEdit() and dataRow.EndEdit() methods. These would disable a series of events and triggers on DataTable level which would increase the performance.

![image](https://github.com/EPPlusSoftware/EPPlus/assets/36417662/bcb9faad-f718-4017-8823-129a1dc4bfd9)

Part 2

Although a DataTable column of type DateTime is marked as "nullable", it does not accept "null" as value, only DBNull.Value. Using ToDataTable for such column will make the method to crash. From my investigations this issue is coming from "ConvertUtil.GetValueDate" which will return null

**Comment by swmal** [comment]
Many thanks for this report. Sounds like valid points, will have a look at it.

**Comment by TCN-AlastairH** [comment]
Hi,

I'd like to raise that the "part 2" appears to be happening with other data types as well, not just the DateTime. I've only just found this thread after we were testing out the ToDataTable and hit what sounds like exactly the same problem with blank cells and where we've formatted that as a Number/Decimal data type in Excel.

Cheers!

**Comment by swmal** [comment]
@TCN-AlastairH Thanks for reporting and apologies for the late reply. We are looking into this.

**Comment by swmal** [comment]
@TCN-AlastairH  currently working on this,  see #1163 for progress.
