### ISSUE TITLE
Deleting multiple columns with non-default widths, then saving, creates a corrupted excel file

### ISSUE THREAD

**Issue by as321d** [EPPlusSoftware/EPPlus#107]
For one, when I delete a column, the new column in its place will not retain its width, and will instead revert to a default width (though reading its Width property says that it retains its width within EPPlus, that does not translate over into the actual Excel File).

A bigger issue that seems to spring from this is that when I delete more than 3 columns **that have non-default widths** , where at least one column is not adjacent to the other columns, the excel file that results is corrupted. It can be recovered, but this is evidently not ideal. 
Ex. Deleting columns B, D, E, F, and G, all with widths greater than the default, will lead to a corrupted file.

This issue does not appear for columns of default width.

**Comment by JanKallman** [comment]
ColumnMin and Column Max were not correctly updated when columns were deleted

**Comment by JanKallman** [comment]
Fixed in version 5.1.2
