### ISSUE TITLE
When insert image and merge cell,the image will getting stretched

### ISSUE THREAD

**Issue by amerina** [EPPlusSoftware/EPPlus#1074]
### EPPlus usage

Personal use

### Environment

.netFramework4.7

### Epplus version

4.5.2

### Description

What I think is that when merging cells, the image will only be displayed in the first cell, for example, the first cell of the second row and the first cell of the third row will be merged, and the image will only be displayed in the first cell of the second row, without the need to fill

**Comment by amerina** [comment]
ExcelRange range = sheet.Cells[1, 1,2, 1];
                range.Merge = true;
                range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                range.Style.VerticalAlignment = ExcelVerticalAlignment.Center;


                var imagePath = @“D:\timg.jpg”
                    using (ExcelPicture pic = sheet.Drawings.AddPicture("title" + 1, Image.FromFile(imagePath)))
                    {
                        var topLeftCell = sheet.Cells[1, 1];

                        // Set the position of the picture to the top-left cell
                        pic.SetPosition(topLeftCell.Start.Row - 1, 0, topLeftCell.Start.Column - 1, 0);
                        pic.SetSize(100, 100);
                        pic.EditAs = eEditAs.OneCell;
                    }

**Comment by swmal** [comment]
Version 4.5.2 is deprecated since years back. The newer versions are free to use for personal use so you can upgrade to version 6 and see if the problem persists.

See https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-5 and https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-6

**Comment by amerina** [comment]
Thanks for your reply，because my soft overall structure is older,

` using (ExcelPicture pic = sheet.Drawings.AddPicture("title" + rowIndex, new FileInfo(imagePath)))
                    {
                        pic.From.Row = rowIndex - 1;
                        pic.From.Column = columnIndex - 1;

                        pic.To.Row = rowIndex;
                        pic.To.Column = columnIndex;
                        pic.SetSize(100, 100);
                        //pic.SetPosition(rowIndex - 1, 1, columnIndex - 1, 1);
                    }` 
just use this method will not resize the picture,if anybody use this version
