### ISSUE TITLE
When line break in the drawing, the content after the line break is not read out. #106

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#108]
Continued confirmation of Issues 106

**Comment by 93910676wangd** [comment]
Additional documents

**Comment by 93910676wangd** [comment]
Why can't I upload my attachment?
Although drawing and xlsx files have been selected

Please don't close this issue first

**Comment by 93910676wangd** [comment]
There is a figure in the attachment test.xlsx, and there is a text with line breaks in the figure

Now according to Chen 106, there should be text after line break in richtext. Is there any problem in my understanding? Please confirm

But look at the debugger information. There are two nodes in richtext. The content of the nodes is the text in front of the line break. Am I wrong?

How can I get the text after the line break?

[test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4590809/test.xlsx)
![Rich Text](https://user-images.githubusercontent.com/19505572/81256637-a43f5f00-9063-11ea-9126-d4e87910072d.png)

**Comment by JanKallman** [comment]
Sorry for the late replay. Yes I see your point. Only the first paragraph was loaded when the `RichText` was loaded from the XML. 
Fix applied. You can try it from our develop [Nuget feed](https://ci.appveyor.com/project/EPPlusSoftware/epplus)

**Comment by JanKallman** [comment]
Fixed in Version 5.2
