### ISSUE TITLE
LoadingFromCollection does not exclude members not included in membersinfo[]

### ISSUE THREAD

**Issue by sofrr** [EPPlusSoftware/EPPlus#1092]
Hello,
this happens only in version 6.2.10. In 6.2.9 it works as expected.
Example : 

`var list = new List<MyClass>();
worksheetData.Cells.LoadFromCollection(list, true, TableStyles.None, System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public, someProperties.ToArray());
`
in MyClass i have a property not included in someProperties Array.
But i see that is generated in worksheetData

**Comment by swmal** [comment]
Hi,

thanks for reporting, we have replicated the issue and will fix it in the next version.

**Comment by swmal** [comment]
This should be fixed now, you can test it via our [development nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed) when the build is done. Will be included in the next version.
