### ISSUE TITLE
Hyperlink subaddress

### ISSUE THREAD

**Issue by nico579** [EPPlusSoftware/EPPlus#1107]
Excel exposes [Subaddress]( https://learn.microsoft.com/fr-fr/office/vba/api/excel.hyperlink.subaddress) for Hyperlink

EPPlus ignore this value (i have an .xlsx file with this value, and EPPlus get only [Hyperlink.Address](https://learn.microsoft.com/fr-fr/office/vba/api/excel.hyperlink.address)

EPPlus could exposes HyperlinkSubaddress

**Comment by JanKallman** [comment]
Is this an internal link inside a workbook?
In that case use ExcelHyperLink.ReferenceAddress ... 
https://epplussoftware.com/docs/6.2/api/OfficeOpenXml.ExcelHyperLink.html#OfficeOpenXml_ExcelHyperLink_ReferenceAddress
Access this properyt by type-casting your Uri to an ExcelHyperLink

**Comment by nico579** [comment]
No, it's a link to a web site :
The value is like this : http://xxx.yy/zzz/#aa,bb=cc

With Vba for Excel, it's ok to read the value  : 
Cells(1,1).hyperlinks(1).address -->  http://xxx.yy/zzz/
Cells(1,1).hyperlinks(1).subaddres --> #aa,bb=cc

With EPPLUS :
Hyperlink.ReferenceAddress --> nothing
Hyperlink.AbsoluteUri --> http://xxx.yy/zzz/
Hyperlink.AbsolutePath --> /zzz/ 
But nothing to get #aa,bb=cc value !

**Comment by JanKallman** [comment]
I see, thanks for letting us know. 
Excel stores this part in the `location` attribute, but EPPlus only reads this attribute for internal references in the workbook.
So if you have an external link the location attribute is ignored when reading the workbook.
We will to provide a fix for this.

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.2.11 and 7.0.0.
The ExcelHyperLink.ReferenceAddress will now contain the subaddress

**Comment by nico579** [comment]
Thank you so much !
Everything works wonderfully

I

Le jeu. 26 oct. 2023 à 16:10, Jan Källman ***@***.***> a
écrit :
