### ISSUE TITLE
read datetime error 2020/05/19 10:00:00 after read 2020/05/19 9:59:59

### ISSUE THREAD

**Issue by shmilyyan** [EPPlusSoftware/EPPlus#111]
When reading time type cells, some time values will be automatically reduced by one minute, as shown in the title

EPPlus nuget version: 4.5.3.3
File:
[importorder.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4628023/importorder.xlsx)

**Comment by JanKallman** [comment]
Yes, this is correct and by design. The values in the cells are different:
Cell T7 - 2020-05-21 10:00:00.0000000 - In Excel using numeric format : 43970,41666666670
Cell T8 - 2020-05-22 09:59:59.9950000 - In Excel using numeric format:  43971,41666660880
