### ISSUE TITLE
Excel Drawings DPI dependent

### ISSUE THREAD

**Issue by FedePorti** [EPPlusSoftware/EPPlus#1121]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

6.2.10

### Spreadsheet application

Excel

### Description

Hi, I have an Excel where I use create drawings (most of them rectangles and lines). I use the pixel measurement of my desktop screen that is 1920x1080 with a scale of 100%. And this is the result:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/3ff520ac-df65-4d5e-9227-309eef1f6d91)

But now I'm using my laptop with a screen of 2880x1800 with a scale of 175% and this is how the drawings look like:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/52248775/2f2b3799-51ab-4ac7-8c0f-0843cfc024eb)

If I change the scale of the laptop to 100% then the drawings are okay. Even if I created the excel with a scale of 175% then close the Excel, change the scale to 100% and open it.

How can I do to obtain the same drawing with a scale different of 100%?

I tried to use a multiplicative factor to the size and position of the drawings but I couldn't make it work.

**Comment by JanKallman** [comment]
Excel renders the workbook differently depending on your scaling settings, so you will never get it to look exactly the same in all resolutions / scales. You will get slightly different column widths depending on your device scale and drawings are dependent on column widths.
