### ISSUE TITLE
Ignore the warning 'This formula in this cell refers to a range that has additional numbers adjacent'

### ISSUE THREAD

**Issue by juanan** [EPPlusSoftware/EPPlus#1135]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.0.0.2

### Spreadsheet application

Excel

### Description

Hi,

How could I disable in C# this warning?

<img width="344" alt="image" src="https://github.com/EPPlusSoftware/EPPlus/assets/17723190/a69de78c-e1fd-42f1-b413-5dd454c00286">

Many thanks.

**Comment by JanKallman** [comment]
You should be able to use the IgnoredErrors collection. See... https://github.com/EPPlusSoftware/EPPlus.Samples.CSharp/tree/master/01-Workbook%20worksheet%20and%20ranges/10-Ignore%20errors
