### ISSUE TITLE
OfficeOpenXml.ExcelRangeBase.Finalize

### ISSUE THREAD

**Issue by lrwaltz** [EPPlusSoftware/EPPlus#1136]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

4.0.5.0

### Spreadsheet application

Excel

### Description

应用程序异常终止
System.OutOfMemoryException
   在 OfficeOpenXml.ExcelRangeBase.Finalize(）

**Comment by JanKallman** [comment]
We don't support EPPlus 4.0.5 here, only version EPPlus 5 and forward.
