### ISSUE TITLE
v7 Auto Filter causing error on Excel

### ISSUE THREAD

**Issue by supertx2** [EPPlusSoftware/EPPlus#1142]
Diff between v6 and v7
![image](https://github.com/EPPlusSoftware/EPPlus/assets/13727650/7d1cd092-bed9-4b51-8602-22be3c3ebfdb)

![image](https://github.com/EPPlusSoftware/EPPlus/assets/13727650/158b34e2-4200-4648-acd4-caa8bd42d449)

**Comment by OssianEPPlus** [comment]
This is a known bug. We've made a fix which is out in our [NuGet develop feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed).

**Comment by OssianEPPlus** [comment]
The fix for this is released as of 7.0.1
