### ISSUE TITLE
Uninitialized CodeModuleName when Cloning Sheets

### ISSUE THREAD

**Issue by Kizaemon** [EPPlusSoftware/EPPlus#1145]
When copying a worksheet (e.g. using `Worksheets.Add(newname, template)`), the `d:sheetPr/@codeName` attribute is being copied from the template to the cloned sheet.

But if there is no VbaProject or CodeModule, the `d:sheetPr/@codeName` is left unchanged in the cloned sheet.

https://github.com/EPPlusSoftware/EPPlus/blob/796c3c7391432b7b7ac50d05fd03681f96690efb/src/EPPlus/Core/Worksheet/WorksheetCopyHelper.cs#L137C29-L137C29

This leads to the state, when all cloned sheets have the same `d:sheetPr/@codeName`, equal to the template's name.

During the save the names are disambiguated, leading to the name length overflow:

Template: Sheet3
Clone1: Sheet31
Clone3: Sheet311
Clone4: Sheet3111
Clone5: Sheet31111
Clone6: Sheet311111
...
Clone30: Sheet311111...1 (<- invalid, too long)

Suggestion is to clear the `d:sheetPr/@codeName` attibute, if there is no VbaProject or CodeModule, or to set it to the name of the cloned sheet.

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this.

**Comment by JanKallman** [comment]
Fixed added in 6.2.12 and 7.0.1
