### ISSUE TITLE
v6 - Adding a sheet by object from one [OfficeOpenXml.ExcelPackage] instance to another drops Images in Header/Footer

### ISSUE THREAD

**Issue by dbronson4672** [EPPlusSoftware/EPPlus#1146]
I can provide some sudo code for this if needed (Powershell), but basically this is the scenario

I am Adding a sheet from one instance to the other by reference using the following method

OfficeOpenXml.ExcelWorksheet Add(string Name, OfficeOpenXml.ExcelWorksheet Copy)

If the worksheet has images in the headers and footers they are dropped as part of the copy method.  My example had 5, not sure if it matters (Top left, Top Right, Bottom Left, Bottom Right and bottom centre

I have two instances of of the object
First instance has the source template and the second instance is a new excel doc

$TargetExcelDoc.Workbook.Worksheets.Add("SHEETNAME", $sourcesheet)

The body of the document is copy, but the images in the headers are dropped.

Not sure if it helps or not
- Problem does not seem to affect the Copy Method OfficeOpenXml.ExcelWorksheet Copy(string Name, string NewName).   However this is copying a sheet within the same instance/document
- The issue raised in #1143 where images are lost during copy occured as well 
- I did not look at the clone methods to see if it is impacted ?

Example Source sheet Header

![image](https://github.com/EPPlusSoftware/EPPlus/assets/28630767/c44e0748-26ab-4255-9815-d0286733de7a)

Example Target Heeader

![image](https://github.com/EPPlusSoftware/EPPlus/assets/28630767/49fa0a7a-054c-4fa5-bab8-57c011d992bc)

**Comment by swmal** [comment]
Thanks for reporting, we will have a look at this.

**Comment by JanKallman** [comment]
Fixed in 6.2.12 and 7.0.1
