### ISSUE TITLE
Creating NamedRange for range containing different areas

### ISSUE THREAD

**Issue by fredbalkenende** [EPPlusSoftware/EPPlus#115]
This goes wrong. Please look at the picture in the bottom. The correct formula for a range consisting of different areas in this case would be: 'Slide4'!$B$6:$D$8;'Slide4'!$B$10:$D$11

The rng.Address and rng FullAddress, which both have these (correct) values. The rng.FullAddressAbsolute looks wrong too. Giving this range a name results in the problem in the picture.

After this error, it is not possible to open the workbook anymore using EPPlus. It fails with the following stack-trace:

   at OfficeOpenXml.ExcelRangeBase..ctor(ExcelWorksheet xlWorksheet, String address)
   at OfficeOpenXml.ExcelNamedRangeCollection.Add(String Name, ExcelRangeBase Range)
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()

![image](https://user-images.githubusercontent.com/44227347/82812342-1e107e80-9e93-11ea-8156-ac1a457d4833.png)

Regards
Fred

**Comment by JanKallman** [comment]
Can you attach a workbook reproducing this issue?

**Comment by fredbalkenende** [comment]
Here you are.
[RD7 - Error2.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4680501/RD7.-.Error2.xlsx)

**Comment by JanKallman** [comment]
Fails on this worksheet defined name:
`<definedName name="ORRange42">'$B$6:$D$8;Slide4'''!$B$10:$D$11</definedName>`
EPPlus expects a worksheet reference to start the address for a workbook scoped defined name, so I'll have to investigate the format of this address reference.

**Comment by fredbalkenende** [comment]
The problem is that EPPlus creates this wrong worksheet reference.

The named range is created using EPPlus using a range with address 'Slide4'!$B$6:$D$8;'Slide4'!$B$10:$D$11

Afterwards, EPPlus has created a named range refering to this misformed address.

**Comment by JanKallman** [comment]
Thanks, that makes more sense.

**Comment by JanKallman** [comment]
Seems to work when I try it...
```
                var ws = p.Workbook.Worksheets.Add("DefinedNamesIssue");
                p.Workbook.Names.Add("Name", ws.Cells["B6:D8,B10:D11"]);
```
Can you provide your code to reproduce the problem?

**Comment by fredbalkenende** [comment]
Ok, apparently you need to use a comma to separate the areas, not a semicolon as I was using. (Excel shows a semicolon.)

I still have a little problem. Please have a look at the attached picture which is showing the range object's properties in the debugger. 
1. The 'FullAddress' now contains the range address twice 
2. 'Rows' has value 3, while the correct value is 5. The same error happens when looping over all cells in this range: Only the cells from first area are used.

![RangeProperties](https://user-images.githubusercontent.com/44227347/82993757-63eb5500-a001-11ea-982b-932ff6126a25.png)

**Comment by JanKallman** [comment]
Yes, semi-colon is the localized separator. The OOXML format uses the invariant separator ",". 
I have fixed the FullAddress issue. Will be applied in the next release.

**Comment by fredbalkenende** [comment]
Thanks for your help Jan!
