### ISSUE TITLE
Getting out of memory exception when trying to load a 65 Mb file.

### ISSUE THREAD

**Issue by TBaltzer** [EPPlusSoftware/EPPlus#1151]
Here is the code snippet:

                FileInfo myExcelFile = new FileInfo(sFilePath);
                using (ExcelPackage xlPackage = new ExcelPackage(myExcelFile))
                {
                    foreach (ExcelWorksheet worksheet in xlPackage.Workbook.Worksheets)

File was too big to upload so I provided a sample.  You can copy/paste to create the full size file.

There are 1 million rows in the original
[sample.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13298948/sample.xlsx)

**Comment by JanKallman** [comment]
You are out of memory. Make sure you compile x64 or Any CPU and do not have the prefer 32-bit flag set. Otherwise increase the memory on you machine. You should look at the unextracted size of you workbook to get an idea of the size of the data (rename you xlsx to *.zip).
