### ISSUE TITLE
Filter Sort Uniqe return #VALUE in some of our cases w nested cells, and Unique return 0 not blank

### ISSUE THREAD

**Issue by Watvedt** [EPPlusSoftware/EPPlus#1156]
In evaluation of EPPlus 7 for the FSU formulas Filter Sort Uniqe, our testing of the free limited version has revealed bugs in those dynamic functions.
This is what or developer Imre says:

Hello,
My mistake that EPPLUS does not return #NAME but #VALUE in some of our cases (nested cells). I created the attached excel workbook that I tested with. The problem for us is that UNIQUE return 0 in empty cells and adds an extra 0 value as last elements when in excel it should be nothing.
In the example excel table for example if we read 'D4' it returns 0 instead of an empty string and 'D6' also return 0 instead of empty string.And because we use those values later we get 0-s where we should not..Bests,Imre

NOTE: Not possible to attach xlsm files, so I have sent test file by email to Jan Källman.

Regards, Jørn Watvedt, Widemore as

**Comment by JanKallman** [comment]
This is a bug in the range not equal operator which fails to compare null values and empty strings. 
I will provide a fix shortly.
I can't see any #Value errors in this file, so if you experience issues with this please provide a reproducible sample.

**Comment by JanKallman** [comment]
This should now be fixed. You can test it using our develop nuget feed...
https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed

**Comment by Watvedt** [comment]
Fix has been tested in our environment, and we herewith confirm that the initial bug i fixed.
However, this fix uncovered a second bug: In our spreadsheet we have specific columns where the entire row can be empty so we are not only using FILTER inside UNIQUE, but also IF. 

Example: =UNIQUE(IF(C2:C12<>"",C2:C12),,-1) which is evaulated to #VALUE

I modified the sample table to include this functions in "G" column so for example G2 will be #VALUE
Link for table: 

https://www.dropbox.com/scl/fi/8an6033cngh4dqbmzh9hg/Book1.xlsm?rlkey=ni2304v8b4etzmtvgdizkhr1w&dl=0

Regards, Jørn Watvedt

**Comment by JanKallman** [comment]
Thanks, I'll have a look at it.

**Comment by JanKallman** [comment]
This is a bug. It happens when you use a blank parameter in the Unique function. I will provide a fix shortly. A workaround for now is to use `false` in the second parameter.

**Comment by JanKallman** [comment]
The second issue should now be fixed and can be tested via our develop Nuget feed.

**Comment by swmal** [comment]
PR #1161 is now merged into our develop7 branch and can be tested via our develop nuget feed.

**Comment by Watvedt** [comment]
Thank you for superfast response. We need some more time to test out this second fix, because we are in the middle of some other pressing issues. Regards, Jørn Watvedt

**Comment by JanKallman** [comment]
Fixed in 7.0.2

**Comment by Watvedt** [comment]
We have now had the opportunity to revisit this issue, and test. 
Confirm that we have tested and that issue is fixed. 
Thank  you for your effort.
Regards, Jørn Watvedt
