### ISSUE TITLE
Nested columns output in wrong order

### ISSUE THREAD

**Issue by grosch-intl** [EPPlusSoftware/EPPlus#1167]
Sorry if this lives somewhere else, but I'm not seeing it on the existing ticket.  This is a much higher priority for me than the other enhancements you're working on for me.

I need nested columns to appear in the "correct" order.  In the below example, Foo is first and Baz is last, but for the employee, it does not appear in the order of Id, then Name, then EmailLink.

```csharp
[EPPlusTableColumnSortOrder(Properties = new string [] { nameof(Foo), nameof(Owner), nameof(Baz) }]
class Outer {
   [EpplusTableColumn(Header = "Foo")]
   public string Foo { get; set; }

   [EpplusNestedTableColumn(HeaderPrefix = "Space Manager")]
   public EmployeeDTO Owner { get; set; }

   [EpplusTableColumn(Header = "Foo")]
   public string Foo { get; set; }
}

[EPPlusTableColumnSortOrder(Properties = new string[] {nameof(Id), nameof(Name), nameof(EmailLink) })
]
public class EmployeeDTO {
    [EpplusIgnore]
    public required bool Active { get; init; }

    [EpplusIgnore]
    public required string? Email { get; init; }

    [EpplusTableColumn(Header = "Email"), JsonIgnore, Ignore]
    public ExcelHyperLink? EmailLink {
        get {
            if (Email is null)
                return null;

            return new ExcelHyperLink($"mailto:{Email}") {
                Display = Email
            };
        }
    }

    [EpplusTableColumn(Header = "WWID")]
    public required int Id { get; init; }

    [EpplusTableColumn(Header = "Name")]
    public required string? Name { get; init; }
}
```

**Comment by swmal** [comment]
**Edit:** This "lived" in https://github.com/EPPlusSoftware/EPPlus/issues/946#issuecomment-1691266002

I have added these to the common issue #1058 

Will start working on this in parallel with the dictionary piece.

**Comment by grosch-intl** [comment]
Thanks.  I was going to reply telling you why that didn't work and then it finally clicked in my brain you said STRING, so I put `"Owner.Name"` instead of the non-valid `nameof(Owner.Name)` :)

This is a good workaround for me until there's full support, and keeps me from getting 100 tickets on Wednesday when I release this tool.  Thanks!
