### ISSUE TITLE
EPPlus 4.5.3.3 - Issue in created Excel file

### ISSUE THREAD

**Issue by gkmspl** [EPPlusSoftware/EPPlus#1184]
We have an asp.net/c# application that adds to an existing blank Excel file and then does a SaveAs to a new .XLSX file.

Such files are not opening from Excel 2019+, but are opening in earlier versions of Excel and also WPS

We are using EPPlus 4.5.3.3 

What could be the issue?

Thanks in advance!

**Comment by JanKallman** [comment]
EPPlus 4.5.3.3 is deprecated and no longer maintained. Please upgrade to a newer version.
