### ISSUE TITLE
Key not found exception when accessing Workbook.Worksheets Property

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#120]
I wrote a very simple console program to isolate this issue.  I am opening an existing Excel *.xslm file and upon accessing the ExcelPackage.Workbook.Worksheets property I receive a "The given key was not present in the dictionary." exception.  Stacktrace below.  I have no issue opening this file with Excel from Office 2016.  I can open other similar files with EPPlus 5.1.2 just fine.  Could there be something about this particular file that is revealing this bug?

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()
   at TestAppEPPPLus.Program.Main(String[] args) in C:\source\TestAppEPPPlus\TestAppEPPPLus\TestAppEPPPLus\Program.cs:line 30

**Comment by JanKallman** [comment]
Very possible. Looks from the stack trace that it is a problem with the reference to the worksheet from a defined name. Can you attach the workbook?

**Comment by rdhasse** [comment]
Hi Jan,

Unfortunately, I cannot it contains sensitive financial data.

I was able to fix the issue locally by simply adding an IF statement and all UT's still pass.  I tried to push it as a feature branch and got a "permission denied" error.   Is there a way for me to create a MR?

Randall

**Comment by JanKallman** [comment]
Hello,
If you use the Polyform Non-Commercial license (for non commercial organisations/companies) you can create a pull request [here ](https://github.com/EPPlusSoftware/EPPlus/pulls) with your changes. If you have a Commercial license you can upload your workbook to our support portal at our website (it's private and feel free to remove any sensitive data) and we'll help you fixing the issue.

**Comment by rdhasse** [comment]
I'm still getting a permission error when trying to push the bug fix branch:

remote: Permission to EPPlusSoftware/EPPlus.git denied to rdhasse.
fatal: unable to access 'https://github.com/EPPlusSoftware/EPPlus.git/': The requested URL returned error: 403

Is there someone that can assist?

**Comment by JanKallman** [comment]
You cant push directly to the repo. You have to create a pull request from your own branch.

**Comment by rdhasse** [comment]
I can't create a pull request if my branch doesn't exist in the remote repo.

**Comment by JanKallman** [comment]
You create the branch in your own repo. For example, look at this closed pull request...  [this](https://github.com/EPPlusSoftware/EPPlus/pull/90)

**Comment by rdhasse** [comment]
I did.  I created a branch locally.  The permission error occurs when I try to push my local branch to the remote repo.  

I work with git everyday so I'm confused about this permission issue.

**Comment by JanKallman** [comment]
You don't have permission to push directly to this repository, so you have to make a clone on your own account. Then create a branch with your changes from the develop branch and create a pull request into this repository again

**Comment by JanKallman** [comment]
You are still trying to push to our repository. Create your own repository by clicking the **Fork** button up to the left. 
![image](https://user-images.githubusercontent.com/982881/84372702-cdf82280-abdb-11ea-818f-772df5439bec.png)
Then clone it locally, make your change, push and create a pull request to this repo.

**Comment by rdhasse** [comment]
Ah yes I didn't realize I needed to fork the entire repo.  I've created a pull request.  Thanks for your help.

**Comment by JanKallman** [comment]
Fixed in Version 5.2
