### ISSUE TITLE
We get incorrect value for a custom format string, on a Norwegian culture.

### ISSUE THREAD

**Issue by vivet** [EPPlusSoftware/EPPlus#1200]
In the attached excel (inside the zip) the formatting is not correct. 
I also added a small C# application that proves the problem.

Let me know if you need more information :-)
[EPPlusNegativeValue.zip](https://github.com/EPPlusSoftware/EPPlus/files/13557162/EPPlusNegativeValue.zip)

**Comment by JanKallman** [comment]
Thank you for reporting this. I'll provide a fix shortly.
It seems that Norwegian culture uses a Unicode negative sign, 0x2212 '−', that differs from the standard 0x2D '-' in later version of .NET  .NET Framework seems to have the normal ASCII negative sign. 
I will use the CurrentCulture.NumberFormat.NegativeSign for this in the future.
