### ISSUE TITLE
Invalid content type Part Uri=/xl/richData/rdRichValueTypes.xml in v7.0.2 and v7.0.3

### ISSUE THREAD

**Issue by ses4j** [EPPlusSoftware/EPPlus#1202]
After we write with EPPlus, we try to read the output with:

```
// Both 2.x and v3.0.0
using DocumentFormat.OpenXml.Packaging;  
SpreadsheetDocument.Open(filePath.ToString(), true);
```

and that read crashes starting in v7.0.2 with:

```
DocumentFormat.OpenXml.Packaging.OpenXmlPackageException: The document cannot be opened because there is an invalid part with an unexpected content type.
[Part Uri=/xl/richData/rdRichValueTypes.xml],
[Content Type=application/xml],
[Expected Content Type=application/vnd.ms-excel.rdrichvaluetypes+xml].
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
```

Did something rtf-related get added in v7.0.2?  idk for sure this is an EPPlus problem, but the other library probably effectively defines the standard.

By the way, we use OpenXml to access `RibbonAndBackstageCustomizationsPart.CustomUI`, so consider this also a feature request. :)

**Comment by JanKallman** [comment]
RichData support was added in EPPlus 7, as it's used for dynamic array formulas. Do you get an error on this in the ooxml SDK validation  as well?
Also, can you add a workbook with this issue?

**Comment by OssianEPPlus** [comment]
Closed due to inactivity.
