### ISSUE TITLE
ArgumentOutOfRange accessing Worksheets property

### ISSUE THREAD

**Issue by EsbenRud** [EPPlusSoftware/EPPlus#121]
Hi, I get an ArgumentOutOfRangeException when trying to get Worksheets[0]. I have attached a .NET project that you can run to recreate the issue. The Excel file is in the Debug folder of the project.
If I open the excel-fiel with Excel and save it again then EPPLus doesn't throw an exception. 

[ConsoleApp26.zip](https://github.com/EPPlusSoftware/EPPlus/files/4757342/ConsoleApp26.zip)

**Comment by JanKallman** [comment]
EPPlus fails on loading the normal style of this workbook. I will try to provide a fix shortly

**Comment by JanKallman** [comment]
Fix applied 99b5f34. The problem was that the normal style was missing the FontId. This caused the crash. FontId's are optional, so now a missing font, fill, border or numberformat will result in the first item in the corresponding collection.

**Comment by EsbenRud** [comment]
Thanks a lot, are there any ways for me to test the fix?

**Comment by JanKallman** [comment]
Yes, try the latest develop build from our nuget feed… https://ci.appveyor.com/nuget/epplus

**Comment by EsbenRud** [comment]
The link seems bad, just says "Default Packages".

**Comment by JanKallman** [comment]
It's a nuget feed. Add it to Visual Studio - Options - Package Sources. 
Or if you prefer to download it locally you will find it here…
https://ci.appveyor.com/project/EPPlusSoftware/epplus/build/artifacts

**Comment by EsbenRud** [comment]
Thanks, it works great.

**Comment by JanKallman** [comment]
Fixed in Version 5.2
