### ISSUE TITLE
ExcelTable.ToToDataTable Conversion exception occurs if there are some special formats

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1210]
I use the latest EPPLUS7 method, in ExcelTable.ToToDataTable method, if the table has some special format, the CellValue of the converted DataTable will show some xml strings.

Something like here:
"<r xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main""><t>MOV_NONE</t></r><r xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main""><rPr><sz val=""11"" /><color theme=""1"" /><rFont val=""等线"" /><family val=""3"" /><charset val=""134"" /><scheme val=""minor"" /></rPr><t>_T00</t></r><phoneticPr fontId=""34"" type=""noConversion"" xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main"" />"
![image](https://github.com/EPPlusSoftware/EPPlus/assets/28550438/a41b6bb1-228a-424c-a9c9-d52467993bbb)

my code is here:
`                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using (ExcelPackage excelPackage = new ExcelPackage(@"C:\Users\19026\Desktop\test.xlsx"))
                {
                    var sht = excelPackage.Workbook.Worksheets["Sheet1"];
                    var excelTable = sht.Tables[0];

                    ToDataTableOptions toDataTableOptions = ToDataTableOptions.Create();
                    toDataTableOptions.EmptyRowStrategy = EmptyRowsStrategy.Ignore;
                    toDataTableOptions.ExcelErrorParsingStrategy = ExcelErrorParsingStrategy.HandleExcelErrorsAsBlankCells;

                    for (int i = 0; i < excelTable.Columns.Count; i++)
                    {
                        toDataTableOptions.Mappings.Add(i, excelTable.Columns[i].Name, typeof(object), true, s => s is OfficeOpenXml.ExcelErrorValue ? s.ToString() : s);
                    }

                    var dt = excelTable.ToDataTable(toDataTableOptions);

                }`

[test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13647190/test.xlsx)

**Comment by swmal** [comment]
Thanks for reporting, we will have a look at this.

**Comment by swmal** [comment]
@minren118 - We have fixed this in our develop-branches for v6 and v7. The fix will be included in the next release.

**Comment by sgada** [comment]
Hi 
If there are empty cells, the following code is erroring at the linq statement dt = worksheet.Cells[1, 1, worksheet.Dimension.End.Row, worksheet.Dimension.End.Column].ToDataTable(c => 

Even with the property   c.EmptyRowStrategy = OfficeOpenXml.Export.ToDataTable.EmptyRowsStrategy.Ignore; 

Please take a look and help.


  ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            //var xlpackage = new ExcelPackage(filepath);
            // get the first worksheet in the workbook
            using (ExcelPackage xlpackage = new ExcelPackage(filepath))
            {
                var worksheet = xlpackage.Workbook.Worksheets[sheetname];
                if (sheetname.Contains("Planning"))
                {
                    dt = worksheet.Cells[1, 1, worksheet.Dimension.End.Row, worksheet.Dimension.End.Column].ToDataTable(c =>
                    {
                        c.FirstRowIsColumnNames = true;
                        c.EmptyRowStrategy = OfficeOpenXml.Export.ToDataTable.EmptyRowsStrategy.Ignore;
                        c.ExcelErrorParsingStrategy = OfficeOpenXml.Export.ToDataTable.ExcelErrorParsingStrategy.HandleExcelErrorsAsBlankCells;
                    });
                    //Remove empty rows
                    if (dt.Rows.Count > 0)
                    {
                        dt = dt.Rows
                            .Cast<DataRow>()
                            .Where(row => !row.ItemArray.All(f => f is DBNull ||
                                             string.IsNullOrEmpty(f as string ?? f.ToString())))
                            .CopyToDataTable();

**Comment by swmal** [comment]
We'll have a look.

**Comment by swmal** [comment]
@sgada - I need a reproducible sample. Please upload the workbook you are using in the code this issue (or just a workbook that replicates the error). Also make sure that the code you provide to replicate the bug compiles without errors.
