### ISSUE TITLE
Inserting row into table with 'table formulas' throws InvalidFormulaException

### ISSUE THREAD

**Issue by aco45** [EPPlusSoftware/EPPlus#1214]
Hello All,

From version 7.0.0 to actual 7.0.3 (works perfectly prior to 7.0.0).
When inserting a row into a table with 'table formulas' (ex: [@[DQR_COMPLETENESS]]+[@[DQR_RELIABILTY]]),
SourceCodeTokenizer.Tokenize throws an InvalidFormulaException : Number of opened and closed brackets does not match.

[] [ERROR] [DQRJob] - [user:] - [job:]  Error on Job execution
OfficeOpenXml.FormulaParsing.Exceptions.InvalidFormulaException: Number of opened and closed brackets does not match
   à OfficeOpenXml.FormulaParsing.LexicalAnalysis.SourceCodeTokenizer.Tokenize(String input, String worksheet)
   à OfficeOpenXml.Table.ExcelTableColumn.SetFormulaCells(Int32 fromRow, Int32 toRow, Int32 colNum)
   à OfficeOpenXml.Core.Worksheet.WorksheetRangeInsertHelper.InsertRowTable(ExcelWorksheet ws, Int32 rowFrom, Int32 rows)
   à OfficeOpenXml.Core.Worksheet.WorksheetRangeInsertHelper.InsertRow(ExcelWorksheet ws, Int32 rowFrom, Int32 rows, Int32 copyStylesFromRow)

You can find a Template Excel file attached.
[Template.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13662852/Template.xlsx)

I think it has everything to do with the '@' token used to refer to a field into the table.

**Comment by JanKallman** [comment]
This issue is fixed and will be released with 7.0.4, released today. You can try it using our develop7 Nuget  feed when PR #1212 has been merged... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed

**Comment by JanKallman** [comment]
We will release 7.0.4 tomorrow.

**Comment by JanKallman** [comment]
Fixed in 7.0.4
