### ISSUE TITLE
"Method not found" exception when using Microsoft.IO.RecyclableMemoryStream version 3.0.0

### ISSUE THREAD

**Issue by luronumen** [EPPlusSoftware/EPPlus#1215]
**Actual Result**
- _Method not found_ exception when using _[Microsoft.IO.RecyclableMemoryStream version 3.0.0](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/3.0.0)_

![Exception](https://github.com/EPPlusSoftware/EPPlus/assets/8019466/b0da8d6b-fb94-4dee-bf4a-3ba82ad2ed97)

**Expected Result**
- No exceptions should occur when using _[Microsoft.IO.RecyclableMemoryStream version 3.0.0](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/3.0.0)_

**Important Notes**
- This issue does NOT happen when using when using _[Microsoft.IO.RecyclableMemoryStream version 2.3.2](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/2.3.2)_

**Environment Setup**
- _Windows 11 Pro Version 23H2_
- _Visual Studio 2022 Version 17.8.3_
- _.NET Framework 4.8.1_

**Comment by JanKallman** [comment]
EPPlus 7 is built against Microsoft.IO.RecyclableMemoryStream version 2.3.2, so using version 3.0 has not been tested by us. Looking at the error message you get, version 3.0 does not seem to be backward compatible.

**Comment by luronumen** [comment]
Hi @JanKallman

Thank you very much for your quick response!

Exactly! _[Microsoft.IO.RecyclableMemoryStream version 3.0.0](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/3.0.0)_ was recently released (3 days ago) and I decided to open this bug to make you aware of this incompatibility so that you can work on a future version of EPPlus 7 that supports version 3.0.0.

My concern is that other NuGet packages of my software start to be dependent on this version 3.0.0 and I have to choose not to upgrade because EPPlus 7 does not support version 3.0.0.

Best Regards,
Luciano

**Comment by JanKallman** [comment]
Ok, I'll add this as an enhancement. We will look into upgrading to version 3.0 in a coming version.

**Comment by luronumen** [comment]
Thank you very much @JanKallman !
Please let me know if you need my help for validating the update when it becomes available.

Best Regards,
Luciano

**Comment by JanKallman** [comment]
I have just upgraded to Microsoft.IO.RecyclableMemoryStream 3.0.0, so you can try the latest develop7 build ... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed.
The upgrade is made for targeting framework: .NET Standard 2.0 & 2.1 and .NET 6, 7 and 8

**Comment by luronumen** [comment]
Hi @JanKallman 

I followed your instruction and retested this issue using the using the _EPPlus version 7.0.5.573-20231227-develop7_ with the _Microsoft.IO.RecyclableMemoryStream version 3.0.0_ and the issue is still reproducible:

![image](https://github.com/EPPlusSoftware/EPPlus/assets/8019466/14763a27-33d7-4f5a-8173-ccf88859de27)

BTW, Could you also update the minimal _Microsoft.IO.RecyclableMemoryStream_ version to at least **2.3.2** for _.NETFramework, Version=v4.6.2_:

![image](https://github.com/EPPlusSoftware/EPPlus/assets/8019466/eae8e083-5ae2-4802-bc08-c06687c4caaf)

Thanks in advanced,
Luciano

**Comment by JanKallman** [comment]
Yes, we have only upgraded targeting framework for .NET Standard 2.0 & 2.1 and .NET 6, 7 and 8 in this build, but I see that 4.6.2 is supported as well. I will upgrade 4.6.2 to 3.0.0 in the next commit.

**Comment by luronumen** [comment]
@JanKallman 

I am using the _EPPlus 7_ for a _.NET Framework 4.8.1_ software project. Based in your last comment probably this is the reason why I am still able to reproduce the issue.

Best Regards,
Luciano

**Comment by JanKallman** [comment]
I just committed an update for this. Try again when the build [7.0.5.575-20231228-develop7](https://ci.appveyor.com/project/EPPlusSoftware/epplus7/builds/48843253) has finished.

**Comment by luronumen** [comment]
Retest result on _EPPlus version 7.0.5.574-20231228-develop7_ with the _Microsoft.IO.RecyclableMemoryStream version 3.0.0_: **PASSED!**

Thank you very much for the fix, @JanKallman !

Best Regards,
Luciano

**Comment by elite-conveyancing** [comment]
hi @JanKallman, when do you expect to release this fix? Thanks

**Comment by JanKallman** [comment]
We will likely create a new release next week.

**Comment by birbilis** [comment]
Please also see this thread: https://github.com/dotnet/Open-XML-SDK/issues/1638

@twsouthwick has offered to provide guidance on migration to newer OpenXml if needed
btw, I find it a bit misleading to use namespace starting with OfficeOpenXml for the ExcelPackage class, didn't notice the issue was coming from EPPlus at first look of the stacktrace

**Comment by birbilis** [comment]
Seems latest EPPlus (7.0.8) now brings in latest RecyclableMemoryStream (3.0.0) as dependency.

Luckily EPPlus is **now fixing the issue** with the ExcelPackage constructor trying to use a missing method from RecyclableMemoryStream 

I had originally reported the issue at https://github.com/dotnet/Open-XML-SDK/issues/1638 and https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/issues/324 confused by the ExclePackage class being an OfficeOpenXml namespace (hadn't noticed it was coming from EPPlus and not from OpenXml SDK)

So I guess you can probably close this issue since it seems to be the same one I was having

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.0.8

**Comment by luronumen** [comment]
> Fixed in EPPlus 7.0.8

Thank you very much @JanKallman 

Best Regards,
Luciano
