### ISSUE TITLE
Incorrect result when formula references negative values  

### ISSUE THREAD

**Issue by smac123** [EPPlusSoftware/EPPlus#1216]
Example 

A1 = -1.5
B1 = -5.0
C1 = 1.5;

Formula:  
=IF((A1+B1)<0,(-A1+-B1)*C1,0)

Epplus result is -5.25 but should be 9.75

**Comment by JanKallman** [comment]
Thanks for reporting this. I will have a look at it.

**Comment by JanKallman** [comment]
This is a bug. It looks like having double negations in of two cells in an expression causes this issue. I will investigate and provide a fix asap.

**Comment by smac123** [comment]
Thanks for looking into this so quickly...

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.0.5
