### ISSUE TITLE
Cannot read 'ExcelConditionalFormattingThreeColorScale' conditional formatting definition

### ISSUE THREAD

**Issue by fredbalkenende** [EPPlusSoftware/EPPlus#122]
Hi Jan

Trying to read such a definition, the LowValue and HighValue properties are 'null' while the Node contains the correct xml-information. Please have a look at the picture. Same problem for the 'ExcelConditionalFormattingTwoColorScale'

Regards
Fred

![image](https://user-images.githubusercontent.com/44227347/84267747-da6e7380-ab26-11ea-82ec-601203e059e3.png)

**Comment by JanKallman** [comment]
Yes, fix applied for Two- and Three- color scales

**Comment by fredbalkenende** [comment]
Great, thanks!
Any idea when you will release the next update?

**Comment by JanKallman** [comment]
This fix will be released with EPPlus 5.2. We hope sometime next week if all tests go well.

**Comment by JanKallman** [comment]
Fixed in Version 5.2
