### ISSUE TITLE
7.0.4 delete sheet issue

### ISSUE THREAD

**Issue by Wddy** [EPPlusSoftware/EPPlus#1220]
Deleting sheets A and B while keeping sheet C generates an error, and sheets A and B both have hyperlinked images pointing to sheet C. Relevant workbooks have been uploaded.
[delTest.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13713803/delTest.xlsx)

**Comment by JanKallman** [comment]
Thanks for reporting this. We will investigate and get back to you.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.0.5
