### ISSUE TITLE
Empty string as valid return value from XLOOKUP

### ISSUE THREAD

**Issue by sdransfeld** [EPPlusSoftware/EPPlus#1227]
Hi,

Should not "" be a valid return value from XLOOKUP?
=XLOOKUP(A1;table[Column1];table[Column2];"")

https://github.com/EPPlusSoftware/EPPlus/blob/develop7/src/EPPlus/FormulaParsing/Excel/Functions/RefAndLookup/XLookup.cs#L106

**Comment by sdransfeld** [comment]
[xlookup.patch](https://github.com/EPPlusSoftware/EPPlus/files/13753038/xlookup.patch)

**Comment by swmal** [comment]
Hi, thanks for reporting. We will have a look at this.

**Comment by JanKallman** [comment]
This should now be fixed in EPPlus 7.0.6

**Comment by SRO-AWATA** [comment]
Is this issue already resolved?

(EPPlus 7.5.1)
worksheet.Cells["A2"].Formula = "XLOOKUP(A1,table[Column1],table[Column2],\"\")";
worksheet.Cells["A2"].Calculate();
Console.WriteLine($"A2.Value={worksheet.Cells["A2"].Value}" ); ⇒#N/A
