### ISSUE TITLE
Crash when shared formula is array formula

### ISSUE THREAD

**Issue by sdransfeld** [EPPlusSoftware/EPPlus#1229]
I have a weird worksheet with a shared array formula:
			<c r="B50">
				<f t="shared" ref="B50:B54" si="3">+_xlfn.XLOOKUP(D50,$X$49:$X$731,$T$49:$T$731,0)</f>
				<v>54229416</v>
			</c>

At https://github.com/EPPlusSoftware/EPPlus/blob/develop7/src/EPPlus/FormulaParsing/DependencyChain/RpnFormulaExecution.cs#L251
FormulaType is "Shared". As I read the code, this will always be false?

Anyways, we get to:
https://github.com/EPPlusSoftware/EPPlus/blob/develop7/src/EPPlus/FormulaParsing/DependencyChain/RpnFormulaExecution.cs#L273
Here, we do _not_ set f._arrayIndex = ix;, as with the code path if the above is true

Much later at:
https://github.com/EPPlusSoftware/EPPlus/blob/develop7/src/EPPlus/FormulaParsing/DependencyChain/ArrayFormulaOutput.cs#L116
_arrayIndex is -1, and we go down the wrong path

[shared.patch](https://github.com/EPPlusSoftware/EPPlus/files/13758048/shared.patch)

**Comment by JanKallman** [comment]
Thanks for reporting this. I'll add this fix to the next version.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.0.6
