### ISSUE TITLE
Exception thrown when parsing conditional formatting

### ISSUE THREAD

**Issue by kirbatious** [EPPlusSoftware/EPPlus#1244]
I am testing using EPPlus v7 with my codebase, in advance of upgrading from 4.5.3.2 and paying for a license. I have hit two significant issues, which I have documented in my repo [EPPlusBugs](https://github.com/kirbatious/EPPlusBugs).

This first issue is that one of my spreadsheets cannot be opened in EPPlus v7 (but opens fine in 4.5.3.2 because an exception is thrown in [ExcelConditionalFormattingDataBar](https://github.com/EPPlusSoftware/EPPlus/blob/19e357827293608f0c6840f345f89ff39a185c05/src/EPPlus/ConditionalFormatting/Rules/ExcelConditionalFormattingDataBar.cs#L109C1-L109C1).

I have tested that the issue is in the develop7 branch, as well as release/epplus7.0.5. 

I couldn't figure out how to fix it (changing Double.Parse to Double.TryParse for HighValue and LowValue just leads to errors elsewhere).

Run [this test](https://github.com/kirbatious/EPPlusBugs/blob/ff6962b17805b3eb0c5e2d369d65a429ea219bef/EPPlusNewTests/CalculationTests.cs#L22C35-L22C35) to replicate the issue. 

The [same test](https://github.com/kirbatious/EPPlusBugs/blob/ff6962b17805b3eb0c5e2d369d65a429ea219bef/EPPlusOldTests/CalculationTests.cs#L17C21-L17C21) passes in 4.5.3.2.

**Comment by OssianEPPlus** [comment]
Ah, I see the issue. This is a bug. Looks like we only parse addresses if the databar input for highest/lowest is of "formula" type likely that has issues as well. This is wrong. I will provide a fix ASAP. Thanks for letting us know!
