### ISSUE TITLE
Issue with Calculation tree not detecting changes properly in v7 (works in 4.5.3.2)

### ISSUE THREAD

**Issue by kirbatious** [EPPlusSoftware/EPPlus#1245]
I am testing using EPPlus v7 with my codebase, in advance of upgrading from 4.5.3.2 and paying for a license. I have hit two significant issues, which I have documented in my repo [EPPlusBugs](https://github.com/kirbatious/EPPlusBugs).

This issue is that calling Calculate() on a workbook doesn't seem to work properly any more (but did in 4.5.3.2).

A simple test demonstrating the issue is [here](https://github.com/kirbatious/EPPlusBugs/blob/ff6962b17805b3eb0c5e2d369d65a429ea219bef/EPPlusNewTests/CalculationTests.cs#L36C26-L36C26).

And the same test passing in 4.5.3.2 is [here](https://github.com/kirbatious/EPPlusBugs/blob/ff6962b17805b3eb0c5e2d369d65a429ea219bef/EPPlusOldTests/CalculationTests.cs#L30C25-L30C25).

All the test does is check that changing a cell from one number to another number leads to cells which just double that cell also change correctly. Unfortunately only one of the output cells changes in EPPlus v7.

**Comment by OssianEPPlus** [comment]
Yep, it's a bug. We've taken a look and know what the issue is. A fix is on the way.

**Comment by OssianEPPlus** [comment]
It'll take a while before there's a release with this but a fix is now available in our [NuGet Develop Feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed) and the fix is slated for our next release.
