### ISSUE TITLE
HeaderFooter - RightAlignedText Set Problem

### ISSUE THREAD

**Issue by cbyzzy** [EPPlusSoftware/EPPlus#1257]
When I set RightAlignedText, the actual setting is CenteredText.

Here is this part of sourcecode:

		string _rightAlignedText = null;
		/// <summary>
		/// Get/set the text to appear on the right hand side of the header (or footer) on the worksheet.
		/// </summary>
		public string RightAlignedText
		{
			get
			{
				return _centeredText;

			}
			set
			{
				_centeredText = ValidateAndTrimText(value);
			}
		}

Is this a bug or just a feature?

**Comment by cbyzzy** [comment]
The Version is 7.0.6

**Comment by JanKallman** [comment]
Yes, this is not right. I will provide a fix shortly

**Comment by JanKallman** [comment]
Fix added to latest develop7. You can try it [using our develop7 Nuget  feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed). We aim for a new release today.
