### ISSUE TITLE
Wiki is wrong on compatibility

### ISSUE THREAD

**Issue by wojciechsmigielskijr** [EPPlusSoftware/EPPlus#1264]
https://github.com/EPPlusSoftware/EPPlus/wiki/Configuration#isworksheets1based

This suggests the value can either be 1 or 0
<appSettings>
    <add key="EPPlus:ExcelPackage.Compatibility.IsWorksheets1Based" value="1" />
</appSettings>

However within the class it is commented as the value being true 

https://github.com/EPPlusSoftware/EPPlus/blob/c38d6770212518a21743b4537ba8fac6310096ee/src/EPPlus/Compatibility/CompatibilitySettings.cs#L55

After testing this, it appears that the comment within the class is correct and setting 1 does not work.

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this.

**Comment by swmal** [comment]
You were right, setting the value 1 in the config file didn't work. I have updated the wiki.
