### ISSUE TITLE
MMULT not currently supported

### ISSUE THREAD

**Issue by keithclarkj** [EPPlusSoftware/EPPlus#1266]
As of the current version, the MMULT function is not supported - is this something that is planned/could be a feature in EPPlus 7?

**Comment by swmal** [comment]
We are working on a number of functions which includes MMULT, so our plan is definately to add support for it. I can unfortunately not give you an estimate on when it will be introduced as of today.

**Comment by swmal** [comment]
Added to the backlog of our [EPPlus Epics](https://github.com/orgs/EPPlusSoftware/projects/2) project.

See #1411

**Comment by swmal** [comment]
Support for MMULT was added in EPPlus 7.2
