### ISSUE TITLE
A row range reference returns the whole usedrange wrongfully. 

### ISSUE THREAD

**Issue by lyc0826** [EPPlusSoftware/EPPlus#1267]
ExcelRange row = worksheet.Cells[i, 1, i, worksheet.Dimension.End.Column]; 
string key = row[1, 1].Text;

The codes above were supposed to get the text of the first column of the row “i“ ; however, actually I got the text of the first row and the first column of the whole usedrange, namely, the cell "A1".

I tried further, to replace the codes with the following:
ExcelRange row = worksheet.Cells[worksheet.Dimension.Address];
string key = row[1, 1].Text; 
And I still got the the text of the first row and the first column of the whole usedrange, namely, the cell "A1".

That's to say,  "worksheet.Cells[i, 1, i, worksheet.Dimension.End.Column];" equals  "worksheet.Cells[worksheet.Dimension.Address];" in my situation, which seems wrongful.

Is it a bug or a purposeful design? Hope to hear from you soon.
Thank you and have a nice day!

**Comment by keithclarkj** [comment]
I've looked into this and interestingly, after indexing an `ExcelRange`  the original range gets changed into the result of that index - I'm assuming that index works with the range's worksheet property? Have a look at this unit test:

```
        [TestMethod]
        public void ExcelRangeIndexTest()
        {
            using (var pck = new ExcelPackage())
            {
                var sheet = pck.Workbook.Worksheets.Add("Sheet1");

                sheet.InsertRow(1, 5);
                
                sheet.Cells["A1"].Value = 1;
                sheet.Cells["A2"].Value = 2;
                sheet.Cells["B1"].Value = 3;
                sheet.Cells["B2"].Value = 4;

                var endColumn = sheet.Dimension.End.Column; // = 2

                var range1 = sheet.Cells[2, 1, 2, 2]; // = A2:B2 before next line - A1 afterwards
                var key1 = range1[1, 1]; // A1

                var range2 = sheet.Cells[2, 1, 2, 2]; // Stays as A2:B2
                var rangeList = range2.ToList(); // List of 2 ExcelRangeBase - A2 and B2
                
                var range3 = sheet.Cells[2, 1, 2, sheet.Dimension.End.Column]; // A2:B2 before next line - A1 afterwards
                var key2 = range3[1, 1]; // A1
            }
        }
```

**Comment by swmal** [comment]
Thanks for reporting, we will have a look at this.

**Comment by JanKallman** [comment]
The `ExcelRangeBase` indexer takes the absolute row and column for the whole worksheet. It is not relative to a previously referenced ranges.
This is the current behavior and cannot be changed without the risk of breaking code, so we can not change it.
You can use the `Offset` method if you want to have a relative range to a previously referenced range object.
I added some examples [here](https://github.com/EPPlusSoftware/EPPlus/wiki/Addressing-a-worksheet).
