### ISSUE TITLE
Calculation Error

### ISSUE THREAD

**Issue by LukesYong** [EPPlusSoftware/EPPlus#1276]
I had implemented some formula into cell based on user requirement and noticed that whenever when I export my excel and import back without saving, the formula won't calculate. As I searched and found out that calculation won't made unless user save it. However, we can use worksheet.Calculate() to explicit calculate it. I tried and it works but one of my formula return wrong value.
Below is my code and explanation:
workSheet.Cells[row, i + 1].Formula = $"TEXT(SUMPRODUCT(VALUE({firstAddress}:{lastAddress})),\"@\")";

this is a for loop to sum up every field in same row as they displayed as text, this worked when I export it.
But when I explicit calculate it, it shows the wrong value and the value stored is refer to the first field value. For an example, the cell formula is =TEXT(SUMPRODUCT(VALUE(A1:Y1)),"@"), if A1 =1000, it will return 1000 since A1 is first cell

**Comment by swmal** [comment]
Thanks for reporting this. The reason for this should be that the VALUE function in EPPlus hasn't support for multicell ranges as argument. It is an easy fix and I will create a PR for the next version.

**Comment by swmal** [comment]
Fix released in EPPlus 7.0.9
