### ISSUE TITLE
Difference between v. 4 and v. 5 chart appearance

### ISSUE THREAD

**Issue by EsbenRud** [EPPlusSoftware/EPPlus#128]
Hi, I am migrating from EPPLus v. 4 to v. 5 and in this process I discovered that v. 5 is missing x- and y-axis labels. I have uploaded ConsoleApp27.zip with a .NET project binded to EPPLus v. 4 and ConsoleApp28.zip with the same .NET project binded to EPPlus v. 5. If you run these projects and look at the output test2.xlsx in the Debug you can see the difference. Is this a bug in v. 5 or has there been some breaking changes? 
[ConsoleApp27.zip](https://github.com/EPPlusSoftware/EPPlus/files/4784732/ConsoleApp27.zip)
[ConsoleApp28.zip](https://github.com/EPPlusSoftware/EPPlus/files/4784734/ConsoleApp28.zip)

**Comment by JanKallman** [comment]
This seems to be fixed in the latest build, even if it looks slightly different. 
Try latest build from our develop nuget feed.

**Comment by EsbenRud** [comment]
Looks fine, thanks a lot :-)
