### ISSUE TITLE
Modify Excel 2016 .xlsx file, After saving, it still shows that you need to save

### ISSUE THREAD

**Issue by dengzibiao** [EPPlusSoftware/EPPlus#129]
using EPPlus.dll version 5.1.1.0,open file and then use ExcelWorksheet.Cells modify cell value,then use ExcelPackage.Save() to save file,the .xlsx file can not open,but if i changed file suffix to .xlsm,the file can be opened

**Comment by JanKallman** [comment]
Can you attach the xlsx template file and some code to reproduce the issue?

**Comment by dengzibiao** [comment]
[Scene_Config.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4792285/Scene_Config.xlsx)


using OfficeOpenXml;
using System.Collections.Generic;

class SaveMap
{
    Dictionary<string, int> namMapDict = new Dictionary<string, int>();

    public void SaveMapConfig()
    {
        ExcelPackage ep;
        ExcelWorksheet collect = ExcelParser.ReadExcel("Scene_Config", "Map_Config", out ep);
        //注：致命bug
        if (ep.Workbook.VbaProject == null)
        {
            ep.Workbook.CreateVBAProject();
        }
        namMapDict.Clear();
        for (int j = 1; j <= collect.Dimension.Columns; j++)
        {
            if (collect.GetValue(2, j) == null) continue;
            string columnName = collect.GetValue(2, j).ToString();
            if (!namMapDict.ContainsKey(columnName))
            {
                namMapDict.Add(columnName, j);
            }
        }
        for (int i = 6; i <= collect.Dimension.Rows; i++)
        {
            //第二行为字段名称
            //第三行为类型
            //第四行为导出类型(客户端还是服务器)
            //第五行为描述
            //余下为数据
            if (i >= 6)
            {
                var mapIDRow = i;

                //把当前配置写入表中
                for (int j = 1; j <= collect.Dimension.Columns; j++)
                {
                    if (collect.GetValue(2, j) == null) continue;
                    string columnName = collect.GetValue(2, j).ToString();
                    var cellValue = collect.GetValue(i, j);

                    int sceneName = namMapDict["sceneName"];
                    int mapConfig = namMapDict["gridFile"];
                    int dataConfig = namMapDict["dataScript"];

                    int cameraPosCol = namMapDict["CameraPos"];
                    int cameraRotCol = namMapDict["CameraRot"];
                    int cameraFOVCol = namMapDict["CamearFOV"];

                    collect.Cells[mapIDRow, sceneName].Value = cellValue;
                    collect.Cells[mapIDRow, mapConfig].Value = cellValue;
                    collect.Cells[mapIDRow, dataConfig].Value = cellValue;

                    collect.Cells[mapIDRow, cameraPosCol].Value = cellValue;
                    collect.Cells[mapIDRow, cameraRotCol].Value = cellValue;
                    collect.Cells[mapIDRow, cameraFOVCol].Value = cellValue;
                }
            }
        }
        ep.Save();
        collect.Dispose();
        ep.Dispose();
    }
}

**Comment by dengzibiao** [comment]
I know what happened,I Use `ep.Workbook.CreateVBAProject();` Create VBA，It must a .xlsm file

**Comment by dengzibiao** [comment]
![截图_20200618100639](https://user-images.githubusercontent.com/7919666/84969516-74e43d80-b14b-11ea-85d0-087110ec4f95.png)
I delete the code `ep.Workbook.CreateVBAProject();`,it works,and .xlsx file has modify,but when i close th .xlsx file，It notify save the file

**Comment by JanKallman** [comment]
I think this happens in older versions of Excel, if Excel makes changes when loading the package. I can't see this behaviour in Excel 2019. Feel free to attach your workbook so I can verify the behavoiur.

**Comment by dengzibiao** [comment]
[Scene_Config.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4812296/Scene_Config.xlsx)
FileInfo file = new FileInfo(excelPath);
using (ExcelPackage package = new ExcelPackage(file))
{
//get first sheet
//modify it
//save it
//dispose it
}

**Comment by JanKallman** [comment]
Works fine in Excel version 2005 - 16.0.12827.20328 for all I can see.
