### ISSUE TITLE
Using +Headings/+Body theme fonts

### ISSUE THREAD

**Issue by johndoh** [EPPlusSoftware/EPPlus#1291]
I'd like to be able to use the +Headings/+Body font names to assign a font from the selected Office theme.

e.g.
```
workSheet.Cells[1,2].Style.Font.Name = "+Headings";
```

Currently this results in "+Headings" being set as a (invalid) font name, but the desired outcome is to use Calibri/Aptos type fonts as defined in the theme.

**Comment by JanKallman** [comment]
I think you should set the Font.Scheme (can have the values: major, minor or none).
If you make the changes to you workbook and save the file in Excel you can then look at the font style xml (rename *.xlsx -> *.zip and look at /xl/styles.xml).
For me it look like this:
```
<fonts count="2" x14ac:knownFonts="1">
<font>
<sz val="11"/>
<color theme="1"/>
<name val="Calibri"/>
<family val="2"/>
<scheme val="minor"/>
</font>
<font>
<sz val="11"/>
<color theme="1"/>
<name val="Calibri Light"/>
<family val="2"/>
<scheme val="major"/>
</font>
</fonts>
```

**Comment by johndoh** [comment]
Font.scheme is exactly what I was looking for. Thanks!
