### ISSUE TITLE
Workbook with the special defined name value once saved using EPPLUS can't open again

### ISSUE THREAD

**Issue by YouZiChaCha** [EPPlusSoftware/EPPlus#1313]
I have a workbook with the special defined name value as follows：
`<x:definedName name="编制单位">"编制单位："&amp;[219]封面!$D$6</x:definedName>`
Once saved by using EPPLUS , the file can't open again  and name value changes to
`<x:definedName name="编制单位">"编制单位："&amp;[219]封面!$D$"</x:definedName>`
This seems to be caused by the following line of code
``` java
  if (Utils.ConvertUtil._invariantCompareInfo.IsPrefix(fullAddress, "\"")) //String value
  {
      namedRange.NameValue = fullAddress.Substring(1, fullAddress.Length - 2);
  }
  else if (double.TryParse(fullAddress, NumberStyles.Number, CultureInfo.InvariantCulture, out double value))
  {
      namedRange.NameValue = value;
  }
  else
  {
      namedRange.NameFormula = fullAddress;
  }
```
In Debug, the value of fullAddress is 
`\"编制单位：\"&[219]封面!$D$6`

**Comment by JanKallman** [comment]
Can you attach a workbook that reproduces this issue?

**Comment by YouZiChaCha** [comment]
> Can you attach a workbook that reproduces this issue?
Yes, attach a workbook here
[SpecialNameValue.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/14373048/SpecialNameValue.xlsx)

**Comment by OssianEPPlus** [comment]
This is a bug, the code segment indeed had a minor issue. But there are more issues. Limitations in our current handling of external references in defined names mostly. We'll update you when we've resolved it in our dev environment
