### ISSUE TITLE
FontFamily CharSet Not Affected Please Help

### ISSUE THREAD

**Issue by lucaswhob** [EPPlusSoftware/EPPlus#132]
Hello
Thank you Very Much For Your Great Library
I Have Little Problem : I Use Arabic Persian Font Family Font Nam In Excel Is Set But Not Affected
I Found This Link 
https://stackoverflow.com/questions/40032251/epplus-font-family-not-affected/40170340
 I Need Charset Method ... In Latest Version Removed Charset Method
[Please See This ScreenShot](https://www.mediafire.com/convkey/e3d3/pfea8xge1ishwv6zg.jpg)

**Comment by JanKallman** [comment]
Added Chartset, Condense, Extend and Shadow  property to ExcelFont and ExcelFontXml.

**Comment by lucaswhob** [comment]
Thank You .
Please Provide Example Thank You Very Much .

**Comment by JanKallman** [comment]
Try this in version 5.2...
ws.Cells["B1"].Style.Font.Charset = 0xB2;
