### ISSUE TITLE
Using `ExcelWorksheet.DeleteRow` on tables with many rows incorrectly adds calculated column formula above table

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#1321]
I have a worksheet with a table that has many rows (over 18,000). This table has a `CalculatedColumnFormula` in column A.

I want to delete all but the last row of the table, so I call:

```csharp
wks.DeleteRow(firstRowAfterHeaderRow, numberOfRows - 2);
```

This does delete the correct rows. However, the cells in column A above the table have now had their values replaced with the calculated column formula - even though these cells are outside the table (and always were).

I have included a unit test below to illustrate the problem. 

Interestingly, if I tweak the unit test to set up the table with `wks.Tables.Add(wks.Cells["A16:B16394"], "Table1")` - i.e. the table now only goes down to row 16394 instead of 18394 - some of the cells _aren't_ replaced with the formula. If I change it again so that the table stops at row 16383, the test passes.

```csharp
[TestMethod]
public void DeleteRow_TableWithCalculatedColumnFormula()
{
    using (var pck = new ExcelPackage())
    {
        // Set up a worksheet with a single table that has lots of rows and a calculated column
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        wks.Cells["A1:A14"].Value = "Data outside table";
        wks.Cells["A16"].Value = "Col1";
        wks.Cells["B16"].Value = "Col2";
        var table = wks.Tables.Add(wks.Cells["A16:B18394"], "Table1");
        table.Columns[0].CalculatedColumnFormula = "ROW()-16";

        // The calculated column formula is only given to rows inside the table
        for (int i = 16; i > 0; i--)
        {
            Assert.AreEqual("", wks.Cells["A" + i].Formula);
        }
        Assert.AreEqual("ROW()-16", wks.Cells["A17"].Formula);

        // Delete all rows in the table except for the header row and the last row
        var listRowsCount = table.Range.Rows;
        wks.DeleteRow(17, listRowsCount - 2);

        // Check that rows above the table haven't been given a formula
        for (int i = 16; i > 0; i--)
        {
            Assert.AreEqual("", wks.Cells["A" + i].Formula, "Formula present in A" + i);
        }
        Assert.AreEqual("ROW()-16", wks.Cells["A17"].Formula);
    }
}
```

**Comment by JanKallman** [comment]
Looks like a bug. I will investigate and try to provide a fix.

**Comment by JanKallman** [comment]
I have added a fix for this, but I will do some more testing before merging this into the develop7 branch

**Comment by craigbrown** [comment]
Hi Jan, thanks for looking at this so quickly. I just did a quick test in your branch with our original workbook and it seems to fix the problem. Many thanks.

**Comment by JanKallman** [comment]
Great, thanks for the feedback!
