### ISSUE TITLE
GetRelativeFormula

### ISSUE THREAD

**Issue by st-dotnet** [EPPlusSoftware/EPPlus#1328]
Hi,

How to get the RelativeFormula in EPPlus?
package.Workbook.Names["SheetName"].GetRelativeNameFormula(3, 3).Select(n => n.Value)

**Comment by swmal** [comment]
There is no such public function in EPPlus. What do you want to achieve?

**Comment by st-dotnet** [comment]
I want to get the formula of a named range relative to the specified relativeRow and relativeColumn.
I have checked the library and we have this
  internal string GetRelativeFormula(int row, int col)
