### ISSUE TITLE
Support asynchronous reads/writes

### ISSUE THREAD

**Issue by benjaminsampica** [EPPlusSoftware/EPPlus#1336]
We are using ASP.NET Core's `IBrowserFile` interface to parse an user-uploaded file and are feeding it into an ExcelPackage to be parsed. Sample code below

 ```
	public async Task<List<ParsedRow>> ParseAsync(IBrowserFile browserFile)
	{
		using var excelPackage = new ExcelPackage(browserFile.OpenReadStream());

               // Open worksheet, parse into ParsedRow.
        }
```

The problem is internally EPPlus is using Write() and Read(), which are not supported in ASP.NET Core by default and throws the following exception.

`System.InvalidOperationException: Synchronous operations are disallowed`

Is this something that is planned on being supported in the future?

**Comment by JanKallman** [comment]
Did you try to use the `excelPackage.LoadAsync` method instead?
See this sample...
https://github.com/EPPlusSoftware/EPPlus.Samples.CSharp/blob/1aa7833383d7e6cc49030fd8603b315f83b889ea/01-Workbook%20worksheet%20and%20ranges/03-Using%20async%20await/UsingAsyncAwaitSample.cs#L57

**Comment by benjaminsampica** [comment]
That worked! Thank you.
