### ISSUE TITLE
Conditional Formatting on a Pivot Table does not save properly.

### ISSUE THREAD

**Issue by jsmcdonaldllc** [EPPlusSoftware/EPPlus#1343]
When creating some conditional formatting on a worksheet with a pivot table, I assigned the PivotTable property to true. When I check the property of the conditional format immediately prior to saving the file, the value is still true. Upon opening the file in EPPlus immediately after saving, the value for the conditional format PivotTable property is false. This causes the conditional formatting to be lost in Excel.

Here is the properties I am setting on the ConditionalFormat:

            var cond = pivotWorksheet.ConditionalFormatting.AddEqual(new ExcelAddress(range));
            cond.PivotTable = true;
            cond.Formula = formulaValue.ToString();
            cond.Priority = priority;
            cond.Style.Fill.PatternType = ExcelFillStyle.Solid;
            cond.Style.Fill.BackgroundColor.SetColor(bgColor);

            if (formulaValue == 9999)
                cond.Style.Font.Color.SetColor(bgColor);
            else
                cond.Style.Font.Color.SetColor(Color.DarkRed);

I have been able to replicate this with a new project and each time the property is reset to false if the conditional format is on a pivot table worksheet.

**Comment by OssianEPPlus** [comment]
We've confirmed this bug and are looking into it. Thanks for reporting!

**Comment by jsmcdonaldllc** [comment]
Thank you for your quick response and action. It is greatly appreciated. Is there an ETA on when this fix might be released to Nuget?

Thanks,
Jim Mc


________________________________
