### ISSUE TITLE
Wildcards in MATCH function not working

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#135]
Wildcard characters (* and ?) are not working correctly within the MATCH function.

I wrote a couple UT's that exhibit the issue and will push as a PR.

The formulas function correctly within Excel.

**Comment by swmal** [comment]
Thanks for this. You can try out the fix in our development nuget feed: https://ci.appveyor.com/nuget/epplus

**Comment by rdhasse** [comment]
Seems to be fixed, thanks!
