### ISSUE TITLE
EPPlus corrupts file after save

### ISSUE THREAD

**Issue by nstout20** [EPPlusSoftware/EPPlus#1350]
EPPlus version 7.0.9 corrupts a file after save. The same code works fine with EPPlus version 6.2.13

using (var package = new ExcelPackage(new FileInfo(filePath))) //filePath is the path of the file Test.xlsx (attached with this issue)
{
package.SaveAs(newfilePath); //newfilePath is the path of the new saved file
}

Expected behavior
The new generated file should open up normally .

Actual behavior
The new generated file seems to be corrupted.

![312617025-e1c395ac-927e-48c3-b59e-b383f81afc9c](https://github.com/EPPlusSoftware/EPPlus/assets/163351193/02890127-54e9-4a5b-8864-6a0f8b1f27ce)

Known workarounds
Use an older version of EPPlus - 6.2.13

Related information
Original file:
[Test.xlsx](https://github.com/Azure/azure-webjobs-sdk/files/14593819/Test.xlsx)

**Comment by OssianEPPlus** [comment]
We've looked into it. This is indeed a bug. Essentially our handling of `"` in numberformats in conditionalformattings was encoded incorrectly when saved with Epplus. A fix is underway. 

If you're curious sheet5 and sheet6 contained the issue. Specifically the number format
"S + "0.00%
seems to be causing the issue.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.1.1
