### ISSUE TITLE
excel package view it in the Excel application without saving

### ISSUE THREAD

**Issue by kadir133** [EPPlusSoftware/EPPlus#1353]
hi. I am using version 5.8.0. I don't know if this issue has been discussed before. I searched a little but couldn't find it. My problem is this: After creating the Excel package and writing the data, I want to view it in the Excel application without saving it. 

How can I do that?

**Comment by OssianEPPlus** [comment]
That's not possible.

Excel uses .xlsx files to read in data. Epplus reads the data from this file in and stores it in memory accessible via programming through its variables for example in a variable of ExcelWorksheet type. There is no file with the edited data until you save. So Excel cannot open it without saving.

**Comment by kadir133** [comment]
Thank you for your interest. Then I found a solution like this. I save it to the temp folder. I'm viewing it from there. The temp file is automatically deleted when the application is closed.

                // Create a temporary file collection and add a temporary file with ".xlsx" extension.
                string filePath = new TempFileCollection().AddExtension("xlsx");

                package.SaveAs(filePath);

                // Create a new Process object to start an external process (Excel application).
                using (var excelProcess = new Process())
                {
                    // Specify the file to be executed (Excel.exe).
                    excelProcess.StartInfo.FileName = "Excel.exe";
                    excelProcess.StartInfo.UseShellExecute = true;

                    // Specify the file information to be opened in Excel. The "/n" parameter ensures that Excel is opened in a new window.
                    excelProcess.StartInfo.Arguments = "/n " + filePath;
                    // Start the Excel application.
                    excelProcess.Start();
                }
