### ISSUE TITLE
Cannot set the clockwise text rotation.

### ISSUE THREAD

**Issue by lyc0826** [EPPlusSoftware/EPPlus#1358]
I'm in trouble with the text rotation. When setting the .TextRotation property to a positive number, say 60, the text will rotate anti-clockwise by 60 degrees. When setting the .TextRotation property to a negative number, which is supposed to make the text rotate clockwise, I get an exception. Just have no idea what is going wrong. Cannot find any useful document on this issue. Hope to hear from you for the solution.

**Comment by JanKallman** [comment]
Easiest is to set the rotation for your cell value in Excel an then look at it in the xml (rename the workbook *.zip and look in the styles.xml) or open the workbook with EPPlus and look at eht style value.

Looking at the OOXML documentation for this attribute, it says...

Text rotation in cells. Expressed in degrees. Values are in the range 0 to 180. The first
letter of the text is considered the center-point of the arc.
For 0 - 90, the value represents degrees above horizon. For 91-180 the degrees below the
horizon is calculated as:
[degrees below horizon] = 90 - textRotation.

**Comment by lyc0826** [comment]
Yeah, it works! Thank you for your kind help.
