### ISSUE TITLE
Epplus result differs from excel for numbervalue function

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1365]
`=numbervalue("")` in Excel returns the number `0`.
`=numbervalue("")` in Epplus returns `#VALUE!`.

Please see attached workbook:
[Empty string numbervalue.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/14653210/Empty.string.numbervalue.xlsx)

This is occurring for me in 6.2.10 and 6.2.18.

Thanks,
-Colby

**Comment by swmal** [comment]
Will be fixed in next release of EPPlus 6
