### ISSUE TITLE
MemoryManager default options

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#1371]
Couple small issues here:

1. ".MemoryManger" is a typo, I assume, and should be "MemoryManager"
2. While it is now possible to override the options EPPlus uses, the documentation for RecyclableMemoryStream says the following

> It is through these properties that you determine how large your pool can grow. If you set these to 0, you can have unbounded pool growth, which is essentially indistinguishable from a memory leak. For every application, you must determine through analysis and experimentation the appropriate balance between pool size and garbage collection.

Source: https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream

Currently, if an EPPlus user does not manually override the "MemoryManger", and continually uploads larger and larger files, the *default behavior of EPPlus* will be to hold onto as much memory as at least as big as the biggest file processed.

**Comment by JanKallman** [comment]
Thanks for reporting this. We will correct the typo and have a look at the default behaviour.

**Comment by JanKallman** [comment]
Added default values for the MaximumSmallPoolFreeBytes and MaximumLargePoolFreeBytes.
