### ISSUE TITLE
Worksheet Count is 0

### ISSUE THREAD

**Issue by jamahalwin** [EPPlusSoftware/EPPlus#1372]
Some documents will not load the worksheet in the workbook after instantiating an ExcelPackage and loading an .xlsx document. As the document opens in Excel, file corruption does not appear to be the cause.

**Comment by JanKallman** [comment]
Please attach a sample to reproduce this. Also make sure these workbooks are not saved in ooxml strict format, as EPPlus does not support that format.

**Comment by JanKallman** [comment]
Closed as issue can not be reproduced. Feel free to reopen and add reproducible case.
