### ISSUE TITLE
Null deference exception in ExcelColumn.ToString()

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#138]
We encountered a case where _colElement is null, which is then dereferenced in ExcelColumn.ToString().  We made a fix locally which resolved the issue.  I'll send a PR.

**Comment by rdhasse** [comment]
Is it possible to provide this fix in the development Nuget feed similar to issue #135?

This issue is currently breaking some functionality we would like to test.

**Comment by JanKallman** [comment]
Hello, thanks for the PR. The _colElement is always null, as it is a only referenced in the ToString(). I will remove it and update the develop branch. Thanks.

**Comment by JanKallman** [comment]
Fixed in version 5.2.1
