### ISSUE TITLE
ws.Drawings.AddPicture don't support jpeg/exif

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#1389]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

linux

### Epplus version

6.2.19

### Spreadsheet application

excel

### Description

i use epplus 6.2.19 export excel with image
...
Image image = Image.FromStream(imageStream);
ExcelPicture pic = worksheet.Drawings.AddPicture(name, imageStream);

then thrown exception:
System.InvalidOperationException: No image handler for image type Jpg

Adding the following code can solve the problem, but can it be solved without adding it? 
Because I want to execute in non-GDI environment
```
package.Settings.ImageSettings.PrimaryImageHandler = new SystemDrawingImageHandler();
```

**Comment by JanKallman** [comment]
This should work. I will have a look.

**Comment by JanKallman** [comment]
This is a bug. I will provide a fix shortly.

**Comment by 93910676wangd** [comment]
Thank you for your confirmation and feedback. Looking forward to release

**Comment by 93910676wangd** [comment]
![test](https://github.com/EPPlusSoftware/EPPlus/assets/19505572/d2758221-4d62-4653-ac5e-e6ba126007c4)
test picture
