### ISSUE TITLE
Delete blank rows

### ISSUE THREAD

**Issue by robertovaldesperez** [EPPlusSoftware/EPPlus#1393]
Hi @simendsjo @swmal @startewho @ariesy @JanKallman How can I delete blank rows from Excel? Thank you!!

**Comment by swmal** [comment]
Hi,

Our issue tracker is not a general support forum, but if anything in EPPlus doesn't work as expected please provide a detailed description of the issue (including minimal code to replicate it) and we will try to fix it.
