### ISSUE TITLE
Bar chart (ColumnClustered) Data Labels Rotation

### ISSUE THREAD

**Issue by jsmcdonaldllc** [EPPlusSoftware/EPPlus#1401]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.1.0

### Spreadsheet application

Excel

### Description

I've created a bar chart that I need the data labels to be rotated 45 degrees. I can produce the chart without an issue until I try to rotate the data label using the following code. When I add the last rotation line the chart will not display in Excel and I get an error. From the documentation I believe this to be the correct way to perform this rotation as it is similar to how the XAxis gets rotated, but I am not exactly sure. The XAxis rotation works correctly. This is in a C# environment and I am using the latest version(7.1.0) of the EPPlus library.

var chart = chartWorksheet.Drawings.AddBarChart(chartName, eBarChartType.ColumnClustered, pivotTableData);
chart.SetPosition(1, 10, 12, 0);
chart.SetSize(1200, 580);
chart.Legend.Remove();
chart.Title.Text = chartTitle;
chart.Title.Font.Bold = true;
chart.Title.Font.UnderLine = eUnderLineType.Single;
chart.Title.Font.Size = 16;

chart.XAxis.LabelPosition = eTickLabelPosition.NextTo;
chart.XAxis.TextBody.WrapText = eTextWrappingType.Square;
chart.XAxis.TextBody.Rotation = 45D;
chart.DataLabel.ShowValue = true;
chart.DataLabel.Position = eLabelPosition.OutEnd;
chart.DataLabel.TextBody.Rotation = 45D;  <= This line causes the error.

**Comment by JanKallman** [comment]
This is a bug. EPPlus does not create the necessary elements needed for the text. 
A workaround for now is to set a font property on the data labels that creates the default xml elements.
For example, adding this row will cause the workbook to be correctly created.
```C#
chart.DataLabel.Font.Bold = false;
```
I will add a fix for this in the coming version.

**Comment by jsmcdonaldllc** [comment]
Thank you. Your workaround fixed the error.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.1.1
