### ISSUE TITLE
Values from the names manager are expanded with additional quotation marks

### ISSUE THREAD

**Issue by FRANKR318** [EPPlusSoftware/EPPlus#1408]
### EPPlus usage

Personal use

### Environment

Windows 11

### Epplus version

7.0.10

### Spreadsheet application

Excel

### Description

I have a workbook created normally in Excel with a name created in the Names Manager. **This name does not refer to a cell but is a fixed value for the entire workbook.** It is a Versionnumber to identify which Version of the specific Excel file it is.

The name refers to **="0.8"**, so the value is 0.8. It is a string.
When I only open and save the workbook with EPPlus without doing any other thing, this already changes the value.
Now, when I open it again in Excel, the refers to for the name is **="""0.8"""**

Why are the "" are added?

Thank you!

**Comment by OssianEPPlus** [comment]
We'll look into this. When excel saves it does so into XML files where `"` are sometimes added to help define a string as values are usually saved as e.g. "0.8" and a string 0.8 then as """0.8""" but this shouldn't affect the end result in excel. It's likely that we "double-wrap" it somewhere by accident.
