### ISSUE TITLE
Unit test reading excel file

### ISSUE THREAD

**Issue by weihan1394** [EPPlusSoftware/EPPlus#142]
Hi, I am trying to test reading of excel file using EPPlus library. The method works when i run the project, but when I am writing the test to mock the file it keep unable to get the worksheet.

**Test.cs**

        [Fact]
        public async Task saveFile_test()
        {
            string rootPath = Directory.GetCurrentDirectory();
            string testAssetsFolder = @"Assets\";
            string testFile = "test.xlsx";
            string testFilePath = Path.Combine(rootPath, testAssetsFolder, testFile);
 
            
            // Arrange.
            var fileMock = new Mock<IFormFile>();
            var physicalFile = new FileInfo(testFilePath);
            var ms = new MemoryStream();
            var writer = new StreamWriter(ms);
            writer.Write(physicalFile.OpenRead());
            writer.Flush();
            ms.Position = 0;
            var fileName = physicalFile.Name;
            //Setup mock file using info from physical file
            fileMock.Setup(_ => _.FileName).Returns(fileName);
            fileMock.Setup(_ => _.Length).Returns(ms.Length);
            fileMock.Setup(_ => _.OpenReadStream()).Returns(ms);
            fileMock.Setup(_ => _.ContentDisposition).Returns(string.Format("inline; filename={0}", fileName));

            List<IFormFile> files = new List<IFormFile>();
            files.Add(fileMock.Object);

            await _service.saveFile(files, "directory", "subDirectory", default);
        }

**Service.cs**

           public async Task saveFile(List<IFormFile> files, string directory, string subDirectory, CancellationToken cancellationToken)
           {
            subDirectory = subDirectory ?? string.Empty;
            var target = Path.Combine(directory, subDirectory);

            Directory.CreateDirectory(target);

            foreach (IFormFile file in files)
            {
                if (file.Length <= 0) return;
                var filePath = Path.Combine(target, file.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream, cancellationToken);
                    try
                    {
                        // add to read encoded 1252 values
                        using (var package = new ExcelPackage(stream))
                        {

                            // Express worksheet
                            ExcelWorksheet worksheet = package.Workbook.Worksheets["Express"];
                            int colCount = worksheet.Dimension.End.Column;  //get Column Count
                            int rowCount = worksheet.Dimension.End.Row;
                            ....
                        }
                    }
                }
           }
         
I am out of clue how I should write a unit test as when I debug I am able to mock the file as Imockfile reading from an existing file. But when the test run to `ExcelWorksheet worksheet = package.Workbook.Worksheets["Express"];` it just shows null.

**Comment by JanKallman** [comment]
I can't help your with the mock, but you have to ensure that the stream send into the constructor of the ExcelPackage class is the workbook containing the worksheet you try to access ("Express").
