### ISSUE TITLE
Copy ExcelGroupShape to another sheet

### ISSUE THREAD

**Issue by FedePorti** [EPPlusSoftware/EPPlus#1427]
How can I copy a ExcelGroupShape?

I can select the shape (that is a ExcelGroupShape) like this:

`Dim shape As ExcelDrawing = sheet.Drawings.Item("Name")`

But how can I add this shape to the Drawings? Because the function AddShape said that I can not cast a ExcelGroupShape to ExcelShape.
Can be a function to AddGroupShape? Or another way to do this?

**Comment by AdrianEPPlus** [comment]
Hello

EPPlus does not currently support copying Shapes. I will mark this as an enhancement for a future version.

**Comment by JanKallman** [comment]
Added in EPPlus 7.2.0
