### ISSUE TITLE
"Can't set bordercolor when style is not set." on Runtime Cell Creation

### ISSUE THREAD

**Issue by hoseinosaty** [EPPlusSoftware/EPPlus#1428]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

4.5.2

### Description

I tried to add a new row with some cells at runtime and tried to set the border style and color, but I received this error: "Can't set border color when style is not set."

**Comment by AdrianEPPlus** [comment]
Hello!

Could you provide some code to help us look into this?

**Comment by JanKallman** [comment]
Please note that EPPlus 4.5.2 is deprecated and no longer maintained by us.
