### ISSUE TITLE
Can we create excel file in memory and can we directly open that in excel application installed on machine I am using this epplus on desktop application for generating excel file.

### ISSUE THREAD

**Issue by shubham-jain17** [EPPlusSoftware/EPPlus#1429]
I am using EpPlus7 in a Desktop application based on winforms my requirement is to create excel file without saving on system and I need to open this file with excel application installed on user machine.
l am already using process class for opening excel file.

Code//
Process.Start(new ProcessStartInfo(ExcelFullPath, tempFilePath) { UseShellExecute = true});

But I need to know is there any other ways which EpPlus provide to open excel file in excel application.

Is there any other platform where I can get support for EpPlus usage.

Thanks

**Comment by JanKallman** [comment]
Excel cannot open a file from memory. You will need to save the workbook to a file to be able to open it in Excel.
