### ISSUE TITLE
WorkSheet address without !

### ISSUE THREAD

**Issue by curtis1757** [EPPlusSoftware/EPPlus#143]
In a formula in MS Excel 2010 you can have something like:
=VLOOKUP(E20,TransTypes,3)

Where TransTypes is the name of a WorkSheet and the expected table/ExcelRange to be returned for that argument is all the cells for the entire worksheet.

EPPlus does not accept that format it wants something like:
=VLOOKUP(E20531,TransTypes!1:1000,3)   (which does work in EPPlus)

Looking in ExcelAddress.cs in 
private static bool SplitAddress(string Address, out string wb, out string ws, out string intAddress)

the logic used makes it a requirement that the Address contain a '!' in order for the function to understand TransTypes as a worksheet name, whereas MS Excel does not require this.

In EPPlus if your try to access/get the cell.Forumla with the formula being '=VLOOKUP(E20,TransTypes,3)' an exception will be thrown.  But you can set the cell.formula to this '=VLOOKUP(E20,TransTypes,3)'  and will be fine.

Is this the intended way for this to work or is it a bug?

Thanks for a great piece of software!!!! So much better than MS Office InterOp!
Curtis

**Comment by JanKallman** [comment]
Sounds like a bug to me. We'll have a closer look and get back to you.

**Comment by curtis1757** [comment]
Thank you Jan,  I have been able to easily work around it, but just though you would like to know since it is inconsistent with MS Excel.

Curtis
  ----- Original Message -----
