### ISSUE TITLE
Clear validations and add new

### ISSUE THREAD

**Issue by sdransfeld** [EPPlusSoftware/EPPlus#1432]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.1.2

### Spreadsheet application

Excel

### Description

        /// <summary>
        /// Removes all validations from the collection.
        /// </summary>
        public void Clear()
        {
            _validations.Clear();
        }

Shouldn't clear in DataValidation/ExcelDataValidationCollection.cs also clear _validationsRD?

I get an error if I do this, saying we already have validation on cell

**Comment by OssianEPPlus** [comment]
Yes, rather certain it should. We will be looking into this.
