### ISSUE TITLE
ExcelControlScrollBar InvalidCastException

### ISSUE THREAD

**Issue by AdrianEPPlus** [EPPlusSoftware/EPPlus#1446]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windwos

### Epplus version

7.1

### Spreadsheet application

Excel

### Description

When initializing a ExcelControlScrollBar it throws the following error
```
System.InvalidCastException: 'Unable to cast object of type 'OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingComment' to type 'OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingControl'.'
```

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.2.2
