### ISSUE TITLE
Dispose always call GC.Collect and may cause bottleneck

### ISSUE THREAD

**Issue by gedomingos** [EPPlusSoftware/EPPlus#145]
I finally identified what was causing my webserver to spike CPU usage and to hang.

When on a scenario where the memory usage is very high and can't be released, if we run Garbage collector, it spikes CPU usage to almost 100% and hangs the server.

The problem is that the current IDispose implementation of ExcelPackage always calls GC.Collect on end.
So on a scenario were we are processing a lot of Excel Files, GC.Collect is running everytime and using all servers resources.

It would be nice to optionally stop the GC.Collect on dispose, or maybe limit the call once per X minutes.

**Comment by JanKallman** [comment]
Sure, we can look into adding a boolean property if the GC.Collect should run on dispose or not.

**Comment by JanKallman** [comment]
Added ExcelPackage.Settings.DoGarbageCollectOnDispose to avoid this issue. Available in 5.4.1
