### ISSUE TITLE
Add support for the LET function

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#1458]
**Is your feature request related to a problem? Please describe.**
The calculation engine in EPPlus doesn't support the LET function (see [Microsoft's documentation](https://support.microsoft.com/en-us/office/let-function-34842dd8-b92b-4d3f-b325-b8b8f9908999)

**Describe the solution you'd like**
Implement support for this function in EPPlus

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.2.0
