### ISSUE TITLE
Problem with SUMPRODUCT

### ISSUE THREAD

**Issue by vzczc** [EPPlusSoftware/EPPlus#1468]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.1.3

### Spreadsheet application

Excel (Latest 365 version)

### Description

When filling the formula property with a formula that uses SUMPRODUCT where one of the factors is an IF that refers to the current row, the if is preceeded by @ in the formula in Excel.

var doubleQuote = "\"\"";
sht.Cells[row, col].FormulaR1C1 = "IFERROR(SUMPRODUCT(IF(rngCurrency=RC1,1,0),rngLedgerDebit,rngDebitRate)/RC6),{doubleQuote})";

When opening this in Excel it looks like this. The problem is the @ before rngCurrency. If removed the formula calculates correctly
=IFERROR(SUMPRODUCT(IF(@rngCurrency=$A6;1;0);rngLedgerDebit;rngDebitRate)/$F6;"")

**Comment by vzczc** [comment]
I made a workaround to avoid the IF statement that handles this case that does not have this problem.
var doubleQuote = """";
sht.Cells[row, col].FormulaR1C1 = "IFERROR(SUMPRODUCT(--(rngCurrency=RC1),rngLedgerDebit,rngDebitRate)/RC6),{doubleQuote})";

**Comment by OssianEPPlus** [comment]
Thanks for your report! We're looking into this

**Comment by OssianEPPlus** [comment]
I am unable to reproduce your error. There's a couple of inconsistencies. The first bit of code:
```
var doubleQuote = """";
sht.Cells[row, col].FormulaR1C1 = "IFERROR(SUMPRODUCT(IF(rngCurrency=RC1,1,0),rngLedgerDebit,rngDebitRate)/RC6),{doubleQuote})";
```
Appears to have an inaccurate formula. The number of parenthesis do not match. There's three `(` and four `)` The doublequotes also are not escaped properly at least not if using c#. I assume what you were going for given the
`=IFERROR(SUMPRODUCT(IF(@rngCurrency=$A6;1;0);rngLedgerDebit;rngDebitRate)/$F6;"")` formula works correctly if the `@` is removed
 was something more like:
```C#
var doubleQuote = "\"\"";
sheet.Cells[row,col].FormulaR1C1 = $"IFERROR(SUMPRODUCT(IF(rngCurrency=RC1,1,0),rngLedgerDebit,rngDebitRate)/RC6,{doubleQuote})";
```

In order for us to get to the bottom of this issue ASAP it would be helpful if you could provide a reproducible codesample and a workbook with the issue of the faulty formula with the `@` symbol present.

If the information is sensitive and/or you can not reproduce it separately you as a commercial customer can always log in to our website and use [our support portal](https://epplussoftware.com/en/Support) to upload files and support tickets privately

**Comment by OssianEPPlus** [comment]
I was able to re-create your error and we are working on a fix. Do note however:
```
var doubleQuote = """";
sht.Cells[row, col].FormulaR1C1 = "IFERROR(SUMPRODUCT(IF(rngCurrency=RC1,1,0),rngLedgerDebit,rngDebitRate)/RC6),{doubleQuote})";
```
Appears to have an inaccurate formula. The number of parenthesis do not match. There's three `(` and four `)` The doublequotes also are not escaped properly at least not if using c#. I assume what you were going for given that the
`=IFERROR(SUMPRODUCT(IF(@rngCurrency=$A6;1;0);rngLedgerDebit;rngDebitRate)/$F6;"")` formula works correctly if the `@` is removed
 was something more like:
```C#
var doubleQuote = "\"\"";
sheet.Cells[row,col].FormulaR1C1 = $"IFERROR(SUMPRODUCT(IF(rngCurrency=RC1,1,0),rngLedgerDebit,rngDebitRate)/RC6,{doubleQuote})";
```
It would potentially help and speed up your case if you could provide a workbook wherein this happens. Also note that as a commercial customer can always log in to our website and use [our support portal](https://epplussoftware.com/en/Support) to upload files and support tickets privately.

**Comment by vzczc** [comment]
The doubleQuote issue was a result of copy/paste loosing this value, it is correct in the code. The same applies to the missing paren.

I will try to create an example for you, but am pressed for time today. I can upload an example in the support portal. There is also another problem when formulas like these are added, if I Calculate the workbook before saving, it takes a very long time. 15 seconds vs 1 if no calculation is done. It is probably easier for you to look at this when you have a test project that does this.

**Comment by OssianEPPlus** [comment]
Any update on this? We have not received a ticket yet.

**Comment by vzczc** [comment]
I have not had time to do this. As we found a way around it, it has not been a pressing issue.

Will try to get back to you shortly with a test that illustrates the issue.

Med vennlig hilsen
Øystein Johnsen
[SynteroLogoBasicNamed3.png]
***@***.******@***.***>
+47 4800 5602
Kronprinsens gate 1
N-0251 Oslo
www.syntero.no<http://www.syntero.no>

**Comment by OssianEPPlus** [comment]
No worries, just checking in as we cannot fully resolve the issue on our end without it.

**Comment by OssianEPPlus** [comment]
Please re-open this issue if you have a workbook available at some point.

**Comment by JanKallman** [comment]
See #1540
