### ISSUE TITLE
Extraneous dependencies added to `net462` target in version 7.1.3

### ISSUE THREAD

**Issue by OronDF343** [EPPlusSoftware/EPPlus#1469]
### EPPlus usage

Noncommercial use

### Environment

Windows 10

### Epplus version

7.1.3

### Description

Version 7.1.3 added the following dependencies to the .NET Framework 4.6.2 target:

[Microsoft.Extensions.Configuration.Json](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/) (>= 8.0.0)
[System.Security.Cryptography.Pkcs](https://www.nuget.org/packages/System.Security.Cryptography.Pkcs/) (>= 8.0.0)
[System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/) (>= 8.0.0)

This change was introduced by PR #1424.

These dependencies were not present in version 7.1.2 and are probably unnecessary, relevant only to newer .NET. Please look into this.

**Comment by AdrianEPPlus** [comment]
Hello!

We are looking into this.

**Comment by JanKallman** [comment]
Removed in EPPlus 7.2.1
