### ISSUE TITLE
Open the file and save it directly without making any changes. The line breaks of all cells are modified.

### ISSUE THREAD

**Issue by H0LIXI** [EPPlusSoftware/EPPlus#1473]
### EPPlus usage

Noncommercial use

### Environment

Windows10

### Epplus version

7.1.x

### Spreadsheet application

Excel

### Description

I used EPPlus to open Excel, modified some cells, and then saved. 
After saving, I found that other cells that I did not modify were also changed. 
And I found that all the changes were line breaks.

I have provided a test project, which contains a TestFile.xlsx. 
After running in the project, TestFile-1.xlsx will be copied and saved using the Epp plug-in. 
After running, you can use BeyondCompare to compare and view
[TestEPPlusLineSymbol.zip](https://github.com/user-attachments/files/15572483/TestEPPlusLineSymbol.zip)

My BeyondCompare result like this.
![image](https://github.com/EPPlusSoftware/EPPlus/assets/19890189/e9973bd4-64da-45e1-8885-d82264f0e656)

**Comment by JanKallman** [comment]
When you have \r\n as line break, it seems to be replaced by two \n\n. I will investigate some more and provide a fix.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.2.2
