### ISSUE TITLE
Read and save excel async is not work

### ISSUE THREAD

**Issue by H0LIXI** [EPPlusSoftware/EPPlus#1481]
### EPPlus usage

Noncommercial use

### Environment

Windows10

### Epplus version

7.1.x

### Spreadsheet application

Excel

### Description

I try to read and save excel async. 
But the excel was not changed after save.

```
using (var excel = new ExcelPackage())
{
    await excel.LoadAsync(excelPath);
    var worksheets = excel.Workbook.Worksheets;
    foreach (var sheet in worksheets)
    {
        sheet.Cells[1, 1].Value = DateTime.Now.ToString();
    }

    await excel.SaveAsync();
}
```

I have provided a simple demo that can reproduce this problem
[TestEPPlusAsync.zip](https://github.com/user-attachments/files/15788111/TestEPPlusAsync.zip)

**Comment by JanKallman** [comment]
The Load/LoadAsync methods will load the file to the `Stream` without setting the ExcelPackage.File property, so if you use SaveAsync it will only save the workbook to the Stream property. Either set the ExcelPackage.File property to the FileInfo you want to save to or use the SaveAsAsync property.

**Comment by H0LIXI** [comment]
> The Load/LoadAsync methods will load the file to the `Stream` without setting the ExcelPackage.File property, so if you use SaveAsync it will only save the workbook to the Stream property. Either set the ExcelPackage.File property to the FileInfo you want to save to or use the SaveAsAsync property.

Thank you for your reply. It works after setting the ExcelPackage.File property
