### ISSUE TITLE
When there is only one member selected, LoadFromCollection adds the class name and not the member value 

### ISSUE THREAD

**Issue by bsonnino** [EPPlusSoftware/EPPlus#150]
When there is only one member selected, LoadFromCollection adds the class name and not the member value. See the attached project. It should add the values of Col2 in the column, but this doesn't happen

[TestEppPlus.zip](https://github.com/EPPlusSoftware/EPPlus/files/4953339/TestEppPlus.zip)

**Comment by swmal** [comment]
I will have a look at this

**Comment by swmal** [comment]
Will be fixed in next version (5.2.1)

**Comment by bsonnino** [comment]
I've submitted a pull request for it.

Bruno

Em ter., 21 de jul. de 2020 às 16:18, Mats Alm <notifications@github.com>
escreveu:

**Comment by swmal** [comment]
Sorry, I missed that. I was working with the LoadFrom[...] functions and removed the nMembers == 1 from the If-statement in my last commit. Good that we came to the same conclusion;)
