### ISSUE TITLE
VALUE function not working with negative values

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#152]
We came across a situation where a value like (10.8)% displays correctly in Excel as -0.108, but throws an error in EPPlus, when used in the VALUE function.  I wrote a test case illustrating this issue and will create a PR.

**Comment by swmal** [comment]
This seems to be a generic thing to implement in the formula calc engine, it doesn't support negative numbers expressed with parenthesis today. I'll see if I can fix it in the VALUE function in the meantime.

**Comment by swmal** [comment]
Hi Randall,

The unit test you provided is now passing and I have added it (with some slight modifications for culture independence) to our codebase. We will have a look at if we should support parenthesis notation for negative numbers in future versions.

**Comment by rdhasse** [comment]
Thanks Mats.  Just so I'm clear, the parenthesis notation will be fixed for the VALUE function in the next release?  Is this fix available in the developer nuget feed?

**Comment by swmal** [comment]
Both... we released a new version on Nuget an hour ago.
