### ISSUE TITLE
Incorrect, misplaced or missing cell values

### ISSUE THREAD

**Issue by robincodex** [EPPlusSoftware/EPPlus#1530]
### EPPlus usage

Personal use

### Environment

Windows

### Epplus version

7.2.1

### Spreadsheet application

Microsoft365 Excel

### Description

[test.xlsx](https://github.com/user-attachments/files/16319065/test.xlsx)
This file was exported by me from a cloud document, after reading the file the cell values are not correct, I tried to read the file using other libraries (e.g. NPOI) is normal values.
I think there may be data formats that EEPLUS did not consider, resulting in incorrect cell values.

**Comment by JanKallman** [comment]
Yes, this is a bug. It seems to happen if you have a shared string item with rich text and an empty `<rPr>` element. I will provide a fix shortly.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.2.2

**Comment by robincodex** [comment]
> Fixed in EPPlus 7.2.2

Great, thanks!
