### ISSUE TITLE
can't find OfficeOpenXml.FormulaParsing.Excel.Functions.Math EPPlus 7.2.1 in .net 8 project

### ISSUE THREAD

**Issue by litn2018** [EPPlusSoftware/EPPlus#1536]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.2.1

### Spreadsheet application

Excel

### Description

added EPPlus 7.2.1 package, but can't find can't find OfficeOpenXml.FormulaParsing.Excel.Functions.Math (DateTime,...) in a .net 8 project. are those implemented and which package should I add too?

thanks

**Comment by JanKallman** [comment]
The  `OfficeOpenXml.FormulaParsing.Excel.Functions.Math` namespace are for the internal math functions used in the formula calculation. It's an EPPlus internal namespace. Why are you referencing this namespace?
