### ISSUE TITLE
MINIFS should return 0 for invalid criteria

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1544]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.2.2

### Spreadsheet application

Excel

### Description

Hello friends, 
I found in EPPlus 7.2.2 that MINIFS returns `#NUM!` if criteria1 is `#NUM!` 

**Syntax & Example:**
`MINIFS(min_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)`
`=MINIFS($F$112:$F$116,$F$112:$F$116,">"&H112)` 

You can see `min_range` and `criteria_range1` are overlapping cell references.
`H112` is `#NUM!` in my worksheet, and EPPlus correctly computes `">"&H112` as `#NUM!` just like Excel.

That yields `=MINIFS($F$112:$F$116,$F$112:$F$116,#NUM!)` but as a final result, Excel returns of `0` while EPPlus returns `#NUM!`

Excel also returns `0` for `criteria` like `#VALUE!`, `">L"`, or blank.
EPPlus returned `0` for `criteria` like `">L"` and blank
EPPlus returned `#VALUE!` for `criteria` `#VALUE!` 

Same results were seen with the `MAXIFS` function as well.

**Comment by swmal** [comment]
Thanks @colbybhearn , we will have a look at this.

**Comment by JanKallman** [comment]
Thanks for the detailed description and the pull request. I will provide a fix shortly.

**Comment by colbybhearn** [comment]
Y'all are the best - thanks so much!

**Comment by swmal** [comment]
@colbybhearn - The PR is merged and the fix will be available in the next version.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.3
