### ISSUE TITLE
Weird layout in Excel for macOS (16.39).

### ISSUE THREAD

**Issue by NgyAnthony** [EPPlusSoftware/EPPlus#155]
### Version
macOS Version: Catalina 10.16
Excel macOS version: 16.39

### Issue
Opening the generated file from the .NET Framework sample with Excel gives me a weird layout, pattern is repeated when I scroll down.
Doesn't happen on Windows and file is normal on Libreoffice for macOS, so it's probably specific to Excel for macOS...

Edit: I did some tests, exporting to PDF is fine, exporting to ODS and back to XLSX fixes the layout issue.

### Screenshot
<img width="1792" alt="Capture d’écran 2020-07-26 à 16 08 15" src="https://user-images.githubusercontent.com/26002874/88481293-c6f25d00-cf5a-11ea-8af6-0e9a2b41e7b5.png">

**Comment by JanKallman** [comment]
I'll have a look

**Comment by NgyAnthony** [comment]
I don't know if it helps but excel already had issues when Apple dropped support for 32 bits apps in Catalina, the spreadsheet was upside down https://answers.microsoft.com/en-us/msoffice/forum/all/excel-text-is-upside-down-and-back-to-front/8b4fc631-92fc-4030-8277-267310b6cf0f

**Comment by NgyAnthony** [comment]
Disabling `worksheet.View.PageLayoutView = true;` fixes the issue

**Comment by JanKallman** [comment]
Might be something wierd with the pagelayout mode and macOS. I'll see if I can fix the sample to look better in page layout.
