### ISSUE TITLE
Error in PivotTable cache when performing multiple writes of DateTime values to source tables

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [EPPlusSoftware/EPPlus#1554]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.2.2

### Spreadsheet application

Excel

### Description

When performing multiple iterations of writing and formatting DateTime values in an Excel table using the OfficeOpenXml library, the second iteration causes an error in the PivotTable cache.

This error is detected and repaired upon opening the Excel file:
![image](https://github.com/user-attachments/assets/278b1626-4be3-4e2a-b7d1-56d6cc9b5349)
![image](https://github.com/user-attachments/assets/f15c961b-a4f5-4b6e-9bdd-17177dd09ad4)

An additional unexpected numerical value can be found in the values for the Date column in the PivotTable cache:
![image](https://github.com/user-attachments/assets/354da72c-9b13-4016-9dab-efd1dd8d4ea3)

I have tried calculating and refreshing PivotTables prior to saving, but the problem persists.

Please find the attached sample workbook and code to reproduce the error:
[PivotTableCache_DateTime_Error.zip](https://github.com/user-attachments/files/16531590/PivotTableCache_DateTime_Error.zip)

**Comment by AdrianEPPlus** [comment]
Not sure yet why this happens, but we will look into it.

**Comment by JanKallman** [comment]
The problem seems to be the way EPPlus handles dates when loading the workbook. EPPlus only converts dates that uses build in number formats to dates. This causes the creation of the pivot cache to identify the date loaded from the workbook as a number instead of a date. I will try to provide a fix for this issue.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.3
