### ISSUE TITLE
ask about Grouping and Collapsed

### ISSUE THREAD

**Issue by goddy2020** [EPPlusSoftware/EPPlus#1559]
this my code
![2024-08-13 16_49_14-VCIS MARS - Microsoft Visual Studio](https://github.com/user-attachments/assets/83b38377-3121-4d4b-a6e0-3f13d138018c)

i need to collapsed at outlinelevel 1 but not working for me 
![2024-08-13 16_51_19-Hard Coat Cumulative Daily Report_20240813_161440 - Excel](https://github.com/user-attachments/assets/1805431d-8e4b-4a45-bdab-4b8669faddcf)

**Comment by JanKallman** [comment]
You can use `SetVisibleOutlineLevel(int)`, if you want to collapse all levels to the same level.
This is descibed in our wiki here: the https://github.com/EPPlusSoftware/EPPlus/wiki/Grouping-and-Ungrouping-Rows-and-Columns
