### ISSUE TITLE
Support for filtering on pivot table fields

### ISSUE THREAD

**Issue by JanKallman** [EPPlusSoftware/EPPlus#156]
Setting filters on Row, Column and page fields. Also see #117 and #133 .

**Comment by mrtristan** [comment]
+1

just spent a _lot_ of time trying to figure out how to do this. is this locked for that 5.3 milestone?

**Comment by JanKallman** [comment]
This is goal. I'm currently working on this and redesigning the pivot table cache as part of the slicer implementation.
If this is not to complicated this will go into 5.3. I'll get back to you when I know for sure.

**Comment by JanKallman** [comment]
We will move this to EPPlus 5.4, as we will make some changes to the pivot cache as well. But I hope this can be available in late September.
