### ISSUE TITLE
Corrupt workbook caused by conditional formatting in pivot table

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#1562]
Adding data to a template with a pivot table that contains conditional formatting causes in some cases a corrupt workbook when opened in Excel.

**Comment by JanKallman** [comment]
WIP https://github.com/EPPlusSoftware/EPPlus/tree/feature/pivottable_conditional_formatting

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.4
