### ISSUE TITLE
Calculation after ClearFormulas fails

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1566]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.2.2

### Spreadsheet application

Excel

### Description

My application integrates with Excel spreadsheets that can also be used by a human via Excel. As such, the Excel template my application starts with has some VBA-defined functions referenced in formulas. In order for EPPlus to calculate the package, I call `ClearFormulas()` on those 1 or 2 cells. This worked great in v5/6, but it is not working in v7. 

Seems the formulas is set to `null`, but the CellStore or RpnFormulaExecution either isn't getting the message or isn't prepared to handle a null.

I will put together a pull request with a broken test which calls `ClearFormulas()` and **then** `Calculate()`.

If there's any way this can make it into v7.2.3, it would be amazing, but I understand if it just doesn't!
All the best.

**Comment by JanKallman** [comment]
Thanks, I have provided a fix.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.3
