### ISSUE TITLE
COUNTIFS not matching true & false as expected

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#1578]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.3

### Spreadsheet application

Excel

### Description

It seems the true/false value matching is not working like Excel's.
Excel matches the value `True` using criteria `True` or `"True"`
EPPlus does _not_ match the value `True` using criteria `True` or `"True"`
EPPlus only matches the value 'True' with `1` or `"1"`.

I did not see tests for true/false values, nor for multiple sets of arguments, so I added those in PR #1575

**Comment by swmal** [comment]
Thanks @colbybhearn - I will have a look at this.
