### ISSUE TITLE
Has AddPicture been optimised? (Old issue: AddPicture is slow when adding a lot of images)

### ISSUE THREAD

**Issue by MHillier98** [EPPlusSoftware/EPPlus#158]
Trying to debug a problem with EPPlus 4.5, but can't find anywhere else to ask this properly, so I'm sorry if this is the wrong place to ask!

I'm currently trying to generate reports with large numbers of images (~20KB each), and anywhere from 1 to a few thousand rows each. I found an old issue here, but it was never resolved: https://github.com/JanKallman/EPPlus/issues/10

I've managed to cut down on *some* time by adding a Dispose() call after loading my System.Drawing.Image and calling AddPicture().

Maybe it's just a downside of adding so many images, but any help would be much appreciated! Thanks!

Edit: Here's a graph I put together:
![image](https://user-images.githubusercontent.com/26564949/88881669-578aaf00-d273-11ea-869f-cb03871b9cde.png)

**Comment by JanKallman** [comment]
I cant help you with the EPPlus 4.5 picture handling as a new picture store has been added in 5.0, mostly to make it more clean, as the old implementation was not that flexible. 
I'm unsure about the performance in your scenario in EPPlus 5, but feel free to try it out.

**Comment by MHillier98** [comment]
Ok, thanks for the quick response!

Unfortunately I'm not sure I'll be able to test my real world solution with EPPlus 5, but I'll see if I'm able to get some time to make a test project.

If you're interested and want to try replicate/test it yourself, the graph above is just a simple for loop, where I set the row height and use the process I mentioned above with AddImage().

**Comment by JanKallman** [comment]
Sure I'll check it out. Thanks for reporting it.

**Comment by JanKallman** [comment]
Is faster now with the new picturestore
