### ISSUE TITLE
Can't insert image in Header or Footer

### ISSUE THREAD

**Issue by d3-oleg-hadkevich** [EPPlusSoftware/EPPlus#1588]
### EPPlus usage

Noncommercial use

### Environment

Mac

### Epplus version

6.2.7

### Spreadsheet application

Numbers

### Description

 Based on the documentation, I can insert an image in the header or footer using this modified example.
**InsertPicture** method doesn't create a picture in the header or footer in Numbers at printing.
I tried 6.2.7 and 7.3
But I'm sure that this functionality is working in 4.5.3.2
```
using System;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Drawing;

namespace EPPlusSamples.DrawingsChartsAndThemes
{
    public static class ShapesAndImagesSample
    {
        public static void Run()
        {
            Console.WriteLine("Running sample 5.1-Shapes & Images");
            var outputFile = FileUtil.GetCleanFileInfo("5.1-ShapesAndImages.xlsx");
            using (ExcelPackage package = new ExcelPackage(outputFile))
            {
                PictureSample(package);
                package.Save();
            }
            Console.WriteLine("Sample 5.1 created {0}", FileUtil.OutputDir.Name);
            Console.WriteLine();
        }

        private static void PictureSample(ExcelPackage package)
        {
            var ws = package.Workbook.Worksheets.Add("Picture");

            var fileInfo = FileUtil.GetFileInfo("05-Drawings charts and themes\\01-Shapes and images",
                "LandscapeView.jpg");
            
            //Inserting the picture doesn't work
            //With any available parameters combination
            //No pictures in Numbers at printing
            var image = ws.HeaderFooter.OddHeader
                .InsertPicture(fileInfo, PictureAlignment.Left);

            using (var fs = new FileStream(fileInfo.FullName, FileMode.Open))
            {
                var drawing = ws.HeaderFooter.OddHeader.InsertPicture(fs, ePictureType.Jpg, PictureAlignment.Left);
            }
        }
    }
}

```

**Comment by AdrianEPPlus** [comment]
I tested your code above using EPPlus 7.3 and it works fine with a few modifications.

I created a new project and added EPPlus using nuget. I changed the FileUtil class to use FileInfo instead as FileUtil only exsist inside the sample project.

Run the code, Open the resulting file in Excel. You can verify that we have a header in 2 ways. First you can go to Insert  -> HeaderFooter and the image should show up in the new view.
Second if you add a value to any cell(either in EPPlus or Excel) you can go to File -> Print and you should see the image in the header in the preview.

```
        public static void Run()
        {
            Console.WriteLine("Running sample 5.1-Shapes & Images");
            var outputFile = @"C:\epplusTest\Testoutput\5.1-ShapesAndImages.xlsx";
            using (ExcelPackage package = new ExcelPackage(outputFile))
            {
                PictureSample(package);
                package.Save();
            }
            Console.WriteLine("Sample 5.1 created {0}", @"C:\epplusTest\Testoutput");
            Console.WriteLine();
        }

        private static void PictureSample(ExcelPackage package)
        {
            var ws = package.Workbook.Worksheets.Add("Picture");

            var fileInfo = new FileInfo(@"C:\epplusTest\Testoutput\ga5g45sa2lmd1.jpeg");

            //Inserting the picture 
            var image = ws.HeaderFooter.OddHeader.InsertPicture(fileInfo, PictureAlignment.Left);

        }
```

**Comment by d3-oleg-hadkevich** [comment]
I have just double-checked.
Yes, it works on Windows, but not on the Mac
Could you investigate it, please?

**Comment by AdrianEPPlus** [comment]
In what way does it not work? Could you provide more information and a step by step of what you are doing?

**Comment by d3-oleg-hadkevich** [comment]
I'm using the same code as you provided. 
Then open in **Numbers** xlsx and print. I don't see any picture in the header.
Then I tried converting this xlsx in online converters (xlsx -> pdf) and I can see the image in the header.

The only difference in OS I suppose

**Comment by d3-oleg-hadkevich** [comment]
Ok, I found the issue. 
If I print via Numbers -> no image logo
If I print via Excel -> the header image logo will be printed
I can close this bug
