### ISSUE TITLE
Vulnerabilities in transitive dependencies

### ISSUE THREAD

**Issue by Tsingis** [EPPlusSoftware/EPPlus#1589]
### EPPlus usage

Personal use

### Environment

Windows/Linux

### Epplus version

7.3.1

### Description

Usage of vulnerable transitive dependencies of `System.Text.Json` and `System.Formats.Asn1`.

**Comment by swmal** [comment]
To fix this vulnerability we most likely need to take direct dependencies on the latest version of these two Nuget packages which are indirect dependencies today. `System.Text.Json` is referenced via `Microsoft.Extensions.Configuration.Json` and `SystemFormats.Asn1` is referenced via `System.Security.Cryptography.Pkcs`. See the following discussions: https://github.com/dotnet/runtime/issues/107342 and https://github.com/dotnet/runtime/issues/105028

We will provide a patch for this.
