### ISSUE TITLE
Is AutoFitColumns async?

### ISSUE THREAD

**Issue by Misiu** [EPPlusSoftware/EPPlus#159]
I'm using EPPlus v 3.1.3.3 in a personal app.
Right now I'm trying to move everything to async/await.
The last part missing is EPPlus.

Currently I have this code:

```
using (var pck = new ExcelPackage())
{
    ExcelWorksheet ws1 = pck.Workbook.Worksheets.Add("A");
    ws1.Cells["A1"].LoadFromDataTable(a, true);
    ws1.Cells[ws1.Dimension.Address].AutoFitColumns();

    ExcelWorksheet ws2 = pck.Workbook.Worksheets.Add("B");
    ws2.Cells["A1"].LoadFromDataTable(b, true);
    ws2.Cells[ws2.Dimension.Address].AutoFitColumns();

    ExcelWorksheet ws3 = pck.Workbook.Worksheets.Add("C");
    ws3.Cells["A1"].LoadFromDataTable(c, true);
    ws3.Cells[ws3.Dimension.Address].AutoFitColumns();

    try
    {
        pck.SaveAs(newFile);
        Process.Start(newFile.FullName);
    }
    catch (Exception ex)
    {
        Debug.WriteLine(ex.Message);
    }
}
```
`LoadFromDataTable` is fast, but `ws1.Cells[ws1.Dimension.Address].AutoFitColumns();` takes much longer to complete (I have around 40 columns and 300 rows).
I've noticed that there is an example showing async/await (https://github.com/EPPlusSoftware/EPPlus.Sample.NetFramework/blob/master/03-UsingAsyncAwait/UsingAsyncAwaitSample.cs) but I can't find anything about async version of `AutoFitColumns`.
If it doesn't exist then is there a chance to add it?

**Comment by swmal** [comment]
Hi Misiu,

there is no async version of AutoFitColumns because it does not contain any asynchronous calls. The async methods we have added all have some kind of i/o calls under the hood. AutoFitColumns  loops over every cell of your range and measures the pixel length of strings and other elements with the selected font, font size, etc with GDI+ which only has a synchronous interface.

/Mats

**Comment by swmal** [comment]
I can add that Jan and I discussed this today and we might test to replace System.Drawing with something else and see If that helps.

**Comment by JanKallman** [comment]
Async for AutoFitColumns will not be an option. We might look into some sort of "fast handling" where you maximize the number of cells checked. Possibly by randomizing a number of cells in a large range. I close this issue and open a new once we implement that functionality.
