### ISSUE TITLE
Property Indexed of class ExcelColorXml always returns 0

### ISSUE THREAD

**Issue by enragez** [EPPlusSoftware/EPPlus#160]
Property "Indexed" of class "ExcelColorXml" always returns 0, even if was initialized as int.MinValue.
This leads to method "LookupColor" of class ExcelColor always returns #FF000000.

**Comment by JanKallman** [comment]
Thanks! I'll try to supply a fix to the next version

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.3
