### ISSUE TITLE
Formula conditional formatting error.

### ISSUE THREAD

**Issue by PashaGoroshko** [EPPlusSoftware/EPPlus#161]
Hello!
I add a condition for the cells, but an error occurs when opening the Excel document. The formula works great in Excel.

                    var _cond = workSheet.ConditionalFormatting.AddExpression(new ExcelAddress(excelCellAddress.Address));
                    //workSheet.ConditionalFormatting.
                    _cond.Style.Fill.PatternType = ExcelFillStyle.Solid;
                    _cond.Style.Fill.BackgroundColor.Color = Color.Red;

                    _cond.Formula = $"IF(IFNA(MATCH(C9;SheetTest!$A$3:$A$4;0);0) > 0;TRUE())";

What can you do about it?

**Comment by swmal** [comment]
Hi,

we will have a look at this

**Comment by swmal** [comment]
I think I see the error. You should not use semi-colon as separators with EPPlus/OOXML, that's a localization thing in the Excel client.

What if you change your last row to this?

`_cond.Formula = $"IF(IFNA(MATCH(C9,SheetTest!$A$3:$A$4,0),0) > 0,TRUE())";`

**Comment by PashaGoroshko** [comment]
I am using Russian localization.

I corrected the formula as you wrote

IF(IFNA(MATCH(C9,SheetTest!$A$3:$A$4,0),0) > 0,TRUE())

Formatting didn't work, BUT I noticed that Excel didn't translate one function correctly.

=ЕСЛИ(**IFNA**(ПОИСКПОЗ(C9;SheetTest!$A$3:$A$4;0);0) > 0;ИСТИНА())

After that, I disassembled the correct Excel, and found that the "IFNA" function is not spelled out much differently. What is the reason, I did not have time to figure it out.
But it helped me.

**_This is a working function!_**

IF(_xlfn.IFNA(MATCH(C9,SheetTest!$A$3:$A$4,0),0) > 0,TRUE())

**Comment by swmal** [comment]
Ok, I recognize the _xlfn prefix from the work with our formula engine. It is a hack in Excel so that older versions that don't have support for newer functions to support them. Could be that your version of Excel requires it in order to execute those functions?

**Comment by swmal** [comment]
IFNA was introduced in Excel 2013. Versions prior would need the _xlfn.
