### ISSUE TITLE
The 'extLst' start tag on line 1 position 1610 does not match the end tag of 'ext'

### ISSUE THREAD

**Issue by lintaoqm** [EPPlusSoftware/EPPlus#1610]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.3.2

### Spreadsheet application

wps

### Description

When the spreadsheet uses the 'autofilter' feature, saving the spreadsheet inserts unmatched </ext>. I suspect there might be an issue with the implementation of ExtLstHelper::ParseIntialXmlToList(string xml, ExcelWorksheet ws) based on my review of the source code. I have provided the source code and the spreadsheet for reproduction nearby.
[ConsoleApp2.zip](https://github.com/user-attachments/files/17198991/ConsoleApp2.zip)

**Comment by OssianEPPlus** [comment]
Epplus is built on the OOXML standard. Your workbook contains the following node:
```XML
 <autoFilter xmlns:etc="http://www.wps.cn/officeDocument/2017/etCustomData" ref="A1:A3" etc:filterBottomFollowUsedRange="0">
  <extLst>
    <etc:autoFilterAnalysis etc:version="v1" etc:showPane="0"/>
  </extLst>
</autoFilter>
```
This is a WPS unique node and it seems WPS has created an autoFilterAnalysis node immediately after the extLst node. This is an invalid child and an invalid use of the ExtLst element in OOXML. As there should be an Ext element after ExtLst. Epplus expects a valid node and as such casts an exception/writes the file incorrectly.

Epplus supports the OOXML standard and it seems WPS has created an invalid node.

Before saving with Epplus, your original workbook has the following issues:
![image](https://github.com/user-attachments/assets/1bc7e290-a6c5-4c80-84cc-ac905e636c6a)
This causes Epplus to save incorrectly.
