### ISSUE TITLE
when adjust the row height as so slower

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#162]
Now i have a problem asking for help, 
（EpplusTemplate.xlsx）there are a lot of shape in the excel template, 
I have to dynamically adjust the row height, 
the execution speed becomes slower (the more shape slower). 
I think it's because adjusting the row height when traversing each shape causes the problem of slowing down, but is that a problem? Please confirm.

Another solution? Or to improve the logic of epplus itself?
epplus:5.2.0

[EpplusTemplate.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5026486/EpplusTemplate.xlsx)

using System;
using System.IO;
using OfficeOpenXml;

namespace EPPLUS_TEST
{
    class Program
    {
        static void Main(string[] args)
        {

            DateTime dt1 = DateTime.Now;
            string pathName = @"D:\EPPLUS\Test\";

            string fileNameTest = pathName + "EpplusTemplate.xlsx";
            FileInfo fi = new FileInfo(fileNameTest);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (ExcelPackage excelPackage = new ExcelPackage(fi))
            {
                ExcelWorksheet firstWorksheet = excelPackage.Workbook.Worksheets[0];
                for (int i = 46; i <= 2000; i++)
                {
                    firstWorksheet.Row(i).Height = firstWorksheet.Row((i - 1) % 45 + 1).Height;
                    Console.WriteLine($"TIME{i}:{DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss.ffffff") }");
                }

                FileInfo fi1 = new FileInfo(pathName + "EpplusTemplateOut.xlsx");
                excelPackage.SaveAs(fi1);
            }

            DateTime dtLast = DateTime.Now;
            Console.WriteLine($"END TIME:{dtLast.ToString("yyyy/MM/dd HH:mm:ss.ffffff") }");
            Console.WriteLine($"TOTAL TIME(s):{(dtLast - dt1).TotalSeconds}");
        }
    }
}

----------log---------

TOTAL   TIME(s):37.10768
----------------------

**Comment by JanKallman** [comment]
Try setting the `package.DoAdjustDrawings = false;` to avoid the resizing.
You will have to do any adjustment to the drawinga size manually when this property is set to false.

**Comment by 93910676wangd** [comment]
Thank you professor. I'll do it and see.

**Comment by 93910676wangd** [comment]
Execution time is now super fast.
thank you very much.
