### ISSUE TITLE
Image sizes broken

### ISSUE THREAD

**Issue by paviad** [EPPlusSoftware/EPPlus#1626]
### EPPlus usage

Personal use

### Environment

Windows

### Epplus version

7.4.1

### Spreadsheet application

Excel

### Description

When creating a new file based on a template, the images in the output are different than those in the template.

This bug applies to versions 7.4.0 and 7.4.1 (in version 7.3.2 it works fine)

This is a screenshot of the template:

![image](https://github.com/user-attachments/assets/456bba84-82eb-4c95-9416-a621dbd0334c)

This is a screenshot of the bad output:

![image](https://github.com/user-attachments/assets/f58f03cc-e99b-45dc-bfe4-d33588fedd5e)

See my repo at https://github.com/paviad/eeplus-bug for a minimal repro.

**Comment by paviad** [comment]
`git bisect` indicates that this is the first bad commit 02ca05034021b2c7b75c212e5eaf96e4d6c0c4ef

**Comment by OssianEPPlus** [comment]
Thanks for reporting! This is a bug introduced with some changes related to image handling to introduce linked pictures. Essentially for some re-calculations we need to load the image at 100% original size, this was intended to be temporary/internal but a bug has been introduced in the handling.
We are working on a fix.
