### ISSUE TITLE
ArgumentOutOfRange accessing Worksheets with conditional formatting

### ISSUE THREAD

**Issue by adaneam** [EPPlusSoftware/EPPlus#163]
Hi, I get an ArgumentOutOfRangeException when trying to read excel created with EPPlus (v5.2.1). This error occurs when you try to access ExcelPackage.Workbook.Worksheets property or when you try to read x.x.Cells[1,1] etc

This happens when you use conditional formatting.
I have attached a .NET core console project to recreate the issue. It will create the excel file on the first run. Second run onward it fails to read this excel.

If you open the excel with MS Excel and save it again then EPPLus doesn't throw an exception. Please let me know if you need more information.

Related issue - #121 

[EPPlus.Issue.zip](https://github.com/EPPlusSoftware/EPPlus/files/5042447/EPPlus.Issue.zip)

**Comment by adaneam** [comment]
Seems like exception occurs when color is missing the alpha. Problematic code in file ExcelDxfStyle.cs
See the below pic for example

![image](https://user-images.githubusercontent.com/5147039/89728600-fec5ce00-da4b-11ea-8b85-c3d149fbf99a.png)

**Comment by adaneam** [comment]
Created a PR #165

**Comment by JanKallman** [comment]
PR merged to develop

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.3
