### ISSUE TITLE
Can you provide a method to quickly find out what functions are not implemented compared to Excel?

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1630]
If I have a list of unimplemented functions, I can pre-judge whether the user has a worksheet function in the Excel file that EPPLUS does not implement, and if so, I don't caculate it

for example FORMULATEXT ,This function is not implemented yet, I can know in advance by comparing it in the list.

The problem I have at the moment is that I calculate the worksheet, and finally convert the ExcelTable into the memory table datatable, and find that I have lost data, and finally know that it is because the formula calculation has no value caused.

**Comment by OssianEPPlus** [comment]
We have a list of implemented functions [here](https://github.com/EPPlusSoftware/EPPlus/wiki/Supported-Functions)

**Comment by minren118** [comment]
Thanks for your efforts, today I re-compared and found that it was amazing that EPPLUS implemented almost all Excel functions

I see a few functions that are still relatively common, and I want to implement them first

ENCODEURL
FILTERXML
FORMULATEXT
ISFORMULA

Finally, I've put together a list of unimplemented functions that I hope you'll find useful
[Excel formula compare.zip](https://github.com/user-attachments/files/17397693/Excel.formula.compare.zip)

**Comment by OssianEPPlus** [comment]
Thank you!

Most of these were on our internal roadmap but I do see a few we might've missed or under-prioritized! We appreciate it.
