### ISSUE TITLE
when create worksheet from template sheet, some cell's formula incorrect

### ISSUE THREAD

**Issue by eurohung** [EPPlusSoftware/EPPlus#1631]
### EPPlus usage

Noncommercial use

### Environment

windows 11

### Epplus version

7.4.1

### Spreadsheet application

Excel

### Description

after create worksheet from template sheet, some cell's formula incorrect.
[issue.xlsx](https://github.com/user-attachments/files/17392184/issue.xlsx)
my test class as follow
``` C#
[TestMethod]
public void copyIssue()
{
    using (var p = OpenTemplatePackage("issue.xlsx"))
    {
        using (var p2 = OpenPackage("issue-save.xlsx", true))
        {
            var src = p.Workbook.Worksheets.First();
            ExcelWorksheet dup = p2.Workbook.Worksheets.Add("dup",src );
            for (int col = 1; col < src.Dimension.End.Column; col++)
            {
                Console.WriteLine($"is equal? :{src.Cells[5, col].FormulaR1C1.Equals(dup.Cells[5, col].FormulaR1C1)},{src.Cells[5, col].FormulaR1C1} => {dup.Cells[5, col].FormulaR1C1}");
            }
            for (int col = 1; col < src.Dimension.End.Column; col++)
            {
                Assert.AreEqual(src.Cells[5, col].FormulaR1C1, dup.Cells[5, col].FormulaR1C1);
            }
            //SaveAndCleanup(p2);
        }
    }
}
```

**Comment by OssianEPPlus** [comment]
Thanks for reporting! Your example made it very easy to verify. This is indeed a bug. 
It's a particular edge-case where the [5, 6] or F5 cell refers to a sharedformula and that shared formula refers "backwards" in this case a range "F2:H5" but considers it's start point "H2" for its formula (see picture).
![bild](https://github.com/user-attachments/assets/0f5fefb5-437c-4cd8-8ee1-16cc39b07425)

We've added handling for this previously but the new changes had not been added appropriately to the copy/clone functions. We are working on a fix!
