### ISSUE TITLE
The AddRow method of ExcelTable fails when another ExcelTable is in another worksheet and a pivot table is referenced

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1639]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.4

### Spreadsheet application

Excel365

### Description

The AddRow method of ExcelTable fails when another ExcelTable is in another worksheet and a pivot table is referenced
When the package.SaveAs method is running, an error is reported that an item with the same key has been added to the dictionary

System.InvalidOperationException
  HResult=0x80131509
  Message=Error saving file \testResult.xlsx
  Source=EPPlus
  StackTrace:
   at OfficeOpenXml.ExcelPackage.Save()
   at OfficeOpenXml.ExcelPackage.SaveAs(String filePath)
   at ConsoleApp2.Program.Main(String[] args) in Program.cs:line 58

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
ArgumentException: 已添加了具有相同键的项。

![image](https://github.com/user-attachments/assets/9b4afd2b-5c8d-4456-8ce4-15f590493bb0)

![image](https://github.com/user-attachments/assets/3500f423-415d-482e-9fac-2a3d46e6f011)
[excelTableAddRowError1.xlsx](https://github.com/user-attachments/files/17428857/excelTableAddRowError1.xlsx)

It is hit when another ExcelTable has an error value, normal when IFEEROR is used to clear the error value, and normal when a pivot table is deleted without clearing the error value

```
            using (var package = new ExcelPackage("excelTableAddRowError1.xlsx"))
            {
                var worksheet = package.Workbook.Worksheets["excelTable1"];  
                var excelTable = worksheet.Tables[0];
                excelTable.AddRow(10);
                package.SaveAs("testResult.xlsx");
            }

```

**Comment by OssianEPPlus** [comment]
We've looked into it, it appears error values in tables that a pivot table is based on do not refresh their values correctly in one of our internal hashtables. We are working on a fix.

**Comment by OssianEPPlus** [comment]
A fix for this is now available in our  [develop NuGet Feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed)

**Comment by minren118** [comment]
thanks your efforts
