### ISSUE TITLE
Broken link "Ofice Open XML"

### ISSUE THREAD

**Issue by Dean-NC** [EPPlusSoftware/EPPlus#164]
Please fix the broken link called "Ofice Open XML" at the top of this page:

https://www.epplussoftware.com/Developers/Features

I was wanting to read more about that, but the link is broken.

**Comment by JanKallman** [comment]
Something temporary? Works fine when I try it. 
Otherwise try this link which also includes the language code...
https://epplussoftware.com/en/Developers/
Let me know if you have further problems.

**Comment by swmal** [comment]
Hi,

sorry for the broken link. Will be fixed in 10 min.

**Comment by Dean-NC** [comment]
Thanks @swmal, it was the Open XML link, not the Features link. I posted the Features link to say where the broken Open XML link was located.

It works now.
