### ISSUE TITLE
When copying rows, the size of the copied shapes will changed (width)

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#1640]
### EPPlus usage

Noncommercial use

### Environment

windows

### Epplus version

7.4.1

### Spreadsheet application

excel

### Description

In EPPlus 7.4.1 version, after using the "ExcelRangeBase.Copy" method to copy shapes, the size（width） of the shapes changed.
Please refer to the images for details.

![image](https://github.com/user-attachments/assets/85ab6a7d-b473-4d44-afec-6e198623e222)

As shown in the figure, when copying from lines 1-10 to lines 11-20, the width of the shape widens and narrows.
[EPPlusLinuxApp.zip](https://github.com/user-attachments/files/17429409/EPPlusLinuxApp.zip)

**Comment by OssianEPPlus** [comment]
It looks similar to the #1627. The `Worksheet.Cells[].Copy` function only copies data. Not the width and height of cells.

It seems the cells may not be set correctly to the pre-defined column widths. At least not when part of a merged cells. We'll invistigate and get back to you.

**Comment by JanKallman** [comment]
This workbook has a font of the normal style that is not present in the EPPlus FontSize collection.
Excel uses the width of the standard font to calculate the width of the columns (see the ooxml documentation for the column width property). EPPlus has a collection of the most common fonts in the static class FontSize.
You can add this font yourself like this:
```C#
                FontSize.FontWidths.Add("ＭＳ Ｐゴシック", new Dictionary<float, short> { { 11, 8 } });
```
