### ISSUE TITLE
 Unable to correctly handle the situation where different parts of text within a single cell have different styles

### ISSUE THREAD

**Issue by uganh16** [EPPlusSoftware/EPPlus#1653]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.4.0

### Spreadsheet application

Excel

### Description

[hero_improve.xlsx](https://github.com/user-attachments/files/17486638/hero_improve.xlsx)

I have some strange files that need to be processed, where different parts of text in some cells have different styles.

![f9f457d1-5882-442d-a26e-f422d8e532f8](https://github.com/user-attachments/assets/c5f51a55-df62-472b-9ad6-a7fa70cbf3f7)

In `hero_improve.xlsx/xl/sharedStrings.xml`, it appears as a `si` element mixed with multiple `t` and `r` elements.

![178bb5f4-4bef-48af-9d99-c049ce7ef24b](https://github.com/user-attachments/assets/e0f39e06-e919-4903-8ba7-449959dd5fe9)

Reference code lines: https://github.com/EPPlusSoftware/EPPlus/blob/90de83fa49039eb334ccfcf1a61cdff32b122543/src/EPPlus/ExcelWorkbook.cs#L340

It seems there is no way to get the full content of the cell.

```c#
using (var package = new ExcelPackage("hero_improve.xlsx"))
{
	ExcelWorkbook workbook = package.Workbook;
	ExcelWorksheet worksheet = workbook.Worksheets[0];

	var cell = worksheet.Cells["C17"];

	// Assert failed: `cell.Text` and `cell.Value` are both empty string
	Debug.Assert(cell.Text == "{\"any_orange_frag\" : 700, \"any_purple_frag\" : 800,\"any_blue_frag\" : 1200, \"any_green_frag\":2500}");
}
```

**Comment by JanKallman** [comment]
You have an empty <t/> element in the beginning of all your si-elements in the shared strings table.
For example:
```Xml
<si>
<t/>
<r>
<rPr>
<sz val="9.75"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t>{"any_</t>
</r>
<r>
<rPr>
<sz val="10.5"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t xml:space="preserve">purple_frag":200, "any_blue_frag" : 200, "any_green_frag" : 500}</t>
</r>
</si>
<si>
<t/>
<r>
<rPr>
<sz val="9.75"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t>{"any</t>
</r>
<r>
<rPr>
<sz val="10.5"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t>_orange_frag</t>
</r>
<r>
<rPr>
<sz val="9.75"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t xml:space="preserve">" : 700</t>
</r>
<r>
<rPr>
<sz val="10.5"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t xml:space="preserve">, "any_purple_frag" : 800,"any_blue_frag" : 1200, "any_green_frag":2500</t>
</r>
<r>
<rPr>
<sz val="9.75"/>
<color rgb="FF000000"/>
<rFont val="Calibri"/>
<family val="2"/>
</rPr>
<t>}</t>
</r>
</si>
```
Resaving this file in Excel causes this element to be removed.
EPPlus currently reads either the t-element (Text) or the list or r-elements (Rich Text).
It seems the standard supports having a t-element and then a list of r element, but I have never seen this before.
We will look at a fix for this in a coming version. For now, if possible, remove the empty t-element.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
