### ISSUE TITLE
About encode /r/n

### ISSUE THREAD

**Issue by H0LIXI** [EPPlusSoftware/EPPlus#1655]
**problem**
I found that in EPP version 7, when reading a cell without modifying its content and then saving it, all the newline characters get re-encoded.

Using Microsoft Excel, create a table and enter content with a newline. Save it directly. When you check the sharedStrings.xml file in hexadecimal, you can see that the newline character is 0D0A, which corresponds to \r\n.
After saving with EPP version 7, 0D0A gets re-encoded as 5F 76 30 30 30 44 5F 0A, which corresponds to _x000D_\n.
After saving with EPP version 6, 0D0A gets rewritten as 0A, which corresponds to \n. (This might be because version 6 uses XmlNodeList to read, which converts \r\n to \n, while version 7 uses XmlReader and can read the original \r\n.)

I'm not quite sure why \r needs to be re-encoded as _x000D_. Perhaps there's some historical reason for this. The encoding happens in ConvertUtil.ExcelEncodeString.

**Desired Solution**
I hope to retain the original \r\n because if the newline characters throughout the file change, it will cause a lot of differences when viewed in comparison tools like BeyondCompare5, which can be confusing.
Alternatively, could we refer to the behavior in EPP version 6, but replace \r\n with \n when saving? (Because BeyondCompare can recognize \r\n and \n as the same.)

**Comment by JanKallman** [comment]
I'll have a look at the encoding again. The _x000D_ (for cr) encoding is used for characters below 0x20, but should probably not be used for crlf.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by JanKallman** [comment]
This has been fixed in EPPlus 7.5.0

**Comment by H0LIXI** [comment]
@JanKallman Hello JanKallman, I found that after this fix, another issue appeared. When the newline character in the previous file was \_x000D\_\r\n, opening it in Excel would show only one line break. After saving with version 750, \_x000D\_\r\n becomes \r\r\n, and opening it in Excel results in two line breaks. After saving in Excel, it becomes \r\n\r\n.

You can use this file to test.
[Test-rrn.xlsx](https://github.com/user-attachments/files/17813605/Test-rrn.xlsx)
