### ISSUE TITLE
Can I read and write a part of a workbook such as a worksheet to improve the performance of excelPackage.Save?

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1660]
At present, I tried to read a multiple worksheet with tens of thousands of rows of data, and Simply read and write a bit of data from some worksheet.
the last run of excelPackage.Save Or excelPackage.SaveAs , would wait for nearly a minute, which is too long.

I understand that a workbook is a zip file, logically, if you can read it step by step, similar to open a zip file, only modify one of the contents, and then save, the speed can be very fast.

**Comment by AdrianEPPlus** [comment]
EPPlus reads the whole worksheet when loading it. If you make any changes EPPlus will save the whole worksheet. Larger workbooks will then take some time to save. We are always looking for ways to improve performance and we might improve the performance of the save method in a future version.
