### ISSUE TITLE
PivotTableCache's RefreshOnLoad is turned on automatically, which is not what I wanted

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#1666]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.4.2.1079

### Spreadsheet application

Excel365

### Description

When I load the Excel file using EPPLUS and modify some contents, I find that the PivotTable cache attribute RefreshOnLoad is updated to true, which is not the effect I want, causing my workbook to update the PivotTable incorrectly because the worksheet protent is locked.

In the epplus source code, in the ExcelWorkbook.Save method, the PivotTable cache should be saved. RefreshOnLoad should be set to true

```

			if (HasLoadedPivotTables)
			{
				//Updates the Workbook Xml, so must be before saving the wookbook part 
				SavePivotTableCaches();
			}

private void SavePivotTableCaches()
{
	foreach (var info in _pivotTableCaches.Values)
	{
		foreach (var cache in info.PivotCaches)
		{
			if (cache._pivotTables.Count == 0)
			{
				cache.Delete();
				continue;
			}
			//Rewrite the pivottable address again if any rows or columns have been inserted or deleted
			var r = cache.SourceRange;
			if (r != null && r.Worksheet != null)              //Source does not exist
			{
				ExcelTable t = r.Worksheet.Tables.GetFromRange(r);

				var fields =
					cache.CacheDefinitionXml.SelectNodes(
						"d:pivotCacheDefinition/d:cacheFields/d:cacheField", NameSpaceManager);
				if (fields != null)
				{
					FixFieldNamesAndUpdateSharedItems(cache, t, fields);
				}

				cache.RefreshOnLoad = true;
				cache.CacheDefinitionXml.Save(cache.Part.GetStream(FileMode.Create));
				cache.ResetRecordXml(_package.ZipPackage);
			}
		}
	}
}
```

I tried a simple replay and found that as long as I updated the pivot table reference area, it set it to true for me

```
            using (ExcelPackage excelPackage = new ExcelPackage("testPivotTable.xlsx"))
            {
                var sht = excelPackage.Workbook.Worksheets["srcData"];

                var excelTable = sht.Tables[0];
                //var rng = excelTable.Range.TakeRows(2);

                //rng.Copy(excelTable.Range.Offset(100, 0));
                excelTable.AddRow(10);
                excelPackage.SaveAs("testPivotTableResult.xlsx");
            }
```

If non-pivot table references are updated, the RefreshOnLoad attribute will not be updated to true

If the areas that are not referenced by the pivot table are updated, the RefreshOnLoad attribute will not be updated to true. Even then, the refreshonLoad attribute is not what I want. I want to leave the refreshonLoad attribute to true and control the pivot table refresh behavior after the user opens the Excel file or uses the COM Excel plugin.

[testPivotTable.xlsx](https://github.com/user-attachments/files/17617736/testPivotTable.xlsx)

**Comment by JanKallman** [comment]
As EPPlus does not render the pivot data to the cells, this is the default behaviour.

**Comment by minren118** [comment]
Can the RefreshOnLoad attribute be left open so the developer can decide if it needs to be changed? In my current situation, strangely enough, I don't know why the RefreshOnLoad is changed to true, I don't think I changed the data source range in the pivot table reference data source area, and when I finally save the file and open the file in Excel, it will bring up the error form because the pivot table is in a worksheet protected by the worksheet. An error was reported while refreshing the worksheet. I haven't found a good way to avoid it yet.

**Comment by minren118** [comment]
Fortunately, I use COM interface to open the Excel file, I can use ExcelApp.DisplayAlerts = false to disable the error prompt, if the EPPLUS generated file, is given to the user to double-click directly to open, pop up this because the sheet is protected error, not very friendly. Especially when I am not actively modifying the pivot table to refer to the data area triggered, I do not need to refresh the pivot table to use it when the worksheet is protected.
