### ISSUE TITLE
Pivot Table: PageField filters

### ISSUE THREAD

**Issue by jhgbrt** [EPPlusSoftware/EPPlus#1681]
**Is your feature request related to a problem? Please describe.**
When adding fields to pivot tables, one can add these as 'row', 'column', 'value' or 'filter' fields (PageField).  Setting filter values is (unless I missed something?) currently only possible for row- and column fields; it would be nice if one could also set filter values for PageFields.

**Describe the solution you'd like**

An API that allows adding filter values to page fields.

**Additional context**
Here's a code sample that I tried:

```
var fruit = new[]
{
    new { Name = "Apples", Location = "Warehouse1", Quantity = 2 },
    new { Name = "Apples", Location = "Warehouse1", Quantity = 11 },
    new { Name = "Apples", Location = "Warehouse2", Quantity = 3 },
    new { Name = "Oranges", Location = "Warehouse2", Quantity = 7 },
    new { Name = "Apples", Location = "Warehouse3", Quantity = 3 },
    new { Name = "Oranges", Location = "Warehouse3", Quantity = 7 },
    new { Name = "Oranges", Location = "Warehouse1", Quantity = 5 }
};

var p = new ExcelPackage();
var ws1 = p.Workbook.Worksheets.Add("Fruit");
var table = ws1.Tables.Add(ws1.Cells[1, 1, fruit.Count() + 1, 3], "FruitTable");
ws1.Cells["A1"].LoadFromCollection(fruit, true);
ws1.Calculate();

var ws2 = p.Workbook.Worksheets.Add("Summary");
var pivot = ws2.PivotTables.Add(ws2.Cells["A3"], table, "FruitPivot");
var dataField = pivot.DataFields.Add(pivot.Fields["Quantity"]);
var pageField = pivot.PageFields.Add(pivot.Fields["Location"]);
var rowField = pivot.RowFields.Add(pivot.Fields["Name"]);

// --> this does not work
pivot.MultipleFieldFilters = true;
pageField.Filters.AddCaptionFilter(ePivotTableCaptionFilterType.CaptionEqual, "Warehouse1");
// <-- this does not work

ws2.Calculate();
pivot.Calculate();

p.SaveAs(@"fruit.xlsx");
```

**Comment by jhgbrt** [comment]
I just realized that the filter functionality for pivot page fields in excel does not seem to have 'Caption' and 'Value' filters, only a possibility to set individual values. Unsure what a good API design would look like for this use case.

**Comment by OssianEPPlus** [comment]
It's true that this is not applied in excel as one might expect.
What epplus does in this case is add a filter node in excel's underlying xml.

But as you have noted page fields in Excel do not have any options for 'Caption' and 'Value' filters.
In essence. Epplus does add the filter, but excel does not calculate it when it's on a pagefield.

The clearest way of seeing this is that if you move the location field to columns or rows in excel:
![image](https://github.com/user-attachments/assets/6e76ed4e-d0c2-43ee-a6ba-f4203041294f)

Then it filters for "Warehouse1" in the row or column.

The feature is technically there but Excel simply does not calculate it. Therefore we unfortunately can't add this as a feature.
You can however make your own sort of filter "manually" in epplus via the "Items" property by doing something like:
```
pageField.MultipleItemSelectionAllowed = true;
pageField.Items.Refresh();
var items = pageField.Items;

for (int i = 0; i < pageField.Items.Count - 1; i++)
{
    if (pageField.Items[i].Text != "Warehouse1")
    {
        pageField.Items[i].Hidden = true;
    }
}
```
Or with some LINQ expression, e.g.
```
pageField.MultipleItemSelectionAllowed = true;
var items = pageField.Items;
pageField.Items.Refresh();

items.Where(x => x.Text != "Warehouse1" && x.Type != eItemType.Default).ToList().ForEach(y => y.Hidden = true);
```
Just keep in mind that the last item in the Items collection is a default value and therefore can't use the Hidden property.

**Comment by jhgbrt** [comment]
That is a great work around, does the trick, and is in fact entirely consistent with the behaviour of Excel. Thanks for the help!
