### ISSUE TITLE
How to add a sub total row to pivot table？

### ISSUE THREAD

**Issue by yangmijun** [EPPlusSoftware/EPPlus#1686]
If I have created a pivot table with 2 row field, how to add a sub total row to each group? 
I'm not meaning the grand total row.
![2024-11-14_08-22-45](https://github.com/user-attachments/assets/2fe20b28-734c-43f3-8b79-ff5e84dd95c2)

**Comment by OssianEPPlus** [comment]
By using the `.SubTotalFunctions` property on the relevant field.
for example:
```c#
var pt = ws.PivotTables
pt.Fields[0].SubTotalFunctions = eSubTotalFunctions.Sum
```

You can also add multiple functions for subtotal, like so:
```c# 
pt.Fields[0].SubTotalFunctions = eSubTotalFunctions.Sum | eSubTotalFunctions.Max;
```

**Comment by yangmijun** [comment]
Thanks for your help. @OssianEPPlus 
I tried the .SubTotalFunctions property, and it works fine on regular field. But I found that I can not show sub total on Calculate Field.

This is sample file.
[TurnoutRate.xlsx](https://github.com/user-attachments/files/17783998/TurnoutRate.xlsx)

Sample code:

        static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage("TurnoutRate.xlsx"))
            {
                var dataSheet = package.Workbook.Worksheets["Data"];
                var pivotSheet = package.Workbook.Worksheets["Pivot"];

                //create pivot table
                var pivotDataRange = dataSheet.Cells[4, 2, 14, 5];
                var pivotTable = pivotSheet.PivotTables.Add(pivotSheet.Cells["C3"], pivotDataRange, "TestPivotTable");

                //add Calculated Field
                var calculatedField = pivotTable.Fields.AddCalculatedField("TurnoutRate", "VoterNumber / TotalPeople");
                calculatedField.SubTotalFunctions = eSubTotalFunctions.Sum;

                //add row fields to pivot table, but only set SubTotalFunctions to the first row field
                var rowField1 = pivotTable.Fields["group1"];
                pivotTable.RowFields.Add(rowField1);
                rowField1.Compact = false;
                rowField1.Outline = false;
                rowField1.SubTotalFunctions = eSubTotalFunctions.Sum;

                var rowField2 = pivotTable.Fields["group2"];
                pivotTable.RowFields.Add(rowField2);
                rowField2.Compact = false;
                rowField2.Outline = false;
                rowField2.SubTotalFunctions = eSubTotalFunctions.None;

                var dataField = pivotTable.Fields["TurnoutRate"];
                var f = pivotTable.DataFields.Add(dataField);
                f.Name = "AvgTurnoutRate";
                f.Function = DataFieldFunctions.Sum;
                dataField.SubTotalFunctions = eSubTotalFunctions.Sum;

                pivotTable.Compact = false;

                package.Save();
            }
        }

**Comment by yangmijun** [comment]
![subtotaloncalc](https://github.com/user-attachments/assets/dbda0c48-3076-48fb-befd-5b5955017477)

This is the Epplus Pivot table.

![subtotaloncalc excel](https://github.com/user-attachments/assets/5a14e62f-9729-4c5a-b94f-b638f3dac4b1)

This is the Excel Pivot table, with automatic option.

**Comment by OssianEPPlus** [comment]
This seems to be because you've added too many/unnecessary subtotals.

Changing your code to:
```
var dataSheet = package.Workbook.Worksheets["Data"];
var pivotSheet = package.Workbook.Worksheets["Pivot"];

//create pivot table
var pivotDataRange = dataSheet.Cells[4, 2, 14, 5];
var pivotTable = pivotSheet.PivotTables.Add(pivotSheet.Cells["C3"], pivotDataRange, "TestPivotTable");

//add Calculated Field
var calculatedField = pivotTable.Fields.AddCalculatedField("TurnoutRate", "VoterNumber / TotalPeople");
calculatedField.SubTotalFunctions = eSubTotalFunctions.Sum;

var rowField1 = pivotTable.Fields["group1"];
pivotTable.RowFields.Add(rowField1);
rowField1.Compact = false;
rowField1.Outline = false;

var rowField2 = pivotTable.Fields["group2"];
pivotTable.RowFields.Add(rowField2);
rowField2.Compact = false;
rowField2.Outline = false;

var dataField = pivotTable.Fields["TurnoutRate"];
var f = pivotTable.DataFields.Add(dataField);
f.Name = "AvgTurnoutRate";

pivotTable.Compact = false;
```

Gets the output you want.

This is still a strange result though the xml looks as though its being set correctly. We're looking into it.

**Comment by OssianEPPlus** [comment]
We have looked into it. This works as intended and as excel. 

If Field Settings on row fields is set and a Values field is set and do not match, excel exhibits strange behaviour. Epplus allows for creating the same scenario:

![ExcelFieldSetting](https://github.com/user-attachments/assets/42dc7502-ead2-45dc-a96f-303b1a537bba)
