### ISSUE TITLE
Replacing an existing drawing/image with an SVG causes NRE

### ISSUE THREAD

**Issue by duncansmart** [EPPlusSoftware/EPPlus#1688]
### EPPlus usage

Commercial use (I have a commercial license)

### Environment

Windows

### Epplus version

7.3.1

### Description

Calling `Image.SetImage` with an SVG against an ExcelPicture that currently has PNG causes a `NullReferenceException`.

For example:

    var pic = sheet.Drawings.AddPicture("mypic", new FileInfo(@"C:\Temp\logo.PNG"));

    // fails
    pic.Image.SetImage(new FileInfo(@"C:\Temp\logo.SVG"));

Error:

    System.NullReferenceException: Object reference not set to an instance of an object.
       at OfficeOpenXml.Drawing.ExcelPicture.OfficeOpenXml.Drawing.Interfaces.IPictureContainer.SetNewImage()
       at OfficeOpenXml.Drawing.ExcelImage.SetImageContainer(Byte[] image, ePictureType pictureType, Boolean removePrevImage)
       at OfficeOpenXml.Drawing.ExcelImage.SetImage(FileInfo imageFile)

**Comment by OssianEPPlus** [comment]
We've re-produced the issue, this is indeed a bug. 
.svg files require a bit of extra xml that is created along with the constructor based on type. It hadn't been taken in consideration for SetImage.
We're currently working on a fix.
