### ISSUE TITLE
Setting styles on full rows/columns does not save if no style is set on cells with a value

### ISSUE THREAD

**Issue by JanKallman** [EPPlusSoftware/EPPlus#1699]

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.5.1

**Comment by arbreen** [comment]
I'm not sure this fix is totally complete. It works if the style is applied after the data is populated. But, if you set the Numberformat.format before populating the data then the style isn't applied. It isn't too difficult for me to change my code for the single export I have to do the formatting at the end of the process. 

For info, I was using it on full columns, e.g.

```c#
sheet.Column(1).Style.Numberformat.Format = "dd-mm-yy";
```
