### ISSUE TITLE
5.2.1 breaks some properties: DisplayBlankAs, ShowHiddenData, and RoundCorners

### ISSUE THREAD

**Issue by kchristman54** [EPPlusSoftware/EPPlus#170]
After upgrading to 5.2.1 from 5.1.2, the `DisplayBlankAs` property seems to be missing when I try to build. I'm able to build fine with 5.1.2.

![image](https://user-images.githubusercontent.com/33758481/90429193-d6148880-e08a-11ea-8a8d-993fb185a44b.png)

`ShowHiddenData` and `RoundedCorners` also complain and can't be found.

I checked the release notes and the breaking changes, but it didn't mention of any breaking changes in this area. 
https://epplussoftware.com/docs/5.2/articles/breakingchanges.html
https://epplussoftware.com/docs/5.2/articles/fixedissues.html

EPPlus is amazing...thank you from Texas A&M University's Energy System Laboratory!

**Comment by JanKallman** [comment]
Thanks for reporting it. I'll supply a fix shortly. 
This property disappeared from the ExcelChart class with the Extended charts implementation. I'll put it back again in the next version. For now you can type cast the chart to ExcelChartStandard or the specific chart type (for example a ExcelLineChart) to access this property.
And thanks for the thanks and good luck with your research!

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.3
