### ISSUE TITLE
ToText includes XML formatting

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#171]
ToText is including formatting info instead of just cell text.  Below is a single cell after calling ToText.  The cell text contents are simply "Beginning balance" but some XML formatting data is included.   

<r xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><rPr><sz val="9" /><color rgb="FF333333" /><rFont val="Arial" /><family val="2" /></rPr><t>Beginning balance</t></r>

**Comment by rdhasse** [comment]
The XML formatting did not show up in my original post, so adding here inside a code section.

`<r xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><rPr><sz val="9" /><color rgb="FF333333" /><rFont val="Arial" /><family val="2" /></rPr><t>Beginning balance</t></r>`

**Comment by JanKallman** [comment]
I will have a look

**Comment by JanKallman** [comment]
EPPlus don't handle richtext cells correctly. I'll provide a fix shortly.

**Comment by JanKallman** [comment]
I have supplied a fix in the latest develop build. Can you try it out?
Nuget Feed:  https://ci.appveyor.com/nuget/epplus

**Comment by JanKallman** [comment]
Fixed in Version 5.3.1
