### ISSUE TITLE
Adding page field will crush pivot table some times

### ISSUE THREAD

**Issue by yangmijun** [EPPlusSoftware/EPPlus#1713]
### EPPlus usage

Noncommercial use

### Environment

Windows 10

### Epplus version

7.4.2 - 7.5.1

### Spreadsheet application

Excel

### Description

After create a pivot table, then try to add a page field (this field is from a column with formula), the pivot table will crush sometime.

[bad__Test2.xlsx](https://github.com/user-attachments/files/17880227/bad__Test2.xlsx)
This is the sample data.

        private static void NewMethod2()
        {
            using (var package = new ExcelPackage("bad__Test2.xlsx"))
            {
                var dataSheet = package.Workbook.Worksheets["ReportData"];
                var pivotSheet = package.Workbook.Worksheets["Pivot"];

                //create pivot table
                var pivotDataRange = dataSheet.Cells[3, 1, 28, 20];
                var pivotTable = pivotSheet.PivotTables.Add(pivotSheet.Cells["C3"], pivotDataRange, "TestPivotTable");

                pivotTable.Compact = false;
                (from pf in pivotTable.Fields
                    select pf).ToList().ForEach(f =>
                {
                    f.Compact = false;
                    f.Outline = false;
                    f.SubtotalTop = false;
                    f.SubTotalFunctions = eSubTotalFunctions.None;
                });

                //add row fields to pivot table
                var rowField1 = pivotTable.Fields["Group1"];
                pivotTable.RowFields.Add(rowField1);

                var dataField2 = pivotTable.Fields["ID2"];
                var f2 = pivotTable.DataFields.Add(dataField2);
                f2.Name = "Count";
                f2.Function = DataFieldFunctions.Count;

                pivotTable.DataOnRows = false;

                //page field will crush pivot table
                var field = pivotTable.Fields["Data_Missing"];
                var pagef = pivotTable.PageFields.Add(field);

                package.Save();
            }
        }

This is the sample code. Pivot table will be fine if I do not add the page field.

**Comment by JanKallman** [comment]
This is a bug. I will provide a fix shortly.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7.5.2
