### ISSUE TITLE
EPPlus won't properly read data validations of .xlsx spreadsheet created with LibreOffice

### ISSUE THREAD

**Issue by megakraken** [EPPlusSoftware/EPPlus#1714]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.5.1

### Spreadsheet application

Excel xlsx

### Description

When opening an .xlsx spreadsheet with data validations that was created with LibreOffice, the `AllowBlank` and `ShowErrorMessage` properties of any `ExcelDataValidation` will always be `false` even if they are in fact enabled in the document.

The spreadsheet was created with LibreOffice 24.8.3 which is the most recent version and the version of EPPlus used is 5.7.1 (.NET Framework).

Attached is a minimalist .xlsx file containing a single data validation for the cells of column B. As can be seen on the screenshots below the `Allow empty cells` and `Show error message when invalid values are entered` are both checked. The following code, however, will print out `false` for both properties:

```cs
using OfficeOpenXml;
using System;

namespace Test {
    class Program {
        static void Main() {
            using (var p = new ExcelPackage("Test.xlsx")) {
                foreach (var v in p.Workbook.Worksheets[0].DataValidations) {
                    Console.WriteLine(v.AllowBlank);
                    Console.WriteLine(v.ShowErrorMessage);
                }
            }
        }
    }
}
```

![data_validations_1](https://github.com/user-attachments/assets/66c87dfd-7f7d-4469-a3d2-dd77942e375a)
![data_validations_2](https://github.com/user-attachments/assets/f0816f86-e739-4f70-b747-6007c9365ff0)
[Test.xlsx](https://github.com/user-attachments/files/17899379/Test.xlsx)

**Comment by AdrianEPPlus** [comment]
It appears that when we read the property in the xml we check if it's set to 1. It appears LibreOffice sets this to true. A fix has been made and will be in a future version,

**Comment by megakraken** [comment]
> It appears that when we read the property in the xml we check if it's set to 1. It appears LibreOffice sets this to true. A fix has been made and will be in a future version,

Great, thank you.
