### ISSUE TITLE
About issue#1227

### ISSUE THREAD

**Issue by SRO-AWATA** [EPPlusSoftware/EPPlus#1726]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.5.1

### Spreadsheet application

Excel

### Description

「Empty string as valid return value from XLOOKUP #1227」
Is this issue already resolved?

(EPPlus 7.5.1)
worksheet.Cells["A2"].Formula = "XLOOKUP(A1,table[Column1],table[Column2],"")";
worksheet.Cells["A2"].Calculate();
Console.WriteLine($"A2.Value={worksheet.Cells["A2"].Value}" );
⇒　A2.Value=#N/A

**Comment by AdrianEPPlus** [comment]
It appears this was not fixed. I have made a fix for a future version

**Comment by SRO-AWATA** [comment]
I confirmed this issue has been resolved in v7.5.2. Thank you.

**Comment by SRO-AWATA** [comment]
I confirmed this issue has been resolved in v7.5.2. Thank you.
