### ISSUE TITLE
When using the TEXTJOIN or CONCAT function with a range that includes '#N/A'."

### ISSUE THREAD

**Issue by SRO-AWATA** [EPPlusSoftware/EPPlus#1729]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.5.1

### Spreadsheet application

Excel

### Description

Is this result a bug?

(EPPlus 7.5.1)
worksheet.Cells["A1"].Value = "A"
worksheet.Cells["A2"].Formula = "VLOOKUP(1,B1:C2,2,FALSE)";  //Return #N/A
worksheet.Cells["A3"].Value = "B";
worksheet.Cells["A4"].Formula = "TEXTJOIN(\"\",TRUE,A1:A3)";
worksheet.Cells["A5"].Formula = "TEXTJOIN(\"\",TRUE,A1,A2,A3)";
worksheet.Cells["A6"].Formula = "CONCAT(A1:A3)";
worksheet.Cells["A7"].Formula = "CONCAT(A1,A2,A3)";

(EPPlus 7.5.1)
A4 = A#N/AB  ←bug?
A5 = #N/A
A6 = A#N/AB  ←bug?
A7 = #N/A

(EXCEL)
A4 = #N/A
A5 = #N/A
A6 = #N/A
A7 = #N/A

**Comment by swmal** [comment]
we will have a look at this

**Comment by swmal** [comment]
We have fixed this error, will be released in next version of EPPlus.

**Comment by SRO-AWATA** [comment]
I confirmed this issue has been resolved in v7.5.2. Thank you.
