### ISSUE TITLE
LENB function

### ISSUE THREAD

**Issue by SRO-AWATA** [EPPlusSoftware/EPPlus#1734]
Hi, I want LENB function.

Thanks!

**Comment by swmal** [comment]
Hi,

for a quick fix you can add your own implementation of LENB as a custom function in EPPlus. See this [wiki article](https://github.com/EPPlusSoftware/EPPlus/wiki/Custom-Functions-For-Calculations)
 
[Microsofts docs](https://support.microsoft.com/en-us/office/len-lenb-functions-29236f94-cedc-429d-affd-b5e33d2c67cb)

LENB will eventually be added to EPPlus, it is on the list of functions to implement

**Comment by SRO-AWATA** [comment]
OK, I create a custom function. 
 Thanks!
