### ISSUE TITLE
ExcelPackage.LoadAsync does not work with non seekable streams

### ISSUE THREAD

**Issue by bjallemad** [EPPlusSoftware/EPPlus#174]
I'm loading the ExcelPackage directly from the Request Body stream, which is not seekable.
For now I solved this by copying to a memory stream first, but that seems very memory intense for large files.
 
The line of code that breaks is in ExcelPackageAsync.LoadAsync:
if (input.Length == 0)

In the non-async version there are checks for this in most cases like:
if (newStream.CanSeek && newStream.Length == 0)

It would be awesome if this check could be implemented in the Async version also!

Thanks

**Comment by JanKallman** [comment]
Thanks for reporting it. I have added a fix. 
Feel free to try it out using our devlop nuget feed... https://ci.appveyor.com/nuget/epplus.

**Comment by JanKallman** [comment]
Fixed in Version 5.3.1
