### ISSUE TITLE
Not supported numberformat [$€-2]\ #,##0.00_);[Red]\([$€-2]\ #,##0.00\)

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#1740]
The `Text` property of EPPlus returns "€ 1 915 826,90" , Excel outputs it as "1 915 826,90". A review of the implementation in the `ExcelFormatTranslator` class for this particular format is needed.

**Comment by JanKallman** [comment]
This is the correct behaviour. The problem was that the incorrect number format was selected for the cell.
