### ISSUE TITLE
LoadFromCollection where list contains other classes doesn't go recursively

### ISSUE THREAD

**Issue by hughmcl** [EPPlusSoftware/EPPlus#1741]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.5.1

### Spreadsheet application

Excel

### Description

I have a situation where i'm creating lists of classes that contain other classes.  When it gets parsed by LoadFromCollection it dumps most of the entries but when it gets to the inner class object it just exports the class name, not the contents of that class.

example class:-

public class TestClass {
    public string Id { get; set; }
    public string Name { get; set; }
    public int Number { get; set; }

    public AnotherTestClass Another { get; set; } = new();

    public class AnotherTestClass {
        public string Test { get; set; }
        public string Test2 { get; set; }

    }

    
}

Output:-

Id | Name | Number | Another
-- | -- | -- | --
123 | Item 1 | 3 | projectName.TestClass+AnotherTestClass
456 | Item 2 | 7 | projectName.TestClass+AnotherTestClass

**Comment by swmal** [comment]
For this scenario you need to use the attributes for nested members, see this link: https://github.com/EPPlusSoftware/EPPlus/wiki/LoadFromCollection-using-Attributes
