### ISSUE TITLE
Cannot delete the last column

### ISSUE THREAD

**Issue by uganh16** [EPPlusSoftware/EPPlus#1742]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

7.5.1

### Spreadsheet application

Excel

### Description

https://github.com/EPPlusSoftware/EPPlus/blob/752596c38433d106eec825323cf969bb77763266/src/EPPlus/Core/Worksheet/WorksheetRangeDeleteHelper.cs#L232C10-L232C82

This should be

```c#
            if (columnFrom < 1 || columnFrom + columns > ExcelPackage.MaxColumns + 1)
```

just like `ValidateRow` at line 222, so that the last column can be deleted?

**Comment by swmal** [comment]
thanks, will be fixed in the next version
