### ISSUE TITLE
Style.Fill.BackgroundColor.Rgb doesn't return all colors

### ISSUE THREAD

**Issue by PirryD3v** [EPPlusSoftware/EPPlus#176]
THis is my Excel File with colored cells 

![excelcolor](https://user-images.githubusercontent.com/65449869/91599199-3696a600-e966-11ea-9dc8-c031abfca392.JPG)

This is the code snippet .. i just get every backgroundcolor of the cells . 

 ```
for (int i = 1; i <= maxColumnNumber; i++)
            {
                var cell = worksheet.Cells[currentRowNum, i];
                string rgbfarbe = cell.Style.Fill.BackgroundColor.Rgb;
                Console.WriteLine("Farbe -> " + rgbfarbe + " ROW: " + currentRowNum + " COL: " + i);


```
and here the output 

Farbe -> FFFF0000 ROW: 1 COL: 1
Farbe ->  ROW: 2 COL: 1
Farbe ->  ROW: 3 COL: 1
Farbe -> FFFFFF00 ROW: 4 COL: 1
Farbe ->  ROW: 5 COL: 1
Farbe -> FFC00000 ROW: 6 COL: 1
Farbe ->  ROW: 7 COL: 1
Farbe ->  ROW: 8 COL: 1

it seems it cannot get all colors ? when i debug in VS the RGB value is ""

**Comment by JanKallman** [comment]
Color can have other properties, like Indexed (if it's an indexed color in Excel), Theme (if it's one of the theme colors) or Auto. 
In those cases the Rgb property is blank.

**Comment by PirryD3v** [comment]
I've seen this .. in the Java Libs .. they calculate RGB .. will this be implemented too here ? 
https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/ExtendedColor.html#getRGBWithTint--

**Comment by JanKallman** [comment]
You can use the ExcelColor.LookupColor() method to get the Rgb value for an indexed color or a tint, but it will not work for theme colors at the moment.

**Comment by PirryD3v** [comment]
Would be great implementation .. you can check NPOI .net port .. there it works fine

**Comment by JanKallman** [comment]
Try it out if it works for you. It's there today, byt will not handle theme colors...
`var rgb = ws.Cells["A1"].Style.Font.Color.LookupColor()`
