### ISSUE TITLE
New charts (BoxAndWhiskerChart, etc.) not rendered when opened in Excel

### ISSUE THREAD

**Issue by kchristman54** [EPPlusSoftware/EPPlus#179]
We were trying to generate the new charts, namely BoxAndWhisker and Histogram, but when we open those EP-Plus generated files in Excel 2016, we get "This chart isn't available in your version of Excel..." message.

Even the XLSX files downloaded from the EP-Plus website has this problem.
[15-ChartsAndThemes.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5164822/15-ChartsAndThemes.xlsx)
![box-and-whisker-chart-in-Excel2016](https://user-images.githubusercontent.com/33758481/92036498-f0f72600-ed35-11ea-9218-5a8a0240f1c2.PNG)

I've also tried Office 365, which also has the same error message.
![box-and-whisker-chart-in-Office365](https://user-images.githubusercontent.com/33758481/92036597-1ab04d00-ed36-11ea-8466-0ff914ea925d.PNG)

Thanks again for this wonderful Excel-library. 

--Energy Systems Lab at Texas A&M University

**Comment by JanKallman** [comment]
You use an older version of Excel not capable of rendering the new extended chart types.
I'm unsure of the exact version but, I think you need 1611 or later.
