### ISSUE TITLE
【System.NullReferenceException】error when copy sheet 

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#180]
Hi，Now that there are 2 files (copyfrom.xlsm and copyto.xlsm), now want to copy the first sheet of (copyfrom.xlsm) into copy to copy to (copyto.xlsm)

, using the following code(**Workbook.Worksheets.Add**) to copy sheet ,then appear the following exception, what is the solution? Please help solve it, thank you. (Not sure if this is a problem with epplus itself)

            using ExcelPackage excelPackage1 = new ExcelPackage(new FileInfo(@"c:\copyfrom.xlsm"));
            using ExcelPackage excelPackage2 = new ExcelPackage(new FileInfo(@"c:\copyto.xlsm"));

            excelPackage2.Workbook.Worksheets.Add(excelPackage1.Workbook.Worksheets[0].Name, excelPackage1.Workbook.Worksheets[0]);

**Exception**:System.NullReferenceException: 'Object reference not set to an instance of an object.'

note：The excel file must contain macro.
[excel file.zip](https://github.com/EPPlusSoftware/EPPlus/files/5169750/excel.file.zip)

**Comment by 93910676wangd** [comment]
Didn't anyone reply?
 I think there is a problem with the source code, when the copy source does not have CodeModule, should not do add, should be modified like this.

https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/ExcelWorksheets.cs

//Copy the VBA code
                if (_pck.Workbook.VbaProject != null)
                {
                    var name = _pck.Workbook.VbaProject.GetModuleNameFromWorksheet(added);
                    _pck.Workbook.VbaProject.Modules.Add(new ExcelVBAModule(added.CodeNameChange) { Name = name, Code = Copy.CodeModule.Code, Attributes = _pck.Workbook.VbaProject.GetDocumentAttributes(Name, "0{00020820-0000-0000-C000-000000000046}"), Type = eModuleType.Document, HelpContext = 0 });
                    Copy.CodeModuleName = name;
                }

⇒

//Copy the VBA code
                if (_pck.Workbook.VbaProject != null)
                {
                    var name = _pck.Workbook.VbaProject.GetModuleNameFromWorksheet(added);
                    _pck.Workbook.VbaProject.Modules.Add(new ExcelVBAModule(added.CodeNameChange) { Name = name, Code = **Copy.CodeModule?.Code**, Attributes = _pck.Workbook.VbaProject.GetDocumentAttributes(Name, "0{00020820-0000-0000-C000-000000000046}"), Type = eModuleType.Document, HelpContext = 0 });
                    Copy.CodeModuleName = name;
                }

**Comment by JanKallman** [comment]
I'll provide a fix for the next version

**Comment by JanKallman** [comment]
Fixed in version 5.3.2
