### ISSUE TITLE
Worksheets.MoveBefore(wsSource.Name, wsNew.Name) - Error

### ISSUE THREAD

**Issue by jonathanjto** [EPPlusSoftware/EPPlus#181]
Hi,

When using the "MoveBefore" function the fourth time the function is called for the worksheet there is an error.

`{`
`  ExcelWorksheet wsNew = this.ExcelPackage.Workbook.Worksheets.Add(newWkNameBuild, wsSource);`
`  this.ExcelPackage.Workbook.Worksheets.MoveBefore(wsSource.Name, wsNew.Name);`
`  this.CurrentWorksheet = wsNew;`
`}`

The error : Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

[ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.]
   System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) +0

`OfficeOpenXml.Core.ChangeableDictionary'1.InsertAndShift(Int32 fromPosition, Int32 add) +120`
`OfficeOpenXml.Core.ChangeableDictionary'1.Move(Int32 fromPosition, Int32 toPosition, Boolean before) +103`
`OfficeOpenXml.Core.Worksheet.MoveSheetXmlNode.RearrangeWorksheets(ExcelWorksheets worksheets, Int32 sourcePositionId, Int32 targetPositionId, Boolean before) +163`

**Comment by JanKallman** [comment]
Fixed in version 5.3.2
