### ISSUE TITLE
No option to hide Values/Data Caption row when generating Pivot table

### ISSUE THREAD

**Issue by nbduong** [EPPlusSoftware/EPPlus#182]
I'm trying to hide the data caption row but there doesn't seem to be a way to do this. I've tried setting the pivotTbl.DataCaption to null but it just displays nothing instead of removing the entire row. Code reproducing the pictures is below.

refer old issue: https://github.com/JanKallman/EPPlus/issues/133

![68747470733a2f2f692e696d6775722e636f6d2f4e61647639346f2e706e67](https://user-images.githubusercontent.com/48197320/92216894-1e240f80-eec1-11ea-873d-d956953490d8.png)
![68747470733a2f2f692e696d6775722e636f6d2f647348476130632e706e67](https://user-images.githubusercontent.com/48197320/92216898-1f553c80-eec1-11ea-8617-f324ad35046a.png)

**Comment by JanKallman** [comment]
This property is part of the extLst, so it will require some more effort to implement. I will have a look at it shortly.

**Comment by JanKallman** [comment]
Added ExcelPivotTable.ShowValuesRow boolean property

**Comment by nbduong** [comment]
Thanks for the help in troubleshooting the issue.
