### ISSUE TITLE
Please implement custom TableStyles

### ISSUE THREAD

**Issue by Zenlil** [EPPlusSoftware/EPPlus#183]
We would like to create custom table-styles for some pivot-tables we are making.

Out requirements are:
* different formatting of the 2+ data-fields we have; like different background).
* different styling on our 3-5 row-fields

illustrated in https://docs.devexpress.com/OfficeFileAPI/113738/spreadsheet-document-api/examples/tables/how-to-create-modify-and-delete-table-styles

**Comment by JanKallman** [comment]
Added in EPPlus version 5.6
