### ISSUE TITLE
Not able to set NumberFormat on Dates in PivotTable-Columns/Row-fields

### ISSUE THREAD

**Issue by Zenlil** [EPPlusSoftware/EPPlus#186]
When adding a date-field as a pivot-table ColumnField or RowField it is not possible to set the "NumberFormat" on that item.
(i.e having data with one day each month and setting numberformat to "mmm-yy")

**Comment by JanKallman** [comment]
In commit be41e7ea5ae5fdd77f47680b3f5341ab7fa58b38

**Comment by JanKallman** [comment]
Added in EPPlus 5.4. Use Format property on the Field.
