### ISSUE TITLE
AutoFitColumns does not have enough column width adjustment in the linux environment.

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#187]
Using the AutoFitColumns method, column width can be adjusted automatically under windows, but in linux (centos) environment, although the column width is also adjusted, but the adjustment value is too small, if you load the font library, can be a little longer, but also did not reach the window level.
I think this is a problem. Please confirm.

[OUTPUT_CentOs.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5200327/OUTPUT_CentOs.xlsx)
[OUTPUT_WIN.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5200333/OUTPUT_WIN.xlsx)

========src=============
       using (var range = worksheet.Cells)
                {
                    range.Style.WrapText = false;
                    range.Style.Font.Size = 9;
                    range.AutoFitColumns();
                }
=======================

I made the adjustment using the following method, which basically enables the following wide auto-adjustment functions of linux.

The measurement length of the longest character in the current column  * the ratio of Win2Linux (1.335)  / the length-to-width ratio under Win(5.985)

**Comment by JanKallman** [comment]
If you have installed libgdiplus correctly, this must be a different behavior in System.Drawing.Common when messuring the text.
We have discussed to look at another library for this, but this is a larger task.

**Comment by 93910676wangd** [comment]
Thank you for your reply.
I have installed libgdiplus correctly, and if i don't install libgdiplus, this method “AutoFitColumns” can't be done without linux. I can only do this now. 
“The measurement length of the longest character in the current column * the ratio of Win2Linux (1.335) / the length-to-width ratio under Win(5.985)”

Expect future version upgrades to solve this problem.

**Comment by JanKallman** [comment]
I tried this in Centos 7 and it seems to resize correctly. 
Note that as you use unicode characters, you need to install the font you use to the system. For example msttcore.
