### ISSUE TITLE
When applying filter (via excel client) date's are not recognized 

### ISSUE THREAD

**Issue by Marcel0024** [EPPlusSoftware/EPPlus#191]
So i generate an excel, with dates are generate like so:

![image](https://user-images.githubusercontent.com/14852157/93898743-d5a78700-fcf3-11ea-8b7f-88590f471a7e.png)

But when i apply filter via excel the data is viewed as text:

![image](https://user-images.githubusercontent.com/14852157/93898558-a09b3480-fcf3-11ea-89e3-eb7657355009.png)

When i go through 'Text to columns' wizard they register as dates. Is there a way to do this in code?

So "Text filters" should be "Date filters":

![image](https://user-images.githubusercontent.com/14852157/93899279-7302bb00-fcf4-11ea-818a-dcf7c7825b4c.png)

**Comment by JanKallman** [comment]
Don't use ToString when you set the Value. This causes the value to be stored as text

**Comment by Marcel0024** [comment]
Legend!
