### ISSUE TITLE
Removing and Adding series corrupts file

### ISSUE THREAD

**Issue by ElyonsNIC** [EPPlusSoftware/EPPlus#193]
We have a bar chart that has 3 series.  We dynamically remove 2 of the bar chart series and readd them as 2 line series.  This works correctly in version 4.5.3.1.  The following code will reproduce the issue. 

Thanks
`
            var ws = _pck.Workbook.Worksheets.Add("Column");
            var l = new List<MyChartData>
            {
                new MyChartData{ Location="SS", SkipCell=null, Value1=0.164, Value2=0.159, Value3= 0.166},
                new MyChartData{ Location="TT", SkipCell=null, Value1=0.189, Value2=0.355, Value3=0.159},
                new MyChartData{ Location="UU", SkipCell=null, Value1=0.178, Value2=0.159, Value3= 0.166}
            };

            ws.Cells["B1"].LoadFromCollection(l, true, OfficeOpenXml.Table.TableStyles.Medium12);

            var chart = ws.Drawings.AddBarChart("Bar1", eBarChartType.ColumnClustered);
            var serie0 = chart.Series.Add("E2:E4", "B2:B4");
            serie0.Header = "E";
            var serie1 = chart.Series.Add("D2:D4", "B2:B4");
            serie1.Header = "D";
            var serie2 = chart.Series.Add("F2:F4", "B2:B4");
            serie2.Header = "F";

            chart.Series.Delete(2);
            chart.Series.Delete(0);

            var lineChartType = chart.PlotArea.ChartTypes.Add(eChartType.Line);
            var lineSeries = lineChartType.Series.Add("E2:E4","B2:B4");
            lineSeries.Header = "Line Series E";
            var lineSeries2 = lineChartType.Series.Add("F2:F4", "B2:B4");
            lineSeries2.Header = "Line Series F";

            chart.SetPosition(2, 0, 15, 0);
            chart.SetSize(1600, 900);

            _pck.SaveAs(new FileInfo("c:\\temp\\epplustest\\chartdebug.xlsx"));

        private class MyChartData
        {
            public string Location { get; set; }
            public string SkipCell { get; set; }
            public double Value1 { get; set; }
            public double Value2 { get; set; }
            public double Value3 { get; set; }
        }

`

**Comment by JanKallman** [comment]
Thanks for reporting it. I'll have a look

**Comment by JanKallman** [comment]
The series id gets duplicated in this case. I'll provide a fix shortly.

**Comment by JanKallman** [comment]
Fixed in version 5.4
