### ISSUE TITLE
How to get print pages count

### ISSUE THREAD

**Issue by rashuf** [EPPlusSoftware/EPPlus#196]
Hello!
How to get print pages count? On MS Excel:
![pages on excel sheet](https://user-images.githubusercontent.com/32777364/95848594-aff82580-0d67-11eb-885f-a70af707362d.png)

**Comment by JanKallman** [comment]
Do you need it in the header? Please have a look at sample 1...
https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/0116db4cca97b761654b67203c4e77602c97ca89/01-GettingStarted/GettingStartedSample.cs#L89
In code using EPPlus, there are not way of getting the number of pages in the document, unless you calculate it from the row height and the paper format.

**Comment by rashuf** [comment]
Thanks for the advice! The same idea came up. But converting from points to mm or px is hard :)
I insert a picture at the beginning of each page.

**Comment by rashuf** [comment]
px = point / (72 * 96)
72 DPI, 96 point per inch

**Comment by JanKallman** [comment]
You can use the worksheet.HeaderFooter.OddHeader.InsertPicture method instead?

**Comment by rashuf** [comment]
No, because I insert QR-code with page num and page count.
Thanks!
