### ISSUE TITLE
Deleting multiple columns not working

### ISSUE THREAD

**Issue by sndcode** [EPPlusSoftware/EPPlus#202]
using this code : 

string path = args[0];
                using (StreamReader sr = new StreamReader(path))
                {
                    ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                    var fi = new FileInfo(path);
                    using (var package = new ExcelPackage(fi))
                    {
                        var ws = package.Workbook.Worksheets[0];
                        ws.DeleteColumn(1);
                        ws.DeleteColumn(2);
                        ws.DeleteColumn(5);
                        ws.DeleteColumn(6);
                        ws.DeleteColumn(7);
                        ws.DeleteColumn(8);
                        ws.DeleteColumn(9);
                        ws.DeleteColumn(10);
                        ws.DeleteColumn(11);
                        byte[] data = package.GetAsByteArray();
                        var GetDirectory = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);

                        string path2 = GetDirectory+"\\final.xlsx";
                        File.WriteAllBytes(path2, data);
                    }
                }

Will delete column 1 but not 2  , then delete 5 but not 6 and so on.
[material_report_test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5421519/material_report_test.xlsx)

**Comment by JanKallman** [comment]
We'll have a look

**Comment by sndcode** [comment]
> We'll have a look

I fixed it myself since im dumb and not realized that the columns would step one column to the left so if i delete Column 2 , then column 3 will be the new column 2 . So i drew myself a quick sheet and made a pattern for my case and its now working . 
![Uploading WhatsApp Image 2020-10-22 at 12.31.19.jpeg…]()
