### ISSUE TITLE
Cannot Fill Data to template

### ISSUE THREAD

**Issue by minhdv48** [EPPlusSoftware/EPPlus#208]
I'd tried change name table on DataSet from "table2" to "table3" but lib cannot fill Data with table name "table3".
Attach is sample test I'd got on github.
[testEPPlus.zip](https://github.com/EPPlusSoftware/EPPlus/files/5432693/testEPPlus.zip)
Please help me, before decision purchase license.

**Comment by JanKallman** [comment]
You seems to use an component `EPPlus.Template.FillReport` to do the work. Can you attach the code for this component, otherwise I cant see what's going on.

**Comment by JanKallman** [comment]
I had a quick look at the FillReport dll and it seems it's using defined names in your template with the name of the datatable. So I dont think the issue is with EPPlus. Please have a look in your template in the Name Manager in Excel

**Comment by minhdv48** [comment]
I send my source, I got on git. Please check help me, before I'd purchase.
[EPPlus.Template_v1.0_11.zip](https://github.com/EPPlusSoftware/EPPlus/files/5444755/EPPlus.Template_v1.0_11.zip)
Thanks!

**Comment by JanKallman** [comment]
You get the data table name from a defined name (ExcelNamedRange) inside the template...
```            
        private static void FillWorksheetData(DataSet data, ExcelWorksheet ws, ExcelNamedRange n, string[] deliminator)
        {
            // region exists in data
            if (data.Tables.Contains(n.Name) == false)
                return;

            var dt = data.Tables[n.Name];
```
