### ISSUE TITLE
PowerShell OSS License question

### ISSUE THREAD

**Issue by dfinke** [EPPlusSoftware/EPPlus#209]
I wrapped EPPlus in PowerShell. https://www.powershellgallery.com/packages/ImportExcel

I wanted to confirm, if I upgrade to the latest version of EPPlus, then folks using the PowerShell version wrapping EPPlus would need to purchase a license if they are using it in a "commercial" company?

Thank you

**Comment by JanKallman** [comment]
Yes, they will either have to comply with the [Polyform NC](https://polyformproject.org/licenses/noncommercial/1.0.0/) or buy a commercial license.
