### ISSUE TITLE
Support: Changed URL to https and now Workbook opens in Protected View

### ISSUE THREAD

**Issue by leefrankeFNC** [EPPlusSoftware/EPPlus#211]
Local intranet site.
http**s**://website.domain.com/GenExcel/Default.aspx.

Switching to https seems to have the workbooks open in Protected View. The page the link is on is https. 

I know each user can go into Excel and change their settings. It just seems odd that switching to https and it opens in Protected View. I've tested it out back and forth between http/https and that seems to be the culprit. 

Anyone else run across this?

Anyone have a solution other than changing the Excel settings?

**Comment by JanKallman** [comment]
I think you should look at your AD policies. For example:
https://getadmx.com/?Category=Office2016&Policy=excel16.Office.Microsoft.Policies.Windows::L_OpenFilesOnLocalIntranetUNCInProtectedView

**Comment by leefrankeFNC** [comment]
I think that might be the right idea. There is probably a security policy somewhere that is causing the ruckus. I'm not sure it's that security policy..

The web page generates the Workbook and then sends it to the browser for the user to download.
`                    this.Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    this.Response.AddHeader(
                              "content-disposition",
                              string.Format("attachment;  filename=\"{0}\"", FileName));
                    this.Response.BinaryWrite(p.GetAsByteArray());
                    this.Response.End();`

Thanks!

lee
