### ISSUE TITLE
Table rows are validated not considering DateTime value thus considering 2 rows with exact same data with different time as duplicates

### ISSUE THREAD

**Issue by DashPriyabrata** [EPPlusSoftware/EPPlus#212]
I'm using v4.5.3.3 so not sure if I still can get a fix. Here goes the issue:

I'm using the following code to generate a excel file from csv input stream:

    ExcelWorksheet worksheet = package.Workbook.Worksheets.Add(excelFileName);
    worksheet.Cells["A1"].LoadFromText(csvInput, format, OfficeOpenXml.Table.TableStyles.Light8, true);
    worksheet.Column(1).Style.Numberformat.Format = DateTimeFormatInfo.CurrentInfo.ShortDatePattern;
    data = package.GetAsByteArray();
            

This gives me exception "An item with the same key has already been added." when I have 2 rows with same value in every column except the value in DateTime column are different - to be exact the time is different but date is the same. e.g.

> 

3/25/2020 3:20 | test | FALSE | FALSE | FALSE | FALSE | test | test | test | {EF72E3E5-9194-4A23-88EF-719AA4590417} | test | tes | tes | test | test@test.com | 123 | 123 | No | FALSE | FALSE | FALSE | FALSE | FALSE | Product group |   |   |   | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance |   |   | TRUE | 1.1 | {20A5AA67-0D4E-445B-93FA-426515BAB7F2}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3/25/2020 2:40 | test | FALSE | FALSE | FALSE | FALSE | test | test | test | {9EF4E01A-E214-452C-8D34-E4BD5277C851} | test | test | test | test | test@test.com | 123 | 123 | No | FALSE | FALSE | FALSE | FALSE | FALSE | Product group |   |   |   | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance | Product group | MDD Certificate | Clinical Relevance |   |   | TRUE | 1.1 | {20A5AA67-0D4E-445B-93FA-426515BAB7F2}

You can see the DateTime value in 1st column is different rest all same.
The detailed stack trace is:

> " at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at OfficeOpenXml.Table.ExcelTableColumnCollection..ctor(ExcelTable table) at OfficeOpenXml.Table.ExcelTable.set_ShowHeader(Boolean value) at OfficeOpenXml.ExcelRangeBase.LoadFromText(String Text, ExcelTextFormat Format, TableStyles TableStyle, Boolean FirstRowIsHeader)

**Comment by JanKallman** [comment]
This repo is only EPPlus 5. 
I don't really recognize this issue, but feel free to try it in version 5.4 and see if it still is an issue.
