### ISSUE TITLE
Collapse/Expand all feature in Pivot Table missing

### ISSUE THREAD

**Issue by shailendragadekar** [EPPlusSoftware/EPPlus#215]

**Comment by SteveWark** [comment]
Searched everywhere for this, seems it is still a missing feature, this is a key requirement

**Comment by JanKallman** [comment]
From version 5.6 you can set the field.Items[0].ShowDetails flag to true or false. 
You can also use the field.Items.ShowDetails(bool) method to expand/collapse all items for a field.
