### ISSUE TITLE
[Question] Reading Excel columns (data types)

### ISSUE THREAD

**Issue by svrebelo001** [EPPlusSoftware/EPPlus#221]
Good evening everyone!

A very fast question: If I have a number data type in my excel column (let's say col A), my C# app should read the column data type as System.Int32 (int) ? I'm getting it as String and I don't know what I'm doing wrong (or missing something).

Thanks in advance!

**Comment by JanKallman** [comment]
If the value is numeric in Excel you will get it as a double in most cases (depending on the format it can be for example a date). 
If the value is a string in Excel (for example formatted as text or with a single quote prefix), you will get it as a string.
