### ISSUE TITLE
ExcelPackage.GetAsByteArrayAsync() gives an error for v5.4 #2

### ISSUE THREAD

**Issue by igigiberia** [EPPlusSoftware/EPPlus#226]
I could share the session, with vs live, or remotely, but code is quite big and it's not easy to provide an example, as it works over the report that is auto generated.
I have referenced the latest code cloned instead of nuget, and this is exact exception what I get:

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OfficeOpenXml.Table.PivotTable.ExcelPivotTableCacheField.UpdateCacheLookupFromItems(List`1 items) in E:\Repos\EPPlus\src\EPPlus\Table\PivotTable\ExcelPivotTableCacheField.cs:line 699

  This exception was originally thrown at this call stack:
    [External Code]
    OfficeOpenXml.Table.PivotTable.ExcelPivotTableCacheField.UpdateCacheLookupFromItems(System.Collections.Generic.List<object>) in ExcelPivotTableCacheField.cs
```

_Originally posted by @igigiberia in https://github.com/EPPlusSoftware/EPPlus/issues/198#issuecomment-727607102_

**Comment by JanKallman** [comment]
I'll see if I can figure out what the problem is from the stack trace.

**Comment by JanKallman** [comment]
Can you validate if this works in 5.4.2?

**Comment by igigiberia** [comment]
From the first look, it seems to be fixed, I will do further more tests and will report back, thank you for your support!

**Comment by JanKallman** [comment]
Great

**Comment by igigiberia** [comment]
Everything works as expected, thank you very much again for your support!
