### ISSUE TITLE
Parameter is not valid when save

### ISSUE THREAD

**Issue by pablogupi** [EPPlusSoftware/EPPlus#229]
Hi! 
I try EPPlus opening big excel with multiple sheets, macros, images and formulas. 

  ```
using (var package = new ExcelPackage(new FileInfo((string)@"/Users/pablo/Downloads/plantilla.xlsx")))
             {
                 var sheet = package.Workbook.Worksheets.Add("My Sheet");
                 sheet.Cells["A1"].Value = "Hello World!";

                 // Save to file
                 package.Save();
             }
```

but always when save return this error: 

Paremeter is not valid
"   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)\n   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)\n   at System.Drawing.Image.Save(Stream stream, ImageFormat format)\n   at OfficeOpenXml.Compatibility.ImageCompat.GetImageAsByteArray(Image image)\n   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, ExcelGroupShape shape)\n   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)\n   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()\n   at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)\n   at OfficeOpenXml.ExcelWorksheet.Save()\n   at OfficeOpenXml.ExcelWorkbook.Save()\n   at OfficeOpenXml.ExcelPackage.Save()"

I run code in MacOSx in a simple project in c#. mono-libgdiplus is installed.Is there a solution for this problem?
Thanks a lot

**Comment by JanKallman** [comment]
Does the package contain emf or wmf images? Check by rename *.xmsx -> *.zip, extract and check in the xl/media folder.
libgdiplus don't support these image formats.

**Comment by pablogupi** [comment]
Thank you very much for the quick reply. Exist one emf image. I have deleted it and now it saves the excel. But the generated xlsx is corrupt and excel cannot open it. The size is similar to the template, what can happen? Thanks

**Comment by JanKallman** [comment]
You can delete it directly in the package as it is referenced from other parts inside the package. Emf files are usually connected to an ActiveX control of some sort, for example a checkbox or combobox.

**Comment by pablogupi** [comment]
I have replaced the image with a jpg image. After the corrupted xlsx it is possible to open it using excel. Apparently it is correct. The excel report is this (Sorry it's in Spanish):

`<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Reparar resultado para modificado20.xml</logFileName><summary>Se han detectado errores en el archivo "/Users/pablo/Downloads/modificado2.xlsx"</summary><removedParts summary="Lista de partes eliminadas:"><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable3.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable3.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable3.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable3.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable4.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable4.xml.  (Vista Tabla Dinámica)</removedPart><removedPart>Parte quitada: Parte /xl/pivotTables/pivotTable4.xml.  (Vista Tabla Dinámica)</removedPart></removedParts><removedRecords summary="Lista de registros eliminados:"><removedRecord>Registros quitados: Propiedades del libro de /xl/workbook.xml parte (Libro)</removedRecord></removedRecords><repairedRecords summary="A continuación se muestra una lista de reparaciones:"><repairedRecord>Registros reparados: Informe de tabla dinámica de /xl/pivotCache/pivotCacheDefinition1.xml parte (Caché de tabla dinámica)</repairedRecord></repairedRecords></recoveryLog>
`

Could it be related to this one?
https://github.com/EPPlusSoftware/EPPlus/issues/50

**Comment by JanKallman** [comment]
Delete the ActiveX control inside Excel (if it is the drawing having a relation to the emf).
