### ISSUE TITLE
ExcelPackage.Workbook.Worksheets(sheetName, copySheet) changed the copySheet Original columns width!

### ISSUE THREAD

**Issue by weiwxg** [EPPlusSoftware/EPPlus#230]

**Comment by weiwxg** [comment]
could you tell me why and how should i do?

**Comment by JanKallman** [comment]
Please provide a sample to reproduce

**Comment by weiwxg** [comment]
I hava a excel as follow: 
![image](https://user-images.githubusercontent.com/24971860/99468754-48dc1b00-297c-11eb-9062-0ff441be0e59.png)
and i want merge 2 sheets into 1 excel as follow:
```csharp
var masterPackage = new ExcelPackage(new FileInfo(@"F:\temp\output.xlsx"));
for (int i = 0; i < 2; i++)
{
      var pck = new ExcelPackage(new FileInfo(@"F:\temp\templet.xlsx"));
      masterPackage.Workbook.Worksheets.Add("Sheet" + (i + 1), pck.Workbook.Worksheets[1]);
}
masterPackage.Save();
```
then all columns width of output.xlsx changed!
![image](https://user-images.githubusercontent.com/24971860/99468986-d15abb80-297c-11eb-8853-1418c26b4b6c.png)

**Comment by JanKallman** [comment]
Which version are you using?
If you use version 5+, please register a support case on our support forum that comes with your commercial license and attach the Excel file you are using.
We no longer provide support for the earlier LGPL versions of EPPlus.

**Comment by weiwxg** [comment]
sorry, i use EPPlus v4.5, but i suppose the same problem will be in version 5+,  Isn't there anyone who can help me with this problem.

**Comment by weiwxg** [comment]
i try it use version 5+, and the problem also exists!
```csharp
ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
var masterPackage = new ExcelPackage(new FileInfo(@"F:\temp\output.xlsx"));
for (int i = 0; i < 2; i++)
{
       var pck = new ExcelPackage(new FileInfo(@"F:\temp\templet.xlsx"));
       masterPackage.Workbook.Worksheets.Add("Sheet" + (i + 1), pck.Workbook.Worksheets[0]);
}
masterPackage.Save();
```

**Comment by JanKallman** [comment]
This is probably due to different normal fonts in the packages, but I cant say for sure without a fully reproducable sample.

**Comment by weiwxg** [comment]
hi, I found the cause of the problem. only when i merged excel sheet into a new ExcelPackage, the problem occured. howerver, when merged into existed excel package, the problem disappered.

**Comment by JanKallman** [comment]
Great, you probably have different fonts set for the Normal style on the packages.
