### ISSUE TITLE
Trying to make SelectSingleItem select only the "false" condition

### ISSUE THREAD

**Issue by EsbenRud** [EPPlusSoftware/EPPlus#233]
After issue #232 I am now ready to do what I originally wanted. I will create a Pivottable with filter on StandardBackup (see ConsoleApp1.zip) using SelectSingleItem on the PageField, but it looks like both "FALSK" (false) and "empty" have been selected. 
I have uploaded a smaple project which you can tru to run, the output is in the Debug folder and is named test.xlsx.
What I am doing wrong?
Best regards
Esben Rud Nielsen, Bankdata
[ConsoleApp1.zip](https://github.com/EPPlusSoftware/EPPlus/files/5565025/ConsoleApp1.zip)

**Comment by JanKallman** [comment]
This occured when an item was blank. Fix applied.

**Comment by EsbenRud** [comment]
Works great, thanks a lot.

**Comment by JanKallman** [comment]
Fixed in version 5.4.2
