### ISSUE TITLE
EPPlus upgrade to net5 makes it incompatible with azure functions 3.x and lower

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#235]
Just a heads up, updating to the latest "microsoft.X" nuget packages with version 5.x makes your package incompatible with azure functions currently.

https://github.com/Azure/azure-functions-host/issues/6674

**Comment by JanKallman** [comment]
Thanks for sharing this. We'll have a discussion if we should revert net5.0 and release a new version. I'll get back to you here.

**Comment by eriove** [comment]
I would suggest to multi-target. Let .NET5 use the new packages and .NET Core 3.X use the old packages. Since you don't have that many projects the conditionals in the .csproj-files shouldn't be too bad to maintain manually (it breaks the GUI for NuGet).

**Comment by JanKallman** [comment]
@eriove We use multi target today, so it would be an easy fix if I understand you correctly...
https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/EPPlus.csproj

**Comment by eriove** [comment]
Yes, looks like you can just change the package versions in some of the conditionals. I.e. change for example [this](https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/EPPlus.csproj#L210) line to
```
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="(,3.1.10]" />
```
Not sure about the range on the package versioning but I think the upper end should be there at least. Probably have to be tested with Azure functions to be sure.

**Comment by JanKallman** [comment]
I have reverted the packages for .NET standard 2.0 and 2.1. Feel free to try it out using our develop nuget feed... https://ci.appveyor.com/nuget/epplus

**Comment by JanKallman** [comment]
Downgraded in EPPlus 5.5
