### ISSUE TITLE
Cell.RichText throws an exception with values like '&'

### ISSUE THREAD

**Issue by MohamedA-Ibrahim** [EPPlusSoftware/EPPlus#236]
When trying to add a text to a cell and that text contains the symbol '&', any operation with the RichText whether it's RichText.Clear or RichText.Add throws this error: "System.Xml.XmlException: 'An error occurred while parsing EntityName. Line 1, position 108.'"

**Comment by JanKallman** [comment]
I'll have a look

**Comment by JanKallman** [comment]
I can't reproduce this issue. Please provide a reproducable test.

**Comment by MohamedA-Ibrahim** [comment]
Here is example code that produces the bug:
![image](https://user-images.githubusercontent.com/39552203/103447025-8d9ee580-4c8e-11eb-8587-f318af7f0cf4.png)
and the excel file:
![image](https://user-images.githubusercontent.com/39552203/103447028-9abbd480-4c8e-11eb-901a-ddb67a4d4f6a.png)

**Comment by JanKallman** [comment]
Thanks. This issue occures when setting the IsRichText property. Fix will be applied shortly. 
For now, use the RichText.Text property or RichText.Add method

**Comment by JanKallman** [comment]
Fixed in version 5.5.1
