### ISSUE TITLE
Order columns

### ISSUE THREAD

**Issue by crowar** [EPPlusSoftware/EPPlus#237]
Column sorting mechanics are required. Now they are sorted in the order of their writing in the class, if you use inheritance, then sorting is not quite correct.

If you do not support ```net35``` and ```net40```, you can use ```DisplayAttribute```.

**Comment by JanKallman** [comment]
Unsure how this should work? On a Table or a Range?

**Comment by crowar** [comment]
This need only when you load from collection, I create PR #239 
If you load from table you can reordered columns before load

**Comment by swmal** [comment]
Hi @crowar,

We have implemented this for the next version (5.5), see PR #258. We have implemented a new attribute - EpplusTableColumn - in that also provides possibility to set numberformat and header text on the column. It supports the earlier versions (3.5 and up).

**Comment by swmal** [comment]
Implemented in v5.5
