### ISSUE TITLE
The file could be corrupted or unsafe

### ISSUE THREAD

**Issue by mehreen7804** [EPPlusSoftware/EPPlus#241]
I used the following code to generate excel file using EPPLUS library but every xls or xlsx file it generates gives following error when opening the file.

ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var fi = new FileInfo(filePath);

            using (var excelPackage = new ExcelPackage(fi))
            {
                var worksheet = excelPackage.Workbook.Worksheets.Add(sheetname);
                worksheet.Cells["A1"].LoadFromDataTable(data, false);
                
                excelPackage.Save();
                
            }
the file format and extension of filename.xls don't match. the file could be corrupted or unsafe. unless you trust its source, don't open it, do you want to open it anyway?

**Comment by JanKallman** [comment]
EPPlus don't support xls, only Office Open Xml files, xlsx and xlsm
