### ISSUE TITLE
Picture width stretched on import as drawing, dpending on template used or not (4.5.3.3)

### ISSUE THREAD

**Issue by Henry-Jones** [EPPlusSoftware/EPPlus#242]
Hello,

I've the following lines:

            ExcelPackage EP = new ExcelPackage(Template, false);
            System.Drawing.Image bild = System.Drawing.Image.FromFile("D:\\cable.jpg");
            ExcelPicture ep = EP.Workbook.Worksheets[1].Drawings.AddPicture("Grafik 1", bild);

            ep.EditAs = eEditAs.OneCell;
            EP.SaveAs(new FileInfo("d:\\test.xlsx"));

the imported picture is wider than the original, even after something like "SetSize(x)" or even "SetSize(bild.Height, bild.Width)".

If I use as first line:
            ExcelPackage EP = new ExcelPackage();

the picture has the correct size. So only the usage of a template file makes a difference. I used even a completetly empty template file with the same result.

In version 5.4.2.0 the problem seems to be solved (both variants result in the same xlsx file). Is there anything to be done for the old version ? Maybe in the future we will buy a license but currently we are in the process of evaulation and if 4.x is enough we'll stay with it.

**Comment by JanKallman** [comment]
Hello,
EPPlus 4 is archived and we will do no updates to it. But you can fork it from https://github.com/JanKallman/EPPlus if you want to look into if yourself.
