### ISSUE TITLE
Error evaluate indirect("MyList") when MyList is a ListObject

### ISSUE THREAD

**Issue by dhalte** [EPPlusSoftware/EPPlus#243]
Tested in 5.4.2
MyList is a ListObject of one or many columns

`            
rg.Formula = $"TEXTJOIN(\"|\", FALSE, INDIRECT(\"MyList\"))";

rg.Calculate();

var v = rg.Value;
`
return #VALUE!

If I index MyList with the name of one column, like INDIRECT(\"MyList[MyFirstColumnName]\", result is correct

Obviously, the first form works in Excel.

**Comment by swmal** [comment]
Thanks for reporting this. 

Can you share a workbook so we can reproduce and have a look?

**Comment by dhalte** [comment]
Hoping to help

 

 

De : Mats Alm <notifications@github.com> 
Envoyé : samedi 28 novembre 2020 22:46
À : EPPlusSoftware/EPPlus <EPPlus@noreply.github.com>
Cc : HALTE, DANIEL <Daniel.HALTE@econocom.com>; Author <author@noreply.github.com>
Objet : Re: [EPPlusSoftware/EPPlus] Error evaluate indirect("MyList") when MyList is a ListObject (#243)

 

Thanks for reporting this.

Can you share a workbook so we can reproduce and have a look?

**Comment by dhalte** [comment]
[EPPlusTest.zip](https://github.com/EPPlusSoftware/EPPlus/files/5614773/EPPlusTest.zip)

**Comment by JanKallman** [comment]
Thanks, we'll have a close look into this

**Comment by JanKallman** [comment]
Fixed for INDIRECT function applied in EPPlus 5.5

**Comment by swmal** [comment]
This commit should make the formula calc engine in EPPlus to handle tables as a named range.

**Comment by JanKallman** [comment]
Fixed in 5.5.2
