### ISSUE TITLE
private property ExcelAddressBase.FullName don't escape special characters

### ISSUE THREAD

**Issue by dhalte** [EPPlusSoftware/EPPlus#247]
This property is private, I regret it. But I wanted to access it by Reflexion.

And when the name of the sheet contains special character simple quote "'", the value is not escaped.
For example it returns "'a'b'!A1" instead of "'a''b'!A1

**Comment by JanKallman** [comment]
I assume you mean ExcelAddressBase.FullAddress? I'll provide a fix for it.

**Comment by dhalte** [comment]
Yep, sorry. It's FullAddress. Thank's
But can you explain me why WorkSheetName et FullAddress are private ? Why can we not have a public getter on these values ?

**Comment by JanKallman** [comment]
I'll change it to public to the next version

**Comment by JanKallman** [comment]
Changed in EPPlus 5.5
