### ISSUE TITLE
Bad Excel file after SelectSingleItem

### ISSUE THREAD

**Issue by EsbenRud** [EPPlusSoftware/EPPlus#248]
After #233 I now experience a bad Excel file after having used SelectSingleItem and then saved the file. Opening the file Excel will show a "Repair" popup. You can try it with the attached ConsoleApp1.zip. Input file is test.xlsx in the Debug folder and output will be the same file.
Best regards
Esben Rud Nielsen, Bankdata
[ConsoleApp1.zip](https://github.com/EPPlusSoftware/EPPlus/files/5622651/ConsoleApp1.zip)

**Comment by JanKallman** [comment]
I'll have a look

**Comment by JanKallman** [comment]
This happends on pivot table columns with boolean values only. The cache fields sharedItems invalidly gets the containsSemiMixedType="0".  I'll apply a fix shortly.

**Comment by EsbenRud** [comment]
Works fine now :-)

**Comment by EsbenRud** [comment]
When will you release a new version?

**Comment by JanKallman** [comment]
We aim to release EPPlus 5.5. this Thursday

**Comment by JanKallman** [comment]
FYI, we hope we can finalize the release tomorrow.

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.5
