### ISSUE TITLE
AutoFitColumns

### ISSUE THREAD

**Issue by Ebobo-2020** [EPPlusSoftware/EPPlus#255]
Hi. The operation of AutoFitColumns differs from the standard auto-width selection. Example of how AutoFit works in Microsoft.Office.Interop.Excel. 
![standart](https://user-images.githubusercontent.com/59816648/101881724-de4a8380-3ba5-11eb-8717-d73b8278357b.PNG)

and an example of how it works in EPPlus. 
![EPPLUS](https://user-images.githubusercontent.com/59816648/101881729-dee31a00-3ba5-11eb-915d-2b153cafbbea.PNG)

Extra space is specially designed? I can get rid of it in some way to make it look like a standard auto-width function?

**Comment by JanKallman** [comment]
The AutofitColumn in not a 100% match with Excel. It uses the text measure in .NET and in some cases saved text width depending on the fonts. So it might depend on the font you are using.

**Comment by Ebobo-2020** [comment]
With any font I've tried, I get the same thing.
above I did AutoFitColumns only for column headers. but if I do an AutoFitColumns of the entire table then I get
`  using (ExcelRange rng = worksheet.Cells[1, 1, ID.Length , DaIndex.Max()])
                    {
                        rng.Style.Font.Name = "Times New Roman";
                        rng.AutoFitColumns();
                    }`

the title does not fit in the column
![image](https://user-images.githubusercontent.com/59816648/102184704-edd90d80-3ec0-11eb-813f-50da52d26d6b.png)
I don't understand why this is happening

**Comment by Ebobo-2020** [comment]
when I do AutoFitColumns() the entire table still get this behavior. 
![image](https://user-images.githubusercontent.com/59816648/104150619-83e25400-53eb-11eb-9b1c-453adaf5a620.png)
what is the problem?

**Comment by JanKallman** [comment]
I cant tell by the image. Might be connected to the unicode characters or the font. 
Please provide a sample that reproduce the problem. Also, is this under Windows or Linux?

**Comment by Ebobo-2020** [comment]
windows.
I made a piece to see how it would be. I get the result as in the picture above
`private void TEST()
        {

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            string fileName = $@"C:\1\newFile.xlsx";
            using (var package = new ExcelPackage(new FileInfo("Default.xlsx")))
            {





                using (ExcelWorksheet worksheet = package.Workbook.Worksheets.Last())
                {

                    worksheet.Name = $"C {NTermoDate1.ToString("dd.MM.yyyy")} по  {NTermoDate2.ToString("dd.MM.yyyy")}";


                    worksheet.Cells[1, 1].Value = "Время начала";
                    worksheet.Cells[1, 2].Value = "Время окончания";
                    worksheet.Cells[1, 3].Value = "Всего сдозировано";
                    worksheet.Cells[1, 4].Value = "Отклонение";




                    for (int i = 1; i < 5; i++)
                    {
                        using (ExcelRange rng = worksheet.Cells[1, i, 2, i])
                        {
                            rng.AutoFitColumns();
                            rng.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                            rng.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                            rng.Style.Border.BorderAround(ExcelBorderStyle.Thin);
                            rng.Merge = true;
                            rng.Style.Fill.PatternType = ExcelFillStyle.Solid;
                            rng.Style.Fill.BackgroundColor.SetColor(200, 204, 204, 255);
                        }


                    }


                    for (int t = 0; t < 5; t++)
                    {

                        worksheet.Cells[3 + t, 1].Value = "12.01.2021 8:24:00";
                        worksheet.Cells[3 + t, 1].Style.Numberformat.Format = "dd.MM.yyyy HH:mm:ss";
                        worksheet.Cells[3 + t, 2].Value = "12.01.2021 11:24:00";
                        worksheet.Cells[3 + t, 2].Style.Numberformat.Format = "dd.MM.yyyy HH:mm:ss";
                        worksheet.Cells[3 + t, 3].Value = Math.Round((double)(Convert.ToDouble("8000")), 2);
                        worksheet.Cells[3 + t, 3].Style.Numberformat.Format = "0.00";
                        worksheet.Cells[3 + t, 4].Value = $"{Math.Round((double)((Convert.ToDouble("9000") - Convert.ToDouble("8000")) / Convert.ToDouble("9000") * 100), 2)}%";
                        worksheet.Cells[3 + t, 4].Style.Numberformat.Format = "0%";
                        worksheet.Cells[3 + t, 4].Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
                        
                    }


                    using (ExcelRange rng = worksheet.Cells[1, 1, 7, 4])
                    {
                        rng.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                        rng.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                        rng.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                        rng.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    }

                    using (ExcelRange rng = worksheet.Cells[1, 1, 7, 4])
                    {
                        // rng.Style.Font.Name = "Times New Roman";
                        rng.AutoFitColumns();
                    }

                    FileInfo fi = new FileInfo(fileName);
                    package.SaveAs(fi);

                    Process excel = new Process();
                    excel.StartInfo.FileName = fileName;
                    excel.Start();



                }
            }


        }`

**Comment by JanKallman** [comment]
AutofitColumns ignore merged and wrapped cells, so headers will be ignored in this code.
