### ISSUE TITLE
Bug with formatted text in a TextBox drawing object

### ISSUE THREAD

**Issue by ZaL133** [EPPlusSoftware/EPPlus#270]
The basics of the issue are that I have an excel document developed outside of epplus which contains a TextBox with a bunch of formatted text. I open the document using EPPlus, save the document without making any changes, and then look at the document in excel, and there are additional new lines. See screenshot

![image](https://user-images.githubusercontent.com/1176354/104206852-0aa02c80-53fe-11eb-9bb4-2bf5140d25aa.png)

Here is sample code which recreates the issue: 
```
        static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var fileInfo = new FileInfo(@"Book1.xlsx");
            using (var pck = new ExcelPackage(fileInfo))
            {
                pck.Save();
            }
        }

```

Here is the text in the TextBox (screenshot has some formatting that won't copy, but the issue recreates even without it)

```
Purpose 
 
- To provide insight into capacity and resource-use trends over time. 
- To allow users additional insights into trends over time for planning.

Audience 
 
- Everyone blah blah
```

From what I can tell in my troubleshooting, the original workbook contains a drawings\drawing1.xml which is saved as unformatted xml. The EPPlus saved workbook has the same drawing, but is saved with formatted xml. There is an element which has it's close tag on a new line due to this which is turning a space into a new line. 

![image](https://user-images.githubusercontent.com/1176354/104208845-fad51800-53fe-11eb-9dd9-46d2d1729424.png)

Thanks!!

**Comment by JanKallman** [comment]
Added in 5.5.1
