### ISSUE TITLE
File with defined names gets corrupted after package.Save() call

### ISSUE THREAD

**Issue by akashkarov** [EPPlusSoftware/EPPlus#272]
There is an issue when I'm trying to save the package with defined names like '\C'. Saving works ok, but then Excel treats the file as corrupted and offers recovering. After recovery, these defined names are back in workbook.xml. Please see the attached test project reproducing this issue.
[DefinedNamesTest_2.zip](https://github.com/EPPlusSoftware/EPPlus/files/5803214/DefinedNamesTest_2.zip)

The original issue #260 is gone.

**Comment by JanKallman** [comment]
I added a fix for this yesterday. The problem was not related to the backslashes in the names, but rather due to an invalid handling of external refeterences.

**Comment by akashkarov** [comment]
Thanks for quick response. I checked the latest code from develop branch and the issue is gone. Is it planned to be in the next release?

**Comment by JanKallman** [comment]
Yes, this fix will go into the next minor.

**Comment by vkirienko** [comment]
Can we get a sense when next release will be? We need to plan some things on our end.

**Comment by JanKallman** [comment]
Tomorrow or early next week

**Comment by JanKallman** [comment]
Fixed in 5.5.2
