### ISSUE TITLE
Named ranges corrupted after writing to Excel workbook

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#273]
Hello,

We are writing to an existing workbook which opens fine before the write (no warnings).  After the write we get a warning about corrupted data and the log reports that some named ranges were removed:

Removed Records: Named range from /xl/workbook.xml part (Workbook)

Can you please provide some insight into why the existing named ranges are not an issue until after the workbook is written by EPPlus?

**Comment by JanKallman** [comment]
I just fixed an issue with defined names with external references. Is this that case for you? Try latest develop build from our nuget feed ... https://ci.appveyor.com/nuget/epplus

**Comment by rdhasse** [comment]
That seems to have fixed it.  Thanks!

**Comment by JanKallman** [comment]
Duplicate, fix will go into version 5.5.2
