### ISSUE TITLE
The xlsx file is damaged and needs to be repaired

### ISSUE THREAD

**Issue by allen3371** [EPPlusSoftware/EPPlus#275]
hi,
i have a xlsx file (1.xlsx),it's length is 4,993,878bytes
i open it by epplus ,and then save as 2.xlsx,it's length is 3,416,315 bytes, then ,open by excel,  excel show the file need fix
epplus version 5.5.1
this is my code 

```
  ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (ExcelPackage package = new ExcelPackage(new FileInfo("d://1.xlsx") ))
            {
                package.SaveAs(new FileInfo("d://2.xlsx"));
            }
```

Thanks!!

[1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5806838/1.xlsx)

[2.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5806835/2.xlsx)

**Comment by JanKallman** [comment]
Your file likely contains something that is not supported by EPPlus. I had a quick look at the file, but it is to massive to troubleshoot and no clear error message is given, so this goes beyond the support we provide here.
