### ISSUE TITLE
Marking a workbook as shared

### ISSUE THREAD

**Issue by robalexclark** [EPPlusSoftware/EPPlus#276]
Is it possible to mark a workbook as "shared" so that more than one user can write to the Excel file?

I did notice the property:

 excelPackage.Workbook.Properties.SharedDoc = true;

But this doesn't appear to mark the workbook as shared when it is opened in Excel

We are investigating using EPPlus to create tracking sheets for our internal users but would need this functionality in order to be able to do this.

**Comment by JanKallman** [comment]
There is no support for Workbook sharing at this time. I am unsure if you mean the Legacy Share Workbook with tracking changes or the new cloud based co-authoring.

**Comment by robalexclark** [comment]
I was referring to the legacy share workbook, but as we have office 365 the cloud based co-authoring would actually be preferable.

If there is no support then I will look into whether the users can manually perform this step after a workbook is created.

**Comment by JanKallman** [comment]
You can use a "template workbook" with the correct setting when you create the new package in the ExcelPackage constructor...
```
using (ExcelPackage package = new ExcelPackage(existingFile))
{
...
}
```

**Comment by robalexclark** [comment]
Fantastic - that will work - thanks!
