### ISSUE TITLE
The xlsx file is damaged and needs to be repaired(edit)

### ISSUE THREAD

**Issue by allen3371** [EPPlusSoftware/EPPlus#280]
hi,
i have a xlsx file (1.xlsx)
i open it by epplus ,and then save as 2.xlsx, then ,open by excel, excel show the file need fix
epplus version 5.5.1
this is my code
```
ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            using (ExcelPackage package = new ExcelPackage(new FileInfo("1.xlsx")))
            {

                package.SaveAs(new FileInfo("2.xlsx"));
            }
```
I deleted a large number of columns, only one column, still suggest that the file needs to be repaired, can you help me see?
[1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5829251/1.xlsx)
[2.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5829254/2.xlsx)

thanks!
 #[https://github.com/EPPlusSoftware/EPPlus/issues/275](url)

**Comment by JanKallman** [comment]
This issue happens if the table header is rich text. Try supplied fix.

**Comment by allen3371** [comment]
thanks!,the new version 5.5.2 has fixed it

**Comment by JanKallman** [comment]
Great
