### ISSUE TITLE
Set Style will remove some contet, if there're empty coloumns in the range.

### ISSUE THREAD

**Issue by Tendx** [EPPlusSoftware/EPPlus#281]
This is the bug demo.

`
using OfficeOpenXml;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            FileInfo file = new FileInfo("test.xlsx");
            file.Delete();
            using (var package = new ExcelPackage(file))
            {
                ExcelWorksheet ws = package.Workbook.Worksheets["Sheet1"];
                if (ws == null)
                    ws = package.Workbook.Worksheets.Add("Sheet1");
                for (int i = 1; i < 11; i++)
                {
                    ws.Cells[i, 1].Value = "A";
                    ws.Cells[i, 10].Value = "B";
                }
                package.Save(); // File will create here, and you can set break point here and check its content.
                ws.Cells["A1:J10"].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                ws.Cells["A1:J10"].Style.Fill.SetBackground(System.Drawing.Color.AliceBlue);
                package.Save(); // After you set its PatternType, some content has been removed.
            }
        }
    }
}
`

**Comment by JanKallman** [comment]
What content is removed? I can see data i column A1:A10 and J1:J10 as set by the code.

**Comment by Tendx** [comment]
You can try the code. After style is set, cells A2:A10 and J1:J10 are cleared only left A1.

**Comment by JanKallman** [comment]
Sorry, I made a slight adjustment to the code. I see the issue now. I'll have a look and will provide a fix

**Comment by JanKallman** [comment]
Fix committed. You can try it using our develop Nuget feed...https://ci.appveyor.com/nuget/epplus. Thanks for reporting this issue.

**Comment by Tendx** [comment]
My pleasure.
When it will be updated on nuget.org? I made it work for setting values after the style :)
