### ISSUE TITLE
How to change chart data range?

### ISSUE THREAD

**Issue by shps951023** [EPPlusSoftware/EPPlus#282]
![image](https://user-images.githubusercontent.com/12729184/105145607-eea53500-5b39-11eb-88dc-03b2b1142830.png)

Try to modify `HeaderAddress`,`XSeries`,`Series` but not work

**Comment by JanKallman** [comment]
Please use our support portal or stackoverflow for support related questions. Have a look at our sample project for this...
https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/tree/master/15-ChartsAndThemes
