### ISSUE TITLE
Change access modifier for OfficeOpenXml.Utils.RecyclableMemory from internal to public

### ISSUE THREAD

**Issue by LIFEfreedom** [EPPlusSoftware/EPPlus#292]
The [OfficeOpenXml.Utils.RecyclableMemory](https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/Utils/RecyclableMemory.cs) class is not accessible from outside, but it has a **SetRecyclableMemoryStreamManager method (Microsoft.IO.RecyclableMemoryStreamManager recyclableMemoryStreamManager)**, which allows you to specify the **RecyclableMemoryStreamManager** so that the program has one
I made a mistake when creating a pull request
And the `GetStream()` methods are just internal

**Comment by LIFEfreedom** [comment]
I created a PR #293 for this issue

**Comment by JanKallman** [comment]
Thanks, merged

**Comment by LIFEfreedom** [comment]
@JanKallman When is the next release planned with this change?

**Comment by LIFEfreedom** [comment]
I see that a new version has been released

**Comment by JanKallman** [comment]
Yes, sorry, I missed you question as this issue was closed.
