### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

### ISSUE THREAD

**Issue by ej401** [EPPlusSoftware/EPPlus#295]
We started to get the subject error after upgrading from a 4.x installation to 5.5.2. The behavior is that you receive a "network error" when first attempting to download the file and the second time it succeeds, though with the same error in the console (tested on Chrome/New Edge).

Related code:

FileInfo excelFile = new FileInfo(reportPath);

                    using (ExcelPackage pck = new ExcelPackage(excelFile)) 
                    {
                        {
                            var DownloadFile = pck.GetAsByteArray();
                            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; ;
                            Response.AddHeader("content-disposition", "attachment; filename=" + fileName);
                            Response.AddHeader("content-length", DownloadFile.Length.ToString());
                            Response.BufferOutput = true;
                            Response.OutputStream.Write(DownloadFile, 0, DownloadFile.Length);
                            Response.Flush();
                            Response.End();
                        }
                    }

**Comment by JanKallman** [comment]
I'm unsure why you get that. Try to start with Response.Clear().

**Comment by ej401** [comment]
Thanks for the response Jan. I think I'm going to close this, though, as I don't believe it's related to EPPlus, but, rather, our network configuration. Although I see this message in my browser when I run the site on my local machine, I am still able to download the file the first time (without the network issue error). When I try it on our production server, it fails the first time and downloads the second.
