### ISSUE TITLE
Out of Memory Error with function "GetAsByteArray"

### ISSUE THREAD

**Issue by YousraHabib** [EPPlusSoftware/EPPlus#298]
I have EP Plus implemented in C# code to generate excel & this is triggered through dynamics 365. I keep getting an error of **"Out of Memory"**. I have traced the code and all works well up to the point of the function "**GetAsByteArray**", your help is highly needed on this point as it is very critical

**Comment by JanKallman** [comment]
You are out of memory. Make sure you compile your code as x64.

**Comment by YousraHabib** [comment]
Thank you for your reply.
I have done that as I read it could be a reason but it still gives the same error. Find attached it being 64 & giving the same error. Any other help is more than welcome as we are stuck at this point Sir. 

![OutOfMemory1](https://user-images.githubusercontent.com/78388737/106588207-93246f80-655b-11eb-9e24-cdf77b113c22.PNG)
![OutOfMemory2](https://user-images.githubusercontent.com/78388737/106588215-94ee3300-655b-11eb-88bf-5716c437b73b.PNG)

**Comment by JanKallman** [comment]
I cant help with this as I don't think this is an EPPlus issue. Out of memory usually means no more memory can be allocated. Maybe you run in some kind of sandbox restricting memory usage. Try to run it from a command line application to verify if it works there.
