### ISSUE TITLE
AddComment throws exception

### ISSUE THREAD

**Issue by A-Shawqi** [EPPlusSoftware/EPPlus#299]
I'm trying to use AddComment method to add a comment for a cell but it throws the following exception: 
"_**Unable to cast object of type 'OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingControl' to type 'OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingComment'**_"
but it works fine till version 5.42.

**Comment by JanKallman** [comment]
Can you provide some code to reproduce it? It works when I try it...
```
var ws = p.Workbook.Worksheets.Add("comment");
var c = ws.Cells["A1"].AddComment("TEST","JK");
var c2 = ws.Comments.Add(ws.Cells["A2"], "Test 2", "JK");
```

**Comment by A-Shawqi** [comment]
Herein a test method and the excel file 
` 
     
        public void WriteDayBillingTest()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (ExcelPackage excelPackage = new ExcelPackage(new FileInfo("DailyBillingTimeTemplate.xlsm")))
            {
                ExcelWorksheet sheet = excelPackage.Workbook.Worksheets.First();
                sheet.Cells[13, 2].AddComment("my comment", "A.Shawky");//this line throws exception starting from EPPlus v5.5.0
                excelPackage.SaveAs(new FileInfo("NewDailyBillingTime.xlsm"));
            }
        }
`
![image](https://user-images.githubusercontent.com/17937102/106828469-f533c080-6692-11eb-8607-14c45b8952bd.png)
[DailyBillingTimeTemplate.zip](https://github.com/EPPlusSoftware/EPPlus/files/5922453/DailyBillingTimeTemplate.zip)

**Comment by JanKallman** [comment]
This issue is fixed in the latest develop build.
