### ISSUE TITLE
.Net Core Unable to save the excel file while the localization culture is th-TH (Thailand) 

### ISSUE THREAD

**Issue by wyong95** [EPPlusSoftware/EPPlus#300]
Exception Message: Length cannot be less than zero. (Parameter "Length") 

I hit this exception at excel.SaveAsAsync(ms) method. 

Can you please investigate what's wrong. I tried with other localization such as Chinese Simplified, Vietnam and English are working fine, but I hit the exception when the localization is Thai. 

It's working on Windows Server 2016, but not working in Windows and Linux environment. 

P/S: The localization is set through HTTP Header - Accept-Language : th-TH from frontend. 

.Net Core 5 
Epplus 5.5.3 

![image](https://user-images.githubusercontent.com/50455272/106836722-a9097000-66d4-11eb-83ee-64bc6f740337.png)

![image](https://user-images.githubusercontent.com/50455272/106836741-b1fa4180-66d4-11eb-9135-250fa5831cc5.png)

![image](https://user-images.githubusercontent.com/50455272/106837320-6ac08080-66d5-11eb-96a6-57fe2284bf60.png)

![image](https://user-images.githubusercontent.com/50455272/106837490-8b88d600-66d5-11eb-8502-2ad503c6f534.png)

**Comment by JanKallman** [comment]
Please attach a reproducible test case. Code and a workbook if necessary.

**Comment by wyong95** [comment]
Hi please clone the project to debug the issue. Thanks. Looking forward to your finding. 

[https://github.com/wyong95/EPPlusIssue.git]

**Comment by wyong95** [comment]
[https://github.com/wyong95/EPPlusIssue.git](url)

**Comment by JanKallman** [comment]
I have added a fix for this. It seems the StringComparison for this culture did not find ":" in some of the string functions. I have specified the culture for these functions. Feel free to try if out using the latest devlop build.

**Comment by wyong95** [comment]
Hi may I know how to try it with the latest development build? where to find the latest development build?

**Comment by JanKallman** [comment]
Add this url to the package manager (inside Visual Studio, if you use that) : 
https://ci.appveyor.com/nuget/epplus

**Comment by wyong95** [comment]
![image](https://user-images.githubusercontent.com/50455272/107485774-31997c00-6bbf-11eb-9819-3dffa838d432.png)

Added the url to package manager but no source found.

**Comment by wyong95** [comment]
the issue has been fixed in version 5.5.4. Thanks.

**Comment by JanKallman** [comment]
@wyong95  FYI: When using our develop Nuget feed you have to check the _Include prerelease_ checkbox when browsing packages. Otherwise it will be empty.
