### ISSUE TITLE
Format of negative values, doesn't follow Excel formatting

### ISSUE THREAD

**Issue by vivet** [EPPlusSoftware/EPPlus#301]
[A1 Text issue.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5926369/A1.Text.issue.xlsx)
Hi

When having this format on a cell in Excel: ```#,##0.0;(#,##0.0);-```, and using the following code snippet:

```
using (var package = new ExcelPackage(new FileInfo(@"A1 Text issue.xlsx")))
{
    Console.WriteLine(package.Workbook.Worksheets[0].Cells[1, 1].Text);
}
```

the output becomes ```-(1.0)```, but should have been ```(1.0)```, unless I have misunderstood something.

**Comment by JanKallman** [comment]
I'll have a look
