### ISSUE TITLE
CircularReferenceException: Index for the same column cannot be computed, even though it works in excel

### ISSUE THREAD

**Issue by virzak** [EPPlusSoftware/EPPlus#304]
Test case is in #303

Formula `INDEX(A:A,1,1)` for cell A2 throws an exception when computed, but computes perfectly fine in [Excel](https://github.com/EPPlusSoftware/EPPlus/files/5936955/Index-Match-issue304.xlsx)

CircularReferenceException is thrown [here](https://github.com/EPPlusSoftware/EPPlus/blob/2b5cf1a442dd59fd42a453bf1e6305967897eece/src/EPPlus/FormulaParsing/ExpressionGraph/ExcelAddressExpression.cs#L82)

**Comment by swmal** [comment]
Thanks, I'll have a look at this.
