### ISSUE TITLE
add releases to the github

### ISSUE THREAD

**Issue by LIFEfreedom** [EPPlusSoftware/EPPlus#305]
Maybe add releases to the github?
So it will be convenient to follow the release of new versions.

**Comment by JanKallman** [comment]
Sorry for the late relay.
EPPlus is distributed as a multi target Nuget package via Nuget. 
Do you mean creating releases without binaries here to see the history or what is the purpose?

**Comment by LIFEfreedom** [comment]
Convenient to follow the history
subscription to updates to immediately know about the new version

**Comment by JanKallman** [comment]
Added release from version 5.6.1

**Comment by LIFEfreedom** [comment]
thanks
