### ISSUE TITLE
No Worksheet Found [DotnetCore 3.1 / EPPLUS 5.5.3)

### ISSUE THREAD

**Issue by Portekoi** [EPPlusSoftware/EPPlus#307]
# Scenario

1. Open this file : 
[Classeur1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5947533/Classeur1.xlsx)

2. use this code in an console project 
```c#

                            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                            using (ExcelPackage xlPackage = new ExcelPackage(file))
                            {
                                if (xlPackage.Workbook.Worksheets.Count == 1)
                                {
                                    var myWorksheet = xlPackage.Workbook.Worksheets[0]; //select sheet here
                                }
                                else
                                {
                                    Console.WriteLine($"No sheet found in {file.FullName}");
                                }
                            }
```

## Expected Result
xlPackage.Workbook.Worksheets.Count == 1

## Results
xlPackage.Workbook.Worksheets.Count == 0

Any Help?

**Comment by JanKallman** [comment]
This workbook uses ooxml strict, currently not supported by EPPlus. I add this as an enhancment.

**Comment by JanKallman** [comment]
Closing this as it's fits under #672.

**Comment by Skybladev2** [comment]
Please show more meaningful error message. It took half an hour to deduce that this particular format is not supported.

**Comment by JanKallman** [comment]
Same as [#672](https://github.com/EPPlusSoftware/EPPlus/issues/672)
