### ISSUE TITLE
Worksheet.Select() doesn't actually scroll to selected cell

### ISSUE THREAD

**Issue by EmaGht** [EPPlusSoftware/EPPlus#308]
Hi, i've noticed that in a large file (~ 9k rows * ~80 columns) when i Select a worksheet's Range, Save it and open the file with Excel, the cell is selected but not scrolled into view.
I would expect EPPLUS to set the scroll of the Excel file to that range but it actually doesn't.
I used COMs directly before and it worked without issues.

Is there anything I'm missing here?
I can provide an example if needed, let me know!

Thanks

**Comment by JanKallman** [comment]
You can set the Worksheet.View.TopLeftCell to the cell address you want.

**Comment by EmaGht** [comment]
Was it added in 5.X?

I'm currently in version 4.X, is there something equivalent there?

**Comment by JanKallman** [comment]
It was added in 5.0.

**Comment by EmaGht** [comment]
That means i am now blocked only by this https://github.com/EPPlusSoftware/EPPlus/issues/294 
Thanks for your support, i will wait for that issue to be gone :)
