### ISSUE TITLE
Template with some pivot tables get corrupted on version 5.5.3

### ISSUE THREAD

**Issue by charneca** [EPPlusSoftware/EPPlus#309]
Hello,

it happens after opening the excel template and saving it.
On version 5.0.4 the file seems to be saved correctly and does not add corrupted data.

![error1](https://user-images.githubusercontent.com/61232803/107239248-91a5ec00-6a20-11eb-957c-9a42087b0a70.jpg)

![error](https://user-images.githubusercontent.com/61232803/107238732-16443a80-6a20-11eb-8d1e-4cba8034812c.jpg)

here is the the excel file and some code.

[test1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/5956944/test1.xlsx)

```
        public class ReportTest
        {
            public string ConfigurationItem { get; set; }
            public int Count { get; set; }
        }

        public void Test1()
        {

            string workingDirectory = AppDomain.CurrentDomain.BaseDirectory;
            FileInfo template = new(workingDirectory + @"Templates\test1.xlsx");
            FileInfo finalFile = new(string.Format(workingDirectory + @"Cache\test1_{0}.xlsx", DateTime.Now.Ticks));

            finalFile.Delete();


            using (var excelFile = new ExcelPackage(template))
            {

                var topCI = new List<ReportTest>
                {
                    new ReportTest{ ConfigurationItem = "Item1", Count =3 },
                    new ReportTest{ ConfigurationItem = "Item2", Count =3 },
                    new ReportTest{ ConfigurationItem = "Item3", Count =3 }
                };

                ////Top CI
                var worksheet = excelFile.Workbook.Worksheets["Top CI"];
                var location = worksheet.Cells["Z1"].LoadFromCollection(Collection: topCI, PrintHeaders: true);
                worksheet.Tables.Add(location, "TopCiTypeTbl" + DateTime.Now.Ticks);


                //change month and select first worksheet
                var wsDashBoards = excelFile.Workbook.Worksheets["Dashboards"];

                wsDashBoards.Cells["A1"].Value = "Test Report";

                wsDashBoards.Select();


                var test = worksheet.PivotTables;

                excelFile.SaveAs(finalFile);
            }
        }
```

**Comment by JanKallman** [comment]
This workbook has pivot tables with chart formats referencing into the pivot cache. Chart formats is not supported, so when recreating the cache these items get out of sync. Please remove the chart formats from the pivot tables.
We will look into this in coming versions.

**Comment by charneca** [comment]
Thank you,

is there a way or parameter to ignore charts and pivot tables like on version  5.0.4 ?

My excel pivot charts and tables have the auto refresh data from a table location when it opens.


> This workbook has pivot tables with chart formats referencing into the pivot cache. Chart formats is not supported, so when recreating the cache these items get out of sync. Please remove the chart formats from the pivot tables.
> We will look into this in coming versions.

**Comment by JanKallman** [comment]
EPPlus from version 5.6 will leave the pivot tables untouched on save if they have not been accessed. Note that some operations like Copy, accessing tables etc will load the pivot tables.
