### ISSUE TITLE
Cannot set the data bars to solid fill mode for XLSX files

### ISSUE THREAD

**Issue by Rekkonnect** [EPPlusSoftware/EPPlus#312]
Despite the option being there and being able to set that mode in the code, the resulting XLSX file will not have the cell's data bars in solid fill mode.

**Comment by JanKallman** [comment]
Solid fills and some more settings seems to be handled by an extLst element. We will look into this for future versions.

**Comment by OssianEPPlus** [comment]
As of Epplus7 this and many other conditional formatting settings are supported.
