### ISSUE TITLE
ExcelWorksheetView ShowHeaders blank value is true

### ISSUE THREAD

**Issue by chriswaadt** [EPPlusSoftware/EPPlus#313]
Hello,

the @showRowColHeaders attribute is not serialized by excel, if the RowColHeaders are shown. But the ShowHeaders Property returns false in this case. Maybe this behaviour has changed in the latest Excel versions. My Excel Version is 2016.

With this change I was able to fix it. 
return GetXmlNodeBool("@showRowColHeaders");
return GetXmlNodeBool("@showRowColHeaders", true);

Best regards,
Christian

**Comment by JanKallman** [comment]
Yes, you are right. The default value if the attribute is empty should be true. I will change it. Thanks!

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.5.5
