### ISSUE TITLE
Does addindent Property support?

### ISSUE THREAD

**Issue by blackbullfx** [EPPlusSoftware/EPPlus#316]
In excel vba, white space can be inserted before and after with AddIndent property.
can't AddIndent property be used in EPPlus?

**Comment by JanKallman** [comment]
This seems to be the style element alignment - attribute justifyLastLine="1" ? 
It is not implemented, but we can add it for a coming version.

**Comment by JanKallman** [comment]
JustifyLastLine has been implemented in Feb 2022
