### ISSUE TITLE
Repeat Labels in Pivot Table fillDownLabels is not defined in C#

### ISSUE THREAD

**Issue by medaminrannen** [EPPlusSoftware/EPPlus#317]
I want to repeat Labels in Pivot Table but the fillDownLabels is not defined in C#
```
`if (!isPivotTree)
        {
            pivotTable1.RowGrandTotals = false;
            pivotTable1.ColumnGrandTotals = false;
            pivotTable1.Fields.ForEach(field =>
            {
                field.Outline = true;
                field.Compact = false;
                field.ShowAll = false;
                field.SubtotalTop = true;
                field.ShowMemberPropertyToolTip = false;
            });
        }`
```

```
/// <summary>
    /// Gets whether or not to repeat item labels in the pivot table for this field.
    /// </summary>
    public bool RepeatItemLabels
    {
        get { return base.GetXmlNodeBool("d:extLst/d:ext/x14:pivotField/@fillDownLabels"); }
    }
```

**Comment by JanKallman** [comment]
I'll see if I can add this to the field to the next version.

**Comment by Yuexs** [comment]
I also encountered this problem. Has it been realized at present

**Comment by Yuexs** [comment]
Is there any other way to achieve it？

**Comment by KikkoVinke** [comment]
I also encountered this problem. Any news?

**Comment by JanKallman** [comment]
No, this has not yet been implemented. The only way to achieve this is to update the xml via the `PivotTableXml` yourself. This is property must be written to the extLst element with on the correct field. You can check the format by setting the property in excel and open it in EPPlus or renaming the workbook *.zip and extract the pivot table xml file.

**Comment by KikkoVinke** [comment]
Can you provide an example please?

**Comment by OssianEPPlus** [comment]
This feature should be accessible since Epplus 7.5.1 via `field.RepeatItemLabels`
