### ISSUE TITLE
New Table Row Not Created When Writing with EPPlus

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#322]
I'm not sure if this is an issue, or if I just don't know how to do it.  Please suggest if there is a way to do it.

Here's an example:
There is a Table defined for range A1:K5.  In Excel, if a user types something into row 6, a new Table row is added and formulas auto-populated in the new row.

However, if I write something into row 6 with EPPlus, a new Table row is not created.  The text is written into the destination cell, but it seems the Table is not extended to include row 6.

I've tried calling Calculate() hoping that would do it but it did not.

**Comment by JanKallman** [comment]
No, EPPlus don't extend tables by default. You can use the AddRow or InsertRow methods of the ExcelTable class to extend the table.
