### ISSUE TITLE
EPPlus return 0 from cell with formula / reference to another sheet

### ISSUE THREAD

**Issue by Josip84** [EPPlusSoftware/EPPlus#323]
I'm trying to read value from sheet which contains cells with some result. This result are fetched from another sheet, for example:

![image](https://user-images.githubusercontent.com/8849217/109631973-cfd98b80-7b46-11eb-85b8-edf9a6da1ff9.png)

    using (var package = new ExcelPackage(new FileInfo(myPath)))
    {
         ExcelWorksheet output = package.Workbook.Worksheets["Results"];
         output.Cells["B2"].Calculate();
         var outval = output.Cells["B2"].Value;
    }

But only what I receive is 0.

**Comment by JanKallman** [comment]
This should work, but I cant tell what's wrong with the code you provide. Please provide a fully reproducible sample if something isn't working properly.
Note that you don't have to calculate unless you change the underlaying values of the sheet you read.

**Comment by Josip84** [comment]
> This should work, but I cant tell what's wrong with the code you provide. Please provide a fully reproducible sample if something isn't working properly.
> Note that you don't have to calculate unless you change the underlaying values of the sheet you read.

Unfortunately I can't provide this Excel file because it contains some business data. But This few lines of core are fully functional.

**Comment by JanKallman** [comment]
Well, doesn't say anything what you are calculating.

**Comment by Josip84** [comment]
> Well, doesn't say anything what you are calculating.

I found another cell which return values is 0 whatever is inside.

This is formula under cell L12:

![image](https://user-images.githubusercontent.com/8849217/109779849-aaac5200-7c06-11eb-994b-665bb207c6ac.png)

and result which this formula give is:

![image](https://user-images.githubusercontent.com/8849217/109779939-c7e12080-7c06-11eb-8266-7095f8154cec.png)


Then with this next lines of code:

using (var package = new ExcelPackage(new FileInfo(myPath)))
{
     ExcelWorksheet output = package.Workbook.Worksheets["MyCalcTable"];
     var outval = output.Cells["L12"].Value;
}

outval is always 0. But when I open Excel to check I see that there is different value.

**Comment by swmal** [comment]
It is not possible for us to say what is going wrong as long as we don't get a chance to replicate the error. In the screenshot you have provided there is at least 20 cell addresses where each one of them potentially could contain an error that affects the calculation. They might also refer to other cells - even if you just calculate one cell, there might be thousands of underlying cells that needs to be calculated first.

You can see if you find any underlying error by following the steps in the "Trouble shooting/Logging" on this page: https://github.com/EPPlusSoftware/EPPlus/wiki/Formula-Calculation

**Comment by JanKallman** [comment]
Feel free to re-open with a reproducable test case-
