### ISSUE TITLE
Minimum negative offset is -60. Parameter name: RowOffsetPixels

### ISSUE THREAD

**Issue by hasangursoy** [EPPlusSoftware/EPPlus#326]
Hello,

Thank you for this nice package.

I have an issue with image position. I've successfully add image with dimensions (auto x 95) but the images are positioned at the end of the given cell. For now I'm placing images on previous row but it would be nice to use negative offset as much as the actual cell height.

    var excelImage = sheet.Drawings.AddPicture($"image of #{order.Id}", img);
    
    //add the image to current row, column M
    excelImage.SetSize(95 * img.Width / img.Height, 95);
    excelImage.SetPosition(row - 1, 1, 12, 5);

![Image position on previous row](https://i.imgur.com/zfilYws.png)

**Comment by JanKallman** [comment]
I have removed this validation in version 5.6. Negative offsets beyond -60 seems to work fine.

**Comment by hasangursoy** [comment]
Just had time to check the update. Sadly I cannot use negative index anymore. It breaks excel file somehow. I get error "Repaired Records: Drawing from /xl/drawings/drawing1.xml part (Drawing shape)"

`excelImage.SetPosition(row, 1, -10, 5);`
