### ISSUE TITLE
Incompatibility between QXlsx (Qt) and EPPlus?

### ISSUE THREAD

**Issue by TwnKey** [EPPlusSoftware/EPPlus#328]
Hi,
I've been working on a tool which decompiles the script files from a game in the form of XLSX spreadsheets. It is using the QXlsx library for Qt. The generated files can be read from QXlsx, as well as opened in Excel without incident.

A C# programmer wanted to use EPPlus library to read such a file, and most of the time (especially when the file is big), the reading fails (EPPlus gets stuck at the line "excel.Workbook.Worksheets["Sheet1"]").

Here, two examples: one which is [working](https://github.com/EPPlusSoftware/EPPlus/files/6103630/working.xlsx) (EPPlus can read it) and one which is [not working](https://github.com/EPPlusSoftware/EPPlus/files/6103639/notworking.xlsx) (stuck). 

One thing to note is that when saving the broken file in Excel (without doing anything), EPPlus will then be able to read it.

I actually don't know if this problem concerns more EPPlus or QXlsx so I decided to start asking here.

**Comment by JanKallman** [comment]
This seems to be a bug when reading the worksheet xml in this specific case. I will provide a fix shortly so you can try on your other workbooks.

**Comment by JanKallman** [comment]
Fixed in version 5.6
