### ISSUE TITLE
.NET Core 3/foreach-loops generate unseen data

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#33]
Original issue reported here: https://github.com/JanKallman/EPPlus/issues/619 and applies to both 4.2 and 5.0.1-beta

**Comment by JanKallman** [comment]
Adding a non valid address B7:I or B:I7 should should throw an exception in ExcelAddressBase

**Comment by MightyFerengi** [comment]
Many thanks! I looks forward to the update!
