### ISSUE TITLE
SUMIFS cannot handle horizontal ranges

### ISSUE THREAD

**Issue by swiftinitdotcom** [EPPlusSoftware/EPPlus#330]
I have seen posts related to this and we have a licensed version. We need to know a fix or a workaround as the formula is used in 50+ places.
the formula is SUMIFS($Y6:$BL6,$Y$1:$BL$1,C$1)

**Comment by swiftinitdotcom** [comment]
I have seen this post-
https://github.com/JanKallman/EPPlus/issues/103

**Comment by swiftinitdotcom** [comment]
We applied this formula on one cell. Formula - SUMIFS($Y6:$BL6,$Y$1:$BL$1,C$1)
2. After that we did calcuation manually like below
_targetpackage.Workbook.FullCalcOnLoad = false;
_targetpackage.Workbook.Calculate();
_targetpackage.Workbook.CalcMode = ExcelCalcMode.Automatic;

3. When we are trying to read value of cell, it gives error of !Value

**Comment by adviknjadhav** [comment]
Epplus team - I'm also facing same issue. Any updates on this issue. Please provide solution to fix this issue as we have scheduled delivery of project.

**Comment by swmal** [comment]
Hi,
I have fixed two bugs that I found in SUMIFS this morning. You can try this version via our development build nuget feed: https://ci.appveyor.com/nuget/epplus

However, non of the bugs I fixed resulted in a #VALUE error so not sure if it helps your cases.

@swiftinitdotcom - see my reply in your support case.

@adviknjadhav - If theses fixes dont help, please provide a reproducable error and we will have a look.

**Comment by swmal** [comment]
We have narrowed this down to three different bugs in SUMIFS that all will be fixed in the next version (v5.6). See the two commits referring to this issue.

**Comment by swmal** [comment]
fix included in 5.6
