### ISSUE TITLE
"Address is not valid" on simple Worksheet Copy

### ISSUE THREAD

**Issue by EmaGht** [EPPlusSoftware/EPPlus#332]
Hi, this piece of code here:
https://github.com/EPPlusSoftware/EPPlus/blob/2053641f0c1f047264c03d3bb3fbc324473616b0/src/EPPlus/ExcelRange.cs#L79

Is breaking a simple
``
wb.Worksheets.Copy("TEMPLATE", "TEST");
``

I can send you the Excel which gives this error by a private channel if you want, and maybe try to setup a repro. Let me know, thanks

**Comment by JanKallman** [comment]
What is the value of the 'Address' property when you get the exception? I see that the StringComparison, is not InvariantCultureIgnoreCase as it should to handle variouse cases on #ref!

**Comment by EmaGht** [comment]
I've attached the project to my application and debugged it...
Address is an empty string:

![image](https://user-images.githubusercontent.com/12494403/111336044-2b426800-8675-11eb-8928-fa2b64dfadda.png)

This is what call ExcelRange's indexer:

![image](https://user-images.githubusercontent.com/12494403/111336223-52009e80-8675-11eb-8dff-30e7776c1884.png)

And name is something like this:

![image](https://user-images.githubusercontent.com/12494403/111336371-778da800-8675-11eb-9678-19cd532e9be7.png)

Anything else you might need?

**Comment by JanKallman** [comment]
Thanks, I have found the issue. I will provide a fix shortly.
The issue occurs if you have a sheet local defined name with an #REF! address.

**Comment by JanKallman** [comment]
Fixed in version 5.6.1
