### ISSUE TITLE
Issue Getting Formulas After First Row with Custom Addin

### ISSUE THREAD

**Issue by emmielewis** [EPPlusSoftware/EPPlus#333]
My excel file has an excel add in to perform some calculations in formulas.  I'm trying to read all of the formulas in the file and it only returns the formula text from the first row of cells.  The rest of the formulas for those rows and cells are blank unless they are standard Excel formulas.  Please advise on how to fix this.  I don't want to calculate using the custom formulas but I do want to read all formulas as raw text in the Excel file.

Example Formula: {=Test($A$6,$A$3,$A$4,$A$5, 1,"TEST")}

                foreach (ExcelWorksheet sheet in package.Workbook.Worksheets)
                {
                    Console.WriteLine(sheet.Name);

                    var start = sheet.Dimension.Start;
                    var end = sheet.Dimension.End;
                    for (int row = start.Row; row <= end.Row; row++)
                    {
                        // Row by row...
                        for (int col = start.Column; col <= end.Column; col++)
                        {
                            // ... Cell by cell...

                            ExcelRange cell = sheet.Cells[row, col];

                            if (!string.IsNullOrEmpty(cell.Formula) || !string.IsNullOrEmpty(cell.FormulaR1C1)) 
                            {
                                Console.WriteLine(cell.Address + " - " + (string.IsNullOrEmpty(cell.Formula) ? cell.FormulaR1C1 : cell.Formula));
                                cell.Clear();
                                cell.Value = "REPLACED!";
                            }

                        }
                    }
                }

**Comment by JanKallman** [comment]
Please attach your workbook as well.

**Comment by emmielewis** [comment]
Do you have a place where I can send it to you vs. posting it on here?  I redacted a lot of the information in it as well.

**Comment by swmal** [comment]
You can send it to info at epplussoftware.com

**Comment by emmielewis** [comment]
I believe the issue is with array formulas.  For some reason, those are not returning back as a valid formula on your side.

**Comment by emmielewis** [comment]
> You can send it to info at epplussoftware.com

I sent the redacted version your way.

**Comment by JanKallman** [comment]
This fix should solve the issue. Please give it a try [using our develop nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed).

**Comment by emmielewis** [comment]
Ok I will test it.

**Comment by emmielewis** [comment]
This works.  When can I expect it in the core Nuget package?

**Comment by emmielewis** [comment]
Actually, the way you have it now I believe is right.  Because it is an array formula, it is only happening on the field where the formula is applied.  The rest of the fields are fill ins from that formula from what I see.  Still testing.

**Comment by emmielewis** [comment]
Your fix works by the way.

**Comment by JanKallman** [comment]
Fixed in version 5.6.1
