### ISSUE TITLE
Disable drag-and-drop for a file 

### ISSUE THREAD

**Issue by iamkarlson** [EPPlusSoftware/EPPlus#338]
Hi, 
I'm getting a lot of problems when I create an excel file and then using drag-n-drop for filling a list with values. There's a item in the menu to disable it - Enable fill handle and cell drag-and-drop:
![image](https://user-images.githubusercontent.com/4534374/111790801-e14ec180-88c2-11eb-9093-1a9330bbf605.png)

Since I do this mostly on a a fresh excel installation I can't rely on excel settings to switch it off. Is there any possibility to change this setting from EPPlus so I cannot use drag-n-drop when I created such a file?

**Comment by JanKallman** [comment]
No, I don't think you can set that in the OOXML file format.
