### ISSUE TITLE
Delete the sheet does not work - 5.6.0

### ISSUE THREAD

**Issue by Ryba1986** [EPPlusSoftware/EPPlus#339]
After upgrading to 5.6.0, the method to delete the sheet does not work. It works fine in version 5.5.5.

![Przechwytywanie](https://user-images.githubusercontent.com/74811542/111864644-8ff60f00-8962-11eb-950b-7714feac8bd1.PNG)

**Comment by JanKallman** [comment]
Hello, I don't think this is a general issue as we have multiple tests on this. From the exception it looks like the ActiveTab property is out of range in your workbook for some reason. I will add a range check when altering this in the delete.

**Comment by JanKallman** [comment]
I think this should be fixed in 5.6.1
