### ISSUE TITLE
Copying a worksheet renames the tables on the sheet

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#342]
I have a worksheet containing a table with a specific name - e.g. `MyTable`. When I use EPPlus to copy this worksheet into a new workbook, EPPlus renames the table on the new worksheet to `Table1`.

This is different behaviour to Excel/Interop, and it also seems reasonable to expect that a 'copy' of a workbook wouldn't have details like this changed - so I would have assumed this is a bug.

However looking at the [WorksheetCopyHelper code](https://github.com/EPPlusSoftware/EPPlus/blob/842d03c6e7e774b0cbb96b0025da0e0fd566484a/src/EPPlus/Core/Worksheet/WorksheetCopyHelper.cs#L438) it seems like renaming the table is a conscious decision. 

So is this a bug or intended behaviour?

**Comment by JanKallman** [comment]
This behaviour should only be when copying within the same workbook. Table name must be unique within the workbook, so a check must be done if a name exists when copying. I'll provide a fix for this in a coming version.

**Comment by JanKallman** [comment]
Fixed in latest devlop build.

**Comment by JanKallman** [comment]
Try it using our develop Nuget feed...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by craigbrown** [comment]
Great, that's working for me! Thanks!
