### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by cuiliang** [EPPlusSoftware/EPPlus#346]
Sorry, I'did not find any support email, so I have to post as an issue.

I wang to buy license and want to confirm if my condition is covered by EULA.

I want to add some excel read write ability to my little product. 
This product is like 'Shortcuts' on iOS, it allow users to create 'Actions' using blocks. Something like 'RPA' software.
![image](https://user-images.githubusercontent.com/1972649/112959328-e2f76f80-9175-11eb-931e-a81ad161b0f5.png)

EPPlus will be distributed as a commponent of the software, and allow users use the it as some kind of wrapping block.

Thank you.

**Comment by JanKallman** [comment]
You have our contact e-mail addresses here: https://epplussoftware.com/en/Home/Contact
You can distribute EPPlus with your software as long as you don't expose EPPlus functionality as a service to other developers. 
See our License FAQ here: https://epplussoftware.com/en/LicenseOverview/LicenseFAQ
