### ISSUE TITLE
EPPLUS still loses formatting after saving a file

### ISSUE THREAD

**Issue by EmaGht** [EPPlusSoftware/EPPlus#347]
Hi, i'm still having the same problem as https://github.com/EPPlusSoftware/EPPlus/issues/294

This is the repro showing the problem:
https://github.com/EmaGht/EPPLUS_Bug

Simple console program that just opens my file and resaves it.
Original file is ~6 MB
Saved file is damaged and only ~4 MB

Let me know if i can help you tracking down the issue

Cheers

**Comment by JanKallman** [comment]
This issue is not related to #294. The issue occurs due an invalid handling of the normal style in EPPlus. Please try the attached fix using our develop Nuget feed.

**Comment by EmaGht** [comment]
Thanks for the quick reply! In 2 words, how do i link your develop Nuget feed?

**Comment by JanKallman** [comment]
Check this wiki article: https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by EmaGht** [comment]
Seems to be working! Just an unrelated question... the diminishing of filesize is still present, is EPPLUS cutting off/optimizing something or is there something i am missing?

**Comment by JanKallman** [comment]
EPPlus removes the calcchain.xml and the printersettings bin file I think. You can compare the xml files if you are interested and check the differences. Just rename the xlsx -> zip and compare the different xml files in the package.

**Comment by EmaGht** [comment]
I see thanks for the pointer! 
This problem is solved, but i have another one with setting the TopLeftCell, i will open a separate issues

**Comment by JanKallman** [comment]
Fixed in version 5.6.2
