### ISSUE TITLE
Creating a Conditional Formatting With Font Styling, And then Reading the Sheet does not pull any Font Styling

### ISSUE THREAD

**Issue by mDeweeseCCD** [EPPlusSoftware/EPPlus#349]
The formula pulls correctly, the background fill pulls correctly, but anything under the Font of the Style of the IExcelConditionalFormattingExpression does not fill in.

That includes Bold, Italic, Strike, Underline, & ExcelDxfColor Color.
HasValue is false.

While opening the resulting excel file in excel will display the correct font styling under the conditional formatting.
Interestingly if I go into the conditional formatting to edit it in excel (Home > Styles > Conditional Formatting > Manage Rules (Show formatting rules for: "This Worksheet") > (Select Conditional Format) > Format... ) , under the "Format Cells" it loses the settings for that conditional formatting. 

So it seems like when the font Style is set for the conditional formatting it's only in a half state of some sort. 

I can provide more information if necessary.

**Comment by JanKallman** [comment]
I'll have a look at this and get back to you

**Comment by JanKallman** [comment]
Fixed in version 5.6.2

**Comment by mDeweeseCCD** [comment]
Thank you! Great work!
