### ISSUE TITLE
Conditional formatting styles crashes when copying a worksheet from another package

### ISSUE THREAD

**Issue by JanKallman** [EPPlusSoftware/EPPlus#35]
https://github.com/JanKallman/EPPlus/issues/464

**Comment by JanKallman** [comment]
EPPlus RC

**Comment by cervengoc** [comment]
Hi @JanKallman ,

Don't exactly know your process and policy, but is there any chance that this can be backported to 4.x? Generally, could it be possible to have one more 4.x maintanence release?
