### ISSUE TITLE
No Way To Determine Partial Locked In a Range of Cells

### ISSUE THREAD

**Issue by mDeweeseCCD** [EPPlusSoftware/EPPlus#350]
If I select a set of cells that have some Styles marked as Locked, some set as Locked false. It will return true. 

Expected, Locked would return null. 

Also expected Locked would be a Nullable<bool>

**Comment by JanKallman** [comment]
Accessing properties on a multi cell range will return the value of the top-left cell. This is not something that can be changed as that would be a breaking change of behavior. Please iterate the cells in the range or use the Offset method to determine each cells value.

**Comment by mDeweeseCCD** [comment]
Thank you for your time on this. Have a good weekend.
