### ISSUE TITLE
Сhecksum of identical files

### ISSUE THREAD

**Issue by zamachuga** [EPPlusSoftware/EPPlus#351]
Checksum of identical files

I create two files considering: one template, one dataset, one filling algorithm.

The file size is the same, the checksum is different (Md5, Crc32, SHA256).

It turns out to be impossible to verify by the checksum that the two files are identical.
Some tools did not have this problem, which made it possible to create autotests. Is it somehow possible to create two files with the same checksum from one template?

**Comment by JanKallman** [comment]
No, the checksum will differ as the zip library sets for example timestamps to the package.

**Comment by zamachuga** [comment]
Very unpleasant.
