### ISSUE TITLE
Null reference when opening xlsx file which doesn't exists

### ISSUE THREAD

**Issue by slim16165** [EPPlusSoftware/EPPlus#357]
The path file should have been Downloads\filename. The backslash is missing so the Fileinfo doesn't find the file. But EPP doesn't check for it to exists and raise a very unspeaking error.

![image](https://user-images.githubusercontent.com/4086781/113859699-7ef02f00-97a5-11eb-964c-7d77baaf8e88.png)

**Comment by JanKallman** [comment]
Yes, this is by design. You can pass a non-existing FileInfo into the constructor and then use the Save method to create it.
