### ISSUE TITLE
Dependency on Microsoft.Extensions.Configuration.Json (>= 3.1.10) in .NETStandard 2.0

### ISSUE THREAD

**Issue by older** [EPPlusSoftware/EPPlus#362]
Asp.Net Core 2.1 is still supported by Microsoft (and will be supported for long time on .NET Framework), but [this dependency](https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/EPPlus.csproj#L277) on higher major/minor version of Microsoft.Extensions.* [makes it impossible](https://github.com/dotnet/extensions/issues/2799#issuecomment-568570096) to use EPPlus in Asp.Net Core 2.1 project.
Would it be possible to lower this dependency to 2.1.1 ?

**Comment by JanKallman** [comment]
Right, I have reverted it. Feel free to try it using our develop Nuget feed ... 
https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by older** [comment]
Seem to be fixed in 5.6.3
Thanks!
