### ISSUE TITLE
how to get cell backgroundcolor

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#364]
hi,I have a problem.

When I read the background color of cell [1,1] with the attachment test.xlms, 
I found that the background color of cell could not be read normally.

"Cells[1,1].Style.Fill.BackgroundColor.Rgb" 
RGB Why is empty?

Is there any other way to read the background color of the cell[1,1]?

thanks
![backgroundcolor](https://user-images.githubusercontent.com/19505572/114492388-1b557e00-9c4b-11eb-956b-492df193bcb1.png)

-----
EPPlus:5.3.2
[test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6301010/test.xlsx)

**Comment by JanKallman** [comment]
This is an indexed color(46). You can use the Color.LookupColor method to get the string rgb value.
