### ISSUE TITLE
Issues in scroll bar functionality

### ISSUE THREAD

**Issue by poornalingama** [EPPlusSoftware/EPPlus#369]
I tried to export 500 rows  in bar charts in Dotnet core ( C#)  but it shows the bars like dot like structure so i tried to add scroller for that bars but its not working.. Is this feature is available in epplus?

**Comment by JanKallman** [comment]
I am unsure exacly what you meen, but you can add scrollbars...
https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/8b1923c8534e919130e24b6a8eb3172fcd682925/26-FormControls/FormControlsSample.cs#L86
