### ISSUE TITLE
'The 'worksheet' start tag on line 2 position 2 does not match the end tag of 'formula'. Line 2, position 799.'

### ISSUE THREAD

**Issue by erikkipp** [EPPlusSoftware/EPPlus#372]
Problem is in 5.6.3, I do not have this issue with 5.5.0.  I am not seeing any xml issues if I unzip the file.

**Comment by JanKallman** [comment]
Can you attach a reproducable sample?

**Comment by JanKallman** [comment]
This should be fixed in version 5.7.0. Otherwise let me know and attach a reproducable sample.
