### ISSUE TITLE
Re-creating the RecyclableMemoryStreamManager if it was set via the SetRecyclableMemoryStreamManager () method

### ISSUE THREAD

**Issue by LIFEfreedom** [EPPlusSoftware/EPPlus#373]
Setting the **RecyclableMemoryStreamManager** via the **SetRecyclableMemoryStreamManager (RecyclableMemoryStreamManager recyclableMemoryStreamManager)** method does not set the **_dataInitialized** variable to _true_. This causes the **RecyclableMemoryStreamManager** to be re-created in the `LazyInitializer.EnsureInitialized (ref _memoryManager, ref _dataInitialized, ref _dataLock)` method;

**Comment by JanKallman** [comment]
Fixed in version 5.7.0
