### ISSUE TITLE
sheet.Cells: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MartinChen1973** [EPPlusSoftware/EPPlus#375]
I noticed that there were dozen of same issues, some of which had been "closed". But still in version 5.6.3 I encountered it again.
This is the code with the bug, and code with the bug "fixed". I thinks it's all about "using package" being disposed.
With bug:

        public IEnumerable<ExcelSheet> ExcelSheets { get; set; }

        public ExcelFile(string path, string templateName)
        {
            Path = path;
            _templateName = templateName;
            using var package = new ExcelPackage(new FileInfo(Path));
            using var jsonDocument = JsonDocument.Parse(File.ReadAllText(_templateName));
            ExcelSheets = package.Workbook.Worksheets.Select(sheet =>
                new ExcelSheet(jsonDocument, sheet)).ToList();
        }

        public string ToJson(int indent)
        {
            using var jsonDocument = JsonDocument.Parse(File.ReadAllText(_templateName));
            var offset = JsonText.IndentOf(indent);
            var jsonText = $"{offset}{{\r\n" +
                            string.Join($",\r\n",
                                ExcelSheets.Select(sheet => sheet.ToJson(indent + 1))) +
                           $"\r\n{offset}}}";

            File.WriteAllText(Path + JsonExt, jsonText);
            return jsonText;
        }

Fixed:

        public ExcelFile(string path, string templateName)
        {
            Path = path;
            _templateName = templateName;
        }

        public string ToJson(int indent)
        {
            using var package = new ExcelPackage(new FileInfo(Path));
            using var jsonDocument = JsonDocument.Parse(File.ReadAllText(_templateName));
            var offset = JsonText.IndentOf(indent);
            var jsonText = $"{offset}{{\r\n" +
                            string.Join($",\r\n",
                                package.Workbook.Worksheets.Select(sheet =>
                                    new ExcelSheet(jsonDocument, sheet).ToJson(indent + 1))) +
                           $"\r\n{offset}}}";

            File.WriteAllText(Path + JsonExt, jsonText);
            return jsonText;
        }

And somewhere in ExcelSheet.ToJson():

            if (sheet == null)
            {
                throw new Exception($"Sheet is null!{NameCell.CellName},{ValueCell.CellName}");
            }
            var cells = sheet.Cells;
            var name = cells[NameCell?.CellName]?.Text;
            var value = cells[ValueCell?.CellName]?.Text;

            return JsonText.IndentOf(indent) + 
                   $"\"{JsonText.Encode(name)}\"" + 
                   $":\"{JsonText.Encode(value)}\"";

with the two different code above, the "var cells = sheet.Cells" will / will not cause the bug.

**Comment by JanKallman** [comment]
Disposing the package will clear all cell stores and set them to null, causing this exception. 
When the package ojbect has been disposed it can no longer be used.

**Comment by MartinChen1973** [comment]
@JanKallman Yes. So I would say, there should be a clearer message like "Excel packages has been disposed when sheet.Cells[] is called." Rather than just an Object Null Exception.

**Comment by JanKallman** [comment]
@MartinChen1973 Yes, I see your point. We'll have a look at the handling of disposed packages and make sure to throw more understandable exceptions.

**Comment by JanKallman** [comment]
I will close this issue and move it to this one ... https://github.com/EPPlusSoftware/EPPlus/issues/378
