### ISSUE TITLE
AutoFit does not work correctly for some font sizes

### ISSUE THREAD

**Issue by arek98** [EPPlusSoftware/EPPlus#382]
There is a bug in ExcelWorkbook.cs, methond GetWidthPixels, line 619.
```C#
if (min == max)
{
	return Convert.ToDecimal(font[min].Width);
}
else
{
	return Convert.ToDecimal(font[min].Height + (font[max].Height - font[min].Height) * ((fontSize - min) / (max - min)));
}
```

When size is not found in retrieved list (in my case size 9 - list contains size 8 and 10) returned value is incorrect.
It is because Height is used instead of Width.

It should be 
```C#
return Convert.ToDecimal(font[min].Width + (font[max].Width - font[min].Width) * ((fontSize - min) / (max - min)));
```

AutoFit still seems to be bit off but it is much closer, with this bug it is always not expanded enough since height is typically much larger then width.

**Comment by JanKallman** [comment]
Thanks, I'll provide a fix
