### ISSUE TITLE
AutoFitColumns is device DPI dependent

### ISSUE THREAD

**Issue by CaringDev** [EPPlusSoftware/EPPlus#384]
# Update, TL;DR;

[Graphics.MeasureString](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.measurestring?view=net-5.0) used [here](https://github.com/EPPlusSoftware/EPPlus/blob/861926c1f9afb0ac91853aa5f8abf2e52df322b6/src/EPPlus/ExcelRangeBase.cs#L898) is device DPI dependent while `AutoFitColumns` should assume 96 ppi. The fix would be to scale the measurement (see e.g. [this SO post](https://stackoverflow.com/questions/33826883/measurestring-gives-different-size-for-different-screen-resolutions)).

# History

`AutoFitColumns` in the following code is dependent on whether we create a WPF window first (because that initializes device DPI awareness). I expected EPPlus to auto fit columns 'properly' regardless of "global state". Is there a known workaround? 

Env: EPPlus 5.6.3, dotnet core 5 (SDK: 5.0.202), Windows 10 20H2

```csharp
using System;
using System.IO;
using System.Windows;
using OfficeOpenXml;

namespace EPP.Test
{
  public class Program
  {
    [STAThread]
    public static void Main(string[] args)
    {
      ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

      // This is the culprit
      // new Window();

      using var package = new ExcelPackage(new MemoryStream());
      var sheet = package.Workbook.Worksheets.Add("Foo");
      sheet.Cells[1, 1].Value = "Some longer random string";
      sheet.Cells.AutoFitColumns();

      // normal: 25.29 (fits perfectly)
      // with new Window: 37.57 (too large)
      var resizedWidth = sheet.Column(1).Width;
    }
  }
}
```

**Comment by JanKallman** [comment]
Running this code in a wpf app using .NET 5 seems to work fine, so I am unsure how you are setup.
Can you zip your test project and attach it here?

**Comment by CaringDev** [comment]
Wow, this is crazy... I created [a repro](https://github.com/CaringDev/EPP.Test) that [does not repro](https://github.com/CaringDev/EPP.Test/runs/2512188031?check_suite_focus=true#step:3:51)... but does on my machine:

![image](https://user-images.githubusercontent.com/421982/117194945-fe910e00-ade4-11eb-8922-8d754c059d71.png)

I will have to investigate further (how 😬)...

Thanks for the great librarz and zour quick reponse ❤

**Comment by CaringDev** [comment]
Ah, found something: I'm on a high resolution monitor and have set DPI-Scaling to 150%. If changed back like so:
![image](https://user-images.githubusercontent.com/421982/117196263-904d4b00-ade6-11eb-8a43-0255ee64bdc0.png)
everything is back to 👌

**Comment by CaringDev** [comment]
For now I'm resorting to `[assembly: DisableDpiAwareness]`... however, changing AutoFit to be DPI independent would probably be great (as otherwise apps using EPPlus' AutoFitColumn look rather ugly on high DPI screens).
The culprit is, that [Graphics.MeasureString](https://github.com/EPPlusSoftware/EPPlus/blob/861926c1f9afb0ac91853aa5f8abf2e52df322b6/src/EPPlus/ExcelRangeBase.cs#L898) is device dependent when for the column width we should assume 96 ppi. Would you consider merging a corresponding PR (see [this SO post](https://stackoverflow.com/questions/33826883/measurestring-gives-different-size-for-different-screen-resolutions))?

**Comment by JanKallman** [comment]
Thanks for the update. Sounds correct that 96 dpi should be assumed. I will look into it.

**Comment by JanKallman** [comment]
I could reproduce the issue and I have added a fix. You can try it using our develop Nuget feed...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by CaringDev** [comment]
Thanks, 5.6.3.603-20210506-develop works for me too 👌
