### ISSUE TITLE
Collapse pivot table row fields by default?

### ISSUE THREAD

**Issue by mwhite34** [EPPlusSoftware/EPPlus#385]
It's possible to do this through workbook VBA as described here, (https://stackoverflow.com/questions/12846334/epplus-pivot-table-collapse-entire-field) but that has its drawbacks.

Ideally, I would like to do this without a macro. Is there a way to do this through EPPlus that I am missing?

**Comment by JanKallman** [comment]
Yes, from EPPlus version 5.6 you can use the `ShowDetails` method on the Row or Column items...
Note that you need to refresh the items before calling this method...
```C#
pivotTable.RowFields[0].Items.Refresh();
pivotTable.RowFields[0].Items.ShowDetails(false);
//...or use on a single item to collapse that item...
pivotTable.RowFields[0].Items[0].ShowDetails = false;
```

**Comment by mwhite34** [comment]
Great, thank you! I will look into updating for this feature!
