### ISSUE TITLE
Row cannot be less than 1. Parameter name: value

### ISSUE THREAD

**Issue by samer1977** [EPPlusSoftware/EPPlus#39]
I have an excel that has some formatting (merged cells, formulas...etc.). You can find a copy of this excel attached. Im restricted with this format as its provided by the client and cannot be changed. Im using the EPPlus (version 4.5.3.3) to populate rows starting from row 8 but Im trying to use the worksheet.InsertRow(8,recordCounter,8) to create a new row for each inserted record and copy all styles as well from the first row, however I keep getting the following exception: 
Row cannot be less than 1. Parameter name: value
[MyExcel.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4237770/MyExcel.xlsx)

**Comment by JanKallman** [comment]
This issue is for all I can see solved in EPPlus 5. The entire cell store has been rewritten.
I noticed a problem with the copying of styles, but it has been fixed in the latest build...
https://ci.appveyor.com/project/EPPlusSoftware/epplus/build/artifacts

**Comment by JanKallman** [comment]
Solved in EPPlus5
