### ISSUE TITLE
InsertColumn does not copy style properly

### ISSUE THREAD

**Issue by jN7** [EPPlusSoftware/EPPlus#392]
I want to insert a new column in an already existing Excel file, only the style of the first cell gets copied.

I also found out during my investigation that there were already similar issues: https://epplus4.rssing.com/chan-7547932/all_p76.html

Also, there seems to be a bug for InsertRows: https://github.com/JanKallman/EPPlus/issues/288

Is there any known bug for the InsertColumn function? 

My code looks as follows:

            FileInfo newFile = new FileInfo(outputName);
            ExcelPackage excel = new ExcelPackage(newFile);
            ExcelWorkbook wb = excel.Workbook;
            ExcelWorksheet y = wb.Worksheets.First();
            y.InsertColumn(1, 1, 2); 
            y.Cells[1, 1].Value = "Test1";
            y.Cells[2, 1].Value = "Test2";
            y.Cells[3, 1].Value = "Test3";

Expected result:
![Snag_a7a3821](https://user-images.githubusercontent.com/18484480/117933456-e009a600-b301-11eb-93d6-ccb01e3cdb41.png)

Actual result:
![Snag_a7a1d37](https://user-images.githubusercontent.com/18484480/117933442-dc761f00-b301-11eb-9660-06e4b22bebe2.png)

**Comment by JanKallman** [comment]
Seems to work when I try it. Is this in version 5.6.3? If so, can you attach your workbook so I can reproduce the issue?

**Comment by jN7** [comment]
Hi Jan,

thanks for your reply, please find attached the Workbook I am using.

[template.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6465359/template.xlsx)

**Comment by jN7** [comment]
The issue was that I was using a Table which started from column B. When adding an additional column, the table was not expanded to the new range. By changing back the table to a normal range, everything is working as expected and the style is copied.
