### ISSUE TITLE
Excel file gets corrupted on saving with specific defined names

### ISSUE THREAD

**Issue by akashkarov** [EPPlusSoftware/EPPlus#395]
When opening and saving ExcelPackage with the following format of defined name's reference, the Excel file is treated as corrupted, and such defined names are removed on repair.

='\\test.sharepoint.com@SSL\1\2\[file.xlsm]Something'!$A$1

**Comment by akashkarov** [comment]
[DefinedNamesTest.zip](https://github.com/EPPlusSoftware/EPPlus/files/6510925/DefinedNamesTest.zip)
Please see attached test project reproducing this issue with sample file.

**Comment by JanKallman** [comment]
Thanks for reporting this. This will be solved in EPPlus 5.7, which will add support for working with external links.
We hope the release will be within in a week or two.

**Comment by vkirienko** [comment]
Data from external link in the sample file is not used anywhere in provided Excel. So seems like issue is not exactly about external links but about defined names that point to external file. I'm just trying to make sure we correctly identify problem there and 5.7 will indeed fix this issue.

**Comment by JanKallman** [comment]
I'm working on it now, so it's work in progress. You can try it if you want to from the branch in PR #371

**Comment by JanKallman** [comment]
Hopefully fixed in version 5.7.0. If you still have problem, please re-open this issue.

**Comment by akashkarov** [comment]
@JanKallman Issue is still reproducible with the test project attached for v5.7.0. Please reopen it.

**Comment by JanKallman** [comment]
Ok, we'll have another look at this

**Comment by JanKallman** [comment]
Fixed in version 5.7.1
