### ISSUE TITLE
Collapse/Expand Group levels in Pivot configuration

### ISSUE THREAD

**Issue by igigiberia** [EPPlusSoftware/EPPlus#396]
Hello,

I can't seem to find an option to collapse/expand group levels in pivot configuration, could you please help with guidance?

**Comment by igigiberia** [comment]
Here's an example of expanded groups that are created from the software that is using only epplus library for generating excel. I couldn't find a way to collapse it programmatically.
[EmsIsufNoTakinRep_202105041843_EmsIsufNoTakin.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6535087/EmsIsufNoTakinRep_202105041843_EmsIsufNoTakin.xlsx)

**Comment by JanKallman** [comment]
Hello, you can do this with EPPlus today...
To collapse a column field (or a row field), you can do like this...
```C#
//First you need to refresh the items, the you can set the ShowDetails flag for all items or on an individual item.
pivotTable.ColumnFields[0].Items.Refresh();
pivotTable.ColumnFields[0].Items.ShowDetails(false);
//...or...
pivotTable.ColumnFields[0].Items[0].ShowDetails = false;
```
I'll try to provide a sample in our wiki shortly

**Comment by JanKallman** [comment]
Wiki changes ...https://github.com/EPPlusSoftware/EPPlus/wiki/Expanding-and-collapsing-Pivot-Table-items
