### ISSUE TITLE
Failed to read big excel file

### ISSUE THREAD

**Issue by yuzhangyi** [EPPlusSoftware/EPPlus#400]
Hi, everyone,

      When I try to use EPPlus (Version: 5.2.1) to read one big excel file (1GB) with “debug, x64”, too much memory is consumed and impact other process execution. Could you give some guidance to work around or solve this issue?
       
![image](https://user-images.githubusercontent.com/44692931/119952036-2aac4300-bfcf-11eb-849a-0330ff4419e0.png)

Thanks!

**Comment by JanKallman** [comment]
Hello,
A 1GB xlsx file is a huge document. Depending on what your file contains it will consume a lot of memory. If the package contains mostly worksheet cell data, each sheet XML document within the file will likley be huge. 
You can rename the xlsx file to *.zip and check the size of the \xl\worksheets\sheetX.xml files to verify the size of the package.

**Comment by yuzhangyi** [comment]
> Hello,
> A 1GB xlsx file is a huge document. Depending on what your file contains it will consume a lot of memory. If the package contains mostly worksheet cell data, each sheet XML document within the file will likley be huge.
> You can rename the xlsx file to *.zip and check the size of the \xl\worksheets\sheetX.xml files to verify the size of the package.

Thanks for your information, @JanKallman , do we have some plan/improvement to reduce the memory usage?

**Comment by JanKallman** [comment]
Without knowing exactly how much cell data you have in the file, I would say 1GB compressed xml is to much data for EPPlus (and Excel) to load smoothly. Storing the data in a database and read parts of it/aggregate it is probably a better solution, if possible.
