### ISSUE TITLE
Some Formula Calculation not working

### ISSUE THREAD

**Issue by shishir28** [EPPlusSoftware/EPPlus#405]
Hi,
 I have an excel file that has a model to calculate Shelf Life for a meat product.  I am playing with an excel file using my C# code.  I have been dumping raw temperature data in the input cell of the excel file and save it. 
I have been setting the formula for some cells in my code. 
a) When I open the excel file saved my C# code in windows explorer, all formula values are calculated correctly. 
b) When I try to read the value of cell after setting the formula , I get #VALUE! for some cases . 

![image](https://user-images.githubusercontent.com/332619/120203096-ae359080-c26a-11eb-9018-c7bedc6c3c2a.png)

  var prevIndex = startRowIndex - 1;
                    currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_NEW_INDEX].Formula = $"IF(J{prevIndex}=\"\",\"\",IF(J{prevIndex}+1>$H$8/$H$13,\"\",J{prevIndex}+1))";
                    currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_NEW_INDEX].Calculate();

// I get value from  currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_NEW_INDEX].Value 

//- ----
                    //=IF(J8="","",OFFSET($D$7,$H$13* ($J8-1),0))
                    var currentForumla = $"IF(J{startRowIndex}=\"\",\"\",OFFSET($D${startRowIndex},$H$13* ($J{startRowIndex}-1),0))";

                    currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_DATE_TIME].Formula = currentForumla;
                    currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_DATE_TIME].Calculate(opt);
 // I get #VALUE! here currentWorksheet.Cells[startRowIndex, TemperatureLogColumnIndex.TIME_TEMP_DATE_TIME].Value 
               
I was wondering what do I need to fix here? 

Thanks 
Shishir

**Comment by swmal** [comment]
Could you try logging the error? Often when you get a #VALUE error there is an underlying Exception somewhere. See these instructions: https://github.com/EPPlusSoftware/EPPlus/wiki/Formula-Calculation#trouble-shootinglogging

Based on your description and the screenshot you have provided it could be that the OFFSET function call is the culprit here. Maybe you could try to run only that function call in the same cell and see if you still got a #VALUE error.

**Comment by shishir28** [comment]
Thanks, swmal. Indeed the problem was with the formula OFFSET. Where I had a problem with the excel formula, I wrote equivalent code in C# and moved ahead. 

Excel Logging suggested by you was helpful in finding the problem. 
Thanks again.
