### ISSUE TITLE
Copying a worksheet to a new workbook doesn't correctly copy named styles

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#407]
I've found a couple of bugs (which I believe are related to each other) regarding the copying of worksheets that have named styles:

### 1. Exception thrown on sheet copy when workbook has more `cellStyleXfs`

When copying a sheet from a workbook that has more "named styles" (`cellStyleXfs`) than "cell formats" (`cellXfs`), an `ArgumentOutOfRangeException` is thrown on [ExcelStyle.cs line 250.
](https://github.com/EPPlusSoftware/EPPlus/blob/9f92c65d3250d32a1c5cd8fc8ad84e7cf2c2eef8/src/EPPlus/Style/ExcelStyle.cs#L250)
To reproduce, download this file: [TestStyles_MoreCellStyleXfsThanCellXfs.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6594020/TestStyles_MoreCellStyleXfsThanCellXfs.xlsx), and use EPPlus to copy the `StylesTestSheet` into a new workbook. You should find it throws an exception.

A bit of background: I've had this workbook for a very long time and it seems to have built up a number of "named styles" that aren't actually used. I'm not sure how that happened - even cutting it down to one very simple sheet didn't delete the styles. But it must be a valid state for a workbook as I haven't done anything unusual to it.

But this got me to thinking, what about the more common case where there are fewer `cellStyleXfs` records than `cellXfs` records? Well...

### 2. Named styles copied incorrectly when workbook has fewer `cellStyleXfs`

To reproduce, download this file: [TestStyles_MinimalWithNamedStyles.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6594022/TestStyles_MinimalWithNamedStyles.xlsx), and again use EPPlus to copy the `StylesTestSheet` into a new workbook. 
  
The `TestStyles_MinimalWithNamedStyles.xlsx` is a new workbook that I've added some named styles to using Excel.
  
This time you will be able to copy the `StylesTestSheet` to a new workbook without any exceptions being thrown. But if you save this new workbook and open it in Excel, you'll see some differences when you compare against the original. 
  
The cells themselves look the same but if you look in the Styles section of the ribbon, you'll see the named styles have been changed.

This image should make it clear what the issue is:

![epplusbug1](https://user-images.githubusercontent.com/8934235/120703948-dcef7900-c4ad-11eb-99ac-caf42a5c32d3.png)

Having had a quick look at the code, I think that the line 250 I mentioned above might be using the wrong dictionary to lookup the style. Or maybe it doesn't need a dictionary lookup at all and can just return the `Index`. Not sure, but hopefully that is somewhat helpful as a starting point. Thanks.

---
**Attachments**
[TestStyles_MoreCellStyleXfsThanCellXfs.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6594020/TestStyles_MoreCellStyleXfsThanCellXfs.xlsx)
[TestStyles_MinimalWithNamedStyles.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6594022/TestStyles_MinimalWithNamedStyles.xlsx)

**Comment by JanKallman** [comment]
Thanks, I'll have a look at this.

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.7.0
