### ISSUE TITLE
Worksheet position out of range

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#415]
Hello,

We have a workbook that throws an Exception "Worksheet position out of range" when we attempt to read it with EPPlus.   Stacktrace below:

   at OfficeOpenXml.ExcelWorksheets.get_Item(Int32 PositionID)
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()

**Comment by rdhasse** [comment]
Attached workbook with the issue.

[workbook_with_issue.zip](https://github.com/EPPlusSoftware/EPPlus/files/6657708/workbook_with_issue.zip)

**Comment by JanKallman** [comment]
Hello,
This happens when you have a worksheet with no relation to a sheet.xml file. In this case the first worksheet is veryHidden and has no relation. These worksheets were ignored by EPPlus, causing the references to sheets to become invalid. I will apply  a fix in version 5.7 released today.

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.7.0
