### ISSUE TITLE
Format with "null" displays as "0"

### ISSUE THREAD

**Issue by vivet** [EPPlusSoftware/EPPlus#417]
The two cells in the attached file are filled out (A1 and A2). There are zero values in both, but A2 is formatted with a “null” formatstring for zeros, meaning that zeros will be displayed as nothing. In EPplus, there is a “real” value and a presentation value where the presentation value would normally always be the same as we see with our eyes – but in this case, both values are “0/0”. They should correctly be “0/null”

[20210617 EPplus test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6674944/20210617.EPplus.test.xlsx)

**Comment by JanKallman** [comment]
Yes, correct. .NET --> double.ToString("") return 0 with differs from Excel.
I'll provide a fix.

**Comment by JanKallman** [comment]
Fixed in version 5.7.1
