### ISSUE TITLE
Azure Information Protection and EPPlus

### ISSUE THREAD

**Issue by SebHonorine** [EPPlusSoftware/EPPlus#419]
Howdy there,

Trying to figure out if EpPLus is ok to open/work with AIP filed excels files. Can't find the answer. 

Thank you

**Comment by JanKallman** [comment]
Hello,
I haven't tried. What are the requirements? EPPlus supports reading and writing encrypted workbooks (both the standard encryption and the newer agile encryption). Workbook/worksheet protection is also supported. 
Are there any other specific requirements needed?

**Comment by SebHonorine** [comment]
I don't really know the requirements or if it works already. I did not try myself, but doing the research and did not find the answer. So I came here.

**Comment by JanKallman** [comment]
Ok, I'm not 100% sure, but I see no reason why it should not work, unless AIP has specific requirements (like if AIP uses the strict OOXML format not supported by EPPlus).
