### ISSUE TITLE
ExcelPackage.Save method is very slow on big datasets

### ISSUE THREAD

**Issue by thetilliwilli** [EPPlusSoftware/EPPlus#424]
Description: 

1. I should export dataset (1 millions of rows X 100 columns) to excel (xlsx) in limited timeframe.
2. EPPlus version 5.6.4

Problem: Right now **ExcelPackage.Save method takes 240 secs** on dataset ( 500k rows X 100 cols, where each cell is just number). 240 seconds is very slow and i can't fit it into time budget i have in my application.

The question: How can I reduce the time of saving? How can I achieve the best results?

![image](https://user-images.githubusercontent.com/25109940/123980788-7dac5800-d9ca-11eb-85cf-65ab7e58ad34.png)

code:

```csharp
static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            var rowCount = 500000;
            var colCount = 100;
            File.Delete("./book1.xlsx");
            using (var package = new ExcelPackage(new FileInfo("./book1.xlsx")))
            {
                var sheet = package.Workbook.Worksheets.Add("Sheet1");
                for (var row = 1; row < rowCount; ++row)
                    for (var col = 1; col < colCount; ++col)
                        sheet.SetValue(row, col, row);
                var start = DateTime.Now;
                package.Save();
                var end = DateTime.Now;
                Console.WriteLine($"Duration, sec: {(end - start).TotalSeconds}");
            }

            Console.WriteLine("Press any key");
            Console.ReadKey();
        }
```

**Comment by JanKallman** [comment]
240s sounds like a reasonble fast time on a huge dataset like that. You can try if more memory in your production machine helps (and of course use x64 ). A huge file like that is probably not optimal to use Excel for, as it will likley load/run pretty slow.

**Comment by thetilliwilli** [comment]
@JanKallman thank you for reply!!!

I have tried all the suggestions: the sample application doesn't use whole available memory - my machine has plenty of RAM 32 GB. My OS is x64 and application built in Release. So it doesn't look for me as memory problem.

I have done perf test with Microsoft Office Excel app - it saves 1M rows X 100 cols = 75 sec
Epplus does saving (1M rows x 100 cols) = 384 sec.

I'm not trying to compare, just trying to get maximum using Epplus 😄 - do you know any ways to achieve the results of MsExcelApp (75 sec)?

**Comment by JanKallman** [comment]
Not with EPPlus, but creating a csv file will be a lot faster, but you will not be able to format/add formulas etc to your data.
