### ISSUE TITLE
Calculations not working when file format is Strict XML.

### ISSUE THREAD

**Issue by yujinmyford** [EPPlusSoftware/EPPlus#425]
Hi,

We are having an issue where calculations do not work when the file format is Strict Open XML instead of standard xlsx files.
We were wondering if Strict Open XML format is supported?

Thank you.

**Comment by JanKallman** [comment]
Hello,
No, the strict format is not currently supported. It's on the todo list, but not planed in any coming version. This issue is the same as #307, so I'll close this one.
