### ISSUE TITLE
Adding rows to a Table, WorkSheet doesn't  Update Formula References in ExcelConditionalFormattingRule

### ISSUE THREAD

**Issue by hiephm3a** [EPPlusSoftware/EPPlus#426]
If i have a ExcelConditionalFormattingRule with rule "Use formula to determine which cells to format", When i add new row to worksheet the apply address of ExcelConditionalFormattingRule  auto shift to new address but address in formula don't update to new address of cell.

**Comment by JanKallman** [comment]
Hmm, no, we don't update formulas for conditional formatting (or data validation). I'll have a look at that and add it for a coming version.

**Comment by JanKallman** [comment]
This is now handled in EPPlus 7 for Conditional Formatting and Data Validation
