### ISSUE TITLE
Opening workbook with specific defined name throws NullReference exception

### ISSUE THREAD

**Issue by akashkarov** [EPPlusSoftware/EPPlus#430]
Please see attached test project. Calling package.Workbook property throws NullReference exception because of the defined name.

[DefinedNamesTest.zip](https://github.com/EPPlusSoftware/EPPlus/files/6802151/DefinedNamesTest.zip)

**Comment by JanKallman** [comment]
Added a fix for this. The formula in the defined name has a prefix of new and then an external address, which was incorrecly identified as an internal address.

**Comment by vkirienko** [comment]
Would be it possible to to have new NuGet package with that fix in next few days so we can deploy it on our end?

**Comment by JanKallman** [comment]
You can use our devlop build, if it's urgent, as this is the only change ... 
https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed
Direct dowload https://ci.appveyor.com/project/EPPlusSoftware/epplus/build/artifacts

**Comment by akashkarov** [comment]
I checked EPPlus.5.7.1.689-20210714-develop and the issue is fixed. Thank you.
Will it go to the next release and when is it planned to happen?

**Comment by akashkarov** [comment]
Fixed in 5.7.2
