### ISSUE TITLE
Chart only shows when opening Excel file and 'validating' cell

### ISSUE THREAD

**Issue by lievencardoen** [EPPlusSoftware/EPPlus#432]
Not sure how to explain this correctly.

We've created an Excel with EPP version 4.5. When opening the Excel file the values and the chart are shown, but the chart is empty. Meaning that it's like the data behind the series is empty (but it's not).

When we double click on the cell that contains the data and press return, the chart now does show correctly.

Screencast probably clears things out.

https://user-images.githubusercontent.com/158455/125461775-54c789d5-a2ae-4745-9fb5-d09ce942aa08.mp4

**Comment by JanKallman** [comment]
We no longer maintain EPPlus with versions below 5. Please verify if it works in version 5.7.1.

**Comment by lievencardoen** [comment]
Tried with version 5.7.1 and seeing the same issue. 

Any idea what could be causing this?

**Comment by JanKallman** [comment]
Try to create the num cache and see if it helps...
`chrt.Series[0].CreateCache();`
Otherwise please attach a reproducible sample.

**Comment by LievenDeFoor** [comment]
There does not seem to be a CreateCache() method on ExcelChartSerie, even though the documentation states it...
What are we doing wrong?

**Comment by JanKallman** [comment]
No its part of ExcelChartStandardSerie ... https://github.com/EPPlusSoftware/EPPlus/blob/f12d97e541d69c1b1b6841c89d6e37e3f46f9ca7/src/EPPlus/Drawing/Chart/ExcelChartStandardSerie.cs#L422
It's not available for extended charts.

**Comment by LievenDeFoor** [comment]
It appears this was caused by the cells values being set a string instead of a numerical value...
This issue can be closed.
