### ISSUE TITLE
Error in images with external reference

### ISSUE THREAD

**Issue by simoselva** [EPPlusSoftware/EPPlus#435]
Hello everyone,

there is an issue when you try to save a file where in some sheets there is an image with a reference to an unreachable uri.
The Drawing property of the worksheet is not being loaded properly and this cause an issue when it tries to save the sheet.

My debugger tells me that the error is here:

OfficeOpenXml.Packaging.ZipPackage.GetPart(Uri partUri)

Regards,
Simone

**Comment by JanKallman** [comment]
Can you provide the workbook with this error1?

**Comment by simoselva** [comment]
[Test1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/6822058/Test1.xlsx)

Here the file, feel free to ask if you want more details.

Regards,
Simone

**Comment by JanKallman** [comment]
This should be fixed in latest develop. Feel free to test using our latest develop build... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by simoselva** [comment]
Many thanks for the quick support, now it's working fine.
