### ISSUE TITLE
NullReferenceException opening xlsm

### ISSUE THREAD

**Issue by azumalabe** [EPPlusSoftware/EPPlus#436]
Using the following code, epk object return NullReferenceException in epk.Workbook.CodeModule and epk.Workbook.VbaProject with the attached xlsm file(PlantillaDefectivo-NotWorking.zip). If I open and save de xlsm file with an old versión of MicrosoftExcel then it works fine(PlantillaDefectivo-Working.zip).

`string excelSourceFile = string.Format(RM.InvariantCulture, "{0}\\Reports\\ReportsExcelTemplate\\{1}", System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath, excelTemplate);`
`template = new FileInfo(excelSourceFile);`
`using (ExcelPackage epk =new ExcelPackage(template))`

[PlantillaDefectivo-NotWorking.zip](https://github.com/EPPlusSoftware/EPPlus/files/6823010/PlantillaDefectivo-NotWorking.zip)
[PlantillaDefectivo-Working.zip](https://github.com/EPPlusSoftware/EPPlus/files/6823015/PlantillaDefectivo-Working.zip)

**Comment by JanKallman** [comment]
The "dir" stream contained the unhandled value 0x4a, that corrupted the reading of the stream

**Comment by azumalabe** [comment]
Thanks for the quick response. ¿How can I fix that in the .xlsm file?

**Comment by azumalabe** [comment]
¿Could it be because there are empty modules in the Macro?

**Comment by JanKallman** [comment]
This should be fixed in latest the latest develop build. Feel free to test... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by azumalabe** [comment]
I have tested it and it works perfectly, thank you.

**Comment by JanKallman** [comment]
Fixed in version 5.7.2
