### ISSUE TITLE
Feature Request: Ability to remove a serie from the legend

### ISSUE THREAD

**Issue by kchristman54** [EPPlusSoftware/EPPlus#438]
We are auto-generating charts, and would like to have a chart with multiple series in it, where only *some* of those series are on the legend.

In Excel, you can easily do this by simply right-clicking on a particular serie's name in the legend, and deleting it. 
![image](https://user-images.githubusercontent.com/33758481/125843061-6ec69f40-def3-4ed4-b16f-2bc2e556a691.png)

In looking at the difference in the XML before and after doing that, the only difference is the `legendEntry` XML entry. 
![image](https://user-images.githubusercontent.com/33758481/125843210-2fb10c1e-6d84-4f10-b079-e4c500d95bee.png)

Thanks for considering this, we love EPPlus at Energy Systems Lab at Texas A&M University.

**Comment by JanKallman** [comment]
Thanks for the input. We'll add this to our to-do list.
