### ISSUE TITLE
TableStyle not Appling After Cells Merging

### ISSUE THREAD

**Issue by yeganehaym** [EPPlusSoftware/EPPlus#439]
first i set table style then i merged some cells but after merge style not applying

without merges styles applying.

the code

```
workBook.Worksheets[0].Tables[0].TableStyle = TableStyles.Light9;
workBook.Worksheets[0].Cells[startRow,1,endRow,1].Merge = true;
```

**Comment by JanKallman** [comment]
You can't merge cells in a table or a part of a table. I will add a check for it.
Add merged cells outside of the table seems to work correcly for all I can see.

**Comment by JanKallman** [comment]
Validation added in EPPlus 5.7.3
