### ISSUE TITLE
Readme.md for EPPlus.Sample.NetFramework Titled Incorrectly

### ISSUE THREAD

**Issue by SAMease** [EPPlusSoftware/EPPlus#452]
This is nothing more than a clerical error I noticed as I was attempting to learn the ropes of EPPlus. 
It seems the .Net Core Readme.md was used as a template and this minor correction was not made. 
It is simply a place of confusion for new users like myself.

![image](https://user-images.githubusercontent.com/87878458/128767034-edb45545-9678-4f06-81b7-70466cd07e4b.png)

**Comment by JanKallman** [comment]
Sorry about that and thanks for reporting it. I have restored the to readme.md to reflect .NET framework again.

**Comment by SAMease** [comment]
No problem at all. Thank you for correcting it so quickly, and thank you for all your hard work on this great project!
