### ISSUE TITLE
How can I trigger macros automatically

### ISSUE THREAD

**Issue by ztmsimon** [EPPlusSoftware/EPPlus#460]
when I used EXCEL Com component of Office--"Microsoft.office.interop.excel",it can trigger macros automatically , but not when I used EPPlus.
Can you tell me how to deal with it?
Do you have any plans to do this feature? @JanKallman

**Comment by JanKallman** [comment]
You can not execute marcos in EPPlus. You will need Excel for that. We have no plans to implement VBA execution at this point. It would be both complex to implement and questionable securitywise.
