### ISSUE TITLE
Can't loop through cells in a range

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#472]
I have a range of several rows and columns. If I want to loop through the range to e.g. set the value of the cell in the first column of each row, I might try to do something like this:

```csharp
var rng = wks.Cells["B2:E7"];
for (var i = 0; i < rng.Rows; i++)
{
    var cell = rng[i + 1, 1];
    cell.Value = i;
}
```

However, as soon as I use the indexer `[]`, the `rng` object has changed to refer to cell `A1`. The indexer also doesn't return what I thought it would - `rng[1,1]` returns the first cell of the worksheet rather than the first of the range.

If I use `foreach` instead to loop through the cells, this doesn't work at all. The enumerator doesn't return any cells, so it just skips over the foreach. 

Not sure if this is how it's supposed to behave. But here's how I expected it to work:
```csharp
[TestMethod]
public void AccessCellInRange()
{
    using (var pck = new ExcelPackage())
    {
        // Create a worksheet
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        
        // Get a range
        var rng = wks.Cells["B3:D5"];
        
        // Check the address property of the range
        Assert.AreEqual("B3:D5", rng.LocalAddress);
        
        // Get the first item of the range
        var cell = rng[1, 1];
        
        // Check the address property of the range again
        Assert.AreEqual("B3:D5", rng.LocalAddress);
        
        // Check the address of the cell
        Assert.AreEqual("B3", cell.LocalAddress);
    }
}

[TestMethod]
public void TestForeachChecksEveryCellInRange()
{
    using (var pck = new ExcelPackage())
    {
        // Create a worksheet
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        
        // Get a range
        var rng = wks.Cells["B3:D5"];
        
        // Check the number of cells in the range
        Assert.AreEqual(9, rng.Rows * rng.Columns);
        
        // Loop through each cell in the range
        var i = 0;
        foreach (var c in rng)
        {
            var a = c.Address;
            i++;
        }
        // Check that all 9 cells were looped through
        Assert.AreEqual(9, i);
    }
}
```

**Comment by JanKallman** [comment]
This is by design. foreach iterates over existing cells (cells that have a value or a style etc). If you want to iterate all cells use a normal for loop with a row and column index.

**Comment by craigbrown** [comment]
But if I use a normal for loop, and try to access cells in the range by using the indexer, e.g. `rng[i, 1]`, the range object changes. Is that also by design?

**Comment by JanKallman** [comment]
The indexer for the range is not relative to the range. It refers to the absolute row and column within the worksheet. 
You can use the `Offset` method to get cells referencing from the top-left cell of the range. 
If you want to set values, you can do something like this:
```C#
using (var pck = new ExcelPackage())
    {
        // Create a worksheet
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        
        for(int row=2;row<7;row++)
        {
          for(int col=2;col<=5;col++)
          {
              wsk.SetValue(row,col,value);
              //Or
              //wsk.Cells[row,col].Value = value;
          }
        }
    }
```

**Comment by craigbrown** [comment]
OK. Thanks for clarifying.
