### ISSUE TITLE
Range object's address is not updated after inserting cells

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#473]
If I have a range that refers to `B3`, and then I insert cells, I expect that the range is updated to either `C3` (if shifting right) or `B4` (if shifting down). But the range object just stays pointing at `B3`. 

Is that expected behaviour? It's different to how it works in VBA/Interop so just wanted to check whether this was intentional.

```csharp
[TestMethod]
public void CheckRangeAddressAfterInsertingCells()
{
    using (var pck = new ExcelPackage())
    {
        // Create a worksheet
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        
        // Get a range
        var rng = wks.Cells["B3:B5"];
        Assert.AreEqual("B3:B5", rng.LocalAddress);
        
        // Insert cells to the left
        rng.Insert(eShiftTypeInsert.Right);
        
        // Check the range has shifted right
        Assert.AreEqual("C3:C5", rng.LocalAddress);
    }
}
```

**Comment by JanKallman** [comment]
No, the range is no updated when inserting or deleting in a range. As this is the current behavior we can't really change it, but we will look at returning the inserted/deleted range from the methods instead, as they are of declared void as of today.
For example:
```C#
[TestMethod]
public void CheckRangeAddressAfterInsertingCells()
{
    using (var pck = new ExcelPackage())
    {
        // Create a worksheet
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        
        // Get a range
        var rng = wks.Cells["B3:B5"];
        Assert.AreEqual("B3:B5", rng.LocalAddress);
        
        // Insert cells to the left
        var insertedRng = rng.Insert(eShiftTypeInsert.Right);
        
        // Check the range has shifted right
        Assert.AreEqual("C3:C5", insertedRng.LocalAddress);
    }
}
```

**Comment by craigbrown** [comment]
OK - that wouldn't technically be the inserted range that you're returning though. The `rng` object currently automatically becomes the inserted range, and you'd be returning the range that `rng` was previously pointing to.

It would make more sense for the inserted range to be returned and `rng` to continue pointing to the same cells which have been shifted right. But if that's too much of a breaking change this is an ok compromise, although some might find it confusing.

**Comment by SebastianCramer** [comment]
Same effect applies when defining a ExcelNamedRange and then inserting a full row before that using `sheet.InsertRow()`.
The Address Attribute of the range gets updated to the original Row +1. Start and End Attributes of the Range are not.

This is a breaking change compared to v5.6.4 which I used previously.

**Comment by SebastianCramer** [comment]
Is there any ETA on this?

**Comment by AdrianEPPlus** [comment]
This issue is fixed and will be in a  newer version. Insert will have a return value and work according to @JanKallman suggestion.

@SebastianCramer This seems like a separate issue. If this is still a problem, please create a new issue with a description.
