### ISSUE TITLE
circular reference in cell Q71

### ISSUE THREAD

**Issue by robertovaldesperez** [EPPlusSoftware/EPPlus#475]
Epplus version: 5.7.3

When I read the file and try to calculate the existing formulas in it, it throws me a circular reference error in cell Q71 of the "Avances" sheet. It is strange because if I open it with microsoft excel and click on trace errors in the sheet it does not show any error.

Can you help me?

Thanks a lot

[Data_Agregado_Clikalia-v6 (1).xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7089304/Data_Agregado_Clikalia-v6.1.xlsx)

**Comment by JanKallman** [comment]
EPPlus checks for circular references on addresses in the creation of the dependency chain for most functions. In this case the circular reference likely don't occur as the function filters out cells in the range. This is something that we will address in future versions. 
For now you can use:
`p.Workbook.Calculate(x=>x.AllowCircularReferences=true);`
