### ISSUE TITLE
Object Reference Not Set when adding a worksheet to a workbook that contains any Macros

### ISSUE THREAD

**Issue by ThomasSoftware** [EPPlusSoftware/EPPlus#479]
This issue occurs in version 5.5.0, 5.7.1, and 5.7.4 (Latest Stable Release)

the furthest I can go back is 5.5.0 because I use the add button control feature. My workbook has macros in it. If I remove the macros it works but then my workbook doesn't work because it needs the macros.

Have any workbook with macros in it.
Open that excel workbook and then do 
ExcelWorksheet Sheet = Excel.Workbook.Worksheets.Add("ANYNAME");

**Comment by JanKallman** [comment]
I'll have a look at it

**Comment by JanKallman** [comment]
This works when I try it. Can you provide a reproducible sample? Also, looking at the history I can see that we have done some modification related to string comparation, so can you please let me know what CultureInfo you use?

**Comment by ThomasSoftware** [comment]
Well I feel like someone who took their car into the shop for a noise. This morning I woke up started creating a project outside of my current one to send yall for a test project and it worked. So I Uninstalled epplus on my original project and reinstalled it instead of letting Nuget update/downgrade the package like I was and it all works now perfectly. So I am going to close this and chalk it up to long nights of coding mixed with a possibility of Nuget not properly upgrading my epplus package.
