### ISSUE TITLE
Copying worksheet containing comment with background image corrupts workbook

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#481]
In Excel, comments usually have a yellow background colour, but you can also set this to be a background image. (This is done in Excel by going to Format Comment > Colors and Lines > Color > Fill Effects > Picture).

I have a worksheet containing one of these comments. If I try to copy the worksheet to a new workbook using EPPlus, the new workbook becomes corrupt and Excel is unable to open it.

I think this is because some content isn't being copied. The `xl/drawings/vmlDrawing1.vml` file contains a reference to the image using the relationship Id `rId1`. But the file `xl/drawings/_rels/vmlDrawing1.vml.rels` isn't copied, so Excel can't see what `rId1` refers to. The image itself in `xl/media/image1.jpeg` also isn't copied.

Ideally these files would also be copied so that the comment still looks the same in the new workbook. But if that's not possible it would be useful if the reference to the image was at least removed so the workbook doesn't become corrupt.

I've attached an example workbook with one of these comments.

[CommentWithImage.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7137084/CommentWithImage.xlsx)

```csharp
[TestMethod]
public void CopyWorksheetContainingCommentWithImage()
{
    using (var pck = OpenPackage("CommentWithImage.xlsx"))
    {
        using (var pck2 = OpenPackage("CommentWithImage_" + System.DateTime.Now.ToString("yyyyMMddTHHmmss") + ".xlsx"))
        {
            var wks = pck2.Workbook.Worksheets.Add("Sheet1", pck.Workbook.Worksheets["Sheet1"]);
            pck2.Save();
        }
    }
    
    Assert.Inconclusive("Now try to open the file in Excel - does it tell you the file is corrupt?");
}
```

**Comment by JanKallman** [comment]
This is currently not supported, but it should be. I will have a look at it and see if it can be added to the next minor.
