### ISSUE TITLE
There are bugs since version 5.6.2

### ISSUE THREAD

**Issue by shishu123cn** [EPPlusSoftware/EPPlus#486]
ExcelPackage.LicenseContext = LicenseContext.Commercial;
            FileInfo fileInfo = new FileInfo(path);
            using (var package = new ExcelPackage(fileInfo))
            {
                if (package.Workbook != null && package.Workbook.Worksheets.Count > 0)
                {
                    var excelWorksheet = package.Workbook.Worksheets.First();
                    package.Save();
                }
                package.Dispose();
            }

After opening the saved file, the following error message will be prompted

已删除的部件: 有 XML 错误的 /xl/styles.xml。 (样式) 加载错误。 行 1，列 0。
已修复的记录: /xl/worksheets/sheet1.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet1.xml 部分的 列信息
已修复的记录: /xl/worksheets/sheet1.xml 部分的 条件格式
已修复的记录: /xl/worksheets/sheet2.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet2.xml 部分的 列信息
已修复的记录: /xl/worksheets/sheet3.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet3.xml 部分的 列信息
已修复的记录: /xl/worksheets/sheet4.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet4.xml 部分的 列信息
已修复的记录: /xl/worksheets/sheet5.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet5.xml 部分的 列信息
已修复的记录: /xl/worksheets/sheet6.xml 部分的 单元格信息
已修复的记录: /xl/worksheets/sheet6.xml 部分的 列信息

**Comment by swmal** [comment]
We need the workbook you are using to see what is going wrong. Can you upload it here or in some other way provide a reproducable example?

**Comment by shishu123cn** [comment]
Sorry, the work network cannot transfer files outside. I will try to find out the bug caused later

**Comment by JanKallman** [comment]
Ok, I'll close this issue then. Feel free to re-open it if you can add a reproducable sample.
