### ISSUE TITLE
 When ExcelAddress is judged to be equal, the index may be out of range。

### ISSUE THREAD

**Issue by shishu123cn** [EPPlusSoftware/EPPlus#488]
public override bool Equals(object obj)
        {
            if (obj is ExcelAddressBase a)
            {
                if (Addresses==null || a.Addresses==null)
                {
                    if (Addresses?.Count > 1 || a.Addresses?.Count > 1) return false;
                    return IsEqual(this, a);
                }
                else
                {
                    for(int i=0;i<Addresses.Count;i++)
                    {
                        **//May index out of range**
                        if (IsEqual(Addresses[i], a.Addresses[i]) == false)
                        {
                            return false;
                        }
                    }
                    return true;
                }
            }
            else
            {
                return _address == obj.ToString();
            }
        }

**Comment by JanKallman** [comment]
Thanks for reporting this. I have added a fix for this and will soon merge it into the develop branch for you to test. 
https://github.com/EPPlusSoftware/EPPlus/blob/861eeee151d5fa08a78046b599e370272dd81225/src/EPPlus/ExcelAddressBase.cs#L1655

**Comment by JanKallman** [comment]
Fixed in version 5.7.5
