### ISSUE TITLE
System.Drawing.Common is deprecated on non-Windows platforms

### ISSUE THREAD

**Issue by safern** [EPPlusSoftware/EPPlus#495]
Hello, I work on the .NET Libraries team, and I saw that this library has a lot of usage in the community and depends on System.Drawing.Common for xplat scenarios.

We made the decision to make `System.Drawing.Common` a windows only library starting .NET6+ due to a lot of reasons after a long discussion. You can see more details here:
https://github.com/dotnet/designs/blob/a15a8c7a324c482c5e38b73e46c2afe56f6bd504/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

Also: https://github.com/dotnet/docs/issues/25257

We wanted to reach out so that you could react to this changes when .NET 6 is released. Also if you have any questions/concerns please do let us know at https://github.com/dotnet/runtime

What is the recommended action to still support winforms/wpf scenarios for example?

You can mark the APIs that need to use System.Drawing.Common to support winforms/wpf as windows only using the `SupportedOSPlatform("windows")` annotation, and then add new APIs that use another library like `ImageSharp` or `SkiaSharp.

**Comment by JanKallman** [comment]
Thanks for the info. I will investigate this further. 
Are there any future plans for adding xplat drawing functionality into the core framework? I mean, imaging and font handling are basic functions that really should be there.

**Comment by safern** [comment]
> Are there any future plans for adding xplat drawing functionality into the core framework? I mean, imaging and font handling are basic functions that really should be there.

That hasn't been decided yet as currently drawing relies heavily for all its operations on GDI+. At the moment we recommend `SkiaSharp` or `ImageSharp` which are great xplat open source libraries for those basic functions.

**Comment by JanKallman** [comment]
Ok thanks. 
FYI: SkiaSharp is probably our best bet, but it lacks a lot of image codecs used in Office (tif, wmf, emf) and that are supported by System.Drawing.Common with GDI+. Are you planning to implement these codecs in SkiaSharp or in any other way provide support for them in .NET 6 and onwards? They are still used in Excel, especially .emf which Excel produces when an ActiveX control is created.

**Comment by safern** [comment]
Thanks for the heads up. That would be a good issue to open on `SkiaSharp` repository directly. I would imagine they would be open to implement the codecs in SkiaSharp.

**Comment by JanKallman** [comment]
Great, I'll do that. Thanks for your help with this.

**Comment by JanKallman** [comment]
@emisand We will release EPPlus 6-beta in the coming days where we replace System.Drawing.Common with native code for all Excel supported image types. See https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-6 (this is still work in progress).
So we will likely not need ImageSharp. We have also implemented interfaces for imaging and text measuring, so using other libraries will be possible if needed. Feel free to test it once we release the beta or try it right now using this branch... https://github.com/EPPlusSoftware/EPPlus/tree/beta/epplus6

**Comment by JanKallman** [comment]
Fixed in 6.0.3. EPPlus will no longer need System.Drawing.Common, as native support for images and autofit columns has been implemented.
System.Drawing.Common can still be used via the EPPlus.System.Drawing for supported environments.
