### ISSUE TITLE
Grammatical error in Getting Started Wiki Page

### ISSUE THREAD

**Issue by IAmSahilVerma** [EPPlusSoftware/EPPlus#497]
It should be **_"to"_** instead of **_"too"_**. Please find attached the photo for reference
![InkedCapture_LI](https://user-images.githubusercontent.com/77562022/134795968-a10bb9e2-219e-4b33-a375-12eba22de634.jpg)
.

**Comment by JanKallman** [comment]
Thanks for letting us know. I have changed it.
