### ISSUE TITLE
Can't purchase a license

### ISSUE THREAD

**Issue by virzak** [EPPlusSoftware/EPPlus#506]
I was going to contact sales, but that wasn't available.

After creating a quote I click the cart icon, but it takes me to a blank screen:

https://epplussoftware.com/Account/AccessDenied

I have a default credit card set up too.

**Comment by JanKallman** [comment]
Hello,
Thanks for reporting this. We will have a look an get back to you. You can always contact us on sales@epplussoftware.com

**Comment by swmal** [comment]
Hi,
I found your account and will contact you via email. Closing this issue.
