### ISSUE TITLE
'_' character in module name on sheet copy causes corrupted workbook

### ISSUE THREAD

**Issue by chris-shelton** [EPPlusSoftware/EPPlus#508]
When copying a sheet, and it copies the VBA module, it gets the module name from sheet name. 

https://github.com/EPPlusSoftware/EPPlus/blob/087784e90519efefa553a22b302b490f72cbcf3d/src/EPPlus/Vba/ExcelVbaModule.cs#L69-L78

When the sheet name starts with a '_' (which is a valid sheet name), it passes the above check and names the module as so. But a module name cannot start with a '_' and causes a corrupted workbook that has to repair on open. 

The '_' should be added into:
https://github.com/EPPlusSoftware/EPPlus/blob/087784e90519efefa553a22b302b490f72cbcf3d/src/EPPlus/Vba/ExcelVbaModule.cs#L28

**Comment by JanKallman** [comment]
Thanks for reporting this. I'll provide a fix for it.
