### ISSUE TITLE
RichText causes xml "corruption"

### ISSUE THREAD

**Issue by dyster** [EPPlusSoftware/EPPlus#52]
Its not exactly corrupt, but excel complains when opening.
"We found a problem with some content in yourfile.xlsx. Do you want us to try to recover as much as we can? if you trust the source of this workbook, click yes"
After repairing a window reports
"Repaired Records: String properties from /xl/sharedStrings.xml part (Strings)"
Version 5.0.3 (the current nuget)
It looks similar to 559 on the original git, and seen similar issues when googling but no solution.

I use this code to generate the spreadsheet, and it is when the richtext section is used that the problem occurs. (it generated 18  sections of rich text in that cell)

the two different sharedstring.xml files are attached
[sharedstrings.zip](https://github.com/EPPlusSoftware/EPPlus/files/4304127/sharedstrings.zip)

`var text = log.Text.Replace('\t', ' ');
                        var textCell = worksheet.Cells[rowindex, 4];

                        if (regexHighlight.Any(r => r.IsMatch(text)))
                        {
                            textCell.IsRichText = true;
                            foreach (var s in text.Split(' '))
                            {
                                var highlight = regexHighlight.Any(r => r.IsMatch(s));
                                var richText = textCell.RichText.Add(s);
                                richText.Bold = highlight;
                                richText.Color = highlight ? Color.Red : Color.Black;
                                textCell.RichText.Add(" ");
                            }
                        }
                        else
                        {
                            textCell.Value = log.Text.Replace('\t', ' ');
                        }`

**Comment by JanKallman** [comment]
Thanks for reporting this issue. The error appears if you add and empty string ("") to the RichText Collection. 
It will generates this xml that is not valid...
```xml
<d:r` xmlns:d="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<d:rPr>
<d:sz val="11"/>
<d:color rgb="FF000000"/>
<d:rFont val="Calibri"/>
</d:rPr>
<d:t xml:space="preserve"/>
</d:r>
```
For now, add a check in your code that `s` is not equal to "". I'll add a fix for this in the next release.

**Comment by JanKallman** [comment]
Adding a blank("") or null string to the RichText Collection or setting the RichText[x].Text to blank will from the next release throw an exception as RichText can't have empty items.

**Comment by JanKallman** [comment]
Will go into EPPlus 5.0.4
