### ISSUE TITLE
ExcelRichTextCollection Add method is throwing errors if empty string in parameter

### ISSUE THREAD

**Issue by nowakpaw** [EPPlusSoftware/EPPlus#521]
We are using something similar to: https://github.com/JanKallman/EPPlus/blob/v4.5.1/EPPlus/Style/ExcelRichTextHtmlUtility.cs
Whenever `ExcelRichTextCollection.Add("")` in code is called - like: 
`thisrt = range.RichText.Add(text);`
where text is `""`, we are getting this error: `System.ArgumentException: Text can't be empty (Parameter 'text').`
It was working previously but we are currently moving to .NET Core 3.1 and updated almost everything - including EPPplus to licensed version:)

**Comment by nowakpaw** [comment]
Thanks for Your feedback. Yes - while converting from HTML tags to rich text formatters. We temporary downgraded version to the latest 4.x via nuget and everything is working as expected (without changes in HTML to RichText converter).

**Comment by JanKallman** [comment]
I can remove the validation as Excel allows it, but adding an empty string to the rich text will never show visually in the cell if saved.

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.8.3
