### ISSUE TITLE
COUNTIFS, AVERAGEIFS and SUMIFS fails with single cell ranges

### ISSUE THREAD

**Issue by Stefano66** [EPPlusSoftware/EPPlus#525]
If SUMIFS arguments are single cell ranges (ie: SUMIFS(H5,H5,">0",K5,">0")), Calculate statement results in a NullReferenceException in OfficeOpenXml.FormulaParsing.Excel.Functions.Math.MultipleRangeCriteriasFunction.GetMatchIndexes(IRangeInfo rangeInfo, String searched).
This issue occurs if you set address to the single cell coordinates (H5) or if you use a range containing a single cell (H5:H5).

Stefano

**Comment by swmal** [comment]
Hi,
thanks for reporting - we will have a look at this.
/Mats

**Comment by swmal** [comment]
This fix will be included in the next version. You can test it using the latest version in our [development Nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed)
