### ISSUE TITLE
Overlapping data validations addresses are validated on save.

### ISSUE THREAD

**Issue by JanKallman** [EPPlusSoftware/EPPlus#528]
Overlapping data validation addresses are validated on save which cause workbooks containing such not to be saved.

**Comment by terasato** [comment]
Hi @JanKallman, I'm sorry for not replying sooner.
I created the smallest repro code. Could you check this?
[EppRepro.zip](https://github.com/EPPlusSoftware/EPPlus/files/7502050/EppRepro.zip)

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.8.3
