### ISSUE TITLE
Unnecessary Yielding of the Time (performance)

### ISSUE THREAD

**Issue by Kizaemon** [EPPlusSoftware/EPPlus#530]
https://github.com/EPPlusSoftware/EPPlus/blob/cbacac1a2b629e349b33b0f88f98d20682fffbdf/src/EPPlus/FormulaParsing/CalculateExtentions.cs#L237

I suppose the `Thread.Sleep(0);` is intended to yield some time to other background processes.
Not sure if this is necessay.

Furthermore the call to the sleep function is done for each cell.
This is surely inefficient to have so frequent context switches.

If you feel the yielding of the time is required, then call the sleep every 10,000th cell.
```
if (int n++ % 10000 == 0)
     Thread.Sleep(0);

```

**Comment by swmal** [comment]
Hello,
you are right and we are in the process of rewriting major parts of the formula calculation to add new functionality and improve performance. This one will go away in future versions.

**Comment by Kizaemon** [comment]
Perfect
