### ISSUE TITLE
Read values from form controls

### ISSUE THREAD

**Issue by Nils89** [EPPlusSoftware/EPPlus#531]
Is it possible to read out the values from existing form controls like a checkbox?

**Comment by JanKallman** [comment]
Yes....
`var value = worksheet.Drawings["chxYourCheckbox"].As.Control.CheckBox.Checked;`

**Comment by Nils89** [comment]
Thanks you very much :)

**Comment by Nils89** [comment]
Hmm I got always a Null Pointer 

Is this working for ActiveX Objects?

**Comment by JanKallman** [comment]
No, EPPlus do not yet support ActiveX controls, only form controls.
