### ISSUE TITLE
Adding FILTER Function

### ISSUE THREAD

**Issue by GarethParry1** [EPPlusSoftware/EPPlus#534]
HI,
i am using the Epplus library and i am trying to add the FILTER function to a sheet.

if i use

`wsdt_Performance.Cells("D8").CreateArrayFormula("=_xlfn.FILTER('Graph Data'!A2:G15,'Graph Data'!A2:A15 = D2,"" "")")`

in excel i get

`{=FILTER('Graph Data'!A2:G15,'Graph Data'!A2:A15 = D2," ")}`

and only by entering the cell do the curly brackets disappear and the function works

if i remove the _xlfn section i get an error when the sheet opens

am i doing something wrong?

thanks

Gareth

**Comment by JanKallman** [comment]
Hi,
EPPlus currently don't support the FILTER function. The FILTER function requires dynamic array formula support, currently not implemented in EPPlus. We will start to look at this in the comming versions.

**Comment by GarethParry1** [comment]
Hi,

Ok no worries. Thanks for coming back to me

I added it by adding a VBA macro module until its implemented

thanks

Gareth Parry
Head of Systems & Business Improvement
Breezemount
Mobile: +44 (0) 7800 528327
Email: ***@***.***
Web: www.breezemount.com<http://www.breezemount.com/>

**Comment by swmal** [comment]
The FILTER function is implemented in EPPlus 7 which supports dynamic arrayformulas.
