### ISSUE TITLE
IntParser (formula calc) cannot handle boolean values.

### ISSUE THREAD

**Issue by virzak** [EPPlusSoftware/EPPlus#536]
Here is a failing test case: #535

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look.

**Comment by swmal** [comment]
This is fixed in commit afb6535356ef5e5e108dab808152f9a7d1a93be4

The fix will be in the next version, to make it work in the current version change FALSE to 0 in the arguments to the MATCH function in your formula.

**Comment by virzak** [comment]
Great, thanks!
