### ISSUE TITLE
Remove filter doesn't work

### ISSUE THREAD

**Issue by sselvatici** [EPPlusSoftware/EPPlus#539]
Hi,

I'm trying to remove a filter, but if I do that I get an error when I manually open the file.
Excel asks to restore content and when I do that, the filter is still present.

I'm using this instruction, I get no error in the code, if I debug it, after the row, I see that Columns collection become 0.

ws.AutoFilter.Columns.RemoveAt(0);

Is it a bug or I'm missing something?

Regards,

Simone

**Comment by JanKallman** [comment]
We'll have a look at it.

**Comment by JanKallman** [comment]
I have tride to reproduce this, but I can't get this behavior. Can you provide a sample, so I can reproduce this?

**Comment by sselvatici** [comment]
We were not considering other code parts, I think we can close the issue, sorry about that and thanks for the quick response.
