### ISSUE TITLE
Range.Merge does not work as expected in 5.0.3

### ISSUE THREAD

**Issue by elmoro666** [EPPlusSoftware/EPPlus#54]
Hi

I ran the following testcode in version 4.5.3.3 and in 5.0.3:

![image](https://user-images.githubusercontent.com/15340253/76201531-b2a00480-61f3-11ea-99c6-9f4e5baeb38d.png)

In 4.5.3.3 it looks as expected:

![image](https://user-images.githubusercontent.com/15340253/76201628-d400f080-61f3-11ea-890d-7ac413d3ce6f.png)

In 5.0.3

![image](https://user-images.githubusercontent.com/15340253/76201678-e7ac5700-61f3-11ea-9d0c-3d72c2ceeffa.png)

As far as I could tell from the relase notes, there shouldn't be any change in this functionality. Let me know if you want me to upload some sample code

**Comment by JanKallman** [comment]
Hi,
Thanks for reporting this issue. 
Setting the Value property for multiple cells cleared the merged cells for the range.
I will add a fix shortly

**Comment by JanKallman** [comment]
Fix added. Feel free to try it out using our app veyor nuget feed, 
https://ci.appveyor.com/nuget/epplus
You can also workaround this bug, by setting the value of the first cell only. In this case ws.Cells[1,1].Value="Header" or merging after setting the value.

**Comment by elmoro666** [comment]
Thnks for the quick fix! I will try it out later today

**Comment by nordicbondpricing** [comment]
tested and it works fine now. Yo may close this issue. Thanks again!

**Comment by JanKallman** [comment]
Will go into EPPlus 5.0.4
