### ISSUE TITLE
Reference NonCommercial license in .NET Core project

### ISSUE THREAD

**Issue by hnguyenp** [EPPlusSoftware/EPPlus#544]
I am using in EPPlus 5 (NonCommerical version) in .NET Core project. I have updated the appsettings with LicenseContext = "NonCommerical". Do I need to reference the PolyForm NonCommerical License (https://polyformproject.org/licenses/noncommercial/1.0.0/) in my source code or in the view where I used the EPPlus tool? If you can send me any examples, it would be helpful. Thanks

**Comment by JanKallman** [comment]
We use header like this...
https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/ExcelPackage.cs
You could add something similar as line 3-5.
I don't think it's mandatory as long as it's clear that you use the Polyform NC when you distribute your code.

**Comment by hnguyenp** [comment]
Thank you !
