### ISSUE TITLE
Circular reference error when a cell uses the same cell from an external workbook

### ISSUE THREAD

**Issue by lolsoftware** [EPPlusSoftware/EPPlus#546]
The error I get is:
"Circular reference occurred at A2"

This happens when I call ws.Calculate() on the [b.xlsx] file.
The formula in A2 is as follows:
='[a.xlsx]Sheet1'!$A$2

The issue occurs only if the cell in [b.xlsx] references the same cell in [a.xlsx].
So only if [b.xlsx]Sheet1'!$A$2 references [a.xlsx]Sheet1'!$A$2

The issue does NOT occur if these two cells have different addresses.
So the issue would not occur if [b.xlsx]Sheet1'!$A$2 referenced [a.xlsx]Sheet1'!$B$20 for example.

I attach the source code and the two Excel files.
[a.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7668268/a.xlsx)
[b.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7668269/b.xlsx)
[bug.zip](https://github.com/EPPlusSoftware/EPPlus/files/7668270/bug.zip)

**Comment by JanKallman** [comment]
I'll have a look at this.

**Comment by JanKallman** [comment]
This is a bug. Try this fix.

**Comment by JanKallman** [comment]
Fix added in 5.8.4
