### ISSUE TITLE
Copy Cells, error :  Invalid Address format U13U18U24

### ISSUE THREAD

**Issue by steph9111** [EPPlusSoftware/EPPlus#548]
my code doesn't work when i copy in the same o another workbook. But Add function work perfectly.

        Dim oAppExcelSource As New ExcelPackage(New IO.FileInfo("09-145.xlsm"))
        Dim _SheetToCopy As OfficeOpenXml.ExcelWorksheet

        Try
            _SheetToCopy = oAppExcelSource.Workbook.Worksheets("Sheet3")
            'add a sheet and the same workbook 
            oAppExcelSource.Workbook.Worksheets.Add("tmpCopy")
            'copy in the same o in another workbook, same issue
            _SheetToCopy.Cells("C1:AB55").Copy(oAppExcelSource.Workbook.Worksheets("tmpCopy").Cells("C1"), ExcelRangeCopyOptionFlags.ExcludeFormulas) 'error at this line Invalid Address format U13U18U24
            oAppExcelSource.Save()

        Catch ex As Exception
            MsgBox(ex.Message)
        Finally
            oAppExcelSource.Dispose()
            oAppExcelSource = Nothing
        End Try

**Comment by JanKallman** [comment]
Please attach you workbook, so this can be reproduced

**Comment by steph9111** [comment]
[09-145.zip](https://github.com/EPPlusSoftware/EPPlus/files/7692713/09-145.zip)

The excel file

**Comment by steph9111** [comment]
[09-145.zip](https://github.com/EPPlusSoftware/EPPlus/files/7694300/09-145.zip)

**Comment by JanKallman** [comment]
Thanks, this is a bug. I'll provide a fix shortly.

**Comment by JanKallman** [comment]
Fix added in 5.8.4
