### ISSUE TITLE
Worksheets.Add a sheet to an another workbook, not keep the values and displays "ERROR" in all cells

### ISSUE THREAD

**Issue by steph9111** [EPPlusSoftware/EPPlus#549]
I have a problem with the add sheet function in another workbook. If the original sheet has cells that fill with functions, the copy does not keep the links and displays "ERROR" in all cells. I did not see an option to copy only the values when adding a sheet to another workbook.

Does anyone have an idea?

**Comment by JanKallman** [comment]
No, you will have to use the Cells[].Copy after the worksheet has been added to leave out formulas (and a lot of other things).
See https://github.com/EPPlusSoftware/EPPlus/wiki/Copy-Ranges-or-Entire-Worksheets
