### ISSUE TITLE
Validation Formula invalid address format error in v5.0.3

### ISSUE THREAD

**Issue by fanc-mso** [EPPlusSoftware/EPPlus#55]
Hi,

following function in my code has been working for quite some time with the v4 packages:

```
private void SetDataValidationToCodeList(ExcelWorksheet worksheet, int column, string listName, int startRow = 3)
        {           
            var rangeToSet = ExcelCellBase.GetAddress(startRow, column, ExcelPackage.MaxRows, column);
            var validation = worksheet.DataValidations.AddListValidation(rangeToSet);
            validation.Formula.ExcelFormula = $"={listName}_descr";
        }
```

In v5.0.3, without changing antyhing else (apart from setting the license environment variable) this returns an error:

> Invalid Address format =LICENSEITEMTYPE_DESCR

(LICENSEITEMTYPE is the value of my listName variable)

This list surely exists in my workbook names, see screenshot while debugging just prior to the error:
![image](https://user-images.githubusercontent.com/29544970/76218120-ed199980-6213-11ea-9174-ec857379b8e1.png)

I'm not seeing anything related to that in the breaking changes page for v5 so I suppose this is a bug ?

Thank you for looking into this

**Comment by JanKallman** [comment]
Thanks for reporting this issue. This is a bug. When checking if the Data Validation reference to an other worksheet and should go into the extLst element this fails if the formula is not an address. Fix coming.

**Comment by fanc-mso** [comment]
Thank you for your quick action ;-)

**Comment by JanKallman** [comment]
Will go into EPPlus 5.0.4
