### ISSUE TITLE
Inserting Linked Datatypes

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [EPPlusSoftware/EPPlus#551]
https://docs.microsoft.com/en-us/office/vba/api/excel.range.converttolinkeddatatype

What is the most straight forward way to do the same in EPPlus?

Range("E5").ConvertToLinkedDataType ServiceID:=268435456, LanguageCulture:= "en-US"

**Comment by JanKallman** [comment]
EPPlus currently does not support this feature natively. You can add a VBA project that adds this when the workbook is opened, if you are ok with using macro-enabled workbooks. We will likely add this feature in a coming version, but's it's currently not on the roadmap.

**Comment by JanKallman** [comment]
This issue is similar to #383, so I'll close this one.
