### ISSUE TITLE
Support for settings.json

### ISSUE THREAD

**Issue by andyb70** [EPPlusSoftware/EPPlus#553]
I haven't seen anybody else mention this which makes me wonder whether I've missed something but how do you set the LicenseContext when using a local.settings.json file? I have tried adding the documented appSettings.json to my local.settings.json but to no avail it simply fails saying I haven't configured the LicenseContext.

````
{
  "EPPlus": {
    "ExcelPackage": {
      "LicenseContext": "NonCommercial"
    }
  }
}
````

**Comment by swmal** [comment]
Which version of .NET are you using and in what kind of application are you experiencing this?

[Here is the code](https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/ExcelPackage.cs#L645) that EPPlus executes to read the license context from the appsettings file if that helps.

**Comment by andyb70** [comment]
Hi, sorry I should have put that down in the first instance!

.NET Core 3.1 and the project types I have tried are Console App and Function App

**Comment by andyb70** [comment]
Looking at the code it is reading the physical file appsettings.json I guess this is the root of my issue as the file is not called that.

**Comment by andyb70** [comment]
Let me get my current task out of the way and I'll take a look in more detail as we have just purchased licenses so I need to integrate that into our production system.

**Comment by andyb70** [comment]
When creating a new Azure Function App project the template provides a local.settings.json file for creating application settings these settings are then replaced when deploying to Azure by entering corresponding values into the Application settings tab on the Configuration blade within the Azure portal.

The local.settings.json file takes the following form and all application settings should be located within the Values object: -

````
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet"
        "EPPlusLicenseContext": "Commercial"
    }
}
````

These values can then be extracted within your Startup.cs class using the same method as defined within the EPPlus sourcecode i.e.

````
var v = Environment.GetEnvironmentVariable("EPPlusLicenseContext",EnvironmentVariableTarget.User);
````

However, this extracts a value for the environment variable target of User and the Function App loads the settings into the Process environment, thus nothing is returned. 

As no license check is performed after deployment to production, could the following code could be utilised to solve this issue?

````
var v = Environment.GetEnvironmentVariable("EPPlusLicenseContext",EnvironmentVariableTarget.User);

if (string.IsNullOrEmpty(v))
{
    v = Environment.GetEnvironmentVariable("EPPlusLicenseContext",EnvironmentVariableTarget.Process);
}
````

**Comment by swmal** [comment]
This code runs only when there is a debugger attached, see [this line](https://github.com/EPPlusSoftware/EPPlus/blob/develop/src/EPPlus/ExcelPackage.cs#L640).

We will have a look at checking other filenames than appsettings.json and we will add your suggested fix with a fallback to EnvironmentVariableTarget.Process. Will be included in the next version.

**Comment by andyb70** [comment]
Thanks Mats it's not causing me any issues I've just added the flag setting in code for now.
