### ISSUE TITLE
StyleXmlHelper  bug

### ISSUE THREAD

**Issue by shishu123cn** [EPPlusSoftware/EPPlus#556]
StyleXmlHelper.cs
line 37      internal int newID = int.MinValue;

Why is int.minvalue set here?

It may cause xfsid to be negative after save。

ExcelStyle.cs
line 60   Numberformat = new ExcelNumberFormat(styles, ChangedEvent, PositionID, Address, _xfs.NumberFormatId);
_xfs maybe null。

<cellStyle name="常规 2" xfId="-2147483648" builtinId="0" />

**Comment by shishu123cn** [comment]
#486

**Comment by shishu123cn** [comment]
#486  
One of my previous problems finally reproduced this bug

**Comment by JanKallman** [comment]
Can you please provide some code to reproduce your issue. Please also provide a workbook if necessary.

**Comment by shishu123cn** [comment]
`<cellStyleXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" /><xf numFmtId="0" fontId="0" fillId="0" borderId="0" /><xf numFmtId="0" fontId="2" fillId="0" borderId="0" /></cellStyleXfs>`

styles.xml is like this,

ExcelStyles.cs :
 private void LoadFromDocument()
{
            ..................................

            //cellStyleXfs
            XmlNode styleXfsNode = GetNode(CellStyleXfsPath);
            if (styleXfsNode != null)
            {
                foreach (XmlNode n in styleXfsNode)
                {
                    ExcelXfs item = new ExcelXfs(_nameSpaceManager, n, this);
                    CellStyleXfs.Add(item.Id, item);
                }
            }
}

ExcelXfsXml.cs ：
            XfId = GetXmlNodeInt("@xfId");

When there is no @xfid field, the default value of int.MinValue will be used, which will cause a series of problems later

**Comment by shishu123cn** [comment]
XmlHelper.cs:
  internal int GetXmlNodeInt(string path, int defaultValue=int.MinValue)

DefaultValue here

**Comment by JanKallman** [comment]
This is just fragments of code. I can not reproduce the issue from this. Please provide full code and a workbook that I can test this with.

**Comment by shishu123cn** [comment]
I am a company network and cannot provide you with a workbook。

**Comment by shishu123cn** [comment]
You can directly modify Xfid to int.MinValue, then open and save the workbook, this problem should occur

**Comment by shishu123cn** [comment]
Why is the default value here set to int.MinValue
`  internal int GetXmlNodeInt(string path, int defaultValue=int.MinValue)`

**Comment by JanKallman** [comment]
This is beyond the support we provide here. If you have a commercial license please provide your workbook inside our support portal.

**Comment by shishu123cn** [comment]
We are a small tool for internal use, not for commercial use

**Comment by JanKallman** [comment]
If you are a commercial company you still need a license for internal use.

**Comment by shishu123cn** [comment]
Ok i got it
