### ISSUE TITLE
Can not use ExcelPackage.Workbook.Names if there are any invaild names.

### ISSUE THREAD

**Issue by DamianRice** [EPPlusSoftware/EPPlus#560]
I was trying to use C# loading Excel Name Manager, however, the name contains invalid chars like "\0". How to deal with that? I can't even 'var name = pkg.Workbook.Names;'.

Error Like this: System.ArgumentException:“Name \0 contains invalid characters”

```
using (ExcelPackage pkg = new ExcelPackage(filePatha))
        {
            var name = pkg.Workbook.Names;
            foreach (ExcelNamedRange excelNamedRange in name)
            {
                Console.WriteLine($"IsNameHidden:{excelNamedRange.IsNameHidden}\n" +
                                  $"Name:{excelNamedRange.Name}\n" +
                                  $"Address:{excelNamedRange.Address}\n" +
                                  $"Formula:{excelNamedRange.Formula}\n" +
                                  $"Text:{excelNamedRange.Text}\n" +
                                  $"Value:{excelNamedRange.Value}\n" +
                                  $"FullAddressAbsolute:{excelNamedRange.FullAddressAbsolute}\n" +
                                  $"---------------------------------\n");
            }
            Console.Read();
        }
```

The class ‘ExcelNamedRangeCollection’ shows
```
    /// <param name="Name">The name</param>
    /// <param name="Range">The range</param>
    /// <returns></returns>
    public ExcelNamedRange Add(string Name, ExcelRangeBase Range)
    {
      if (!ExcelAddressUtil.IsValidName(Name))
        throw new ArgumentException("Name contains invalid characters or is not valid.");
      if (this._wb != Range._workbook)
        throw new InvalidOperationException("The range must be in the same package. ");
      return this.AddName(Name, Range);
    }
```
Maybe an update with `StringBuilder` to solve strings like `\0` could be implemented?

**Comment by JanKallman** [comment]
I'll have a look at it.

**Comment by JanKallman** [comment]
What is the actual problem here?
The name can't contain invalid characters when you add it. You should however be able to load it from an existing workbook, but it will give you an error in Excel later when you open it.

**Comment by DamianRice** [comment]
> 
What I mean is "Excel Defined Names MAY contains invalid chars".
If using Aspose or other packages to auto-generate `Defined Names`, it may cause that names contained invalid characters.
Such as "\0" "\_123"。
I've tried to use Excel Name Manager to create names contained invalid char and it will be banned by Excel.
However, I solved this problem with OpenXML
