### ISSUE TITLE
Setting ExcelRange.Value to null does nothing if the range covers more than one cell

### ISSUE THREAD

**Issue by lolsoftware** [EPPlusSoftware/EPPlus#568]
If I try to clear a range of cells by setting Value to null, nothing changes. It works only if the range of cells contains just a single cell. However, setting Value to an empty string (rather than null) works fine in both cases.

`ExcelRange range = ws.Cells[minRowNum, minColNum, maxRowNum, maxColNum];`
`range.Value = null; //this does nothing`
`range.Value = ""; //this works fine`

I attach a sample source code file and an input Excel file.
[Program.zip](https://github.com/EPPlusSoftware/EPPlus/files/7769602/Program.zip)
[in.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7769604/in.xlsx)

**Comment by JanKallman** [comment]
I'll have a look. You can use `range.Clear()` as an alternative way of doing this.

**Comment by lolsoftware** [comment]
As far as I know, `range.Clear()` removes cell values as well as cell formatting. While `range.Value = null` removes cell values only. So `range.Clear()` is not an alternative to `range.Value = null`.

**Comment by JanKallman** [comment]
Yes correct, I have added a fix for this issue.

**Comment by JanKallman** [comment]
Fixed in EPPlus 5.8.5
