### ISSUE TITLE
Null deference exception related to cell styles

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#574]
Hello,

Using EPPlus 5.8.4, we have a workbook where a null dereference exception is thrown when read via EPPlus.   Exception message and stacktrace below.  I also uploaded the workbook.

'this.BaseWorkbook.Styles' threw an exception of type 'System.NullReferenceException'

at OfficeOpenXml.ExcelStyles.LoadFromDocument()
at OfficeOpenXml.ExcelStyles..ctor(XmlNamespaceManager NameSpaceManager, XmlDocument xml, ExcelWorkbook wb)
at OfficeOpenXml.ExcelWorkbook.get_Styles()

**Comment by rdhasse** [comment]
[GSI_TCB_TWD_20220111.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7847567/GSI_TCB_TWD_20220111.xlsx)

**Comment by JanKallman** [comment]
Thanks, I'll have a look at it.

**Comment by JanKallman** [comment]
This workbook is saved in the Strict Open XML format, currently not supported by EPPlus. If possible re-save it in Excel as a normal Excel Workbook
