### ISSUE TITLE
Improve SUBTOTAL handling of hidden cells

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#579]
Steps to replicate:

- Fill a range with numbers
- Use that range as parameter for SUBTOTAL with a single digit func number, for example SUBTOTAL(9, A1:A5)
- Add a filter to the range and uncheck one of the rows.
- SUBTOTAL should then ignore this value even though it uses a single digit func num.
Current version of EPPlus only ignores hidden cells when being called with a three digit func num.

**Comment by JanKallman** [comment]
Fixed in version 5.8.6
