### ISSUE TITLE
ExcelWorksheet.Dimension doesn't correctly determine sheet dimension if data resides on last excel row

### ISSUE THREAD

**Issue by thetilliwilli** [EPPlusSoftware/EPPlus#583]
**[Description]**
EPPlus version: 5.8.5

1. Put some data on last row of excel 
![image](https://user-images.githubusercontent.com/25109940/150536758-202f04d5-35c5-4608-804d-71d5e82d18f4.png)

2. Open book with EPPlus

**[Result]**

![image](https://user-images.githubusercontent.com/25109940/150544347-588ad7f2-da35-4bdb-81e1-3b60abfa0ee0.png)

**[ExpectedResult]**

Correctly determine sheet dimension (A1048576). E.g. if i put on the row before last 
![image](https://user-images.githubusercontent.com/25109940/150544758-e73eb1cb-5529-4cc0-9576-34259d10dad1.png)
everything is fine
![image](https://user-images.githubusercontent.com/25109940/150544907-f226cb3f-3f84-4ea9-ad4f-6eb90278040f.png)

**[AdditionalInfo]**
Here is screenshot of inner contents of excel file with data on last row 
![image](https://user-images.githubusercontent.com/25109940/150545627-f0e6f1d6-9cc9-4c27-9c63-5824cd47b5a1.png)

**Comment by JanKallman** [comment]
Thanks for reporting this. I'll have a look at it.

**Comment by JanKallman** [comment]
Fixed in version 5.8.6

**Comment by thetilliwilli** [comment]
@JanKallman i'm sorry, i've just checked and it doesn't seem fixed in 5.8.6 version
![image](https://user-images.githubusercontent.com/25109940/154666138-217016a9-1742-47e5-8e2d-355331f89608.png)
