### ISSUE TITLE
Pie chart with horizontal serie direction doesn't use different color

### ISSUE THREAD

**Issue by remi0411** [EPPlusSoftware/EPPlus#584]
Hello,

I'm trying to work with PieCharts.
I've no problem if my categories on pie chart are on a vertical direction, but when I use the other direction, my chart only have one color

![image](https://user-images.githubusercontent.com/9786969/151024264-145a4a57-e505-47a3-abda-01f6e8b7830a.png)

If my series are on a vertical direction, I haven't the problem

This is my chart code : 
![image](https://user-images.githubusercontent.com/9786969/151024393-423be0b4-010a-4fec-822e-173156f5ca5a.png)

Thank you

**Comment by JanKallman** [comment]
Thanks for reporting this. It's a bug. Data point were only generated on rows when styling a pie chart.
I'll provide a fix shortly.

**Comment by JanKallman** [comment]
Fixed in version 5.8.6
