### ISSUE TITLE
Adding rows to ExcelTable that has only single row and option ShowHeader false, results moving the table instead of adding rows

### ISSUE THREAD

**Issue by maxlego** [EPPlusSoftware/EPPlus#585]
This occurs only if option ShowHeader turned off.
After inserting a single row to my table, Range changes, but not as expected

Before inserting row table Range is A3:RK3.
And after insert: A5:RK5.

**Comment by JanKallman** [comment]
Seems to happen when you insert at position 0? I'll provide a fix.

**Comment by JanKallman** [comment]
Fixed in version 5.8.6
