### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException when Excel has the same hyperlink

### ISSUE THREAD

**Issue by jucheap** [EPPlusSoftware/EPPlus#587]
when i import data from excel, and has the same hyperlink for email column . the program will crash.
![Excel File](https://img2022.cnblogs.com/blog/99090/202201/99090-20220127141940509-1059782995.png)
[https://www.cnblogs.com/jucheap/articles/15849746.html](https://www.cnblogs.com/jucheap/articles/15849746.html)
```
[TestMethod]
        public void ExcelHyperLinkTest()
        {
            using (var memoryStream = new MemoryStream(System.IO.File.ReadAllBytes("d:\\EmpShare.xlsx")))
            {
                using (var package = new ExcelPackage(memoryStream))
                {
                    **//The following code will crash**
                    if (package.Workbook.Worksheets.Count == 0)
                    {
                        Debug.WriteLine("no sheet");
                        Assert.Fail();
                    }
                }
            }
        }
```

**Comment by JanKallman** [comment]
Can you attach your xlsx-file?

**Comment by JanKallman** [comment]
I can' reproduce this. Feel free to re-open this issue with a reproducible workbook

**Comment by jucheap** [comment]
> Can you attach your xlsx-file?

[File](https://files.cnblogs.com/files/jucheap/EmpShare.zip?t=1644313767)
