### ISSUE TITLE
EPPLUS Implementation of MROUND Incorrect

### ISSUE THREAD

**Issue by RoyMcDoug** [EPPlusSoftware/EPPlus#588]
In Excel if you MROUND an empty cell you get 0.
But EPPLUS produces #VALUE! and the log shows the below exception:

    OfficeOpenXml.FormulaParsing.Exceptions.ExcelErrorValueException: #VALUE!
at OfficeOpenXml.FormulaParsing.Excel.Functions.Math.Mround.Execute(IEnumerable`1 arguments, ParsingContext context)

Here's a C# Test Method to demo this issue:
(Excel file is attached.) 
If attachment fails, just create an Excel file with nothing in D6 and in E6 put this: =MROUND(D6,0.1)
[testMRound.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7966766/testMRound.xlsx)

[TestMethod]
		public void TestMROUND()
		{
			string filePath = @"c:\temp\testMRound.xlsx";
			FileInfo existingFile = new FileInfo(filePath);
			using (ExcelPackage package = new ExcelPackage(existingFile))
			{
				Debug.WriteLine($"D4: {package.Workbook.Worksheets["Sheet1"].Cells["D4"].Text}");
				Debug.WriteLine($"E4: {package.Workbook.Worksheets["Sheet1"].Cells["E4"].Text}");

				Debug.WriteLine($"D5: {package.Workbook.Worksheets["Sheet1"].Cells["D5"].Text}");
				Debug.WriteLine($"E5: {package.Workbook.Worksheets["Sheet1"].Cells["E5"].Text}");

				Debug.WriteLine($"E6: {package.Workbook.Worksheets["Sheet1"].Cells["E6"].Text}"); // Before calling .Calculate E6 correctly reports that blank rounded equals 0

				package.Workbook.Worksheets["Sheet1"].Cells["E6"].Calculate();

				Debug.WriteLine($"E6: {package.Workbook.Worksheets["Sheet1"].Cells["E6"].Text}"); // But after .Calculate E6 has #VALUE! I think this is a bug in EPPLUS's implementation of MROUND.
				// Here's what the log file shows:
				//		OfficeOpenXml.FormulaParsing.Exceptions.ExcelErrorValueException: #VALUE!
				//		at OfficeOpenXml.FormulaParsing.Excel.Functions.Math.Mround.Execute(IEnumerable`1 arguments, ParsingContext context)
			}
		

}

**Comment by swmal** [comment]
Thanks, we'll have a look at this.

**Comment by swmal** [comment]
This is now fixed, the fix applies to all rounding functions. We will release a new version in the coming days.

**Comment by RoyMcDoug** [comment]
Thank you VERY much!
Loving EPPlus :)

**Comment by JanKallman** [comment]
Fixed in version 5.8.6

**Comment by RoyMcDoug** [comment]
Awesome. Thanks a million!
