### ISSUE TITLE
Duplicate attributes added when copying row with notes

### ISSUE THREAD

**Issue by R4cOOn** [EPPlusSoftware/EPPlus#589]
Hi,

I noticed another issue related to row copying with notes (related to my issue raised in issue #552).

When notes are copied attributes in **VmlDrawingPart** are duplicated: 
- one attribute is in the default namespace (local name = fully qualified name)
- the same attribute is created in a namespace (local name <> fully qualified name)

The attached issue reproduces the issue with attributes _v:shape_ and _o:insetmode_.  

In production we have the same issue as before where we have duplicate _spid_s.  
They exhibit the same pattern where one of the attributes is fully qualified and the other isn't.  

Attached is a sample file and solution in .NET 6.0.  
It does a check for duplicate attributes, then copies a row with a note and checks for duplicates again (and fails).  
Unfortunately I couldn't reproduce the duplicate _spid_ error in a sample test case. 
[ExcelTesting.zip](https://github.com/EPPlusSoftware/EPPlus/files/7970173/ExcelTesting.zip)

Cheers.

**Comment by JanKallman** [comment]
Thanks, I'll have a look at it.

**Comment by JanKallman** [comment]
Yes, the copy operation does not look if an attribute has a namespace uri, causing a new attribute without the namespace prefix to be created. I have added a fix for issue for you to test.

**Comment by R4cOOn** [comment]
Cheers. Where can I get the fix you mentioned?

**Comment by JanKallman** [comment]
Use our develop nuget feed...
https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by R4cOOn** [comment]
It does seem to fix the the duplicate issue, thanks.

Do you have an ETA for the next NuGet package release?

**Comment by JanKallman** [comment]
I hope we can create a release later this this week.

**Comment by JanKallman** [comment]
Fixed in 5.8.6
