### ISSUE TITLE
Defining a range in a function using names ("MyRange1:MyRange2") causes error

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#593]
In Excel I can define a range in a function like this: `=SUM("A1:A10")` which will sum the cells from A1 to A10. 

If I add two names to the sheet, defining A1 as "MyRange1" and A10 as "MyRange2", I can write the same function like this: `=SUM("MyRange1:MyRange2")` and this will give me the same result in Excel.

But with EPPlus, if I use the latter style and then try to get the value, I get an error:
```
System.InvalidCastException: Object must implement IConvertible.
```

**Unit Test**
```csharp
[TestMethod]
public void Sum_NamedRangeToNamedRange()
{
    using (var pck = new ExcelPackage())
    {
        var wks = pck.Workbook.Worksheets.Add("Sheet1");
        wks.Cells["C3"].Value = 7;
        wks.Cells["C4"].Value = 1;
        wks.Cells["C5"].Value = 2;
        wks.Names.Add("MyName1", wks.Cells["C3"]);
        wks.Names.Add("MyName2", wks.Cells["C5"]);
        wks.Cells["F6"].Formula = "SUM(C3:C5)";
        wks.Cells["F7"].Formula = "SUM(MyName1:MyName2)";

        pck.Workbook.Calculate();

        Assert.AreEqual(10, wks.Cells["F6"].GetValue<double>(), 1E-10);
        Assert.AreEqual(10, wks.Cells["F7"].GetValue<double>(), 1E-10);
    }
}
```

**Comment by swmal** [comment]
See commit 335c1a5c75abb327b907de416f206a40744bf827 (missed the # when I commited so it doesn't show up here). Still some work to do but it fixes this particular case. We still need to handle the case when only the right side reference in an address is a name. This will work with "Name1:Name2" and "Name1:C5" but not with "A1:Name1"...

**Comment by craigbrown** [comment]
Thanks @swmal I've tested the latest build and "Name1:Name2" seems to be fixed for most functions. But I'm still seeing this issue for `SUMPRODUCT`.

```csharp
[TestMethod]
public void SumProduct_NamedRangesToNamedRanges()
{
    using (var pck = new ExcelPackage())
    {
        var sheet1 = pck.Workbook.Worksheets.Add("Sheet1");
        sheet1.Cells["A1"].Value = 10;
        sheet1.Cells["A2"].Value = 4;
        sheet1.Cells["A3"].Value = 1.6;
        sheet1.Cells["B1"].Value = 5;
        sheet1.Cells["B2"].Value = 7;
        sheet1.Cells["B3"].Value = 10;
        sheet1.Cells["C1"].Value = 1;
        sheet1.Cells["C2"].Value = 0.5;
        sheet1.Cells["C3"].Value = 0.5;

        sheet1.Names.Add("MyName1", sheet1.Cells["A1"]);
        sheet1.Names.Add("MyName2", sheet1.Cells["A3"]);
        sheet1.Names.Add("MyName3", sheet1.Cells["B1"]);
        sheet1.Names.Add("MyName4", sheet1.Cells["B3"]);
        sheet1.Names.Add("MyName5", sheet1.Cells["C1"]);
        sheet1.Names.Add("MyName6", sheet1.Cells["C3"]);

        sheet1.Cells["C6"].Formula = "SUMPRODUCT(MyName1:MyName2,MyName3:MyName4,MyName5:MyName6)";

        pck.Workbook.Calculate();

        Assert.AreEqual(72, sheet1.Cells["C6"].GetValue<double>(), Tolerance);
    }
}
```

**Comment by swmal** [comment]
Sorry for the late response, @craigbrown . This is fixed in the latest build and will be included in next release.

**Comment by swmal** [comment]
Closing this now as we released the fix yesterday. There are minor things left as mentioned above ("A1:Name1" still not working), these will be taken care of when we rewrite the whole thing. Let us know if these causes you any problems and if so please create a new issue.
/Mats
