### ISSUE TITLE
Possible to read data filtered?

### ISSUE THREAD

**Issue by UweKeim** [EPPlusSoftware/EPPlus#602]
### Scenario

1. Having an existing Excel XLSX file with a table and data.
2. This table is filtered. E.g. it would have 100 rows without a filter and is currently filtered to only have 10 rows visible.
3. I want to use EPPlus to read that very filtered 10 rows from the XLSX file.

An example of unfiltered rows might look like this:

![image](https://user-images.githubusercontent.com/415439/155586143-84e38b40-4df5-427e-85be-915c510c89a3.png)

The same data filtered might look like this:

![image](https://user-images.githubusercontent.com/415439/155586205-98b3eaf4-347d-4f29-91be-89283d4b07df.png)

### Question

Is it possible to get only those filtered rows?

**Comment by JanKallman** [comment]
Yes, you will have to check if the `ExcelRow.Hidden `property is false (visible rows)...
```
If(worksheet.Rows[x].Hidden==false)
{
//Process visible rows.
}
```

**Comment by UweKeim** [comment]
Works perfectly, thanks a lot @JanKallman.
