### ISSUE TITLE
 OutlineLevel create "+" and "-" button on wrong row (the following one)

### ISSUE THREAD

**Issue by SoniaRicci** [EPPlusSoftware/EPPlus#607]
Hi all,
I read a treelist from excel sheet, and I try to create the same with epplus
This is my input file
![immagine](https://user-images.githubusercontent.com/100683684/156150071-db718e51-d5cc-4c6b-b04f-010de6f6ef32.png)

I use wpf mvvm with prism
I create a recursive class

  public class RAMS 
    {
        public string Structure { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public List<RAMS> Items { get; set; }
     }

I would like to have the same structure in output excel file

I use the following methods:

private void LogFileRAMS(ref ExcelWorksheet worksheet, List<RAMS> rams)
        {
            worksheet.Cells[3, 1].Value = "Title";
            worksheet.Cells[3, 1].AutoFitColumns();
            worksheet.Cells[3, 2].Value = "code";
            worksheet.Cells[3, 2].AutoFitColumns();
            worksheet.Cells[3, 3].Value = " Description";
            worksheet.Cells[3, 3].AutoFitColumns();

            worksheet.Row(3).Style.Border.Top.Style = ExcelBorderStyle.Thin;
            worksheet.Row(3).Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            worksheet.Row(3).Style.Border.Left.Style = ExcelBorderStyle.Thin;
            worksheet.Row(3).Style.Border.Right.Style = ExcelBorderStyle.Thin;
            worksheet.Row(3).Style.Fill.PatternType = ExcelFillStyle.Solid;
            worksheet.Row(3).Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGreen);

            int rowCounter = 3;
            RecurseNodes(ref worksheet, rams.OrderBy(x => Convert.ToInt32(x.Code)).ToList(), ref rowCounter, 0);
        }

 private void RecurseNodes(ref ExcelWorksheet worksheet, List<RAMS> currentNode, ref int row,int indent)
        {
            foreach (RAMS node in currentNode)
            {
                row++;
                worksheet.Cells[row, 1].Value = node.Structure;
                worksheet.Cells[row, 1].AutoFitColumns();
                worksheet.Cells[row, 2].Value = node.Code;
                worksheet.Cells[row, 2].AutoFitColumns();
                worksheet.Cells[row, 3].Value = node.Description;
                worksheet.Cells[row, 3].AutoFitColumns();
              
                if (indent == 0)
                {
                    worksheet.Row(row).Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Fill.PatternType = ExcelFillStyle.Solid;
                    worksheet.Row(row).Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Red);
                    worksheet.Row(row).OutlineLevel = indent;
                }
                if (indent == 1)
                {
                    worksheet.Row(row).Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Fill.PatternType = ExcelFillStyle.Solid;
                    worksheet.Row(row).Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Orange);
                    worksheet.Row(row).OutlineLevel = indent;
                }
                if (indent == 2)
                {
                    worksheet.Row(row).Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Fill.PatternType = ExcelFillStyle.Solid;
                    worksheet.Row(row).Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.Yellow);
                    worksheet.Row(row).OutlineLevel = indent;
                }
                if (indent == 3)
                {
                    worksheet.Row(row).Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    worksheet.Row(row).Style.Fill.PatternType = ExcelFillStyle.Solid;
                    worksheet.Row(row).Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.White);
                    worksheet.Row(row).OutlineLevel = indent;
                }

                if (node.Items.Count != 0)
                {
                    RecurseNodes(ref worksheet, node.Items, ref row, indent+1);
                }
            }
        }

I create a title light green, a first level red, a second level orange, a third level yellow and a fourth level white (the last)

I succeded to write the line in excel and if I click on the button 1,2,3,4 it seems correct

![immagine](https://user-images.githubusercontent.com/100683684/156151830-cee13fc3-d152-45f1-8448-8de882cc740f.png)

If I open all level the "+" and "-" items are on wrong row, not the correct but the following one

![immagine](https://user-images.githubusercontent.com/100683684/156151871-578a8350-c828-4b6f-a178-3d167182b944.png)

I don't understand why this happens

Please could you help me?

Thanks
Sonia

**Comment by JanKallman** [comment]
Hello Sonia,  
You should set `worksheet.OutLineSummaryBelow = false;` to get the buttons at the top.

**Comment by SoniaRicci** [comment]
Hi JanKallaman, it works!!
Thanks a lot for your help
Sonia
