### ISSUE TITLE
Open and read documents with different regional settings.

### ISSUE THREAD

**Issue by anarro** [EPPlusSoftware/EPPlus#61]
Hello, I am trying your library and I have many problems with the different regional configuration formats, I need to open and read documents with the European configuration (dd / MM / yyyy) and (1,000.15%) and there is no way.., Where can I indicate what format to use?, could you be told when opening the document?

Thank you for your great job!

**Comment by JanKallman** [comment]
Hello, 
I wrote a little bit about number formats in the wiki, [here](https://github.com/EPPlusSoftware/EPPlus/wiki/Formatting-and-styling)…
Unsure if this helps you or not. 
Please note that if you use our Commercial version of EPPlus 5, you can ask more support related questions at our support service.
