### ISSUE TITLE
Does the EPPlus support the ods format?

### ISSUE THREAD

**Issue by balkarov** [EPPlusSoftware/EPPlus#610]
Hello. 

Thank you for your library.

I found that EPPlus supports ods format by [link](https://products.fileformat.com/spreadsheet/net/epplus/).
But how can I generate ods format?

**Comment by JanKallman** [comment]
No, EPPlus do not support the ods format, only the Office Open XML format (xlsx, xlsm and xlst). We have currently no plans to support the ods file format in the near future
