### ISSUE TITLE
PIVOT TABLE NOT SHOWING IN PROTECTED VIEW

### ISSUE THREAD

**Issue by zolaikhahammad** [EPPlusSoftware/EPPlus#613]
Pivot table is not showing when file is downloaded via internet and by default downloaded in protected view. Is it the library related issue if yes? then how long it will take to resolve ?
![EPPLUSPIVOTISSUE](https://user-images.githubusercontent.com/70544823/158596899-bf7b07b0-f04a-4ad9-80c7-18d1e7d03e76.PNG)

**Comment by JanKallman** [comment]
No, EPPlus don't currently calculate pivot tables, so it relies on Excel to do that. We'll likely implement this in the future, but it's currently not on the roadmap.
