### ISSUE TITLE
Read Excel Worksheets is Zero

### ISSUE THREAD

**Issue by itcsdnnet** [EPPlusSoftware/EPPlus#620]
![image](https://user-images.githubusercontent.com/41314183/161188938-89da35bc-e03e-4cba-8951-d2c8888fc6b3.png)
As shown in the figure, read the file provided by the customer, the worksheets is 0, there is no problem in creating a new locally, and there is no problem in copying the content of the customer document to the local

**Comment by itcsdnnet** [comment]
[1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/8395078/1.xlsx)
可以使用此文档测试

**Comment by JanKallman** [comment]
Please use english

**Comment by JanKallman** [comment]
The attached file is corrupt and cannot be opened in Excel. It only contains a theme and no worksheet data, if you unzip it.
