### ISSUE TITLE
Calculation problem sum with enabled autofilter

### ISSUE THREAD

**Issue by Aurelianus** [EPPlusSoftware/EPPlus#623]
Hi,

i'm facing a problem when applying sum function over an auto filtered range.

The following tests work until version 5.8.3, since 5.8.4 until 6.0.2-beta the second will fail.

I did not found the root, sorry.

```
        [TestMethod]
        public void SumWithAutoFilter()
        {
            using (var p = new ExcelPackage())
            {
                var ws = p.Workbook.Worksheets.Add("test");
                ws.Cells["A1"].Value = 1.0;
                ws.Cells["B1"].Formula = "A1";
                ws.Cells["D1"].Formula = "IF(AND(A1=0,B1=0,C1=0),\"no\",\"yes\")";

                ws.Cells["B2"].Formula = "A2";                                
                ws.Cells["D2"].Formula = "IF(AND(A2=0,B2=0,C2=0),\"no\",\"yes\")";

                var filterRange = ws.Cells["A1:D2"];
                filterRange.AutoFilter = true;
                var filter = ws.AutoFilter.Columns.AddValueFilterColumn(3);
                filter.Filters.Add(new ExcelFilterValueItem("yes"));
                ws.AutoFilter.ApplyFilter();

                ws.Cells["B4"].Formula = "SUM(B1:B2)";

                ws.Calculate();
                Assert.AreEqual(1d, ws.Cells["B4"].Value);
            }   
        }
        [TestMethod]
        public void SumWithAutoFilter_Fail()
        {
            using (var p = new ExcelPackage())
            {
                var ws = p.Workbook.Worksheets.Add("test");
                ws.Cells["A2"].Value = 1.0;
                ws.Cells["B2"].Formula = "A2";
                ws.Cells["D2"].Formula = "IF(AND(A2=0,B2=0,C2=0),\"no\",\"yes\")";

                ws.Cells["B3"].Formula = "A3";
                ws.Cells["D3"].Formula = "IF(AND(A3=0,B3=0,C3=0),\"no\",\"yes\")";

                var filterRange = ws.Cells["A1:D3"];
                filterRange.AutoFilter = true;
                var filter = ws.AutoFilter.Columns.AddValueFilterColumn(3);
                filter.Filters.Add(new ExcelFilterValueItem("yes"));
                ws.AutoFilter.ApplyFilter();

                ws.Cells["B4"].Formula = "SUM(B2:B3)";

                ws.Calculate();
                Assert.AreEqual(1d, ws.Cells["B4"].Value);
            }
        }
```

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this.

**Comment by JanKallman** [comment]
Hello,
This happens as the auto filter is applied on a column that contains a formula. When applying the filter the value of the cells in column 3 is all null, as they are not yet calculated. This causes the filter to hide row 2 and 3, and later cause the sum function to return 0. Adding Calculate before the ApplyFilter will solve this issue:
```C#
ws.Calculate(); //Calculates the values, so the filter can be applied
ws.AutoFilter.ApplyFilter();

ws.Cells["B4"].Formula = "SUM(B2:B3)";

ws.Cells["B4"].Calculate();
```
This likely worked in earlier versions as EPPlus had a bug that ignore hidden rows in the Sum function. We could consider adding a parameter to the ApplyFilter method to calculate the range before applying the filters.

**Comment by Aurelianus** [comment]
Hy,
thank you for your quick response. It wasn't obvious that i have to calculate before filtering. I guess this works with MsExcel because of the auto calculation feature.
Maybe to clearify this a parameter to ApplyFilter could hint at this unexpected behaviour or ApplyFilter always calculates if needed because it cannot filter if the values are not calculated thus it did not working as expected.

Thanks a lot.

**Comment by Aurelianus** [comment]
Hy Jan, why did you introduce "ignore hidden rows in the sum function"? Microsoft Excel does not do this.

**Comment by JanKallman** [comment]
Yes, a parameter will likely be the best solution, as you might not always want/need to perform a calculation when applying the filters.

**Comment by JanKallman** [comment]
Paramerter bool calculateRange=false added to the method ExcelAutoFilter.ApplyFilter in version 6.0.3.
