### ISSUE TITLE
Formula empty string problem

### ISSUE THREAD

**Issue by emrahdincadam-fisg** [EPPlusSoftware/EPPlus#625]
Hi,

I am facing an issue with calculation of Text functions like _LEN, UPPER, FIND, LEFT_ etc.  EPPLUS gives an error and value becomes {#VALUE!} if the value inside the formula is empty. But Excel doesn't give an error so I can't have the same result as Excel. I think EPPLUS behaves this blank values as NULL value and throws an error. I have to change all the formulas and have to add ISBLANK function to check if the value is blank or not and this situation leads the formulas to be more complex.

For example : 

The first formula below works fine with Excel but EPPLUS gives {#VALUE!}  when the field is empty. So we have to check if the value is blank or not for each formula (Second formula works fine for both Excel and EPPLUS).

=CONCATENATE(PROPER('DATA ENTRY'!BQ2)," (",UPPER('DATA ENTRY'!BR2),")")

=CONCATENATE(IF(ISBLANK('DATA ENTRY'!BQ2),"",PROPER('DATA ENTRY'!BQ2))," (",IF(ISBLANK('DATA ENTRY'!BR2),"",UPPER('DATA ENTRY'!BR2)),")")

Is there a way/option with EPPLUS to handle these values as empty not null or can it be added to calculation options as in the **PrecisionAndRoundingStrategy** that has DotNet and Excel options?

Thanks and regards,
ED

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this.

**Comment by swmal** [comment]
From what I could see it was the UPPER and LOWER functions that didn't handle empty cells correctly. I have fixed this and it will be included in the next release. You can test it via our development nuget feed if you like. https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by swmal** [comment]
This is included in the latest release 5.8.9
