### ISSUE TITLE
Azure App Configuration

### ISSUE THREAD

**Issue by vasnick** [EPPlusSoftware/EPPlus#628]
App keys _LicenseContext_ and _IsWorksheets1Based_ is not working when using Azure App configuration for Azure function using .Net 6.0. It works when having the configuration in json format in appsettings.json but not when having keys like EPPlus:ExcelPackage.LicenseContext in Azure App configuration.
Azure App configuration works for MVC application written in .Net 4.7. 

Using EPPlus version 6.0.3

**Comment by JanKallman** [comment]
LicenseContext can be set via the Environment variable `EPPlusLicenseContext` (EPPlus reads the user and process target), if you user Azure Application Settings.
`IsWorksheets1Based` can not be set this way, so you will have to set it via the ExcelPackage.Compatibilty.IsWorksheets1Based property for now, if you can't use the config files. We can look at setting IsWorksheets1Based via environments as well property as well.

**Comment by swmal** [comment]
We have added better support for setting this property via configuration in v 6.0.7. This includes the possibility to specificy filename and location for your configfile. See [this wiki article](https://github.com/EPPlusSoftware/EPPlus/wiki/Configuration)
