### ISSUE TITLE
'sheet.HeaderFooter.EvenFooter.RightAlignedText' cannot be followed by a line break in text by adding \n

### ISSUE THREAD

**Issue by kelicto** [EPPlusSoftware/EPPlus#631]
Automatically cleans up the line break symbols after the text, but it seems to work properly at the very beginning for me.

My current version 4.5.3.3, if there is a way to simply remedy this, please let me know, thanks.

**Comment by kelicto** [comment]
Nice! So, we could use `ㅤ` to fix it. Of course, It's only a patch.

**Comment by JanKallman** [comment]
I have applied a fix for this. Try it using our develop nuget feed...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by kelicto** [comment]
@JanKallman Why don't use `xml:space="preserve"` to fix? This attribute confuses me and I don't know what the correct way to use it is. Although I have consulted some information, I am still confused.
