### ISSUE TITLE
FileStream may be left open on exception

### ISSUE THREAD

**Issue by arnileibovits** [EPPlusSoftware/EPPlus#640]
https://github.com/EPPlusSoftware/EPPlus/blob/861926c1f9afb0ac91853aa5f8abf2e52df322b6/src/EPPlus/ExcelPackage.cs#L885

If an exception should occur during `Write`, the `FileStream` will not be disposed and will remain open (with file locked) for an undetermined time.

The proper way to open streams is with a `using` scope.

**Comment by JanKallman** [comment]
Yes, thanks, I'll add a fix for this.

**Comment by JanKallman** [comment]
Fixed in 5.8.10 and 6.0.4
