### ISSUE TITLE
SumIf with empty string parsing

### ISSUE THREAD

**Issue by Aurelianus** [EPPlusSoftware/EPPlus#642]
Hi,
it looks like that the fix for Issue #624 is not complete.

1) [EPPlusTest.FormulaParsing.Excel.Functions.Math.SumIfTests].**SumIfEqualToEmptyString** fails if the formula has to be parsed
2) It is possible to select empty cells with operator "=" as opposite to "<>" (unequal thus unempty). See Formlua B4 (works in Ms Excel)

```
[TestMethod]
public void SumIfEqualToEmptyString_Parser()
{
    using (var pck = new ExcelPackage())
    {
        var sheet = pck.Workbook.Worksheets.Add("test");
        _worksheet.Cells["A1"].Value = null;
        _worksheet.Cells["A2"].Value = string.Empty;
        _worksheet.Cells["A3"].Value = "Not Empty";
        _worksheet.Cells["B1"].Value = 1d;
        _worksheet.Cells["B2"].Value = 3d;
        _worksheet.Cells["B3"].Value = 5d;

        sheet.Cells["B4"].Formula = "SUMIF(A1:A3,\"=\",B1:B3)";
        sheet.Cells["B5"].Formula = "SUMIF(A1:A3,\"\",B1:B3)";
        sheet.Calculate();
        Assert.AreEqual(4d, sheet.Cells["B4"].Value);
        Assert.AreEqual(sheet.Cells["B4"].Value, sheet.Cells["B5"].Value);
    }
}
```

3) Parsing like in (1) applies for [EPPlusTest.FormulaParsing.Excel.Functions.Math.SumIfTests].**SumIfNotEqualToNull** as well
Following test fails

```
[TestMethod]
public void SumIfNotEqualToNull_Parser()
{
    using (var pck = new ExcelPackage())
    {
        var sheet = pck.Workbook.Worksheets.Add("test");
        _worksheet.Cells["A1"].Value = null;
        _worksheet.Cells["A2"].Value = string.Empty;
        _worksheet.Cells["A3"].Value = "Not Empty";
        _worksheet.Cells["B1"].Value = 1d;
        _worksheet.Cells["B2"].Value = 3d;
        _worksheet.Cells["B3"].Value = 5d;

        _worksheet.Cells["B4"].Formula = "SUMIF(A1:A3,\"<>\",B1:B3)";
        _worksheet.Calculate();
        Assert.AreEqual(8d, sheet.Cells["B4"].Value);
    }
}
```

Thanks

**Comment by Aurelianus** [comment]
Hi,
unfortunately the fix
https://github.com/EPPlusSoftware/EPPlus/commit/7c87e0063a21c411a73509289316219e0e6c1baf

is not complete.

Point (2) uploaded test case
      ```
  [TestMethod]
        public void SumIfEqualToEmptyString_Parser()
        {
            using (var pck = new ExcelPackage())
            {
                var sheet = pck.Workbook.Worksheets.Add("test");
                sheet.Cells["A1"].Value = null;
                sheet.Cells["A2"].Value = string.Empty;
                sheet.Cells["A3"].Value = "Not Empty";
                sheet.Cells["B1"].Value = 1d;
                sheet.Cells["B2"].Value = 3d;
                sheet.Cells["B3"].Value = 5d;

                sheet.Cells["B4"].Formula = "SUMIF(A1:A3,\"=\",B1:B3)";
                sheet.Cells["B5"].Formula = "SUMIF(A1:A3,\"\",B1:B3)";
                sheet.Calculate();
                Assert.AreEqual(1d, sheet.Cells["B4"].Value);
                Assert.AreEqual(4d, sheet.Cells["B5"].Value);
            }
        }
```
Formula B4 and B5 will do the same and sum all lines if column a is empty. Thus the expected value is B1+B2 = 4.

Point 3 above, i made a misstake. The expected result is 5 = B3. The operator <> means is not blank and function IsBlank is true if the value is null oder string.Empty.

**Comment by swmal** [comment]
Thanks, I’ll have another look.

**Comment by swmal** [comment]
Hi @Aurelianus ,

From what I can see Excel calculates this example with the same results as the current version of EPPlus. See this screenshot where I have used these two unit tests to create a workbook, removed the EPPlus Calculate call and let Excel do the calculation:

![image](https://user-images.githubusercontent.com/897655/169758918-0ea8fe91-8555-4ac1-9297-221f5a39c809.png)

Do you get a different result or maybe I'm misunderstanding something?

**Comment by Aurelianus** [comment]
Hi @swmal 
you are right. I thought that string.Empty equals null but its not. I could create such a file with empty string via single quote and it equals in xml structure the EPPlus file with `<v>0</v>` for empty string and no tag for empty.

The ISBLANK function returns false for empty string as well thus its logically consistent.

Thanks for helping me out.
