### ISSUE TITLE
ExcelWorksheet.InsertRow is slow.

### ISSUE THREAD

**Issue by guogangj** [EPPlusSoftware/EPPlus#653]
I called ExcelWorksheet.InsertRow many times in the loop to insert new rows, from the first row2 until row2000+, I found that the execution of InsertRow is getting slower and slower, I used tick count, its time consumption is roughly the following chart:
![image](https://user-images.githubusercontent.com/6103026/169675558-92b410ad-64b8-4723-97cd-b5b7ddb65514.png)
However, in EPPlus 4.x, this phenomenon is not obvious and InsertRow execution in EPPlus 4.x is faster.

**Comment by JanKallman** [comment]
This depends on many things, as EPPlus 5+ adjust formulas, named ranges, conditional formatting, data validations and a lot of other things that EPPlus 4 didn't update correctly. I'm not sure how the workbook you have performed the test looks like?

**Comment by JanKallman** [comment]
Yes, the reading and writing to the xml takes a lot of performance when adjusting drawing sizes. We'll see if we can move the xml read/write to load and save of the drawings instead.
