### ISSUE TITLE
ExcelWorksheet.InsertRow breaks the shape of existing images.

### ISSUE THREAD

**Issue by guogangj** [EPPlusSoftware/EPPlus#654]
I use ExcelWorksheet.InsertRow to generate an Excel document from a template document. And I have several images in the template document. I found that images' size would be changed after the InserRow method was called. Like this:
![image](https://user-images.githubusercontent.com/6103026/169676096-aa0571ba-88a7-447e-ab5a-ad6da2906e67.png)

**Comment by guogangj** [comment]
Additional notes: EPPlus 4.x is fine. Both EPPlus 5.x and 6.x have this issue.

**Comment by JanKallman** [comment]
Can you attach the workbook you use as template?

**Comment by guogangj** [comment]
> Can you attach the workbook you use as template?
Okay, it's here:
[export_template1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/8755317/export_template1.xlsx)

**Comment by JanKallman** [comment]
Please try latest develop build... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by JanKallman** [comment]
This is fixed in version 5.8.11 and 6.0.5
