### ISSUE TITLE
Set the column width value to automatically modify other values

### ISSUE THREAD

**Issue by kelicto** [EPPlusSoftware/EPPlus#655]
The value set for the width of the column is 10, and when I open Excel, I find that the value inside is 9.29. I knew that Excel would automatically modify the values, but not too much, but using the API revealed some rather large differences.

```C#
for (var i = 0; i < 13; i++)
{
    sheet.Column(i + 1).Width = 10;
}
```

**Comment by JanKallman** [comment]
The value in Excel and the value in the ooxml file is not the same. You can read about converting the width value in the ooxml documentation: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.column?view=openxml-2.8.1

**Comment by kelicto** [comment]
Totally understand, thanks.

**Comment by kelicto** [comment]
Hi, @JanKallman! I read the documentation and it's great. But I have a doubt, what is 'Truncate' and what is the corresponding conversion in the .net library? What will happen if I don't use it?

**Comment by JanKallman** [comment]
You can use `Math.Truncate`

**Comment by kelicto** [comment]
So, Equivalent to Math.Floor(double).

**Comment by kelicto** [comment]
I'm currently working on this problem and I've run into a very fatal problem. Damn Excel always floats and adjusts the value I want (+/-0.5) against my will. Makes my wish (full fill) fall through.
For example, I want the value of the column in Excel to be 9.36, but when it comes to Excel it gives me a value of 9.29. I have used the formula you told me and tried various formulas, and it never works properly.
Can I write a demo and can you help me analyze the reasons and how I can ensure perfect filling?

**Comment by kelicto** [comment]
```C#
  var excelCharacters = worksheet.ComputeTotalCharacters(13);

  // columns is 13.
  for (var i = 0; i < 13; i++)
  {
      // what?
      var width = 1 / 13 * excelCharacters;

      // Test code, I don't know how to write
      var width2 = Math.Truncate((width * 7 - 5) / 7 * 256) / 256;

      worksheet.Column(i + 1).Width = Convert.ToDouble(width2);
  }

private static double ComputeCharacters(this ExcelWorksheet worksheet, int columns, int dpi = 96)
{
    // A4
    var paper = worksheet.PrinterSettings.PaperSize;

    var paperWidth = 29.7m / 2.54m;

    worksheet.PrinterSettings.LeftMargin = 1.78m / 2.54m;
    worksheet.PrinterSettings.RightMargin = 1.78m / 2.54m;
    worksheet.PrinterSettings.TopMargin = 1.78m / 2.54m;
    worksheet.PrinterSettings.BottomMargin = 1.78m / 2.54m;

    var sideBorder = worksheet.PrinterSettings.LeftMargin + worksheet.PrinterSettings.RightMargin;
    var contentWidth = paperWidth - sideBorder;
    var contentPixels = contentWidth * dpi;

    return Convert.ToDouble(Math.Truncate((contentPixels - 5 * columns) / 7 * 100 + 0.5m) / 100);
}
```
