### ISSUE TITLE
XLSX internal xml files start with a byte order mark

### ISSUE THREAD

**Issue by SebAtMinalea** [EPPlusSoftware/EPPlus#656]
And Excel is not happy about it. Unfortunately I cannot upload the excel file as it contains sensitive data.

`We found a problem with some content in 'xxx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.`

Recovery procedure yields: 
```
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Repaired Part: /xl/workbook.xml part with XML error.  (Workbook) HRESULT 0x8000ffff Line 1, column 0.
```
![image](https://user-images.githubusercontent.com/61281912/170059117-f41c53cf-f99c-406c-93f3-4f389272ece7.png)

Inside the xlsx, the xml files indeed have a BOM (upper: original, lower: "recovered" by excel)
![chrome_FjizLhLyfC](https://user-images.githubusercontent.com/61281912/170058826-aabd1875-d848-4ceb-bce8-19e67854cffe.png)

I suspected the data source to contain invalid unicode characters but it doesn't seem to be the case.

I've been using EPPlus 5.8.1 and upgraded to 6.0.4 but that doesn't make any change.

Any idea what could cause this? Thanks in advance for any hint!

**Comment by JanKallman** [comment]
Is the file created from a template xlsx file or from Scratch? Which xml file are you getting this error from?

**Comment by JanKallman** [comment]
This is likely issue is not due to the byte order in the beginning of the workbook.xml. If you cannot attach the xlsx file, try download the ooxml productivity tool and run a validation of the workbook. It can be downloaded from here ... https://web.archive.org/web/20190116000204/https://www.microsoft.com/en-us/download/details.aspx?id=30425

**Comment by Cebe74** [comment]
Thank you. You're absolutely right, we have a template from which we generate the final report (and unfortunately both are full of personal data so I cannot share them)

I've tried the ooxml productivity tool (which I could find at https://github.com/OfficeDev/Open-XML-SDK) and a Visual Studio Code extension that runs the same (https://marketplace.visualstudio.com/items?itemName=mikeebowen.ooxml-validator-vscode) -- I'm sharing that in case someone else comes across the same problem.

The template has the following validation errors but it opens just fine in Excel

![image](https://user-images.githubusercontent.com/37379498/170969948-618587c5-98b3-4e5d-8666-8c56f2345aaa.png)

The generated file has the same errors plus an additional validation error about pivot table cache -- this file triggers a recovery in excel

![image](https://user-images.githubusercontent.com/37379498/170969532-c6718ffa-1058-4cb5-9a4b-ffa2ca02e3ab.png)

I'd think this pivotCache could be the reason of the error. The others errors can be ignored.

I'll investigate this and document my findings here.

Thanks!

**Comment by SebAtMinalea** [comment]
Thank you. You're absolutely right, we have a template from which we generate the final report (and unfortunately both are full of personal data so I cannot share them)

I've tried the ooxml productivity tool (which I could find at https://github.com/OfficeDev/Open-XML-SDK) and a Visual Studio Code extension that runs the same (https://marketplace.visualstudio.com/items?itemName=mikeebowen.ooxml-validator-vscode) -- I'm sharing that in case someone else comes across the same problem.

The template has the following validation errors but it opens just fine in Excel

![image](https://user-images.githubusercontent.com/37379498/170969948-618587c5-98b3-4e5d-8666-8c56f2345aaa.png)

The generated file has the same errors plus an additional validation error about pivot table cache -- this file triggers a recovery in excel

![image](https://user-images.githubusercontent.com/37379498/170969532-c6718ffa-1058-4cb5-9a4b-ffa2ca02e3ab.png)

I'd think this pivotCache could be the reason of the error. The others errors can be ignored.

I'll investigate this and document my findings here.

Thanks!

**Comment by JanKallman** [comment]
Yes, very likely. But I can't say what is wrong without having the file. Can you remove the sensitive data and attach it here or in the support case? Which EPPlus version are you using?

**Comment by SebAtMinalea** [comment]
I previously tried to remove the sensitive data but it proved to be very tedious... I gave up on that one.  We're using the latest at this time: 6.0.4

However it is solved!

We have a rather complex template which indeed had a pivot table, which should be deleted from the final xlsx file; the author of the template realized he didn't really need this pivot table, and without it indeed works like a charm!

So the excel error line 1 column 0 was very misleading in the end. Thanks for your help!
