### ISSUE TITLE
New Lines in merged cells doesn't work well

### ISSUE THREAD

**Issue by vcastro45** [EPPlusSoftware/EPPlus#66]
If I create a multiline value in a merged CellRange the newline is not displayed in Excel.

Code Example:
```csharp
var cells = sheet.Cells["A1:H3"];
cells.Merge = true;
cells.Value = $"{name}{Environment.NewLine}{title}{Environment.NewLine}{desc}";
```

**Comment by swmal** [comment]
Thanks for reporting, we will have a look at this asap.

**Comment by JanKallman** [comment]
You need to set the Style.WrapText property as well…
`cells.Style.WrapText = true;`
