### ISSUE TITLE
VBA corruption copying worksheet into another workbook

### ISSUE THREAD

**Issue by rolyp** [EPPlusSoftware/EPPlus#665]
I’m seeing corrupted VBA using EPPlus 6.0.3 to open an `.xlsx` file and move a worksheet to another Excel package loaded from an `.xlsm` file.

<img width="1222" alt="Screenshot 2022-06-08 at 10 47 27" src="https://user-images.githubusercontent.com/121074/172587310-9df8da79-b9ec-4ac0-901f-b984a5445d92.png">

A similar issue seems to have been reported on [your previous repo](https://github.com/JanKallman/EPPlus/issues/7).

The steps are:
- open package from `.xlsx` (source)
- retrieve worksheet
- open package from `.xlsm` (target)
- add (copy of) source worksheet to target worksheets
- save target package

**Comment by JanKallman** [comment]
I'll have a look.

**Comment by JanKallman** [comment]
This is basically the same code as I use. Can you attach the workbook(s) you are using.

**Comment by rolyp** [comment]
@JanKallman [Archive.zip](https://github.com/EPPlusSoftware/EPPlus/files/8867730/Archive.zip). Thanks for looking into this.

**Comment by JanKallman** [comment]
Thanks, I have found the issue. This happends when you have vba code that only have LF as EOL symbol. EPPlus expects CRLF. This is likely releated to workbooks saved on MAC. I'll provide a fix for you shortly.

**Comment by rolyp** [comment]
@JanKallman Ah, that would explain the stripped-off character. Thanks -- really appreciate your taking the time to  look into this for us!

**Comment by JanKallman** [comment]
This is fixed in version 5.8.11 and 6.0.5

**Comment by rolyp** [comment]
@JanKallman Amazing. Thanks for the quick turn around and very useful package!
