### ISSUE TITLE
EPPlus differs from Excel with three specific formula conditions

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#666]
I found EPPlus differing from Excel when it encounters a single formula which

1. uses `@Indirect` to access a decimal number, and
2. the indirectly accessed decimal number is formatted as text, and
3. an integer is added (outside the `@indirect` function) 

**Example:** `=@INDIRECT("Link_"&A1,TRUE)+2`

All three aspects seem required, as I tested these permutations:

- using `@indirect` to access a number formatted as text works as expected
- adding some integer to an indirect accessed number formatted as a number works as expected
- adding some integer to a number formatted as text works as expected

Can you take a look at the attached spreadsheet and sample code? It replicates A) the more complicated scenario in which this behavior was found and B) the simplest, minimal example I could come up with. 

Here's the sample code I used with the attached file.
```
string filepath = @"C:\IndirectSample.xlsx";
ExcelPackage.LicenseContext = LicenseContext.Commercial;
ExcelCalculationOption o = new ExcelCalculationOption();
o.AllowCircularReferences = false;
o.PrecisionAndRoundingStrategy = PrecisionAndRoundingStrategy.Excel;
using (var package = new ExcelPackage(new FileInfo(filepath)))
{
    try
    {
        package.Workbook.Calculate(o);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C2"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C3"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C4"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C5"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C6"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C7"].Value);
        Trace.WriteLine(package.Workbook.Worksheets["ref"].Cells["C8"].Value);                    
    }
    catch (Exception e)
    {
    }
}
```
[IndirectSample.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/8866920/IndirectSample.xlsx)

I pulled down commit 6854ceb4a3e9ca0ca8c18a9162561f771fb6b0dc to recreate this issue.

Thank you for your time and being just generally awesome.

**Comment by swmal** [comment]
This should be solved now, will be included in next version of both v 5 and 6.
