### ISSUE TITLE
Threaded comments causing crash

### ISSUE THREAD

**Issue by R4cOOn** [EPPlusSoftware/EPPlus#667]
[TestFile.zip](https://github.com/EPPlusSoftware/EPPlus/files/8870541/TestFile.zip)

Hi,

I'm processing an Excel file that contains threaded comments (made with the "new comment" instead of the "new note" menu item in Excel).
There's a NullPointerException that comes up.
Deleting the comment makes the error go away.

I'm using 6.0.4 with a commercial license on .NET Core 6.0

I attached a sample solution that reproduce the issue using the part of the code from our production system that triggers the error.

**Comment by swmal** [comment]
Thanks for reporting, we will have a look at this.

**Comment by JanKallman** [comment]
When clearing a range the comment(Note in Excel) used by the threaded comment for backward compatibility is deleted before the actual threaded comment. When deleting the treaded comment, no check is made that this comment exist, causing an exception. I'll provide a fix shortly.

**Comment by JanKallman** [comment]
This is fixed in version 5.8.11 and 6.0.5
