### ISSUE TITLE
Copy/duplicate a NamedRange from one workbook to another?

### ISSUE THREAD

**Issue by ses4j** [EPPlusSoftware/EPPlus#668]
I cannot find in documentation (or code) a good way to create a Named Range based on a 'template' in another Workbook.

https://stackoverflow.com/a/51432674/237091 seemed useful but no longer works.

I have something like this, but the parser is too weak.

```
foreach (var name in mergePackage.Workbook.Names)
{
    var splitAddr = name.Address.Split(new char[] { '!' }, 2);
    var ws = outputPackage.Workbook.Worksheets[splitAddr[0]];
    var range = ws.Cells[splitAddr[1]];

    outputPackage.Workbook.Names.Add(name.Name, range);

}```

**Comment by JanKallman** [comment]
There is currently no function to copy a named range from one package to another, so you will have to do it manually like you do. 
Worksheet Names are copied if you copy the entire worksheet.
