### ISSUE TITLE
Corrupted Copied Sheets

### ISSUE THREAD

**Issue by A-Shawqi** [EPPlusSoftware/EPPlus#673]
Hello,
I'm using the following function to copy a sheet multiple times but the copied sheets are corrupted while using the attached excel file and it throws the following exception in other cases as shown in the below image.
![image](https://user-images.githubusercontent.com/17937102/175181680-7370e5a5-6629-4210-8983-ad0979371b62.png)
![image](https://user-images.githubusercontent.com/17937102/175182104-d28e990b-6327-42ae-8b37-201f56b6c958.png)

`OfficeOpenXml.ExcelWorksheets  public ExcelWorksheet Copy(string Name, string NewName)`
[TestCopySheet.zip](https://github.com/EPPlusSoftware/EPPlus/files/8962621/TestCopySheet.zip)

**Comment by JanKallman** [comment]
Please provide some code to reproduce this issue.

**Comment by A-Shawqi** [comment]
Herein a simple test method that throws the null exception
![image](https://user-images.githubusercontent.com/17937102/175257279-4cd4a14d-ed02-4379-a18c-e2b44bee2515.png)

      ```
 [TestMethod()]
        public void CopySheetNullExceptionTest()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using var excelPackage = new ExcelPackage(new FileInfo("TestCopySheet.xlsm"));
            excelPackage.Workbook.Worksheets.Copy(excelPackage.Workbook.Worksheets.First().Name, "copied sheet");
            excelPackage.SaveAs(new FileInfo("OutputFile.xlsm"));
        }
```

**Comment by JanKallman** [comment]
It seems to work when I try it. Which version are you using? Which Environment (Windows, Linux), Regional settings (CultureInfo)?
