### ISSUE TITLE
Performance creating an ExcelPackage with EPPlus drops dramatically when using ExcelGenerator.Cells[x,y].AddComment

### ISSUE THREAD

**Issue by hedenm** [EPPlusSoftware/EPPlus#679]
We're creating an ExcelPackage with EPplus in our .NET MVC WebApplication. The number of rows is about 180 and the number of columns is 90. Not all cells have content, but I think we are filling about 10.000 cells. 

The problem is: When we don't add comments to the cells it takes 1 minute to generate the package. 
But when we do add comments to the cells (see code below)  it takes 3 minutes! And when we increase the amount of rows or columns we even get an Out-Of-Memory exception in our WebApp. What is causing this big perfomance drop when we use addComment? Is there another way to add comments with EPPlus?

```
var comment = _worksheet.Cells[rn, _col].AddComment($"{act.LeesbareTijden} \r\n" +
                 locatieNaam +
                 $"{act.Activiteittype.Naam}\r\n" +
                 $"{act.Omschrijving}"
               );                            
comment.AutoFit = true;

**Comment by JanKallman** [comment]
Yes, comments will likely be slower as it works with the XML DOM to update the data. Comments has separate xml files with both a CommentX.xml and a vml file for the drawing. We should likely look at an alternative way of working with these files to get better performance. I'll add this as an enhancement.

**Comment by hedenm** [comment]
> Yes, comments will likely be slower as it works with the XML DOM to update the data. Comments has separate xml files with both a CommentX.xml and a vml file for the drawing. We should likely look at an alternative way of working with these files to get better performance. I'll add this as an enhancement.

**Comment by hedenm** [comment]
Thank you for your answer, Jan. Could this also be the reason that we get an out-of-memory exception when we export toom many rows and cells? 
Regards, 
Martijn

**Comment by hedenm** [comment]
Jan, Thank you, We're allready building for Any CPU ánd are using the latest version of EPPlus.
But we will solve it by using a webjob for large excelsheets.

But now I have another error: I have upgraded all the NuGet Packages that we use in our Solution, but when we try to create an export we get the following error: 
![image](https://user-images.githubusercontent.com/10180276/178998115-b696d90d-32a2-40a7-9c68-fad77d63f5fa.png)
I have checked if the Microsoft.IO.RecycableMemoryStream is installed and even re-installed this package ánd the EPPlus package but that doesn't seem to fix the problem

**Comment by JanKallman** [comment]
Try to clean your solution and Delete the /bin and /obj folder in your project folders to make sure older references are removed.

**Comment by hedenm** [comment]
Hello Jan,
It turned out that we get this problem when we update the package Microsoft.IO.RecycableMemoryStream from 1.4.1 to 2.2.0. So for now we just keep this package on version 1.4.1 and then our problem is solved.
Thanks for thinking with us about our problems!
Regards,
Martijn

**Comment by Coops9** [comment]
I now this ticket is old (but I don't know of a newer ticket) however this seems to have been fixed in a version of EPPlus - I don't know which version but I know I had this exact problem adding 10,000+ comments used 25GB of RAM on EPPlus version 6.2.8

In version 8.6.3 - with the exact same code - the problem did not exist! no additional RAM usage and ran as fast as before - (ran in seconds NOT minutes!)
