### ISSUE TITLE
ExcelRangeBase is not well iterable

### ISSUE THREAD

**Issue by vcastro45** [EPPlusSoftware/EPPlus#68]
I am not sure of how the `ExcelRangeBase` interation should work but in the case where it shoud be iterable over each cell in the range, the iteration is broken when it's over a range in only one column.

Example:
```csharp
foreach (var cell in worksheet.Cells["I5:I8"])
{
     Console.WriteLine("Hello !");
}
```
In this example, nothing is printed in the console.

Workaround:
```csharp
var cells = worksheet.Cells["I5:I8"];
var start = cells.Start;
var end = cells.End;
for (int row = start.Row; row <= end.Row; row++)
{
    for (int col = start.Column; col <= end.Column; col++)
    {
        Console.WriteLine("Hello !");
    }
}
```

**Comment by JanKallman** [comment]
This is by design. `ExcelRangeBase` only iterates cells with values.
Setting `worksheet.Cells["I5:I8"].Value = 1;` will cause the foreach loop to hit the cells in the range.
If you want to iterate both empty and non-empty cells in a range, please use the approach you use above.
