### ISSUE TITLE
Slow performance reading big xlsx files

### ISSUE THREAD

**Issue by LenonBordini** [EPPlusSoftware/EPPlus#682]
I have an excel file with about 40 worksheets (some worksheets contains more than 500.000 rows), and I just need to read the first one getting some cell values by their workbook names.

```csharp
// It takes about 6 seconds
using var ep = new ExcelPackage(new FileInfo("some-file.xlsx"));

// It takes about 20 seconds
var ws = ep.Workbook.Worksheets.First();

var example = ws.Workbook.Names["example_name"].GetValue<string>();
```

I'll read all the worksheets later in background, but I really need the data inside the first worksheet.
Is there a way to read this faster?

**Comment by LenonBordini** [comment]
I had to use the package [ExcelDataReader](https://github.com/ExcelDataReader/ExcelDataReader) for better performance reading only one worksheet. It demands more code, but works nicely.

Let me know if exists a solution with EpPlus please.

**Comment by JanKallman** [comment]
No, EPPlus currently read the entire workbook, so at the moment there is no way of doing this faster.
