### ISSUE TITLE
Review how values read from ranges in defined names corresponds to the current column

### ISSUE THREAD

**Issue by swmal** [EPPlusSoftware/EPPlus#686]
Scope: formula calculation

Description of this functionality:

Add a name to the workbook and let it refer to a range with a locked address.

**1. If the range has multiple rows**
If you use this name in a cell on another worksheet than the range refers to(in newer Excel versions the @-operator must be used) the corresponding value will be fetched. If the cell contining the name is out side the corresponding range a #VALUE error will be returned.

**2. If the range has only one row**
You can use the name in any other row, the value will be fetched from the corresponding column.

In newer Excel versions there will be spillover if the @-operator is not used.

This issue needs more investigation and there is no quick fix for it. Will most likely be implemented in 6.1 or 6.2.

**Comment by JanKallman** [comment]
Fixed in EPPlus 7
