### ISSUE TITLE
Issue with INDEX formula when used with SUM

### ISSUE THREAD

**Issue by kulesshhh** [EPPlusSoftware/EPPlus#688]
I am trying to use the **SUM** of a range by using **INDEX** method inside it. For e.g. **=SUM(B2:INDEX(A2:C6, 5, 2)).** 
This is working fine in excel sheet but giving error result through my code. 

I was trying to understand the issue and it seems that INDEX just returns value of the cell in EPPLUS. However, It should return the _cell reference_ when used in conjunction with the **SUM or SUMIFs** formula.

If you look at the Microsoft documentation for INDEX formula: _"It can return value of the cell as well as reference of the specified cells"_
[https://support.microsoft.com/en-us/office/index-function-a5dcf0dd-996d-40a4-a822-b56b061328bd#__reference_form](https://support.microsoft.com/en-us/office/index-function-a5dcf0dd-996d-40a4-a822-b56b061328bd#__reference_form)

Looking forward for resolution or this issue

**Comment by swmal** [comment]
Hi,

Assuming that this refers to the calculation capabilities of EPPlus.

We are aware of this and support for the INDEX function (and more functions) in addresses is under development and will be included in the next minor version (6.1).

**Comment by swmal** [comment]
Just an update on this issue, this will be included in the next major version (EPPlus 7), which will have a rewritten calculation engine.

**Comment by mlankamp** [comment]
Too bad, was hoping this would come sooner. Any workaround?

**Comment by JanKallman** [comment]
Implemented in EPPlus 7
