### ISSUE TITLE
Columns collapsing doesn't work.

### ISSUE THREAD

**Issue by milestonefollower** [EPPlusSoftware/EPPlus#694]
Setting `ExcelColumn.Collapsed = true` doesn't make columns collapsed, in a way it works for `ExcelRow`

Test case:
1. Use sampled code:
```cs
using OfficeOpenXml;

ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

using var excel = new ExcelPackage();
var wb = excel.Workbook;
var ws = wb.Worksheets.Add("test");

for (var colNum = 1; colNum <= 5; colNum++)
{
    ws.Cells[1, colNum].Value = $"Column_{colNum}";
    ws.Column(colNum).OutlineLevel = 1;
    ws.Column(colNum).Collapsed = true;
}

using FileStream fs = new FileStream("test.xlsx", FileMode.OpenOrCreate, FileAccess.ReadWrite);
excel.SaveAs(fs);
```

2. Check created file "test.xlsx".

Expected result:
When opening file, columns should be collapsed.
![image](https://user-images.githubusercontent.com/111522803/185443249-a47a706c-8260-40d0-87bc-225d20a175cb.png)

Actual result:
Columns are expanded:
![image](https://user-images.githubusercontent.com/111522803/185443384-5da5e12b-780b-4a64-b277-c54bb811fa5e.png)

**Comment by JanKallman** [comment]
I'll have a look

**Comment by JanKallman** [comment]
The collapsed property does not automatically set the column as hidden. For now, set the Hidden property as well as the Collapsed property:
`ws.Column(colNum).Hidden = true;`
We will have a look at this behavior as it not what is expected.

**Comment by JanKallman** [comment]
See the new methods added in EPPlus 6.1... https://github.com/EPPlusSoftware/EPPlus/wiki/Grouping-and-Ungrouping-Rows-and-Columns
