### ISSUE TITLE
Copying comments causes duplicate attributes

### ISSUE THREAD

**Issue by R4cOOn** [EPPlusSoftware/EPPlus#698]
[TestFile.zip](https://github.com/EPPlusSoftware/EPPlus/files/9393970/TestFile.zip)

Hi,

We noticed that copying comments sometimes causes duplicate XML attributes.  
We also noticed that some caused duplicate "spids" in the vmlDrawing part but 
we couldn't find an easy way to reproduce the issue (for now).

Please find attached a small sample that reproduces the error.  
I run the same validation before and after copying the lines.

Cheers.

**Comment by JanKallman** [comment]
I'll have a look at it.

**Comment by JanKallman** [comment]
This should be fixed in latest develop. You can try it using our develop Nuget feed ...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by JanKallman** [comment]
Fixed in 5.8.13 and 6.0.7
