### ISSUE TITLE
Hidden Rows & Columns on xlsx saved by LibreOffice6+ are not detected

### ISSUE THREAD

**Issue by Wortex17** [EPPlusSoftware/EPPlus#70]
When creating an xlsx file with LibreOffice 6.4.2 (ealryer 6.x version were also affected), opening the xlsx file via EPPlus will not detect the hidden rows and columns as hidden.

* Opening and saving the file will therefore make the rows/columns visible again
* Inspecting the sheet e.g. ```worksheet.Row(2)``` also shows ```false```
* You may download & inspect the [example file](https://www.dropbox.com/s/fp64oab5k7ebnv4/LibreOfficeHiddenRowsAndColumns.xlsx?dl=0) which has row 2 and column B hidden 

I'm aware this might be a fault on LibreOffice's side, but it would probably be easier to fix it in EPPlus to have broader format compatibility. For reference:
* Opening the file in OpenOffice detects & retains the hidden state
* Importing the file in Google Spreadsheets detects & retains the hidden state
* Uploading & Opening the file in Microsoft Office 356 / Office Online Excel detects & retains the hidden state
* I am not able to verify non-cloud Microsoft Office Excels behaviour, as I do not have any license for it

**Comment by JanKallman** [comment]
LibreOffice set the hidden attribute (and other boolean attributes) using the value `true` / `false`, while Excel uses 1 / 0.
For example:
`<col width="11.52" style="0" min="2" max="2" outlineLevel="0" hidden="true" customWidth="false" collapsed="false"/>`
I'll add a fix for this shortly.

**Comment by JanKallman** [comment]
Fixed in version 5.1
