### ISSUE TITLE
Corrupted file when trying to add new column

### ISSUE THREAD

**Issue by irvalchev** [EPPlusSoftware/EPPlus#701]
Hello,

I have been trying to add a column in a table and the file got corrupted. Here is the sample code and the workbook to reproduce the issue. I have removed a lot of the workbook's content that is attached here, but the issue happens exactly the same on the attached one as well as the original unmodified one.

`
            using ExcelPackage excelPackage = new ExcelPackage(@"FMEDA_Arduino_UNO_Rev3_1658488649636.xlsx");
            ExcelTable partsTable = excelPackage.Workbook.Worksheets
                .SelectMany(x => x.Tables)
                .SingleOrDefault(x => x.Name == "TblComponents");

            if (!partsTable.Columns.Any(x => x.Name == "TEST"))
            {
                partsTable.Columns.Add();
                var newCol = partsTable.Columns.Last();
                excelPackage.Save();
            }
`

[FMEDA_Arduino_UNO_Rev3_1658488649636.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/9426298/FMEDA_Arduino_UNO_Rev3_1658488649636.xlsx)

**Comment by JanKallman** [comment]
I'll have a look at this.

**Comment by JanKallman** [comment]
This seems to work in latest develop (EPPlus 6.0.6). I think we have fixed an issue like this in previous versions. Which version are you using?

**Comment by irvalchev** [comment]
I am using 6.0.6. Here is a screenshot of the Excel log:

![image](https://user-images.githubusercontent.com/2835895/187163889-5d6fd8b7-c9f8-414b-80f0-adbe53b82005.png)

And here the corrupted file that I get after running the code from above
[FMEDA_Arduino_UNO_Rev3_1658488649636 - Copy.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/9443156/FMEDA_Arduino_UNO_Rev3_1658488649636.-.Copy.xlsx)

**Comment by JanKallman** [comment]
Yes, seems to be a problem with the print titles in one of the worksheets. I'll see if I can provide a fix.

**Comment by JanKallman** [comment]
Fixed in 5.8.13 and 6.0.7
