### ISSUE TITLE
ToDataTable method of ExcelRange with the same start and end rowindex throws an error

### ISSUE THREAD

**Issue by kadir133** [EPPlusSoftware/EPPlus#703]
When I want to convert a range with the same start and end rows to a datatable, although I say "FirstRowIsColumnNames = false" in the options, the validate method in the "DataTableExporter" class throws an error: System.IndexOutOfRangeException: 'SkipNumberOfRowsEnd was out of range: 0'

When I examine the code, there is no FirstRowIsColumnNames control in the validate method. Could this be the cause of the error?

Class codes:

    public void Export()
    {
          int num = (_options.FirstRowIsColumnNames ? (_range.Start.Row + 1) : _range.Start.Row);
          Validate();
          ...
    }

    private void Validate()
    {
          if (_options.SkipNumberOfRowsStart < 0 || _options.SkipNumberOfRowsStart >= _range.End.Row)
          {
              throw new IndexOutOfRangeException("SkipNumberOfRowsStart was out of range: " + _options.SkipNumberOfRowsStart);
          }
          
          if (_options.SkipNumberOfRowsEnd < 0 || _options.SkipNumberOfRowsEnd >= _range.End.Row - _range.Start.Row)
          {
              throw new IndexOutOfRangeException("SkipNumberOfRowsEnd was out of range: " + _options.SkipNumberOfRowsEnd);
          }
        
          if (_options.SkipNumberOfRowsEnd + _options.SkipNumberOfRowsStart > _range.End.Row - _range.Start.Row)
          {
              throw new ArgumentException("Total number of skipped rows was larger than number of rows in range");
          }
    }

**Comment by swmal** [comment]
Hi,

thanks for reporting, we'll have a look at this.
