### ISSUE TITLE
6.0.7 column order breaks when using more than 16 columns using LoadFromCollection

### ISSUE THREAD

**Issue by bdsoko** [EPPlusSoftware/EPPlus#708]
### To reproduce

```cs
void Main()
{
	using var excel = new ExcelPackage(output);
	{
		var tableData = Enumerable.Range(1, 10)
		.Select(_ => new Columns16
		{
			C01 = 1,
			C02 = 2,
			C03 = 3,
			C04 = 4,
			C05 = 5,
			C06 = 6,
			C07 = 7,
			C08 = 8,
			C09 = 9,
			C10 = 10,
			C11 = 11,
			C12 = 12,
			C13 = 13,
			C14 = 14,
			C15 = 15,
			C16 = 16
		}).ToArray();
		var sheet = excel.Workbook.Worksheets.Add("16Columns");
		var table = sheet.Cells["A1"].LoadFromCollection(tableData);
	}
	{
		var tableData = Enumerable.Range(1, 10)
		.Select(_ => new Columns17
		{
			C01 = 1,
			C02 = 2,
			C03 = 3,
			C04 = 4,
			C05 = 5,
			C06 = 6,
			C07 = 7,
			C08 = 8,
			C09 = 9,
			C10 = 10,
			C11 = 11,
			C12 = 12,
			C13 = 13,
			C14 = 14,
			C15 = 15,
			C16 = 16,
			C17 = 17
		}).ToArray();
		var sheet = excel.Workbook.Worksheets.Add("17Columns");
		var table = sheet.Cells["A1"].LoadFromCollection(tableData);
	}
	{
		var tableData = Enumerable.Range(1, 10)
		.Select(_ => new Columns18
		{
			C01 = 1,
			C02 = 2,
			C03 = 3,
			C04 = 4,
			C05 = 5,
			C06 = 6,
			C07 = 7,
			C08 = 8,
			C09 = 9,
			C10 = 10,
			C11 = 11,
			C12 = 12,
			C13 = 13,
			C14 = 14,
			C15 = 15,
			C16 = 16,
			C17 = 17,
			C18 = 18
		}).ToArray();
		var sheet = excel.Workbook.Worksheets.Add("18Columns");
		var table = sheet.Cells["A1"].LoadFromCollection(tableData);
	}
}

[EpplusTable(PrintHeaders = true, AutofitColumns = true)]
public class Columns16
{

	[EpplusTableColumn(Header = "C01")]
	public int C01 { get; set; }

	[EpplusTableColumn(Header = "C02")]
	public int C02 { get; set; }

	[EpplusTableColumn(Header = "C03")]
	public int C03 { get; set; }

	[EpplusTableColumn(Header = "C04")]
	public int C04 { get; set; }

	[EpplusTableColumn(Header = "C05")]
	public int C05 { get; set; }

	[EpplusTableColumn(Header = "C06")]
	public int C06 { get; set; }

	[EpplusTableColumn(Header = "C07")]
	public int C07 { get; set; }

	[EpplusTableColumn(Header = "C08")]
	public int C08 { get; set; }

	[EpplusTableColumn(Header = "C09")]
	public int C09 { get; set; }

	[EpplusTableColumn(Header = "C10")]
	public int C10 { get; set; }

	[EpplusTableColumn(Header = "C11")]
	public int C11 { get; set; }

	[EpplusTableColumn(Header = "C12")]
	public int C12 { get; set; }

	[EpplusTableColumn(Header = "C13")]
	public int C13 { get; set; }

	[EpplusTableColumn(Header = "C14")]
	public int C14 { get; set; }

	[EpplusTableColumn(Header = "C15")]
	public int C15 { get; set; }

	[EpplusTableColumn(Header = "C16")]
	public int C16 { get; set; }

}

[EpplusTable(PrintHeaders = true, AutofitColumns = true)]
public class Columns17 : Columns16
{
	[EpplusTableColumn(Header = "C17")]
	public int C17 { get; set; }
}

[EpplusTable(PrintHeaders = true, AutofitColumns = true)]
public class Columns18 : Columns17
{
	[EpplusTableColumn(Header = "C18")]
	public int C18 { get; set; }
}
```

From 1 to 16 columns, column order is preserved:
![image](https://user-images.githubusercontent.com/11299552/187529933-94b569c7-3d5b-4b58-ace9-11d6863e9760.png)

More than 16 columns, column order is broken:
![image](https://user-images.githubusercontent.com/11299552/187529980-4cb941a9-5d3f-4c01-bad0-df47fdd6f19e.png)

### Environment
EPPlus Version 6.0.7
Windows 10.0.19044
dotnet 6.0.400

**Comment by swmal** [comment]
Thanks for reporting, we'll have a look at this asap.

**Comment by swmal** [comment]
Hi,
The reason for why this happens at 16 items seems to be how the underlying .NET sort function is implemented. When you are using the EPPlusTableColumn attribute without specifying the sort order all comparisons will evaluate as equal and this is the result.

There is one bug here in EPPlus that we will fix to the next version - when you use the `EPPlusTableColumn` attribute without setting the sortorder EPPlus should use the order that the members are returned in from the Type.GetProperties (i.e. reflection). That would do it for a single class but not neccesarily when you use inheritance as in your example. In the current version this only works if you remove the EPPlusTableColumn attribute, but then you will not get the header.

My advice for now would be to set the sortorder explicitly via the `EPPlusTableColumn` attribute or via the `EPPlusTableColumnSortOrder` (on class level).

Here is how to use the `EPPlusTableColumnSortOrder` on your Columns16 class:

```csharp
[EpplusTable(PrintHeaders = true, AutofitColumns = true)]
[EPPlusTableColumnSortOrder(
	Properties = new string[] {
        	nameof(C01), nameof(C02), nameof(C03), nameof(C04), nameof(C05), nameof(C06), nameof(C07), nameof(C08), nameof(C09), nameof(C10), nameof(C11), nameof(C12), nameof(C13), nameof(C14), nameof(C15), nameof(C16) })
		]
public class Columns16 { ... }
```

and here is how to set the sort order via the `EPPlusTableColumn` attribute:

```csharp
	[EpplusTable(PrintHeaders = true, AutofitColumns = true)]
	public class Columns17 : Columns16
	{
		[EpplusTableColumn(Header = "C17", Order = 17)]
		public int C17 { get; set; }
	}
```
We will provide a fix for the "order as returned via reflection" issue in our develop branch. Will be back here when it is done.

**Comment by swmal** [comment]
See last commit, you can try it out with our development nuget feed. https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by bdsoko** [comment]
I can confirm that the issue is resolved without adding the EPPlusTableColumnSortOrder attribute or updating the EPPlusTableColumn attribute with a Order property.

I did have to refactor my example code to not use inheritance for this to work.

**Comment by swmal** [comment]
Ok, thanks. The fix we added will be included in the next version.
