### ISSUE TITLE
Setting ShowErrorMessage to true in AddListValidation not working in Version 5.

### ISSUE THREAD

**Issue by caloyboy** [EPPlusSoftware/EPPlus#71]
If you follow the AddListValidationFormula function in Sample11 the Error Style, Error Title, and Error gets applied. However, setting the ShowErrorMessage to true defaults back to false in the spreadsheet. 

This code was working back in version 4.5 and the issue started once upgraded to version 5.

**Comment by swmal** [comment]
Thanks for reporting!

Can you help me to replicate this by posting the code that generates this error? I did the following (took the code from the AddListValidationFormula in Sample 12).

```csharp
using(var package = new ExcelPackage())
            {
                var sheet = package.Workbook.Worksheets.Add("list formula");
                sheet.Cells["B1"].Style.Font.Bold = true;
                sheet.Cells["B1"].Value = "Source values";
                sheet.Cells["B2"].Value = 1;
                sheet.Cells["B3"].Value = 2;
                sheet.Cells["B4"].Value = 3;

                // add a validation and set values
                var validation = sheet.DataValidations.AddListValidation("A1");
                // Alternatively:
                // var validation = sheet.Cells["A1"].DataValidation.AddListDataValidation();
                validation.ShowErrorMessage = true;
                validation.ErrorStyle = ExcelDataValidationWarningStyle.warning;
                validation.ErrorTitle = "An invalid value was entered";
                validation.Error = "Select a value from the list";
                validation.Formula.ExcelFormula = "B2:B4";

                package.SaveAs(new FileInfo(@"C:\temp\dv1.xlsx"));
            }
```
validation.ShowErrorMessage is true after it is set, both using the debugger and when I check the workbook xml:
```xml
<dataValidation error="Select a value from the list" errorTitle="An invalid value was entered" errorStyle="warning" showErrorMessage="1" sqref="A1" xr:uid="{6CA92624-6822-4A3B-A1D7-07044B369602}" type="list">

<formula1>B2:B4</formula1>

</dataValidation>
```

**Comment by caloyboy** [comment]
Hi,
I have attached the following:
1. A console app to replicate the issue
2. A "temp.xlsx" that gets generated
3. An image of the Data Validation prompt that shows that the "Show error alert ..." checkbox is unchecked.
![Annotation 2020-04-06 192111](https://user-images.githubusercontent.com/1764825/78543367-eba3b700-783b-11ea-92a8-4275cbea1dbd.png)

[EpplusIssue71.zip](https://github.com/EPPlusSoftware/EPPlus/files/4437341/EpplusIssue71.zip)
[temp.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4437344/temp.xlsx)

**Comment by swmal** [comment]
Thank you, I’ll have a look at this and will get back.
