### ISSUE TITLE
Support DescriptionAttribute on enum values in ExcelRangeBase.LoadFromCollection

### ISSUE THREAD

**Issue by DanielStaroscik** [EPPlusSoftware/EPPlus#712]
Same issue on older version of EPPlus repository:

[Support DescriptionAttribute on enum values #602](https://github.com/JanKallman/EPPlus/issues/602)

Can You add again this fix?

**Comment by JanKallman** [comment]
Yes, we'll try to add fix for this.

**Comment by JanKallman** [comment]
This will go into EPPlus 6.1. See...[enum-display-attribute-LoadFromCollection](https://github.com/EPPlusSoftware/EPPlus/tree/feature/enum-display-attribute-LoadFromCollection)

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.1
