### ISSUE TITLE
Saving xls memorystream results in System.IO.InvalidDataException

### ISSUE THREAD

**Issue by mileaminute** [EPPlusSoftware/EPPlus#718]
With version 6.0.6 loading .xls from file or httpclient results in this error:

System.IO.InvalidDataException: 'The file is not a valid Package file. If the file is encrypted, please supply the password in the constructor.'

at this line:

ExcelPackage package = new ExcelPackage(memStream);

However, loading same file but saved as .xlsx file works fine. Is there a potential fix or workaround?

**Comment by JanKallman** [comment]
EPPlus only supports Office Open Xml files (for example xlsx, xlsm). Xls is the legacy binary format used in versions prior to Excel 2007, so consider convert them to xlsx if possible.
