### ISSUE TITLE
Table References in Formulas are broken

### ISSUE THREAD

**Issue by leecannon** [EPPlusSoftware/EPPlus#72]
It seems that any table references in formula e.g "=COUNTIF(Base[Date],[@Date])" are not saved correctly, resulting in only "=COUNTIF(#REF,#REF)" after saving.

This happens whether the formula was prexisting in the workbook or added by EPPlus. Just opening and then saving the file is enough to break the references.

I have a simple repro of this issue [here](https://github.com/leecannon/EPPlus-Bug-Repo)

The above repro contains a simple excel with one sheet and two tables with one of the table refering to itself and the other table with the COUNTIF formula show above.

The code is simply
``` cs
private static void Main()
{
	ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

	var simpleFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory!, "Simple.xlsx");
	var outputFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory!, "Output.xlsx");

	using var package = new ExcelPackage(new FileInfo(simpleFile));
	package.SaveAs(new FileInfo(outputFile));
}
```

**Comment by JanKallman** [comment]
Thanks for reporting it. I'll have a look at the issue and get back to you.

**Comment by JanKallman** [comment]
This should work now. The R1C1 translation did not handle table addresses. 
You can try the source or the latest build from this feed
https://ci.appveyor.com/nuget/epplus

**Comment by leecannon** [comment]
This issue has been resolved by your changes.
