### ISSUE TITLE
AutoFitColumns stopped working on v6

### ISSUE THREAD

**Issue by molfarrrr** [EPPlusSoftware/EPPlus#720]
Hello,
We recently have updated the library from v5 to 6 & AutoFitColumns is now throwing null reference exceptions.  I have drilled down into the code to find the root cause. The error is coming from OfficeOpenXml.Core.AutofitHelper live 89:
`int PositionID = styles.GetNormalStyle().StyleXfId;` 

GetNormalStyle gives back null. 
Please see below the code snippet that I am using to generate the excel sheet:

`var stream = new MemoryStream();
await _excelMapper.SaveAsync(stream, _records, worksheetName);
var newWorkbookStream = new MemoryStream(stream.ToArray());
using var package = new ExcelPackage(newWorkbookStream);
var worksheet = package.Workbook.Worksheets[worksheetName];
worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();
`
Exactly that code was working fine with v5 lib. Would you be so kind as to advise me on how to fix this?

**Comment by molfarrrr** [comment]
To eliminate any potential side effects that might(or might not) be caused by the custom ExcelMapper just as an experiment I have tried to follow exactly your code example from https://www.epplussoftware.com/en/Developers/
However, the result is, unfortunately, the same - null reference exception at OfficeOpenXml.Core.AutofitHelper live 89

Code for the reference:
`IEnumerable<TClass> enumerable = someDataForTable
package.Workbook.Worksheets.Add(worksheetName);
package.Workbook.Worksheets[worksheetName].Cells["A1"]
                .LoadFromCollection(enumerable,  true, TableStyles.Medium9);`

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.1
