### ISSUE TITLE
How to read table by row and fields

### ISSUE THREAD

**Issue by samusaran** [EPPlusSoftware/EPPlus#723]
We are planning to replace ClosedXML with EPPlus in our projects due to performance concerns, and while writing an XLSX file with EPPlus is very very good, we currently have some issues in reading back the data we write.

With ClosedXML we can read Tables and map them to DTOs by reading row by row and addressing the cells by the header name, like this:
```
foreach (var row in table.DataRange.Rows())
{
    var item = new TResult();

    foreach (var prop in properties)
    {
        var fieldName = GetPropDescription(prop);

        var value = row.Field(fieldName, prop.PropertyType);

        prop.SetValue(item, value);
    }

    list.Add(item);
}
```

How can I achieve the same thing with EPPlus? I cannot find any example on your documentation, and if I'm being honest, there's very little documentation about Tables at all, while for our use case those are essential.

**Comment by JanKallman** [comment]
You will have to use the table.Range or table.DataRange and iterate using a for or foreach loop.
```c#
foreach(var cell in table.DataRange)
{
   //Code to map values...
}
```
...or...
```c#
for(int row=table.DataRange.Start.Row;row<=table.DataRange.End.Row;row++)
{
  for(int col=table.DataRange.Start.Column;col<=table.DataRange.End.Column;col++)
  {
     var v = worksheet.Cells[row, col].Value;
   //Code to map values...
  }
}
```
