### ISSUE TITLE
Epplus 6.0.7 sorting cannot be reset or cleared?

### ISSUE THREAD

**Issue by konijntje2** [EPPlusSoftware/EPPlus#728]
When you set sorting on a range, the sort state is each time extended.
So if you do
ws.Cells["A:C"].Sort(new int[] { 0, 1 }, new bool[] { true, false });
or
ws.Cells["A:C"].SortBy.Column(0, eSortOrder.Descending).ThenSortBy.Column(1);

each time the sorting state is extended with a rule.

But how do you clear or reset the sorting state, so you can start from scratch with sorting in stead of that sorting state is extended with a search rule?

When you edit 3 times the same file and edit sorting the file gets corrupt and gives an error on xml : sort element.
After 64 times you get an error that the sorting collection is oversized.

**Comment by swmal** [comment]
Thanks for reporting this, we'll have a look.

**Comment by konijntje2** [comment]
Is the fix present in version 6.1.0? Thank you.

**Comment by JanKallman** [comment]
Yes, fixed in EPPlus 6.1
