### ISSUE TITLE
Problem while opening excel with specific worksheet

### ISSUE THREAD

**Issue by nascimento3** [EPPlusSoftware/EPPlus#73]
Hi all,

I've had a very big excel file, that would crash my application whenever I was ... as you can see on the image below.

![image](https://user-images.githubusercontent.com/9201150/78570076-6361e980-781c-11ea-8ae1-f37f5c1b928e.png)

I've narrow down my excel file, and I did find which worksheet was causing the problem.
I took that worksheet and have "clean it" but the problem is still there. 

[Book4.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4439031/Book4.xlsx)

Can you give it a look? 

Thanks

**Comment by joaosousa91** [comment]
Hello, I'm having a similar problem. Good timing @nascimento3 .

Can someone help?

Thanks in advance.

**Comment by joaosousa91** [comment]
Perfect, thank you @JanKallman. Fixed.
