### ISSUE TITLE
Set a custom column width

### ISSUE THREAD

**Issue by shishuai0410** [EPPlusSoftware/EPPlus#734]
`static void SetColumnWidth(ExcelWorksheet workSheet, Dictionary<int, double> columnlen)
        {
            if (columnlen != null && columnlen.Count > 0)
            {
                foreach (var cols in columnlen)
                {
                    int col = cols.Key + 1;
                    //workSheet.Column(col).Width = cols.Value;
                    workSheet.Column(col).Width = 90;
                }
            }
        }`
The actual column width set using this code will be super wide.
![1666681843429](https://user-images.githubusercontent.com/85278712/197706900-f2237897-5d56-40d1-b95f-4abc07a90cfa.jpg)

**Comment by JanKallman** [comment]
The width set by EPPlus is the value defined by OOXML (the value saved in the workbook) and will not correspond to the value shown in Excel at runtime. 
You can read how to convert them here... https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.column?view=openxml-2.8.1
