### ISSUE TITLE
Form button `SetSize` not having any effect in 6.0.8.1069-20221026-develop

### ISSUE THREAD

**Issue by dantronik-markus** [EPPlusSoftware/EPPlus#737]
I noticed that the Form Button SetSize method in the development build is not having any effect and that the created buttons always have the dimensions of the cell they're contained in.

Here's a sample project to reproduce the problem:
[EPPlusWrongButtonSizeTest.zip](https://github.com/EPPlusSoftware/EPPlus/files/9871199/EPPlusWrongButtonSizeTest.zip)

If you change the dependency to the latest final version, `SetSize` works properly.

**Comment by JanKallman** [comment]
Thanks for reporting this. I'll have a look at it.

**Comment by JanKallman** [comment]
This seems to work when I run your program. Are you refering to this row...
`button.SetSize(135, 70);`

**Comment by dantronik-markus** [comment]
![2022-10-27 10_52_16-test   Gruppe  - Excel (Fehler bei Produktaktivierung)](https://user-images.githubusercontent.com/67917640/198239664-603fe94c-eec5-4df9-803a-f2c9838c57a1.png)
This is with EPPlus 6.0.8-1069

![2022-10-27 10_54_16-test   Gruppe   Repariert  - Excel (Fehler bei Produktaktivierung)](https://user-images.githubusercontent.com/67917640/198240102-5f639167-4a0c-41d8-bd95-7653b31f21c1.png)
This is with EPPlus 6.0.8

Can you not reproduce the issue?

**Comment by JanKallman** [comment]
Yes, I have been able to reproduce this. It happens when you have a different normal style font that default (Calibri 11pt).
I will provide a fix shortly.

**Comment by dantronik-markus** [comment]
Closing since it's fixed in the final version.
