### ISSUE TITLE
Issue mixing table and cell references in formulas

### ISSUE THREAD

**Issue by leecannon** [EPPlusSoftware/EPPlus#74]
If a formula contains both a table reference and a cell reference after saving then opening in Excel the message "We found a problem with some content in '...'. Do you want us to recover as much as we can?" is presented.

If you answer 'Yes' to the prompt the formulas are striped but the saved value of the cell is retained.

An example of this type of formula is, within a table: "=COUNTIF($B$3:$B$18,[@Date])"

I have a repro of this issue [here](https://github.com/leecannon/EPPlus-Bug-Repo)

**Comment by JanKallman** [comment]
This should now work in version 5.1.
