### ISSUE TITLE
"User-defined type not defined" error message in EPPlus development build 6.0.8.1094-20221031-develop

### ISSUE THREAD

**Issue by dantronik-markus** [EPPlusSoftware/EPPlus#741]
I just wanted to test the fix for #737 but now when I click any of the buttons, it keeps telling me that the user-defined type `MSForms.ComboBox` is not defined. This probably rings true for all of the MSForms dependencies.

Here's the ZIP archive from the other issue, the EPPlus dependency just needs to get updated to the latest nightly:
[EPPlusWrongButtonSizeTest.zip](https://github.com/EPPlusSoftware/EPPlus/files/9910910/EPPlusWrongButtonSizeTest.zip)

This worked with the 1072 build.

**Comment by JanKallman** [comment]
We'll have a look

**Comment by JanKallman** [comment]
Thanks for spotting this. It's a problem that occurs after our new VBA signatures (Agile and V3) implementation released with EPPlus 6.1. I will provide a fix shortly.

**Comment by JanKallman** [comment]
Try latest develop-build

**Comment by dantronik-markus** [comment]
Thank you! I've already tried the latest build shortly after it was built and it seems to work.

Another question: Do you have any project-wide guidelines regarding when to close Github issues? When the issue is fixed in a dev build or a final build or does it not matter?

**Comment by JanKallman** [comment]
We usually close issues when they are fixed and released in a version. Since this issue is not in any released version you can close it if you have verified that it works.

**Comment by dantronik-markus** [comment]
Alright, closing.
