### ISSUE TITLE
Blazor sBase64.replace not a function

### ISSUE THREAD

**Issue by Frank00006** [EPPlusSoftware/EPPlus#747]
After upgrading a project from .Net Core 3.1 to 6.0 including upgrading EPPlus to 6.1. I'm getting s64base.replace not a function when I attempt to export data to excel. Looks like it's in the JS for EPPlus. Worked fine when it was .Net Core 3.1 with EPPlus 5.4.0.

The EPPlus example shows using Byte Array, but according to JavaScript the replace function is only good on strings. I did just attempt changing the byte array I was using to string; but, though it got passed the java script error, the downloaded file failed to open in Excel.  I also tried a few suggestions from MicroSoft and StackOverflow, to no avail.

I have tried in .Net core 5 as well, and worked fine there; it's only after upgrading to Core 6.

The issue seems to be in the filedownload.js, were function BlazorDownloadFile is calling base64DecToArr which seems to abort on sB64Enc = sBase64.replace(/[^A-Za-z0-9\+\/]/g, "").

**Comment by swmal** [comment]
Hi,

I assume that this is related to JavaScript and not to EPPlus directly? When we made the sample we tried to use the Blazor scripts/JS interop, but couldn't make it work so we ended up with a solution using a script that we [found here](https://developer.mozilla.org/fr/docs/Web/API/WindowBase64/D%C3%A9coder_encoder_en_base64). Our aim was just to provide a sample where EPPlus runs in Blazor.

Note that our web sample has been .NET 6 all the time and works as is. If you look in our web sample there is a function named `BlazorDownloadFile` which takes 3 arguments: filename, contentType and content where content is a byte-array from EPPlus. As you can see, the comment in this function says:

`// Blazor marshall byte[] to a base64 string, so we first need to convert the string (content) to a Uint8Array to create the File`

My guess would be that you have a newer version of Blazor where this statement is no longer true and one thing you could do is to debug your javascript and see if the argument `content` still is a base64 encoded string.
