### ISSUE TITLE
IsWorksheets1Based does not apply to all 1-based references

### ISSUE THREAD

**Issue by davimack** [EPPlusSoftware/EPPlus#75]
When using the IsWorksheets1Based property, it affects Worksheets[ ] but does not appear to affect .Cells[ , ]  I would expect that if I set IsWorksheets1Based = 0 that a reference to .Cells[0,0] would reference the first cell in the sheet.

![image](https://user-images.githubusercontent.com/12926523/78610154-1b8d9300-7819-11ea-9a95-07c7a5d9a991.png)

**Comment by JanKallman** [comment]
This property only applies to the Worksheets collection. Reusing the the `IsWorksheets1Based` for this behavior would break code, so it can not be applied. 
Adding a new property for this is an option, but would be a quite large implementation.

**Comment by davimack** [comment]
I understand. May I just point out, however, that the variable itself presents a breaking change. Also, the expectation of everyone who has worked on a Microsoft Office product realizes that things are one based. By you changing this, you have introduced a variable in how people work which is not present within the Microsoft products. I, for one, will be setting everything back to one based simply because I do not want to remember that the library uses base zero sometimes depending on which property I am referencing.
