### ISSUE TITLE
Inconsistency in retrieving of font informations of richText

### ISSUE THREAD

**Issue by michaelschroeder2** [EPPlusSoftware/EPPlus#752]
**Issue:** The first richText entry of a cell does not contain information regarding the font if its the same as the cell.
All other richText entries of the cell contain these informations, even if they are the same as the cell. Note, the font is not null, its just an object with only default values such as empty string, 0, false, ...

**Note:** This can be bypassed with checking the cell if something is empty. Though not something major, it would be nice, if it would be consistent.

**Sample File:**
[Markups.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10112265/Markups.xlsx)

**Sample Code:**
```
using OfficeOpenXml;
using System;
using System.IO;

namespace GetColors
{
	class Program
	{
		static void Main(string[] args)
		{
			ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

			var fileName = "Markups.xlsx";
			if (!File.Exists(fileName))
			{
				Console.WriteLine("File does not exist.");
				Console.ReadKey();
				return;
			}

			using (var excelPackage = new ExcelPackage(new FileInfo(fileName)))
			{
				for (int row = 1; row <= excelPackage.Workbook.Worksheets[0].Dimension.End.Row; row++)
				{
					if (excelPackage.Workbook.Worksheets[0].Cells[row, 1].Text == "") continue;

					var cell = excelPackage.Workbook.Worksheets[0].Cells[row, 3];

					Console.WriteLine($"\n--> {excelPackage.Workbook.Worksheets[0].Cells[row, 1].Text}");
					Console.Write($"Cell Font: [{cell.Style.Font.Name}], Size: [{cell.Style.Font.Size}]");
					if (cell.Style.Font.Bold) Console.Write(", Bold");
					Console.WriteLine();

					foreach (var richText in cell.RichText)
					{
						Console.Write($"RichText {richText.Text} Font: [{richText.FontName}], Size: [{richText.Size}]");
						if (richText.Bold) Console.Write(", Bold");
						Console.WriteLine();
					}
				}

				Console.ReadKey();
			}
		}
	}
}
```

**Result:** 
![image](https://user-images.githubusercontent.com/50169678/204511148-ca457ebd-ccd8-4332-bbd8-225690f3f86b.png)

**Comment by JanKallman** [comment]
Thanks, we'll have a look at this.

**Comment by JanKallman** [comment]
Yes, EPPlus will return the font specified in the rich text xml. If blank the cells style could be returned instead. 
Changing this will be a behavior change, so I will add this as an enhancement for a future major.
