### ISSUE TITLE
`#NAME?` error with `CEILING.MATH` and `FLOOR.MATH`

### ISSUE THREAD

**Issue by mitchpaulus** [EPPlusSoftware/EPPlus#753]
With the following MWE:

```C#
ExcelPackage package = new ExcelPackage(@"C:\Users\mpaulus\test.xlsx");
ExcelWorksheet sheet = package.Workbook.Worksheets.Add("Sheet");
sheet.Cells[1, 1].Formula = "CEILING.MATH(1.6)";
package.Save();
```

I get a `#NAME()` error when opening the output xlsx. There is no EPPlus exception for unknown function. 

When I look at the output XML in the `sheetData` element, everything looks fine:

```xml
<sheetData><row r="1"><c r="A1" s="0"><f>CEILING.MATH(1.6)</f></c></row></sheetData>
```

If I make a spreadsheet within Excel itself and look at that, it looks like:

```xml
<sheetData><row r="1" spans="1:1" x14ac:dyDescent="0.35"><c r="A1"><f>_xlfn.CEILING.MATH(1.6)</f><v>3</v></c></row></sheetData>
```

When I looked through the code base, it looks like the `_xlfn` is removed on purpose in a few places. 

```
src/EPPlus/FormulaParsing/ExpressionGraph/FunctionExpression.cs
62:                // older versions of Excel (pre 2007) adds "_xlfn." in front of some function names for compatibility reasons.
64:                if (funcName.StartsWith("_xlfn.", StringComparison.OrdinalIgnoreCase)) funcName = funcName.Replace("_xlfn.", string.Empty);

src/EPPlus/DataValidation/Formulas/ExcelDataValidationFormula.cs
102:            formula = formula.Replace("_xlfn.", string.Empty).Replace("_xlws.", string.Empty);
```

I did confirm if I manually add that `_xlfn` back in, there is no error, meaning:

```c#
sheet.Cells[1, 1].Formula = "_xlfn.CEILING.MATH(1.6)";
```

did work.

Is this a case where that prefix is required?

I am using EPPlus version 6.1.1. 
Excel version is 2210 (Build 15726.20202)

**Comment by swmal** [comment]
Hi,

The "xlfn." is something that the Excel client adds as a prefix to the formula if the function is unrecognized but can be found in an compatibility pack or similar. See this link: https://support.microsoft.com/en-us/office/issue-an-xlfn-prefix-is-displayed-in-front-of-a-formula-882f1ef7-68fb-4fcd-8d54-9fbb77fd5025

We tested this with Excel version 2210 and could see that Excel adds the prefix to these functions. I would assume that this has something to do with the added support for dynamic array formulas in the newer versions (you can add a range like A1:A2 as the argument and get an array back).

EPPlus does not have any logic to add the prefix in formulas so my advice would be to exactly as you have done: add it manually in the formula.

/Mats
