### ISSUE TITLE
BUG: CalculatedColumnFormula and Calculate() only work with specific syntax

### ISSUE THREAD

**Issue by ses4j** [EPPlusSoftware/EPPlus#758]
Hi - I was getting very odd crashes or failures to Calculate() when using a table with `CalculatedColumnFormula`s.  Example:

![image](https://user-images.githubusercontent.com/435529/206525535-2e9a4c4b-c7a1-4bc6-9c07-90f1c0648bad.png)

If the CalculatedColumnFormula was actually `[@ColA]+[@ColB]` as shown, the resultant Calculate() would put 0 in.  Some more examples:

```
// works:
c.CalculatedColumnFormula = "Table1[[#This Row],[ColA]]+Table1[[#This Row],[ColB]]";

// doesn't work but I think they all are acceptable to Excel
// c.CalculatedColumnFormula = "[@ColA]+[@ColB]";  // gives #NAME
// c.CalculatedColumnFormula = "Table1[[@ColA]]+Table1[[@ColB]]"; // gives 0
// c.CalculatedColumnFormula = "Table1[@ColA]+Table1[@ColB]"; // gives 0
// c.CalculatedColumnFormula = "[[#This Row],[ColA]]+[[#This Row],[ColB]]"; // crashes
```

**Comment by ses4j** [comment]
[test-columnformula.zip](https://github.com/EPPlusSoftware/EPPlus/files/10188078/test-columnformula.zip)

Here is some code to reproduce.

**Comment by JanKallman** [comment]
Hello,
You will have to use the OOXML syntax. The @ syntax is only used in the Excel GUI, not in OOXML. 
The address must start with the table name and then use the section and/or the column names as in your working example. I suggest you create the formula in Excel,  Save, and then look at the syntax in the table xml.

**Comment by ses4j** [comment]
Ok.  Right now I'm using this hack to 'adjust' my stuff (which is not perfect, I'm sure there are formulas that will break my simple regex):

```
RE_FORMULA_HACK = re.compile(r"(?:" + table_name + r")?(?:\[@\[|\[|@)@?([^]]+)\]\]?")
fixed_formula = RE_FORMULA_HACK.sub(sheet.table_name + r"[[#This Row],[\1]]", formula)
```

It might be worth documenting this on, e.g., https://github.com/EPPlusSoftware/EPPlus/wiki/Formula-Calculation under "some common mistakes" or in the docs around Tables?  It took quite a while for me to even notice it was silently failing to calculate, then to dig up the uncommon syntax, test to see if it fixed things, etc... It caused several production issues for us.

Anyway, thanks for responding!  Love the product.

**Comment by JanKallman** [comment]
Yes, I agree, I'll try to document this in the wiki.

**Comment by JanKallman** [comment]
See this page: https://github.com/EPPlusSoftware/EPPlus/wiki/Referencing-tables-in-formulas for some samples.

**Comment by ses4j** [comment]
thanks, very informative!
