### ISSUE TITLE
Not possible to create Array Function

### ISSUE THREAD

**Issue by Krzysztof1234534** [EPPlusSoftware/EPPlus#761]
I've try to create array function, but it is not possible, in the generated xml file (when I rename xlsx file to zip) it is only:
<c r="C29" s="0"><f>
without t="array"
I've check source code and the bug is in ExcelRangeBase.Set_SharedFormula, there is 
f.FormulaType = ExcelWorksheet.FormulaType.Shared;
without any condition (Set_SharedFormula is used in CreateArrayFormula with IsArray=true parameter).
ExcelWorksheet.UpdateRowCellData adds t="array" attribute only if f.FormulaType == FormulaType.Array

Is this possible to fix it?

**Comment by JanKallman** [comment]
You can create an array formulas via the ExcelRange.CreateArrayFormula method, but EPPlus cannot calculate it. Excel will however do that when the file is opened. Then newer dynamic array formulas are not supported in EPPlus yet, but we will add support for it in a comming version. Shared formulas is not the same as array formulas.

**Comment by Krzysztof1234534** [comment]
The problem is that EPPlus not writing formulas created by CreateArrayFormula as array. In excel it has different value and is not array formula. I need to go to cell and than click CTLR+SHIFT+ENTER to convert it to array formula.
Here is some example:
`using (var package = new ExcelPackage())
            {
                var sheet = package.Workbook.Worksheets.Add("Page1");
                sheet.Cells["A1"].Value = 0;
                sheet.Cells["B1"].Value = 5;
                sheet.Cells["A2"].Value = 0;
                sheet.Cells["B2"].Value = 1;
                sheet.Cells["A3"].Value = 1;
                sheet.Cells["B3"].Value = 1;
                sheet.Cells["A4"].Value = 1;
                sheet.Cells["B4"].Value = 4;
                sheet.Cells["F1"].Value = 1;
                sheet.Cells["G1"].CreateArrayFormula($"MIN(IF(A1:A4=F1,B1:B4))");
                package.SaveAs(@"test.xlsx");
            }`
When I open excel it looks like this:
![obraz](https://user-images.githubusercontent.com/121023722/208617704-ea2a64e6-91a1-44b0-936f-53f3708d06b5.png)
After clicking ctrl+shift+enter:
![obraz](https://user-images.githubusercontent.com/121023722/208617807-302c7cf8-7fc5-4c1a-8b10-2dda7a71c783.png)
So as you can see this is normal formula without {  } and the value is different. 
As I said to fix this it will require only one line of code change.

**Comment by JanKallman** [comment]
I see, yes, this is a bug. I will provide a fix shortly.

**Comment by JanKallman** [comment]
Feel free to try this fix...https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed

**Comment by Krzysztof1234534** [comment]
I've checked 6.1.1.1134 and it is working, thanks

**Comment by JanKallman** [comment]
Fixed in 6.1.2
