### ISSUE TITLE
implement Number Cache for ExcelChart 

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#762]
Dear Epplus dev team,

I am missing one feature in Epplus. I have a simple excel file [TestDoc_Diagram.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10259366/TestDoc_Diagram.xlsx) with a chart. 

If I open it with EPPlus  and change any figure in series, the chart is not beeing updated, either I call Calcuate() or not. The chart stays in the same state unit I open the file in excel. The problem is, I am not going to open it in excel. I am going to export the chart after update.

The chart is not beeing updated, because it's numCache node (see \xl\charts\chart1.xml in the attached file) is not actualized 
![image](https://user-images.githubusercontent.com/33231799/208430417-0df2667d-27e1-4ddf-8367-888eabcf1c6a.png)

Unfortunatelly there is no code in EPPlus, which deals with numCache neither by chart creation, nor by update. But in my case important would be only the update

**Comment by JanKallman** [comment]
Hi, 
You can try using the `serie.CreateCache()` method to update the cache...
        [TestMethod]
```C#
        public void i762()
        {
            using (var p = OpenTemplatePackage(@"TestDoc_Diagram.xlsx"))
            {
                var ws = p.Workbook.Worksheets[0];
                ws.Cells["C5"].Value = 15;
                var pc = ws.Drawings[0].As.Chart.PieChart;
                pc.Series[0].CreateCache();

                SaveAndCleanup(p);
            }
        }
```
Note that if you have formulas in the series, they must be calculated before creating the cache.

**Comment by ihorbach** [comment]
Hi Jan,
thank you very much for the fast response! 
My first test in my sandbox shows perfect results.

Sorry, I should have found out it by myself. But I somehow managed to check out a wrong or old branch of EPPlus code. Looking up there brought no result.

**Comment by JanKallman** [comment]
Well, it's not that well documented. I will try to update the documentation of charts in the wiki, so easier to find.

**Comment by ihorbach** [comment]
Might it be a good idea to couple call of this function to Worksheet.Calculate() function?
