### ISSUE TITLE
ExcelRangeBase iterator miscounts if range contains period (A1:A3;A4;A5)

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#763]
If ExcelRangeBase contains periods (**A1:A3**;A4;A5), it will misscount when iterating throug it. It will iterate through A1:A3 twice.

This simple example shows how the problem can be reproduced:

![image](https://user-images.githubusercontent.com/33231799/209362258-e5f216f4-3105-4643-ab92-6ed39b179526.png)

**Comment by JanKallman** [comment]
Yes. This is a bug. I'll have a look at your PR.

**Comment by JanKallman** [comment]
Fixed in 6.1.2
