### ISSUE TITLE
Autofilter cannot be removed

### ISSUE THREAD

**Issue by AlexCBlm** [EPPlusSoftware/EPPlus#765]
I am using 6.1.1
Cant remove autofilter on a first row, no matter what I try.
Code below, its very simple.

var sheet = package.Workbook.Worksheets.Add("Sheet");                    
                    sheet.Column(4).Style.Numberformat.Format = "mm-dd-yyyy";                    
                    var tableRange = sheet.Cells["A1"].LoadFromDataTable(dt, true, TableStyles.None);
                    tableRange.AutoFilter = false;                    
                    tableRange.AutoFitColumns();                    
                    sheet.Column(4).Width = 12;                
                    sheet.Row(1).Style.Border.Bottom.Style = ExcelBorderStyle.Thick;
                    sheet.Row(1).Style.Font.Bold = true;  
                    sheet.View.FreezePanes(2, 1);    
                    excelData = package.GetAsByteArray();

**Comment by JanKallman** [comment]
You must do that on the table object it the filter applies to a table, not the range. 
You can use the `tableRange.GetTable()` method to get the table or get it from the `sheet.Tables` collection...
For example:
```C#
vat t=tableRange.GetTable();
t.ShowFilter = false;
```
