### ISSUE TITLE
Precision error in SUM function

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#766]
SUM fuction suffers on precision problems. Following snippet shows the problem:

```
sheet.Cells["A2"].Value = 0.2;
sheet.Cells["B2"].Value = 21.9;
sheet.Cells["D2"].Value = 22.1;
sheet.Cells["E2"].Formula = "=D2-SUM(A2:B2)";

p.Workbook.Calculate();

Assert.AreEqual("0", sheet.Cells["E2"].Value.ToString());
```

Result will be 

> Assert.AreEqual failed. Expected:<0>. Actual:<3,552713678800501E-15>

This is quite a "normal" behaviour when using double data type. I fixed this problem in my local copy of EPPlus and testet it several years on millions of complex excel files. This fix proved to be good and stable one. I will provide it as a PR

**Comment by JanKallman** [comment]
EPPlus Software WIP: Check both with and without PrecisionAsDisplayed and a NumberFormat
