### ISSUE TITLE
Missing range calculation

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#768]
![image](https://user-images.githubusercontent.com/33231799/209691454-77c86ea5-b57d-4075-98b9-62ecbcd4b7bd.png)

there are two possibilities in excel to sum up two colums row by row:

> **1.** write formula _=B1+C1_ in the cell D1 and copy it down the column

> **2.** create named range _range_1_ for the **column B** and _range_2_ for the **column C**
>    write formula _=range_1+range_2_ , select the whole colum D an copy-paste it there

The second way is much more elegant and flexible, when working with very big excel ranges, which length constantly changes. EPPlus seems not to know this expression

**Comment by JanKallman** [comment]
Dynamic array formulas is currently not supported by EPPlus. We will add this in a coming version.

**Comment by ihorbach** [comment]
Hello Jan, can you look at my pull request to this issue? 
https://github.com/EPPlusSoftware/EPPlus/pull/769
I don't know, if you already began to work on this feature. Otherwise it might be helpful.

**Comment by JanKallman** [comment]
Yes, we are working on a major redesign of the dependency chain and expression handling where we will implement dynamic array formulas... https://github.com/EPPlusSoftware/EPPlus/tree/feature/formula_parser_rpn

**Comment by adamshakhabov** [comment]
This [article](https://github.com/EPPlusSoftware/EPPlus/wiki/EPPlus-7-Preview) mentions that EPPlus 7 Preview now supports "Dynamic array formulas". Does this mean that the issue has been resolved in the `develop` branch? 

I'm asking because the test from #769 PR is still failing.

**Comment by swmal** [comment]
@ashahabov - sorry for the late response to this issue. Dynamic arrayformulas is supported in EPPlus 7, see [this wiki page](https://github.com/EPPlusSoftware/EPPlus/wiki/Dynamic-arrayformulas)
