### ISSUE TITLE
Multiple Font styles within a single cell

### ISSUE THREAD

**Issue by ShmuelLevine** [EPPlusSoftware/EPPlus#777]
I can't find anything in the documentation, and the interface doesn't appear to provide this functionality.

In Excel, I can change the font formatting of different text within the same cell.  I need to replicate this functionality.  

How can this be done through EPPlus?  If nothing currently exists, can you please provide this needed feature?

**Comment by JanKallman** [comment]
You can use the `worksheet.Cells[].RichText` property. Like in this sample :
https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/3c94b6c467e9891f6da280c018d8b8dc218c5311/20-CreateFileSystemReport/CreateAFileSystemReport.cs#L225
