### ISSUE TITLE
No check for hyperlink max length of 2080 chars

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#778]
If cell contains a hyperlink with special characters such es ö, ä, ü etc. excel encodes such link not with UTF-8 to keep the rule that a target link must be shorter than 2080 characters. 

Epplus always uses the normal UTF-8 encoding. In this case the Hyperlink would likely extend to over 2079 characters, resulting in a corrupt Excelfile that can not be opened by Excel.

To reproduce the problem you can open and save attached file with EPPlus. After that it cannot be opened with excel. (Okay, it can, but  you need to click through the dialogs, that the file will be restored and corrupt content will be deleted, which we don't want)

[HyperlinkIssue.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10330523/HyperlinkIssue.xlsx)

**Comment by JanKallman** [comment]
Thanks for reporting, I'll provide a fix shortly

**Comment by JanKallman** [comment]
Fixed in version 6.1.2
