### ISSUE TITLE
Missing FullPrecision calculation property d:calcPr/@fullPrecision

### ISSUE THREAD

**Issue by ihorbach** [EPPlusSoftware/EPPlus#779]
If Excel has rounding errors (due to the fact that calculation is always done with floating points) some formulas like "If" will get wrong results due to after effects. One can do work around that issue by ticking the checkbox "precision as displayed" in the advanced excel options.This function was not yet implemented in EPPlus.

**Comment by adamshakhabov** [comment]
Are there any updates or plans in place regarding this feature?

**Comment by ashahabov** [comment]
Are there any updates or plans in place regarding this feature?

**Comment by JanKallman** [comment]
Added in EPPlus 7.3
