### ISSUE TITLE
When using (excelPackage!.Workbook.Calculate();), an error occurred during the recalculation execution of excel.

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#789]
**epplus version 5.8.13**

![image](https://user-images.githubusercontent.com/19505572/215412672-0f78026d-066f-4621-a1bc-dac2f840b2c3.png)
![image](https://user-images.githubusercontent.com/19505572/215412920-93c5d5d6-160a-4bfe-a57c-50904cb5fca1.png)

**sample source:**

using (ExcelPackage excelPackage = new ExcelPackage(@"f:\sample.xlsx"))
{
    excelPackage.Workbook.Calculate();
}

error:
OfficeOpenXml.FormulaParsing.Exceptions.CircularReferenceException: 'Circular Reference in cell sample1!B5'

The problem was found in 5.8.13, but it still exists in the latest version 6.1.2.
I'm afraid it's a bug of epplus.
Please confirm.

**attachment files:**
[sample.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10533429/sample.xlsx)

**Comment by swmal** [comment]
To avoid this exception you should set the AllowCircularReferences parameter to true. You can do this either by supplying it as a parameter to the Calculate function (in the lambda) or by configuration files.

See this page: https://github.com/EPPlusSoftware/EPPlus/wiki/Circular-references

**Comment by 93910676wangd** [comment]
> To avoid this exception you should set the AllowCircularReferences parameter to true. You can do this either by supplying it as a parameter to the Calculate function (in the lambda) or by configuration files.
> 
> See this page: https://github.com/EPPlusSoftware/EPPlus/wiki/Circular-references

thanks for replay
but...error has occurred. Not resolved.
please confirm.
![image](https://user-images.githubusercontent.com/19505572/215425236-9131a42d-7c4f-4d87-ab22-62edb1f5006f.png)

**Comment by swmal** [comment]
I had a look at how EPPlus reads this parameter from configuration, it turns out that the current version only uses json-configuration for .NET Core apps. ConfigurationManager is only used for .NET Framework.

I'll make this clearer in the docs.

**Comment by 93910676wangd** [comment]
> I'll look further into why it doesn't work with app/web.config, but it calculates without exception if you do the configuration via code:
> 
> `p.Workbook.Calculate(x => x.AllowCircularReferences = true);`

That's right, but I hope the source side will not change.

**Comment by 93910676wangd** [comment]
> 



> However, it looks like you are indeed running .NET Framework not .NET Core? EPPlus tries to get a value from appsettings named exactly like this:
> 
> `EPPlus:ExcelPackage.AllowCircularReferences`
> 
> I'll try to replicate this and will fix it in a future version if it doesn't work.

attached image is dotnet fw source.

Actually Net core or . Net FW can not work properly.
We will attach the Dotnet core sample source tomorrow.
After that, please confirm again.

I think it's probably a bug

**Comment by 93910676wangd** [comment]
attached dotnet6 sample source
Error still exists.
please confirm

[test.zip](https://github.com/EPPlusSoftware/EPPlus/files/10541843/test.zip)

**Comment by swmal** [comment]
I've the via app you supplied. It works when you set AllowCircularReferences via code, but there seems to be an error when reading from configuration. Will be back with a solution.

**Comment by swmal** [comment]
Thanks for the test app, it helped.

Firstly, for EPPlus to find your config-file you must right-click it in Visual Studio and set Build Action to Content. Otherwise EPPlus will not find the config file (it looks for it in the output directory by default). If you prefer you can set your own path to the config-file via the [ExcelPackage.Configure()](https://github.com/EPPlusSoftware/EPPlus/wiki/Configuration#the-excelpackageconfigure-method) method.

Secondly there was a bug in the ExcelWorkbook.Calculate method. Given that you change the build action on your config file as above your example will work if you call Calculate on worksheet level instead.

```csharp
excelPackage.Workbook.Worksheets.First().Calculate();
```
...or...

```csharp
foreach(var sheet in excelPackage.Workbook.Worksheets)
{
   sheet.Calculate();
}
```

I will provide a fix for this later today and and it will be available in our development nuget feed after that. Will ping you here when it is done.

**Comment by swmal** [comment]
You can test the fix via our [development nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed). Will be included in the next version.

**Comment by 93910676wangd** [comment]
> You can test the fix via our [development nuget feed](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed). Will be included in the next version.

thanks,it has been confirmed that there is no problem with this version
