### ISSUE TITLE
ToDataTable for transpose worksheet data

### ISSUE THREAD

**Issue by spk33** [EPPlusSoftware/EPPlus#794]
is there easy way to load worksheet data into DataTable  , where the sheet is has transposed data like below

Hey can we use TODataTable options for easily reading transposed data in excel

![image](https://user-images.githubusercontent.com/7496315/216588700-c09b09fc-08f4-480c-b62f-29901b81b07f.png)

**Comment by swmal** [comment]
No, unfortunately not.. you'll have to read from the sheet cell by cell.

But a good idea to support this, I'll add the enhancement label to this issue and we´ll see what we can do,

**Comment by spk33** [comment]
awesome thanks for considering

**Comment by JanKallman** [comment]
Added in EPPlus 7.2
