### ISSUE TITLE
NullReferenceException in ExcelExternalWorkbook.UpdateCache()

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#796]
**ws** is used here despite being null. https://github.com/EPPlusSoftware/EPPlus/blob/56af20457299f8a187335f84e70c5de3a6ea2f6a/src/EPPlus/ExternalReferences/ExcelExternalWorkbook.cs#L681-L687

Aside from not referencing ws when it's null, I suppose you might have to throw an exception with a message to give us some context as to why EPPlus can't update the cache for a given address. 

Background:
I found this because, as #795 says, I had two workbooks, each with a "LinkTab" sheet, and one LinkTab linking to the other. In one set of workbooks, I fixed the sheet naming issue to workaround false positive CircularReferences. However, I needed to swap back to a different version of wb1 also containing the external reference. Obviously, this different version of wb1 was not aware of the rename in the external reference (wb2) from LinkTab to LinkTab2. I believe that led to **ws** in the code above being null.

**Comment by JanKallman** [comment]
Fix added in version 6.1.3
