### ISSUE TITLE
Possible bug while calculating formula

### ISSUE THREAD

**Issue by MrSogris** [EPPlusSoftware/EPPlus#797]
Hi!

It seems I've found a bug when working with formulas which conatins a link to value to another worksheet. The example below writes values from two rows - one contains formulas and other one - only values.
When I get value EPPlus returns a strange string - "#NAME". Google tells me it's excel error message, but the file is good, it opens, shows values, etc.

```
class Program
    {
        static void Main(string[] args)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var xlsx = new ExcelPackage("Test.xlsx"))
            {
                xlsx.Workbook.Calculate();

                var sheet = xlsx.Workbook.Worksheets.FirstOrDefault(it => it.Name == "BOM_ing");

                sheet.Cells.Calculate();

                for (int rowIndex = 4; rowIndex < 6; rowIndex++)
                {
                    for (int columnIndex = 14; columnIndex < 17; columnIndex++)
                    {
                        var cell = sheet.Cells[rowIndex, columnIndex];

                        if (!string.IsNullOrEmpty(cell.Formula))
                            cell.Calculate();

                        var cellValue = cell.Value;

                        Console.WriteLine($"Cell ({columnIndex}, {rowIndex}) is {cellValue}");
                    }
                }
            }
        }
    }
```

[Test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/10719438/Test.xlsx)

I've tried different versions, currently at 5.8.0, updated to the latest - nothing changed. Or maybe I'm doing something wrong...

**Comment by swmal** [comment]
Hello,
This error occurs because Phos_rate!H6:J8 contains numeric values that are stored as formulas. This makes EPPlus "believe" that this is a defined name and that is what generates the "#NAME" error.

Here is what it looks like in the worksheet xml:

```xml
<c r="H8" s="39">
   <f>4.00801603206413E-06</f>
   <v>4.0080160320641298E-6</v>
</c>
```
You can also see it in Excel, just click one of these cells and you will see that it starts with an equal sign (i.e. "=0,0004")

If you can change this so that it is stored as Value only it will work.

This is something that EPPlus should handle, so we will keep this issue open as a bug and fix it in the next version.

**Comment by MrSogris** [comment]
Thanks for your answer and a workaround. But still our users want to use such formulas, so I will wait for updated EPPlus anyway.

**Comment by MrSogris** [comment]
Very good, waiting for fix, of course!

**Comment by swmal** [comment]
I think we have fixed this (see commit above). You can test it via our development nuget feed in 20 minutes or so.

https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed

**Comment by MrSogris** [comment]
Hi!
I've tried develop version, but it failed. When I run the code above, Calculate() throws an error - Unexpected token 1E+30... It seems it can't parse some number or something...

**Comment by swmal** [comment]
Hello,

we found another error in connection with this and has just commited a fix to our dev feed. You can try to calculate again using our dev nuget feed (url above). Should be available within 30 minutes or so.
