### ISSUE TITLE
\r added to number format with format copied from Excel. Commas and periods get swapped

### ISSUE THREAD

**Issue by inabahare** [EPPlusSoftware/EPPlus#798]
- Epplus 6.1.2.0
- .NET Framework 4.7
- Visual Studio 2022 - 17.5.0 Preview 6.0

So I'm to format a cell with one of the money formats from excel. Specifically this one: _\_-\* #.##0,00 kr.\_-;-\* #.##0,00 kr.\_-;\_-* "-"?? kr.\_-;\_-@\_-_. However when I look at the cell format in Excel I see the following: _\_-\* #,##000 k\r,\_-;-\* #,##000 k\r,\_-;\_-\* "-"?? k\r,\_-;\_-@\_-_

I expected it to show _44.303,00 kr._ but instead I get:  _44303,000 kr,_

I've made a small example, and generated [a file](https://github.com/EPPlusSoftware/EPPlus/files/10731819/test.xlsx) (with both correct and incorrect results)

```cs
ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

var excel = new ExcelPackage(new FileInfo("test.xlsx"));
var worksheet = excel.Workbook.Worksheets.Add("Test");
           
var cell = worksheet.Cells["A1"];

cell.Value = 44303;
cell.Style.Numberformat.Format = "_-* #.##0,00 kr._-;-* #.##0,00 kr._-;_-* \"-\"?? kr._-;_-@_-";

var memoryStream = new MemoryStream();
excel.SaveAs(memoryStream);
            
var fullPath = Path.Combine(Path.GetTempPath(), "test.xlsx");
            
File.WriteAllBytes(fullPath, memoryStream.ToArray());
```

As far as I can tell (with [this](https://www.soscisurvey.de/tools/view-chars.php)) Visual Studio doesn't add any special characters. At least none that I can copy

**Comment by inabahare** [comment]
Hi

Yeah I can see that. The quotemarks completely disappear, all letters seem to get a \ prepended. Can that really be because of culture issues, and if so how do I, like, make it not do that?

Also, another thing I noticed is that it completely changes periods? When using this format _#,##0.00 kr._ the text shows up as Kr, instead. Which makes it suck to be Danish as the other money format we have is ,- that gets changed to .- too :v

**Comment by JanKallman** [comment]
You will have to set the format as Excel does in the OOXML. As I said, format a cell in a workbook in Excel with the desired format and then extract the format string from the package either via using EPPlus or by renaming the workbook *.xlsx and copy the string from the styles.xml

**Comment by inabahare** [comment]
Alight so I actually just figured out how to mitigate this without opening the Excel file in an archive program. Turns out you have to escape the characters you don't want Excel to do it's own i18n formatting to.

So for example you'd have to set the format to this: ```"#,##0.00\\ \\k\\r\\."``` for it to show the thousand separator properly, to not change the last period after kr to a comma, and such.
