### ISSUE TITLE
Open multiple Excel Files created with EPPlus causes missing Data and grey background

### ISSUE THREAD

**Issue by Bonekit** [EPPlusSoftware/EPPlus#800]
Hello,

I have a Problem with Excel Files created with EPPlus. 
If i open only one file, everything works fine, but if i open multiple files i get a view with grey colored background. All data is missing and i can't work with the files.
This happens only with Excel 2016!

If i use Excel 2019 or higher, everything works fine. 

Best Regards,
Tobias

**Comment by JanKallman** [comment]
I have never heard of this issue before. Sounds more like an issue with your Excel 2016 installation. 
Can you attach one of the failing workbooks, so I can check if it's valid or if it has any OOXML validation errors?

**Comment by Bonekit** [comment]
Hello, thanks for the fast response. 
I can't attach a file, they are full with company data.
What are OOXML validation errors and how can i locate them?

**Comment by JanKallman** [comment]
You can use the [OOXML sdk](https://github.com/dotnet/Open-XML-SDK) for that or if you want something easier, use the OOXML 2.5 productivity tool found here...https://web.archive.org/web/20190116000204/https://www.microsoft.com/en-us/download/details.aspx?id=30425

**Comment by Bonekit** [comment]
Thank you for the Link.
I fixed the Issue, the Template caused the problem.
I recreated the Template with my Excel 2019 and everything worked fine on 2016 and 2019.
