### ISSUE TITLE
InvalidCastException when calling ExcelWorksheet.InsertRow

### ISSUE THREAD

**Issue by R4cOOn** [EPPlusSoftware/EPPlus#803]
Version 6.1.1 works fine but with 6.1.2 I get the error message
> Unable to cast object of type 'System.Linq.EmptyPartition`1[OfficeOpenXml.FormulaParsing.LexicalAnalysis.Token]' to type 'System.Collections.Generic.List`1[OfficeOpenXml.FormulaParsing.LexicalAnalysis.Token]'.

with the associated stack trace
 >   at OfficeOpenXml.Core.Worksheet.WorksheetRangeInsertHelper.GetTokens(ExcelWorksheet ws, Int32 row, Int32 column, String formula)
>    at OfficeOpenXml.Core.Worksheet.WorksheetRangeInsertHelper.FixFormulasInsertRow(ExcelWorksheet ws, Int32 rowFrom, Int32 rows, Int32 columnFrom, Int32 columnTo)
>    at OfficeOpenXml.Core.Worksheet.WorksheetRangeInsertHelper.InsertRow(ExcelWorksheet ws, Int32 rowFrom, Int32 rows, Int32 copyStylesFromRow)
>    at OfficeOpenXml.ExcelWorksheet.InsertRow(Int32 rowFrom, Int32 rows, Int32 copyStylesFromRow)
>    at OfficeOpenXml.ExcelWorksheet.InsertRow(Int32 rowFrom, Int32 rows)

The line that triggers the error (in not all cases) is:
` ws.InsertRow(81, 1);`
with `ws` an instance of `ExcelWorkSheet`.

I'll try to create a repro project that I can share. 
Currently the Excel file contains data that I can't share.

Chers.

**Comment by JanKallman** [comment]
Thanks, sounds great. I'll have a look at it once the repro is in place.

**Comment by ryan-mccartney-cs** [comment]
Just want to add that I also experienced the same error. InsertRow on a range with styling and exact same unable to cast issue. Reverting from 6.1.2 to 6.1.1 resolved, I suspect there's an unhandled error happening in here: https://github.com/EPPlusSoftware/EPPlus/compare/v6.1.1...v6.1.2#diff-d45ce0717737f5bce2bd9218c9ada0e0b828b011ac3e3cc1e36acdba3d69774cR773

**Comment by JanKallman** [comment]
Yes this is a bug. The issue happens if you have a formula that has been cleared and then insert rows. 
I will add a fix shortly.

**Comment by R4cOOn** [comment]
Nice, I won't have to spend time creating a repro project then :)
