### ISSUE TITLE
Worksheet.HeaderFooter - Issue with Symbols in the Header

### ISSUE THREAD

**Issue by Bonekit** [EPPlusSoftware/EPPlus#804]
Hello,

I have a new Issue with Symbols in the Worksheet.HeaderFooter.OddHeader.LeftAlignedText 

`            ws.HeaderFooter.OddHeader.LeftAlignedText = "&7&\"WingDings3\" g";
`
Should add a Arrow Symbol, i tried it in Excel directly. 
But my Worksheet has only a **g** in the Header as Text with the Font **WingDings3**.
Am i doing something wrong or is it not possible to add symbols into the header with EPPlus?

Best Regards,
Tobias

**Comment by JanKallman** [comment]
Have a look at our sample here... https://github.com/EPPlusSoftware/EPPlus.Sample.NetCore/blob/3c94b6c467e9891f6da280c018d8b8dc218c5311/01-GettingStarted/GettingStartedSample.cs#L86
Optionally check how Excel saves the format by renaming your workbook *.zip an check the format in the headerFooter element in the xl/worksheets/sheet1.xml. In my case it looked like this : &"Wingdings3,Normal"&7g

**Comment by Bonekit** [comment]
I found this in my sheet1.xml:

`<headerFooter scaleWithDoc="0" differentOddEven="1"><oddHeader>&amp;C&amp;"Wingdings3,Normal"&amp;7g</oddHeader><oddFooter>&amp;RSeite &amp;P von &amp;N</oddFooter><evenHeader>&amp;C&amp;"Wingdings3,Normal"&amp;7g</evenHeader><evenFooter>&amp;RSeite &amp;P von &amp;N</evenFooter></headerFooter>`

So my looks a little bit different, but why?

**Comment by JanKallman** [comment]
I don't think the order of the font properties matters. Also note that EPPlus will add the &L, &C or &R in the beginning depending on which property you use (LeftAlignedText, CenterText, RightAlignedText). It also appear that Normal and Regular both works.

**Comment by Bonekit** [comment]
Hello again,

My Code is now working, it took me a while to find out where the issue was.
`"&8&\"Wingdings,Normal\"è";`
Using Wingdings3 is not working, but Wingdings works great. I don't know why EPPlus is not working with Wingdings3, but i have my Arrow.

Next Question:
Can i set a Code for the Color Red into the String above?
I want the Arrow in Red not in Black. 

Best Regards,
Tobias
