### ISSUE TITLE
SUMIF does not work when comparing dates

### ISSUE THREAD

**Issue by olikeller** [EPPlusSoftware/EPPlus#809]
In Excel this formula works but in epplus it does not:

SUMIF(B1:B10,A1,C1:C10)

Where:
B1 to B10 are dates
C1 to C10 are values corresponding to a date from B1 to B10
A1 contains the date which values should be summed up

The SUMIF formula works in epplus if I replace the comparison type, as example with a greater than comparision e.g. SUMIF(B1:B10,\">0\",C1:C10).

I tested with the 6.1.3 and the 5.6.3 version. The problem exists in both versions. 

Thanks for help :)

**Comment by OssianEPPlus** [comment]
Hi! We found a bug internally that was causing this. We've since resolved it and are currently working on getting it out into our [Develop Branch](https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed). 

Where you should be able to test it out once the pull request completes.

**Comment by OssianEPPlus** [comment]
The fix has now been merged into develop

**Comment by olikeller** [comment]
I tested it and in works. Thanks!
