### ISSUE TITLE
HeaderFooter - Format Text not working

### ISSUE THREAD

**Issue by Bonekit** [EPPlusSoftware/EPPlus#816]
Hello Folks,

I used `&K:xxxxxx` to add the Color Red to my HeaderFooter Text.
But it's not working. Is there a problem with EPPlus or with my Code?

`const string arrow = "&K:FF0000&8&\"Wingdings,Normal\"è";`
The Result in my HeaderFooter is: 
**:FF0000**

Best Regards,
Tobias

**Comment by JanKallman** [comment]
Look like this when I try it in Excel...
`&"Wingdings,Normal"&8&KFF0000test`
Try to remove the ":"

**Comment by Bonekit** [comment]
Now i have Red Arrows. Thanks for the help!
**Try to remove the ":"** fixed my problem!
