### ISSUE TITLE
Utilize recyclable memory stream instead of "new MemoryStream" all over

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#82]
It would be nice if you guys utilized a recyclable memory stream to reduce LOH and GC

https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

There is a package here that makes this super easy.

**Comment by JanKallman** [comment]
Thanks for the suggestion! We'll try to have a look at this for the next version.

**Comment by LIFEfreedom** [comment]
@JanKallman I'll try to make a request for these improvements, if you don't mind. I did not find this in the created branches, I hope you did not start doing this))
Most of the replacements are ready, there are a few places left
