### ISSUE TITLE
ExcelRange.RichText.Clear method is cleared all cell style properties   

### ISSUE THREAD

**Issue by Piyush791** [EPPlusSoftware/EPPlus#821]
I am upgrading EPPLUS from 4.0.1 to 6.1.2 and after switching i have facing problem while i am working on excel cell.
In updated version, after using ExcelRange.RichText.Clear method , all cell style properties are also cleared and this was working in free version (4.0.1). Please help
My Code : 
excelRange.RichText.Clear();

**Comment by JanKallman** [comment]
Yes, this is not correct. Styles should not be cleared here. I'll add a fix for this. As a workaround you can use:
`excelRange.Value=null;`

**Comment by Piyush791** [comment]
It is not worked and facing same issue

**Comment by JanKallman** [comment]
Try latest develop build ... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed

**Comment by JanKallman** [comment]
Fixed in 6.1.1

**Comment by Piyush791** [comment]
Thanks Jan.. it is resolved now.
But now i am getting null reference error while getting column from work sheet using below method:
workSheet.Column(int columnNum) 
It did not come before this release.
FYI.. i am trying to create below excel file using epplus 
![image](https://user-images.githubusercontent.com/128135893/233285828-39352eac-59f6-41a5-a033-320def6728b5.png)
please help.
