### ISSUE TITLE
ExcelControl size null

### ISSUE THREAD

**Issue by LenonBordini** [EPPlusSoftware/EPPlus#822]
I need some help with `ExcelControl`.
After adding them, I want to know what's the size of the control based on the text I informed to add another on the right side.

```csharp
var radio1 = ws.Drawings.AddRadioButtonControl("someRadio");
radio1.Text = "Some text";
radio1.SetPosition(10, 10);
radio1.AdjustPositionAndSize();

var radio2 = ws.Drawings.AddRadioButtonControl("anotherRadio");
radio2.Text = "Another text";
radio2.SetPosition(10, radio1.Size.Width + 10); // radio1.Size is null
```

**Comment by JanKallman** [comment]
You have the coordinates in the `From `and `To` properties if the `CellAnchor` is `TwoCell`

**Comment by LenonBordini** [comment]
Thanks for answering, I managed to solve with another idea.
