### ISSUE TITLE
epplus uses version 5.71. On linux, it does not support using System.Drawing references

### ISSUE THREAD

**Issue by hailang2ll** [EPPlusSoftware/EPPlus#826]
epplus uses version 5.71, and does not support using System.Drawing references on linux, so it cannot parse and save the pictures in the table. Is it possible to parse the table pictures on linux now? thank you

**Comment by JanKallman** [comment]
EPPlus 6.0 and later will use an internal image handler on Linux. You can use System.Drawing.Common and LibGdiPlus, if you want to but I would recommend to use the internal handler. It is used by default.

**Comment by hailang2ll** [comment]
ExcelPicture excelPicture = GetImage(worksheet, cell.Start.Row, cell.Start.Column);

excelPicture.Image，How to save Pictures？
![微信图片_20230327175123](https://user-images.githubusercontent.com/28613121/227907383-e9c76cc3-77be-43f8-9002-2312389fcdda.png)

**Comment by JanKallman** [comment]
Use the `excelPicture.Image.Type` and `excelPicture.Image.ImageBytes` properties

**Comment by hailang2ll** [comment]
var bytes=excelPicture.Image.ImageBytes
How to save bytes as a picture? What are the built-in methods?

**Comment by JanKallman** [comment]
It's a byte array. Just use a `FileStream`, the `File` class or whatever method you prefer to save it. 
I'll close this issue.
