### ISSUE TITLE
请问 能否使得模板导出方法支持 dynamic 类型的数据进行传入处理

### ISSUE THREAD

**Issue by 1542793315** [EPPlusSoftware/EPPlus#827]
Magicodes.ExporterAndImporter.Excel.ExcelExporter.ExportByTemplate<dynamic>

请问 能否使得模板导出方法支持 dynamic 类型的数据进行传入处理

**Comment by 1542793315** [comment]
我这边大多数情况下的数据无法每个都进行构建泛型类，在不构建类的情况下 我都是转化为dynamic  类型进行处理的，但是模板导出中传入dynamic  类型的数据 会导致无法读取到指定字段

**Comment by JanKallman** [comment]
Please use English

**Comment by 1542793315** [comment]
Can I enable the template export method to support dynamic type data for incoming processing

In most cases, I cannot build generic classes for each of the data on my side. Without building classes, I convert them to dynamic types for processing. However, data of dynamic types passed in during template export will result in the inability to read the specified fields

**Comment by 1542793315** [comment]
In most cases, the data on my side cannot be used to construct generic classes,

Without building a class, I always convert it to a dynamic type for processing,

However, dynamic type data is passed in during template export

Will cause the specified field to be unreadable

**Comment by 1542793315** [comment]
![image](https://user-images.githubusercontent.com/48785885/228151594-cda165da-d7cc-4258-9882-adc69ed391b7.png)
这个是错误信息

**Comment by 1542793315** [comment]
Error message indicates that the field cannot be read
But it's okay when I go get it myself

**Comment by 1542793315** [comment]
![image](https://user-images.githubusercontent.com/48785885/228153734-089e6c5d-50af-47ba-9d45-480ebb21d21e.png)

This is my data

**Comment by 1542793315** [comment]
exportData is a collection of dictionary types.
