### ISSUE TITLE
Can I enable the template export method to support dynamic type data for incoming processing

### ISSUE THREAD

**Issue by 1542793315** [EPPlusSoftware/EPPlus#828]
In most cases, the data on my side cannot be used to construct generic classes,

Without building a class, I always convert it to a dynamic type for processing,

However, dynamic type data is passed in during template export

Will cause the specified field to be unreadable

![image](https://user-images.githubusercontent.com/48785885/228156570-de31ed3d-2069-401e-9923-ad7119fd39dc.png)
Error message indicates that the field cannot be read
But it's okay when I go get it myself

![image](https://user-images.githubusercontent.com/48785885/228156662-8a5aab37-7ed0-48ed-a87c-ac57fb736af9.png)
This is my data   
exportData is a collection of dictionary types.

**Comment by JanKallman** [comment]
I can't see that you use EPPlus?

**Comment by 1542793315** [comment]
new ExcelExporter().ExportByTemplate(destinationFilePath, templateData, templateFilePath);
@JanKallman

**Comment by JanKallman** [comment]
That is not EPPlus.

**Comment by 1542793315** [comment]
Oh, sorry, it's used together with the Epplus and Magicodes components. I got the wrong project address。
Thank you
