### ISSUE TITLE
Expose mechanism for freeing memory consumed by RecyclableMemoryStream

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#832]
It would be great to be able to set some configuration/limits on the RecyclableMemoryStream, as well as get back some of the memory, rather than it just growing to the size of the biggest excel file being processed, and staying that size

**Comment by JanKallman** [comment]
We will look at moving the RecyclableMemoryStream inside of EPPlus in a coming version, so we can look at config options at the same time.

**Comment by onionhammer** [comment]
Any update on this one?

**Comment by JanKallman** [comment]
No, we will look at this for EPPlus 7

**Comment by Artein** [comment]
Please, make something with memory consumption. Right now it is too much and I can't free it even if I dispose everything. Hope, this changes will help.

Edit: Just checked 7.0.0-beta1, and I see no changes in memory consumption.

**Comment by JanKallman** [comment]
Thanks for reminding us. I'm looking at it now. I'll update you here.

**Comment by JanKallman** [comment]
Added in EPPlus 7, `package.Settings.MemorySettings`
