### ISSUE TITLE
Not able to add image to excel with error "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by middiu** [EPPlusSoftware/EPPlus#834]
Hi there, 

we are facing an issue when we add an image to Excel.
The issue is occurring only with one specific image file for now.
The image file doesn't seem to be corrupted, in fact we can open it with an image app, edit it, etc etc. We also tried to open the file and convert it to a different format but still same issue.

Unfortunately in our application users can upload their own image files, and they except them to be stamped to an Excel file, so we cannot simply change the file.

This is the EPPlus package version installed (latest):  6.2.0
Dotnet version is 6

This is the code we use to add images to Excel: 

Our code is usually deployed in Azure as an Azure Fucntion App, but the error occurrs when ran locally in Visual Studio as well.

````
mapImage = ews01.Drawings.AddPicture(imageTitle, locationMapImage);
````

where **imageTitle** is a string, **locationMapImage** is the image Stream.

Error message is:
````
Index was outside the bounds of the array.
   at OfficeOpenXml.Drawing.ImageReader.IsGif(BinaryReader br)
   at OfficeOpenXml.Drawing.ImageReader.GetPictureTypeFromMs(MemoryStream ms)
   at OfficeOpenXml.Drawing.ImageReader.GetPictureType(Stream stream, Boolean throwException)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddImageInternal(String Name, Stream pictureStream, Nullable`1 pictureType, Uri Hyperlink)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddPicture(String Name, Stream PictureStream)
   at XYZ.API.Services.ReportFactoryService.AddImageToExcel(ExcelWorksheet ews01, Stream locationMapImage, String imageTitle, Int32 globalRowIndex, Int32 globalFromColumnIndex, Int32 globalToColumnIndex, Int32 maxWpixels, Int32 maxHpixels) in C:\git-projects\etc etc

````

I can share the image via email or through a private channel (EPPlus support portal) if required, as it cannot be published publicly.

**Comment by JanKallman** [comment]
Hello,
I can add this image without a problem. Looking at the failing method...
https://github.com/EPPlusSoftware/EPPlus/blob/0bc5864afe2ab70355387bcb929da034ce1f8823/src/EPPlus/Drawing/ImageHandling/ImageReader.cs#L328
... it looks like the image for some reason has zero bytes or is not accessible? Can this be the case?
Here is my working test:
```C#
        [TestMethod]
        public void i834()
        {
            if (File.Exists("issue834.xlsx")) File.Delete("issue834.xlsx");

            using (ExcelPackage package = new ExcelPackage("issue834.xlsx"))
            {
                //package.Settings.ImageSettings.PrimaryImageHandler = new SystemDrawingImageHandler();
                //package.Settings.ImageSettings.PrimaryImageHandler = new GenericImageHandler();
                var ws = package.Workbook.Worksheets.Add("Sheet1");
                ws.Drawings.AddPicture("Img1", "c:\\temp\\Issue834.PNG");
                package.Save();
            }
        }
```
Can you provide a test that reproduces the issue and fails?

**Comment by middiu** [comment]
Hi Jan,

I will work on settimg a small app that reproduces the problem.
I will get back to you asap.

Regards

**Comment by middiu** [comment]
> ... it looks like the image for some reason has zero bytes or is not accessible? Can this be the case?

this is it!
This comment made me think there was something wrong in how the file was read, and that was the problem.
For some reason the file was now read correctly, and then memory stream was empty/zero size.

I fixed the our code that read the file in the correct way, and now the same file can be added to Excel.

Thanks a lot for you help.

Cheers

**Comment by JanKallman** [comment]
Thanks for the info. We should add a check if the image file is empty and throw a more informative exception.
