### ISSUE TITLE
Error while accessing ExcelPackage

### ISSUE THREAD

**Issue by Deszynski** [EPPlusSoftware/EPPlus#835]
I used to make EPPlus apps in .net framework 4.7.3, now im trying to rewrite one to .net 6, got error like this:

Attempt by security transparent method 'OfficeOpenXml.ExcelPackage.Init()' to access security critical method 'System.Text.CodePagesEncodingProvider.get_Instance()' failed.

Assembly 'EPPlus, Version=6.2.0.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

on line 
using (ExcelPackage package = new ExcelPackage(existingFile))

I dont know what to do about it, cause its clearly EPPlus error, whole code is the same in .net framework 4.7.3 and it works well.
I tried readding EPPlus to project and use previous versions, clear debug and solution, recompile project, didn't worked.

**Comment by JanKallman** [comment]
I have never heard of this issue before. I assume it has something to do with the trust settings. Can you provide a small sample.

**Comment by Deszynski** [comment]
Error throws literally in `using (ExcelPackage package = new ExcelPackage(existingFile))` line.

`public object MyAction()
        {
            string fromPath = @"C:\Users\User\Downloads\ZK\";
            string toPath = @"C:\Users\User\Downloads\ZK\temp\";

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            DirectoryInfo dir = new DirectoryInfo(fromPath);
            FileInfo[] excelFiles = dir.GetFiles("*.xlsx");
                
            foreach (FileInfo file in excelFiles)
            {
                var filePath = file.FullName;
                FileInfo existingFile = new FileInfo(filePath);

                using (ExcelPackage package = new ExcelPackage(existingFile))
                {
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                    int rowCount = worksheet.Dimension.Rows;
                    string[,] data = new string[rowCount, 8];

                    for (int row = 2; row < rowCount; row++)
                    {
                        for (int col = 1; col <= 8; col++)
                        {
                            if (worksheet.Cells[row, col].Value != null)
                                data[row - 2, col - 1] = worksheet.Cells[row, col].Value.ToString();
                        }
                    }

                    ZalozTowary(data);
                    ZalozDokument(data);
                }

                File.Move(fromPath + file.Name, toPath + file.Name);
            }

            return 0;
        }`

I think its something about project build, but i added EPPlus from nuget like i always do. It should work.

**Comment by Deszynski** [comment]
Thats definitely it.
I tried to make App.Config
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<runtime>
		<!-- enables legacy CAS policy for this process -->
		<NetFx40_LegacySecurityPolicy enabled="true" />
	</runtime>
</configuration>
```
and Web.config file
```
<?xml version="1.0"?>
<configuration xmlns="https://schemas.microsoft.com/.NetConfiguration/v2.0">
	<appSettings/>
	<connectionStrings/>
	<system.web>

		<compilation debug="false"/>

		<authentication mode="Windows"/>

		<trust level="Full" />
	</system.web>
</configuration>
```
from the link you sent i wanted to try
1. Opening the Project Properties of the ClickOnce project in question
2. Opening the Security tab
3. Changing the trust settings to "This is a partial trust application"
4. Changing the trust settings back to "This is a full trust application"

but there's no Security settings in my Project, cause its not type of web project.
Is there another way to change EPPlus `AllowPartiallyTrustedCallers` attribute? Maybe from code somehow?
