### ISSUE TITLE
List validation doesn't allow empty values since 6.2.0

### ISSUE THREAD

**Issue by omeaart** [EPPlusSoftware/EPPlus#838]
We use EPPlus to generate excel files that can be filled and after that uploaded and processed. Since the last version generation of our sample files fails due to the changes in validation.

Repro:
```
using var excel = new ExcelPackage();
var sheet = excel.Workbook.Worksheets.Add("Sheet1");
sheet.Cells[1, 1].Value = "Column1";
var boolValidator = sheet.Cells["A2:A1048576"].DataValidation.AddListDataValidation();
{
	boolValidator .Formula.Values.Add("");
	boolValidator .Formula.Values.Add("True");
	boolValidator .Formula.Values.Add("False");
	boolValidator .ShowErrorMessage = true;
	boolValidator .Error = "Choose either False or True";
}
	
excel.Save();
```

This throws with InvalidOperation "Validation of A2:A1048576 failed: value cannot be null or empty"

The goal is to generate a file without prefilled values, but with validation when set to a value. This worked < 6.20

**Comment by OssianEPPlus** [comment]
This is indeed a bug, after update of DataValidations we seem to have accidentally disallowed empty values where they were allowed before. We'll hopefully be releasing a version today that fixes this and a number of other small bugs. I apologise for the inconvinence!

**Comment by OssianEPPlus** [comment]
We've released version 6.2.1 that should fix this issue. Does that version work for you?

**Comment by omeaart** [comment]
@OssianEPPlus yes, is resolved 👍

**Comment by OssianEPPlus** [comment]
Excellent, happy to be of aid!
