### ISSUE TITLE
BC40056	Namespace or type specified in the Imports 'EPPlus' doesn't contain any public member or cannot be found.

### ISSUE THREAD

**Issue by agerber85** [EPPlusSoftware/EPPlus#840]
I'm trying to use the EPPlus NuGet package for a vb.net console project in VS 2022 Professional (V4.8.04084) (Win 10, up-to-date).  At first, the NuGet Package Manager would not find the EPPlus package, so I had to install it using the console.  The line 
`Imports EPPlus`
returned the error "BC40056	Namespace or type specified in the Imports 'EPPlus' doesn't contain any public member or cannot be found."
I followed the instructions in the readme and added the system variable 'EPPlusLicenseContext' with a value of 'NonCommercial'.  The error persisted.  I then went into the NuGet Package Manager (which suddenly had no problem finding EPPlus), and rolled back to EPPlus 6.1.3 (instead of the latest stable, 6.2.0).  The error still persists. 
Any thoughts on how to get past this?

**Comment by agerber85** [comment]
I also thought I might need to add a reference, but I am unable to find anything related to EPPlus in the ReferenceManager.

**Comment by JanKallman** [comment]
Hello 
The top namespace is called `OfficeOpenXml`, so use 
`Imports OfficeOpenXml`
