### ISSUE TITLE
Regression between 6.1.2 and 6.2.0 loading ExcelPackage from stream

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#841]
When using an ExcelPackage loaded from an ASP.NET input stream; just uploading a 30 kb Excel file

```C#
var package = new ExcelPackage(); // this line succeeds
await package.LoadAsync(stream, cancellationToken); // this line succeeds
var worksheet = package.Workbook.Worksheets[0]; // <-- hangs here, and starts consuming gigabytes upon gigabytes of memory
```

The code now completely hangs, and actually starts consuming more and more and more memory until my PC  becomes unusable. 

The only code change is the upgrade from 6.1.2 to 6.2.0

Before request:
![image](https://user-images.githubusercontent.com/969938/230216390-66ca7b0f-a012-46b5-bfed-4501a8385379.png)

During request, the request never ends, since `.Worksheets[0]` never returns.
![image](https://user-images.githubusercontent.com/969938/230215698-d7e997f3-aa04-4e50-af56-c7b774e7a341.png)

**Comment by JanKallman** [comment]
We just released version 6.2.1, with some updates to the reading of data validations. Please try it, and see if it helps. Otherwise please attach a workbook to reproduce this issue.
