### ISSUE TITLE
Can't remove picture

### ISSUE THREAD

**Issue by TheR7angelo** [EPPlusSoftware/EPPlus#843]
When I want to delete an image, I get the error:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the collection size.

My variable that contains my Excel drawing comes from a foreach on the draw object though.
I get the same error with a clear.

![Capture d’écran 2023-04-13 094654](https://user-images.githubusercontent.com/26413622/231690333-e2a53a80-c52d-411d-a4e5-ffa9fa78d564.png)

**Comment by JanKallman** [comment]
Can you provide a workbook and some code to reproduce this issue?

**Comment by TheR7angelo** [comment]
The file: https://www.transfernow.net/dl/20230414gju7Flku

`
    public Task<(List<string> uris, List<string> names)> CleanPicture(List<string> app, int insee)
    {
        var picture = Book.Workbook.Worksheets["Photos"];
        var rowMax = picture!.Dimension.End.Row;
        var uris = new List<string>();
        var names = new List<string>();

        for (var row = rowMax - 1; row >= 2; row--)
        {
            var name = picture.Cells[row, 1].Value;
            if (name is null) continue;

            var nameStr = name.ToString()!.Trim();
            if (nameStr.Equals(string.Empty)) continue;

            // if (nameStr.Equals("0956099_1.jpg") & insee.Equals(47254)) Console.WriteLine("hey");

            nameStr = nameStr.Split('_')[0];

            var xname = nameStr;
            if (xname[0].Equals('0')) xname = xname[1..];

            if (app.Contains(nameStr) || app.Contains(xname)) continue;

            var us = DeletePicture(row, 4);
            if (us is not null) uris.AddRange(us);

            try
            {
                picture.DeleteRow(row - 1, 2);
            }
            catch (Exception e)
            {
                names.Add(name.ToString()!);
                Console.WriteLine(e);
                // throw;
            }
        }

        return Task.FromResult((uris, names));
    }
`

**Comment by JanKallman** [comment]
I can't run this code.

**Comment by TheR7angelo** [comment]
> I can't run this code.

do you have the same problem as me?
The Book variable represents the Package class

**Comment by TheR7angelo** [comment]
`    
private IEnumerable<string>? DeletePicture(int row, int col)
    {
        var pics = Drawings.Where(s => s.From.Row.Equals(row - 1)).ToList();

        if (!pics.Any()) pics = Drawings.Where(s => s.From.Row.Equals(row - 2)).ToList(); // GetPicture(row - 2, col);

        if (!pics.Any()) return null;

        var uris = new List<string>();
        foreach (var pic in pics)
        {
            var picture = pic as ExcelPicture;
            var uri = GetPictureUri(picture);

            if (uri is null) continue;
            uris.Add(uri);

            try
            {
                Drawings.Remove(picture);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                // Console.WriteLine("-----------------------------------");
                // throw;
            }
        }

        return uris;
    }

    private static string? GetPictureUri(ExcelPicture? picture)
    {
        var uri =
            picture?.GetType().GetInterface("IPictureContainer")?.GetProperty("UriPic")?.GetValue(picture, null) as Uri;
        return uri?.OriginalString;
    }`

Drawings is the sheet photos

**Comment by JanKallman** [comment]
Ah,ok, I see the problem. When you use a ExcelPicture object to delete it seems to go wrong. 
As a workaround use the index in the drawing collection instead. I'll provide a fix shortly.

**Comment by TheR7angelo** [comment]
> Ah,ok, I see the problem. When you use a ExcelPicture object to delete it seems to go wrong. As a workaround use the index in the drawing collection instead. I'll provide a fix shortly.

thanks

**Comment by TheR7angelo** [comment]
but the naming is supposed to be unique
I use the index and it's work

**Comment by JanKallman** [comment]
Yes, names should be unique. I have added a fix for this, so it will work in the next release.

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.2.3
