### ISSUE TITLE
Incorrect formulas after second InsertRow call

### ISSUE THREAD

**Issue by dnezamaev** [EPPlusSoftware/EPPlus#848]
Initial worksheet.
![image](https://user-images.githubusercontent.com/1729333/232081454-c2ca802e-4e87-4cce-995e-25a7f0539089.png)

Now insert blank row below first. Formula updated fine.
![image](https://user-images.githubusercontent.com/1729333/232083829-dd54d7fa-2c36-4cf0-b5d6-868fa5b26ae0.png)

Now insert blank row below second filled row (with header 3). Formula should be still A3\*B3. But it is updated to A2\*B2. Why?
![image](https://user-images.githubusercontent.com/1729333/232084680-926d318d-78b6-4e36-a128-be98be2caed9.png)

[Sample project](https://github.com/dnezamaev/EppInsertRowsIssue) to reproduce bug.

Bug reproduced on EPPlus versions 6.20, 6.21. 

But on 6.0.3 it worked fine, formulas were correct.

**Comment by JanKallman** [comment]
Thanksm, we will have a look at this.

**Comment by KristofVerbiest** [comment]
This was OK in 6.1.1, the first version with this problem is 6.1.2.

If this is not fixed soon, I have to revert all the way back to EPPlus 5.6.4 (I cannot revert to 6.1.1 due to issue #780). So a quick fix would be greatly appreciated!

**Comment by KristofVerbiest** [comment]
Thanks for the quick response! 

I tried the new release. Using the sample project of [dnezamaev](https://github.com/dnezamaev) there is no problem anymore.

However I still am having problems that I think are related. 
Sample code:
```
[TestMethod]
public void Issue848()
{
    ExcelPackage.LicenseContext = LicenseContext.Commercial;
    using var package = new ExcelPackage();
    var worksheet = package.Workbook.Worksheets.Add("Sheet1");

    // We start with a single row that has a formula
    worksheet.Cells["A1"].Value = 1;
    worksheet.Cells["B1"].Value = 2;
    worksheet.Cells["C1"].Formula = "A1*B1";

    // Insert a row and copy the original row
    worksheet.InsertRow(2, 1);
    worksheet.Cells["A1:C1"].Copy(worksheet.Cells["A2:C2"]);
    Debug.Assert(worksheet.Cells["C1"].Formula == "A1*B1");
    Debug.Assert(worksheet.Cells["C2"].Formula == "A2*B2");

     // Insert another row and copy the original row
    worksheet.InsertRow(3, 1);
    worksheet.Cells["A1:C1"].Copy(worksheet.Cells["A3:C3"]);
    Debug.Assert(worksheet.Cells["C1"].Formula == "A1*B1");
    Debug.Assert(worksheet.Cells["C2"].Formula == "A2*B2");
    Debug.Assert(worksheet.Cells["C3"].Formula == "A3*B3");

    // Delete the original row
    worksheet.DeleteRow(1);
    Debug.Assert(worksheet.Cells["C1"].Formula == "A1*B1"); // This still succeeds...
    Debug.Assert(worksheet.Cells["C2"].Formula == "A2*B2");

    // Insert a row the end
    worksheet.InsertRow(4, 1); // This seems to trigger the issue

    // Next line fails, the formula in C1 is "A2*B2" (which is wrong)
    Debug.Assert(worksheet.Cells["C1"].Formula == "A1*B1"); //  ... Now this fails
    Debug.Assert(worksheet.Cells["C2"].Formula == "A2*B2");
}
```

I have the feeling this is related to this issue, but if you want I can create a separate issue.

**Comment by JanKallman** [comment]
@KristofVerbiest I'll have a quick look and see if it's something we can squeeze into 6.2.2 released today.

**Comment by JanKallman** [comment]
Yes, this is the same issue. The problem is that we have done an optimization to read the formula tokens from the token store, but they do not update when deleting the row. I will remove this optimization and create the tokens when the insert is made, to avoid the risk that the token store is not updated on other places.
