### ISSUE TITLE
saving a worksheet of 90K rows x 2k columns throws zip exception

### ISSUE THREAD

**Issue by khatran79** [EPPlusSoftware/EPPlus#86]
```
using (var excel = new ExcelPackage())
            {
                var ws = excel.Workbook.Worksheets.Add("test");
                for(int r = 1; r < 90000; r++)
                {
                    for (int c = 1; c < 2000; c++)
                    {
                        ws.Cells[r, c].Value = r * c;
                    }
                }

                excel.SaveAs(new FileInfo(excelFilePath));
            }
```

OfficeOpenXml.Packaging.Ionic.Zip.ZipException: 
Compressed or Uncompressed size, or offset exceeds the maximum value. 
Consider setting the UseZip64WhenSaving property on the ZipFile instance.

Any idea pls

**Comment by JanKallman** [comment]
That's a really big Excel file. It seems the size for Zip32 is exceed.
I'm unsure if Excel supports Zip64, but we can have a look at it for future versions.

**Comment by khatran79** [comment]
That is the size of our excel file generated using gembox v35. Any idea how to replace this Zip32 by Zip64 in case you dont have any plan to handle this bug soon? Thanks

**Comment by JanKallman** [comment]
Do you use the Commercial or Non-Commercial license of EPPlus?

**Comment by khatran79** [comment]
Non-Commercial license

**Comment by JanKallman** [comment]
I'll keep this issue open to fix for a future version.

**Comment by JanKallman** [comment]
I had a brief look at this and setting the Zip64 flag in DotNetZip will cause the package to be corrupt.
So I can't apply a quickfix for this. We might have to replace DotNetZip with something else. I will have another look if Microsoft has fixed the threading issues i the System.IO.Packaging api in later versions (this is the main reason we have our own implementation). 
Alternatively, we can look at a fix for the issue in DotNetZip. An article that might help can be found here…
https://rzymek.github.io/post/excel-zip64/

**Comment by JanKallman** [comment]
Enabled Zip64 when needed and fixed DotNetZip issue causing Excel to fail on load.
[feature/zip64](https://github.com/EPPlusSoftware/EPPlus/tree/feature/zip64)

**Comment by JanKallman** [comment]
Enabled Zip64 in  version 5.2.1
