### ISSUE TITLE
Filling a Row with a color when a Column has borders causes borders to be copied

### ISSUE THREAD

**Issue by CyberBotX** [EPPlusSoftware/EPPlus#861]
Below is sample code to demonstrate my issue:

```csharp
using var ep = new OfficeOpenXml.ExcelPackage();
var ws = ep.Workbook.Worksheets.Add("Test");

for (int row = 1; row < 6; ++row)
	for (int col = 1; col < 6; ++col)
		ws.Cells[row, col].Value = $"{row}:{col}";

var wsCol = ws.Column(3);
wsCol.Style.Border.Left.Style = wsCol.Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
wsCol.Style.Fill.SetBackground(System.Drawing.Color.Gray);

ws.Row(3).Style.Fill.SetBackground(System.Drawing.Color.Yellow);

await ep.SaveAsAsync(new System.IO.FileInfo(System.IO.Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.MyDocuments), "TestBorders.xlsx")));
```

What happens here is that I put borders on the left and right of column C (3rd column), fill in the column with the color gray, then I fill in row 3 with the color yellow. When that happens and I load the resulting file, either in LibreOffice or in Excel, I see that every single cell within row 3 has a border on its left/right.

I've also found that this happens even if column C isn't filled with a color, and it also happens if only one of those borders are set. I've also found it happens if ANY borders are set on the column before I fill in the row's color. The choice of color for the row does not seem to matter.

It does not seem to happen if only individual cells within the column have the border set instead of the whole column, it only seems to happen when an entire column is given a border.

It does not happen if I do things the other way around: if I set the borders for the entire row and then fill in the color of the column, the other cells in the column do not copy.

It seems that the row color filling applies the border of the last column that had a border. If I change the code so it applies a border on the left to column B (2) and a border on the top to column D (4), then when I fill in the row, all the cells in the row have a top border.

As far as I can tell, this has been an issue in EPPlus since even all the way back to version 4.5.1, but I hadn't noticed the problem until recently when I was making spreadsheets via EPPlus that had column borders and then I filled in a row's color.

**Comment by OssianEPPlus** [comment]
Thanks for letting us know! This appears to be a bug within our internal styleID handling. We're working on a fix. In the meantime it seems that putting the line

`ws.Row(3).Style.Fill.SetBackground(System.Drawing.Color.Yellow);`

above `var wsCol = ws.Column(3);`

is a workaround that produces the expected results.
