### ISSUE TITLE
An error occurs when setting Shape.Text ."Name cannot begin with the ' ' character, hexadecimal value 0x20"

### ISSUE THREAD

**Issue by menrock** [EPPlusSoftware/EPPlus#874]
In the class "EPPlus/src/EPPlus/Style//ExcelParagraphCollection.cs"

line 124  “defNode.InnerXml = "<a:latin typeface=\"Calibri\" />< a:cs typeface=\"Calibri\" />";”

There is an extra space between < and a,resulting in an error:"Name cannot begin with the ' ' character, hexadecimal value 0x20".

**Comment by JanKallman** [comment]
Thanks for reporting this. I just committed this change.

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.2.5
