### ISSUE TITLE
REPLACE() behavior differs from Excel

### ISSUE THREAD

**Issue by colbybhearn** [EPPlusSoftware/EPPlus#880]
Hey, I accidentally passed too large a value for the parameter `num_chars` when calling `REPLACE()`

In Excel, `=REPLACE("OLDTEXT",5,20,"NEW")` yields `OLDTNEW` 

In EPPlus, `=REPLACE("OLDTEXT",5,20,"NEW")` yields `#VALUE!`

It's an easy fix for me to use the function properly in the first place, but I figured you'd want to be aware of the difference. 
Thanks,
-Colby

**Comment by JanKallman** [comment]
Thanks for reporting this. We'll have a look at it.

**Comment by swmal** [comment]
Hi Colby,

I could replicate this so it should be an easy fix for next version. Our implementation of REPLACE uses the .NET String.Substring function and your example generates an "index out of bounds" error, which then causes the #VALUE!.

**Comment by swmal** [comment]
This should be fixed in the latest version.
