### ISSUE TITLE
Can EPPLUS After Generate Excel Object Like Chart,then can Use it in Clipboard For VSTO Addin Consume?

### ISSUE THREAD

**Issue by minren118** [EPPlusSoftware/EPPlus#883]
Now I use VSTO to develop Excel plug-ins. For some operations requiring high performance, I want to use EPPLUS to achieve them. Is it possible to implement a method in EPPLUS that after copying some Excel objects, can generate effects in the clipboard memory that can be pasted by CTRL+V on Excel interface?

In addition to high performance, the big problem was that I not only needed to develop a plug-in for Excel, but also to make it compatible with the Chinese office software WPS, which was a near perfect copy of Excel's VBA object model. So it's very easy to develop in one go for both Excel and WPS.

But unfortunately, the VBA object model of WPS, there are still a lot of bugs exist, the same VSTO code, complex object model, compatibility is very limited.

If EPPLUS can generate an Excel object in memory and output it to the clipboard, I can call the WorkSheet.Paste method in VSTO and output the result to Excel or WPS.

**Comment by minren118** [comment]
It Can Use insideClipboard to find what is the Excel Consume In the Clipboard contents, like copy Range,it will use the [XML Spreadsheet] type  to paste in the worksheet. other like chart object is clip type is [Art::GVML ClipFormat] is the zip file type of open xml

![image](https://github.com/EPPlusSoftware/EPPlus/assets/28550438/4284ee86-2a81-412d-9692-8b9bd455044d)

![image](https://github.com/EPPlusSoftware/EPPlus/assets/28550438/5450fd69-3145-416a-a7f0-2b7bfd23b361)

**Comment by minren118** [comment]
I did a test comparing the chart1.xml file in the clipboard with the chart1.xml file extracted from the xlsx file. They were almost identical. Replacing the chart1.xml file in the xlsx file with the chart1.xml file on the clipboard and re-opening it in Excel was successful.



Or is it possible that, in EPPLUS, I can get the chart1.xml content corresponding to this chart, and with the xml text in this file, I can successfully construct the contents of the clipboard and eventually paste the modified contents of EPPLUS for VSTO to use.

**Comment by JanKallman** [comment]
Yes you can, via the ExcelChart.ChartXml property.
