### ISSUE TITLE
AutoFitColumns appears to miscalculate

### ISSUE THREAD

**Issue by Paul3816547290** [EPPlusSoftware/EPPlus#884]
After using autofit on a whole worksheet (i.e. worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();)

And then opening in Excel I notice the following.

1. Any cell with multilines is miscalculated - I had some lines with Rich Text lines "This is some text\r\nThis is some more text\r\n" and this would horizontally wrap too short (like it was word wrapping the lines, not wrapping on line breaks - like excel would)
2. Excel autofit will enlarge all cells about 1 pixel.  And would resize those miscalculated above

**Comment by JanKallman** [comment]
EPPlus currently ignore cells with the WrapText style property set. The autofit columns property is not exact, but you can play with the settings for it if needed. Have a look at this [wiki page](https://github.com/EPPlusSoftware/EPPlus/wiki/Autofit-columns)
