### ISSUE TITLE
.GetAsByteArray()'  'System.ObjectDisposedException' 

### ISSUE THREAD

**Issue by steph9111** [EPPlusSoftware/EPPlus#89]
EPPLUS version 5.1

Dim _ExcelApplication As ExcelPackage = New ExcelPackage(New IO.FileInfo("file1.xlsx"))
        Dim _ExcelApplication2 As ExcelPackage = New ExcelPackage(New IO.FileInfo("file2.xlsx"))

        Dim _SheetToCopy As ExcelWorksheet = _ExcelApplication.Workbook.Worksheets(2)

        _ExcelApplication2.Workbook.Worksheets.Add("test1", _SheetToCopy)

        _ExcelApplication2.Save()

or

        Dim bin As Byte() = _ExcelApplication2.GetAsByteArray()

Error

		StackTrace	"   à System.IO.__Error.StreamIsClosed()" & vbCrLf & "   à System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)" & vbCrLf & "   à OfficeOpenXml.Packaging.ZipPackagePart.GetStream(FileMode fileMode, FileAccess fileAccess)" & vbCrLf & "   à OfficeOpenXml.Packaging.ZipPackagePart.WriteZip(ZipOutputStream os)" & vbCrLf & "   à OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)" & vbCrLf & "   à OfficeOpenXml.ExcelPackage.GetAsByteArray(Boolean save)" & vbCrLf & "   à OfficeOpenXml.ExcelPackage.GetAsByteArray()"

**Comment by JanKallman** [comment]
I can't reproduce this. Can you attach the xlsx file you are using.
