### ISSUE TITLE
Locked cell not working

### ISSUE THREAD

**Issue by VidsPatel005** [EPPlusSoftware/EPPlus#891]
Hello,

I'm using Excel Package version 4.5.3.1 and I try to lock the selected range of the excel cell but it not work, I tried below lines.

ws.Column(3).Style.Locked = true;
ws.Cells["A2:A50"].Style.Locked = true;

**Comment by OssianEPPlus** [comment]
Hi there!
Version 4.X is deprecated. However you could checkout [this wiki page](https://github.com/EPPlusSoftware/EPPlus/wiki/Encrypt-and-Protect-your-workbook)

It might be because you are missing the
```
sheet.Protection.AllowSelectLockedCells = false;
sheet.Protection.SetPassword("EPPlus");
```
parts.

**Comment by VidsPatel005** [comment]
Hello,

I updated Excel Package version from 4.5.3.1 to 6.2.4 and I try to lock the selected range of the excel cell but it not work.

sheet.Protection.AllowSelectLockedCells = false;
sheet.Protection.SetPassword("123");
ws.Column(3).Style.Locked = true;
ws.Cells["A2:A50"].Style.Locked = true;
