### ISSUE TITLE
Windows Platform FIPS error

### ISSUE THREAD

**Issue by fadeless509** [EPPlusSoftware/EPPlus#892]
When I encrypt an excel file, a FIPS error

**Comment by fadeless509** [comment]
Example：
ExcelPackage l_ep = new ExcelPackage ();
FileInfo fileInfo = new FileInfo(this.FileName);
l_ep.SaveAs(fileInfo, pwd);

**Comment by JanKallman** [comment]
Please attach the xlsx file.

**Comment by fadeless509** [comment]
[](url)
[TEST_20230607.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/11673362/TEST_20230607.xlsx)
When I use FileInfo to get the file, use the SaveAs method of ExcelPackage and encrypt it

**Comment by JanKallman** [comment]
Works fine when I save this file with encryption. Please provide a fully reproducible sample and  let me know which environment you are running in.

**Comment by fadeless509** [comment]
![65a353f5-8061-4018-822d-d8c2997dadd8 original](https://github.com/EPPlusSoftware/EPPlus/assets/13887176/2d68c8bb-6055-4b65-8cbb-07323762dc47)

My Server has enabled use FIPS settings, in Windwos Server 2012R2.
Due to information security requirements, FIPS must be enabled
Does the encryption method of EPPLUS have a mode of passing FIPS?

**Comment by JanKallman** [comment]
Hmm, no, EPPlus uses the standard .NET classes for encryption. 
For the Agile encryption(default) AES256 is used and SHA512 for hashing. 
I'm not sure what the requirement for FIPS compliant algorithms are. Do you have a stack trace with more detailed information for the exception?

**Comment by fadeless509** [comment]
Stack Trace：
System.Security.Cryptography.RijndaelManaged..ctor()
OfficeOpenXml.Encryption.EncryptedPackageHandler.EncryptDataAgile(Byte[] data, EncryptionInfoAgile encryptionInfo, HashAlgorithm hashProvider)
OfficeOpenXml.Encryption.EncryptedPackageHandler.EncryptPackageAgile(Byte[] package, ExcelEncryption encryption)
OfficeOpenXml.ExcelPackage.Save()

**Comment by JanKallman** [comment]
It seems to fail in the constructor here ...
https://github.com/EPPlusSoftware/EPPlus/blob/83e33c3e1e1bd35db4cd3d159deec93b0bd2ccac/src/EPPlus/Encryption/EncryptionHandler.cs#L204
I assume the `RijndaelManaged` is not FIPS compliant. I'll have a look and see if there is a newer version of this class.

**Comment by fadeless509** [comment]
Understood, thank you very much for your help

**Comment by JanKallman** [comment]
Have a look at this thread. https://stackoverflow.com/questions/939040/when-will-c-sharp-aes-algorithm-be-fips-compliant
I have not tried this, but you seem to be able to disable the policy check via the config file only for your app...
`<configuration> <runtime> <enforceFIPSPolicy enabled="false"/> <runtime> </configuration>`
This might be an option, if you are allowed to do this.

**Comment by fadeless509** [comment]
I've tried but it doesn't work

**Comment by JanKallman** [comment]
I have changed the `RijndaelManaged` class to `AES ` from version 6.2.5 for .NET framework .NET Standard and .NET 6-7 already used the `AES` class.
