### ISSUE TITLE
Locked cell not working

### ISSUE THREAD

**Issue by VidsPatel005** [EPPlusSoftware/EPPlus#897]
Hello,

I updated Excel Package version from 4.5.3.1 to 6.2.4 and I try to lock the selected range of the excel cell but it not work and I'm using EP plus non commercial license, Please review the my controller code below.

ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

sheet.Protection.AllowSelectLockedCells = false;
sheet.Protection.SetPassword("123");

ws.Column(3).Style.Locked = true;
ws.Cells["A2:A50"].Style.Locked = true;

Please try to response ASAP.

**Comment by OssianEPPlus** [comment]
Locking seems to work just fine. But you do need to apply the protection on the same worksheet as you apply the styles to so it should be:

```
ws.Protection.AllowSelectLockedCells = false;
ws.Protection.SetPassword("123");
```
not sheet.

Also keep in mind that all cells in excel are considered locked by default so if you want to be able to select for example "B1:B5" but keep other cells locked you may want to try

```
ws.Protection.AllowSelectUnlockedCells = true;
ws.Cells["B1:B5"].Style.Locked = false;
```

**Comment by JanKallman** [comment]
I assume this works. Re-open this issue otherwise with a description of the issue.
