### ISSUE TITLE
Inaccurate column width

### ISSUE THREAD

**Issue by Sc7-git** [EPPlusSoftware/EPPlus#912]
Set in code:
` worksheet.Columns[1].Width = 40 ；`
But in Excel, the column width is only 39.2.

**Comment by JanKallman** [comment]
The width in EPPlus is the OOXML width. It differs from the width in Excel. 
You can look at the formula here, on the width property, to convert to into the Excel GUI format: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.column?view=openxml-2.8.1
