### ISSUE TITLE
Applying Border style is really slow

### ISSUE THREAD

**Issue by supertx2** [EPPlusSoftware/EPPlus#92]
I have an excel with 214 rows and 14035 columns
It takes around 12 minutes to apply each style to the cells range, in total 48 minutes
Is there something that I can do to improve speeds?
```
using (var range = worksheet.Cells[1, 1, maxRows, maxColumns])
{
    range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
    range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
    range.Style.Border.Right.Style = ExcelBorderStyle.Thin;
    range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
}
```

**Comment by JanKallman** [comment]
The style cache for columns was not used in a correct manner, causing bad performance.

**Comment by JanKallman** [comment]
Try latest build from this feed…
https://ci.appveyor.com/nuget/epplus

**Comment by supertx2** [comment]
Thank @JanKallman it's great now
