### ISSUE TITLE
Conditional formatting range incorrectly updated when deleting a column

### ISSUE THREAD

**Issue by peitschie** [EPPlusSoftware/EPPlus#923]
This occurs in 6.2.6.

Basically, if conditional formatting is applied to a range of columns, and then a column before the conditional formatting is removed, the formatting range incorrectly shrinks by one.

For example:
1. Create a workbook with 10 columns (A => I)
2. Apply conditional formatting from column C => Z
3. Now remove column 1
4. Note that the conditional formatting no longer appears to affect the last column with values (will be column H after removal)

Here's the worksheet without removing column 1:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/1052079/3fc1eb7c-c178-4ae3-8237-ade0e8af3b0d)

Here's the worksheet after removing column 1:
![image](https://github.com/EPPlusSoftware/EPPlus/assets/1052079/6cb4f6d9-22ca-4521-bb06-7e8f1cddcca4)

Note that the highlighted range has shrunk from 7 columns to 6 columns, despite the removal occurring outside the selected format range.

This behaviour used to work as expected in EPPlus v4.5.3, so it's regressed somewhere since then.

Reproduction based off the sample projects:

Adding and removing the `worksheet.DeleteColumn(1); // <--- THIS LINE CAUSES THE BUG` line shows the bug.

```
namespace EPPlusSamples
{
class ConditionalFormatting
{
    /// <summary>
    /// Sample 14 - Conditional formatting example
    /// </summary>
    public static string Run()
    {
      FileInfo newFile = FileUtil.GetCleanFileInfo("11-ConditionalFormatting.xlsx");
      using (ExcelPackage package = new ExcelPackage(newFile))
      {
        // add a new worksheet to the empty workbook
        ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Conditional Formatting");

        // Create 4 columns of samples data
        for (int col = 1; col < 10; col++)
        {
          // Add the headers
          worksheet.Cells[1, col].Value = "Sample " + col;

          for (int row = 2; row < 21; row++)
          {
            // Add some items...
            worksheet.Cells[row, col].Value = "Me";
          }
        }

        var range = worksheet.Cells["C:Z"];

        // -------------------------------------------------------------------
        // Create a ContainsText rule
        // -------------------------------------------------------------------
        var cfRule28 = range.ConditionalFormatting.AddContainsText();
        cfRule28.Text = "Me";
        cfRule28.Style.Fill.BackgroundColor.Color = Color.FromArgb(198, 239, 206);

        worksheet.DeleteColumn(1); // <--- THIS LINE CAUSES THE BUG

        // save our new workbook and we are done!
        package.Save();
      }

      return newFile.FullName;
    }
}
}
```

**Comment by OssianEPPlus** [comment]
This is indeed a bug! We're working on a fix, thanks for letting us know!

**Comment by peitschie** [comment]
Thanks for the rapid fix @OssianEPPlus ❤️

**Comment by OssianEPPlus** [comment]
No worries! Happy to help
