### ISSUE TITLE
Update TabSelected and TopLeftCell

### ISSUE THREAD

**Issue by TheR7angelo** [EPPlusSoftware/EPPlus#924]
Hi i've got this error when I change properties TopLeftCell and SetTabSelected from Worksheet view

`
var package = new ExcelPackage(file);
var workbook = package.Workbook;
var sheet = workbook.Worksheets[0];

var sheetView = sheet.View;

sheetView.SetTabSelected();
sheetView.TopLeftCell = "W96";

package.Save();
`
the lines are frozen elsewhere

[bug.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/11904415/bug.xlsx)
[original.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/11904419/original.xlsx)

**Comment by JanKallman** [comment]
Hi,
Try this:
```C#
sheetView.PaneSettings.TopLeftCell = "W96";
sheetView.Panes[2].SelectedRange = "W96";  //Index 2 is the bottom right pane.
sheetView.Panes[2].ActiveCell = "W96";
```
I will have a look how this works with with splitted panes.

**Comment by OssianEPPlus** [comment]
Closed due to inactivity.
