### ISSUE TITLE
How to save xlsm as xlsx with EPplus

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#94]
Hi

How to save xlsm as xlsx with EPplus?

After executing with the following code, the saved file cannot be opened
----------------------------------------
 var file = new FileInfo(RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ? @"/usr/local/src/DockerWebAPI/test.xlsx" : @"G:\test.xlsm");
            using (ExcelPackage pck = new ExcelPackage(file))
            {
                            pck.SaveAs(new FileInfo(RuntimeInformation.IsOSPlatform(OSPlatform.Linux) ? @"/usr/local/src/DockerWebAPI/test2.xlsx" : @"G:\test2.xlsx"));
            }

help me

**Comment by 93910676wangd** [comment]
It can be implemented in the following way of Documentformat.openxml,
But what I want to know is can EPPlus achieve the same function directly?
If so, please help me. esteem it a favor.
--------------------------------------------------------------------------------
using (var inputStream = System.IO.File.OpenRead(@"G:\test.xlsm"))
            using (var outStream = new MemoryStream())
            {
                inputStream.CopyTo(outStream);
                using (var doc = SpreadsheetDocument.Open(outStream, true))
                {
                    doc.DeletePartsRecursivelyOfType<VbaDataPart>();
                    doc.DeletePartsRecursivelyOfType<VbaProjectPart>();
                    doc.ChangeDocumentType(DocumentFormat.OpenXml.SpreadsheetDocumentType.Workbook);
                }
                System.IO.File.WriteAllBytes(@"G:\test2.xlsx", outStream.ToArray());
            }

**Comment by JanKallman** [comment]
Hello,
You should remove the VBA project, but I noticed that this did not work correctly in the current version. I have supplied a fix for it which also add a new method pck.Workbook.RemoveVBAProject(). pck.Workbook.VbaProject.Remove() also work when this fix has been applied.

**Comment by JanKallman** [comment]
Fixed in version 5.1.1
