### ISSUE TITLE
Problem with copy and style

### ISSUE THREAD

**Issue by steph9111** [EPPlusSoftware/EPPlus#96]
I use this code

`
        Dim _ExcelApplication As ExcelPackage = New ExcelPackage(New IO.FileInfo("copy0.xlsx"))
        Dim _ExcelApplicationCopy As ExcelPackage = New ExcelPackage(New IO.FileInfo("other1.xlsx"))

        Dim wsheet As ExcelWorksheet = _ExcelApplicationCopy.Workbook.Worksheets.Add("Fiche Fab")

        _ExcelApplication.Workbook.Worksheets("fiche fab").Cells("A1:AX50").Copy(wsheet.Cells("A1:AX50"), ExcelRangeCopyOptionFlags.ExcludeFormulas)

        _ExcelApplicationCopy.Save()

 `
Or this code

`
        Dim _ExcelApplication As ExcelPackage = New ExcelPackage(New IO.FileInfo("copy0.xlsx"))
        Dim _ExcelApplicationCopy As ExcelPackage = New ExcelPackage(New IO.FileInfo("other1.xlsx"))

        Dim wsheet As ExcelWorksheet = _ExcelApplicationCopy.Workbook.Worksheets.Add("Fiche Fab")

        _ExcelApplication.Workbook.Worksheets("fiche fab").Cells("A1:AX50").Copy(wsheet.Cells("A1:AX50"), ExcelRangeCopyOptionFlags.ExcludeFormulas)

        For i As Integer = 1 To 50
            wsheet.Row(i).StyleID = _ExcelApplication.Workbook.Worksheets("fiche fab").Row(i).StyleID
        Next
        _ExcelApplicationCopy.Save()

`
But the result it'only then same

Source:

![source](https://user-images.githubusercontent.com/43347051/80372252-9e7a9a00-8869-11ea-854c-fd653abf1fac.PNG)

Result copy:

![result](https://user-images.githubusercontent.com/43347051/80372272-a9352f00-8869-11ea-8fe5-239704397171.PNG)
[copy0.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4539573/copy0.xlsx)
[other1.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/4539575/other1.xlsx)

**Comment by JanKallman** [comment]
Thanks, I'll have a look

**Comment by JanKallman** [comment]
The Copy method will only copy the cells and their settings. In this case you copy between two packages where you have different color themes, different settings for the worksheet etc.
Also when you copy between two packages you can't copy the StyleId as you do for rows. StyleId's are referencing the package internal style table, so they will not match in another package.
