### ISSUE TITLE
After row deletion, the from.rowoff offset of the following shape is incorrect

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#98]
EPPlus 5.1.1
Premise: there is line shape after the row to be deleted, and it is a horizontal line
Problem: however, after deleting a row with the deleterow method of the worksheet, the from.rowoff of the  shape under the original row becomes 0, which causes the line representation to shift. I hope this error can be corrected

![epplus-error](https://user-images.githubusercontent.com/19505572/80475600-aaef1780-897b-11ea-9715-68d05217bb72.png)

**Comment by JanKallman** [comment]
Row/column offset is always adjusted. Fix will be added shortly

**Comment by JanKallman** [comment]
Fixed in version 5.1.2
