### ISSUE TITLE
Chart series with static values

### ISSUE THREAD

**Issue by kadir133** [EPPlusSoftware/EPPlus#981]
hi,

I want to create chart series with static values (as in the picture) without any cell references. But the series cannot be created without the cell reference. Is it possible to improve on this?

![image](https://github.com/EPPlusSoftware/EPPlus/assets/37574590/ae1fe969-c427-458f-ae2b-90c62137fe4b)

**Comment by OssianEPPlus** [comment]
You can actually already do this!

You can try for example:
```
var ws = package.Workbook.Worksheets.Add("LineCharts");
var chart = ws.Drawings.AddLineChart("LineChart", eLineChartType.Line);
var serie = chart.Series.Add("{1.0, 2, 3, 4.5}");
serie.Header = "Static Values";
chart.SetPosition(0, 0, 6, 0);
chart.SetSize(1200, 400);   //Make this chart wider to make room for the datatable.
chart.Title.Text = "A Line Chart With Static Values";
chart.PlotArea.CreateDataTable();
```

**Comment by kadir133** [comment]
Sorry, I missed something. I actually tried this way but got an error.
Then I realized in your answer that I should use commas to separate numbers, whereas office uses semicolons.

thanks...

**Comment by OssianEPPlus** [comment]
No worries! It's an easy thing to have happen. I've made that mistake myself before.
The seperators in office are language culture dependent, we use commas as a standard since that's what the xml requires but opening any epplus generated file shows the local settings for seperators within office for the formula

**Comment by kadir133** [comment]
I will pay attention to it from now on.😀
Thanks again for your help. 

I closed the issue.
