### ISSUE TITLE
How to export pivot table data ?

### ISSUE THREAD

**Issue by ado5** [EPPlusSoftware/EPPlus#986]
How to get the range of data of a pivot table output?

**Comment by JanKallman** [comment]
You cannot do that, because EPPlus relies on Excel to calculate and render the pivot table. We will likely add calculation and rendering of pivot tables in a future version.

**Comment by JanKallman** [comment]
I'll close this for now. We will start looking at pivot table calculation and rendering after EPPlus 7 has been released, ETA Q3/Q4.
