### ISSUE TITLE
Set Conditional Formatting DataBar Border Color

### ISSUE THREAD

**Issue by geoced** [EPPlusSoftware/EPPlus#996]
Hello,

I have added conditional formatting to a range of cells, and I've chosen a databar. I can't seem to find how to set the data bar border color. Using Excel's GUI, it looks like this:

Excel GUI
![image](https://github.com/dfinke/ImportExcel/assets/40609578/eeaaafca-b548-489e-8e90-51cf4a0835c6)

With EPPlus:
![image](https://github.com/dfinke/ImportExcel/assets/40609578/1de559c8-707c-460c-ab05-2840715c2a41)

Is there a way to set the data bar border color or is this not supported by EPPlus ?

Thanks in advance !

**Comment by swmal** [comment]
Hi.
Our Conditional Formatting expert @OssianEPPlus  is on holiday, but I know that he has made some improvements regarding databars in EPPlus 7, which currently is available as a preview: https://www.nuget.org/packages/EPPlus/7.0.0-preview2

I will ask him to have a look at this issue when he is back.

**Comment by OssianEPPlus** [comment]
Hi there! Apologies for the late response. The Databar support in 6.2.7 and before is limited to only the fill color, there is no border color option. but as of recently in our 7.0.0 preview we've added support for all available databar color options. 

Not just Border color but NegativeFillColor, NegativeBorderColor and AxisColor as well. 

Do keep in mind that in 7.0.0 you do need to specify e.g.
`myDatabarVariable.BorderColor.Color = Color.Red`
As we've also added other color options such as theme color.

**Comment by OssianEPPlus** [comment]
As off Epplus 7.0 you can now set Databar Border Color. [See wiki](https://github.com/EPPlusSoftware/EPPlus/wiki/Conditional-Formatting-%E2%80%90-Databars)

For examples see the [Databar Example](https://github.com/EPPlusSoftware/EPPlus.Samples.CSharp/blob/master/03-Styling/02-Conditional%20formatting/DatabarsExample.cs) in the [Sample Project](https://github.com/EPPlusSoftware/EPPlus.Samples.CSharp)
