### ISSUE TITLE
Why all numbers read from a spreadsheet are doubles?

### ISSUE THREAD

**Issue by drcolombo** [EPPlusSoftware/EPPlus#998]
I can't say if that's a bug or a "feature" and I'm not sure even if that's anyway related to EPPlus or to Excel itself.
However, we got a quite critical issue related to decimal to double and vice versa conversion that happens... not even sure where exactly.

I made a small test:
```
[TestMethod]
public void TestDataConversion()
{
    var cultureBeforeTest = Thread.CurrentThread.CurrentCulture;
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-GB");
    var fileName = $"{Guid.NewGuid()}.xlsx";
    string initialStringValue;
    string stringValueAfterReading;
    using (var package = new ExcelPackage(fileName))
    {
        var worksheet = package.Workbook.Worksheets.Add("Test");
        worksheet.Cells[1, 1].Value = 6153199192.4500027M;
        package.Save();
        initialStringValue = worksheet.Cells[1, 1].Value.ToString();
    }

    using (var package = new ExcelPackage(fileName))
    {
        var worksheet = package.Workbook.Worksheets["Test"];
        var value = worksheet.Cells[1, 1].Value;
        stringValueAfterReading = value.ToString();
    }

    Thread.CurrentThread.CurrentCulture = cultureBeforeTest;
    Assert.AreEqual(initialStringValue, stringValueAfterReading);
}
```
The results of the execution are really not what I would expect:
1. in .NET 6:
```Assert.AreEqual failed. Expected:<6153199192.4500027>. Actual:<6153199192.450003>. ```
2. in .NET Framework 4.8.1:
```Assert.AreEqual failed. Expected:<6153199192.4500027>. Actual:<6153199192.45>. ```

I appreciate any assitance of how properly handle that. Basically, the requirement is that the value that was assigned to a cell initially should match the value in the same cell after opening an Excel spreadsheet. As the initial data type is decimal, that means the value should match in all digits after a decimal point (I know that Excel considers only 15 digits of precision, but here even that doesn't happen).
Saying that the issue is critical means all those numbers are actually money amounts and even a difference in one digit somewhere after the decimal point can be extremely critical. That's why we operate with decimal data type, not double. Apparently, when you read data from the spreadsheet, all numbers become doubles :(

**Comment by swmal** [comment]
I would classify this as a "feature".

Both EPPlus and Excel uses a double to store numbers (i.e. the IEEE 754 binary 64-bit floating point format). There is no way in the Office Open Xml format to define another datatype, so when an xlsx file is read by EPPlus numbers are read into doubles. The .NET double type is the type that corresponds to the "Excel double", so EPPlus is built from ground up using this data type. The decimal datatype is more exact but consumes twice the amount of memory (128 bits vs 64).

We have written an article about this for EPPlus Calculate method: https://github.com/EPPlusSoftware/EPPlus/wiki/Formula-Calculation#floating-point-precision

The difference between .NET 6 and .NET Framework 4.8.1 is most likely a question that should be directed to the Microsoft .NET teams. EPPlus doesn't do anything different depending on the frameworks, it returns a double that has been parsed from a string in the worksheet xml in both cases.
